Repository projectcalico/calico, pull requests merged in 2018-06, with the labels that each got.

#2032 Remove description field from CRDs
  _includes/master/manifests/kdd-crds.yaml
  v2.6/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v2.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  v2.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  v3.0/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  v3.1/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
Labels: cherry-pick-candidate

#2034 update WEP yaml for errors
  master/reference/calicoctl/resources/workloadendpoint.md
Labels: kind/bug

#2035 fix WEP manifest errors
  v2.0/reference/calicoctl/resources/workloadendpoint.md
  v2.1/reference/calicoctl/resources/workloadendpoint.md
  v2.2/reference/calicoctl/resources/workloadendpoint.md
  v2.3/reference/calicoctl/resources/workloadendpoint.md
  v2.4/reference/calicoctl/resources/workloadendpoint.md
  v2.5/reference/calicoctl/resources/workloadendpoint.md
  v2.6/reference/calicoctl/resources/workloadendpoint.md
  v3.0/reference/calicoctl/resources/workloadendpoint.md
  v3.1/reference/calicoctl/resources/workloadendpoint.md
Labels: kind/bug

#2038 allocate-ipip-addr: retry loop around IPAM AutoAssign()
  calico_node/allocateipip/allocate_ipip_addr.go
Labels: release-note-required
