Repository projectcalico/calico, pull requests merged in 2019-12, with the labels that each got.

#3010 Minor kind test fixes
  Makefile
  hack/development-environment/README.md
  hack/development-environment/kind-local-up.sh
Labels: docs-not-required, release-note-not-required

#3009 Move Network design to Reference
  _data/master/navbars/networking.yml
  _data/master/navbars/reference.yml
  master/networking/bgp.md
  master/networking/external-connectivity.md
  master/reference/architecture/design/l2-interconnect-fabric.md
  master/reference/architecture/design/l3-interconnect-fabric.md
  master/reference/faq.md
  master/reference/resources/bgppeer.md
Labels: docs-not-required, release-note-not-required

#3018 Minor fixes to determine best networking
  master/networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3019 Update liveness checks to be used only network is calico
  _includes/master/charts/calico/templates/calico-node.yaml
  master/getting-started/kubernetes/installation/config-options.md
Labels: docs-pr-required, release-note-required

#3014 Fix whitespace
  master/introduction/index.md
  v3.8/introduction/index.md
Labels: docs-pr-required, release-note-required

#3023 YAO Bank manifest updates for k8s 1.16
  master/security/tutorials/app-layer-policy/manifests/10-yaobank.yaml
  master/security/tutorials/app-layer-policy/manifests/20-attack-pod.yaml
Labels: docs-pr-required, release-note-required

#3020 Istio 1.1.8-1.1.17 and 1.2.0-1.2.9
  master/getting-started/kubernetes/installation/app-layer-policy.md
  master/getting-started/kubernetes/requirements.md
  master/manifests/alp/istio-inject-configmap-1.1.10.yaml
  master/manifests/alp/istio-inject-configmap-1.1.11.yaml
  master/manifests/alp/istio-inject-configmap-1.1.12.yaml
  master/manifests/alp/istio-inject-configmap-1.1.13.yaml
  master/manifests/alp/istio-inject-configmap-1.1.14.yaml
  master/manifests/alp/istio-inject-configmap-1.1.15.yaml
  master/manifests/alp/istio-inject-configmap-1.1.16.yaml
  master/manifests/alp/istio-inject-configmap-1.1.17.yaml
  master/manifests/alp/istio-inject-configmap-1.1.8.yaml
  master/manifests/alp/istio-inject-configmap-1.1.9.yaml
  master/manifests/alp/istio-inject-configmap-1.2.0.yaml
  master/manifests/alp/istio-inject-configmap-1.2.1.yaml
  master/manifests/alp/istio-inject-configmap-1.2.2.yaml
  master/manifests/alp/istio-inject-configmap-1.2.3.yaml
  master/manifests/alp/istio-inject-configmap-1.2.4.yaml
  master/manifests/alp/istio-inject-configmap-1.2.5.yaml
  master/manifests/alp/istio-inject-configmap-1.2.6.yaml
  master/manifests/alp/istio-inject-configmap-1.2.7.yaml
  master/manifests/alp/istio-inject-configmap-1.2.8.yaml
  master/manifests/alp/istio-inject-configmap-1.2.9.yaml
Labels: docs-pr-required, release-note-required

#3046 Add Istio 1.3.x support
  master/getting-started/kubernetes/installation/app-layer-policy.md
  master/getting-started/kubernetes/requirements.md
  master/manifests/alp/istio-inject-configmap-1.3.0.yaml
  master/manifests/alp/istio-inject-configmap-1.3.1.yaml
  master/manifests/alp/istio-inject-configmap-1.3.2.yaml
  master/manifests/alp/istio-inject-configmap-1.3.3.yaml
  master/manifests/alp/istio-inject-configmap-1.3.4.yaml
  master/manifests/alp/istio-inject-configmap-1.3.5.yaml
Labels: docs-pr-required, release-note-required

#3047 Configure BGP peering How to
  master/getting-started/openstack/installation/redhat.md
  master/getting-started/openstack/installation/ubuntu.md
  master/networking/bgp.md
  master/networking/routereflector.md
  master/reference/node/configuration.md
  master/reference/resources/node.md
Labels: docs-not-required, release-note-not-required

#3048 Updates for patch releases - v3.8.5, v3.9.4, v3.10.2
  _data/versions.yml
  _includes/v3.10/release-notes/v3.10.2-release-notes.md
  _includes/v3.8/release-notes/v3.8.5-release-notes.md
  _includes/v3.9/release-notes/v3.9.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#3012 [Patch] Update 3.8, 3.9 and 3.10 liveness probe
  _includes/v3.10/charts/calico/templates/calico-node.yaml
  _includes/v3.8/charts/calico/templates/calico-node.yaml
  _includes/v3.9/charts/calico/templates/calico-node.yaml
  v3.10/getting-started/kubernetes/installation/config-options.md
  v3.8/getting-started/kubernetes/installation/config-options.md
  v3.9/getting-started/kubernetes/installation/config-options.md
Labels: docs-not-required, release-note-required

#3050 Fix node version
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3044 Add descriptions
  master/getting-started/bare-metal/installation/index.md
  master/getting-started/calicoctl/configure/index.md
  master/getting-started/index.md
  master/getting-started/kubernetes/hardway/index.md
  master/getting-started/kubernetes/index.md
  master/getting-started/kubernetes/installation/index.md
  master/getting-started/openstack/index.md
  master/getting-started/openstack/installation/index.md
  master/maintenance/index.md
  master/networking/enabling-ipvs.md
  master/networking/external-connectivity.md
  master/networking/index.md
  master/networking/legacy-firewalls.md
  master/networking/node.md
  master/networking/openstack/configuration.md
  master/networking/openstack/connectivity.md
  master/networking/openstack/floating-ips.md
  master/networking/openstack/host-routes.md
  master/networking/openstack/kuryr.md
  master/networking/openstack/labels.md
  master/networking/openstack/multiple-regions.md
  master/networking/openstack/neutron-api.md
  master/networking/openstack/semantics.md
  master/networking/openstack/service-ips.md
  master/networking/use-ipvs.md
  master/networking/workloads-outside-cluster.md
  master/reference/architecture/index.md
  master/reference/calicoctl/index.md
  master/reference/calicoctl/ipam/index.md
  master/reference/calicoctl/node/index.md
  master/reference/etcd-rbac/index.md
  master/reference/host-endpoints/index.md
  master/reference/index.md
  master/reference/resources/index.md
  master/reference/typha/index.md
  master/release-notes/index.md
  master/security/comms/crypto-auth.md
  master/security/comms/reduce-nodes.md
  master/security/comms/secure-metrics.md
  master/security/index.md
  v3.8/networking/routereflector.md
Labels: docs-pr-required, hold-merge, release-note-required

#3017 Kind XDP disabled for dev environment
  hack/development-environment/kind-local-up.sh
Labels: docs-pr-required, release-note-required

#3052 Add a check for required repos to vagrant-development-environment setup
  hack/development-environment/install.sh
Labels: docs-not-required, release-note-not-required

#2881 Ip auto detection
  _data/master/navbars/networking.yml
  master/networking/ip-autodetection.md
Labels: docs-not-required, release-note-not-required

#3059 Fix indentation for CRD name
  _includes/master/charts/calico/templates/kdd-crds.yaml
Labels: docs-pr-required, release-note-required

#3056 Fix kubectl apply commands
  master/getting-started/kubernetes/installation/calico.md
  v3.10/getting-started/kubernetes/installation/calico.md
Labels: docs-not-required, release-note-not-required

#3057 Fix mismatch between doc and left nav
  _data/master/navbars/networking.yml
Labels: docs-not-required, release-note-not-required

#3063 Fix indentation for CRD name in patch releases (#3059)
  _includes/v3.10/charts/calico/templates/kdd-crds.yaml
  _includes/v3.8/charts/calico/templates/kdd-crds.yaml
  _includes/v3.9/charts/calico/templates/kdd-crds.yaml
Labels: docs-pr-required, release-note-required

#3061 Add Calico Enterprise marketing doc
  _data/master/navbars/security.yml
  images/visualizer.png
  master/security/adopt-zero-trust.md
  master/security/calico-enterprise/network-visibility.md
  master/security/calico-network-policy.md
  master/security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#3021 Add howto for dual stack setup
  _data/master/navbars/networking.yml
  master/networking/dual-stack.md
Labels: docs-pr-required, release-note-required

#3069 WIP: Add calico enterprise logo
  _includes/enterprise_footer.html
  _includes/enterprise_header.html
  _includes/enterprise_icon.html
  _layouts/docwithnav.html
  css/style.scss
  images/calico-enterprise-blue-shield-24px.png
  images/calico-enterprise-logo-128px.png
  master/security/adopt-zero-trust.md
  master/security/calico-enterprise/network-visibility.md
Labels: docs-not-required, release-note-not-required

#3071 Add new Overview
  _data/master/navbars/security.yml
  master/security/policy-rules-overview.md
Labels: docs-not-required, release-note-not-required

#3078 Add icon to links
  _data/master/navbars/security.yml
  master/security/calico-network-policy.md
  master/security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#3080 Fix missing images from release tarball
  Makefile
  _data/versions.yml
Labels: docs-not-required, release-note-required

#3081 SCTP ports reference docs
  _includes/master/endpointport.md
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
Labels: area/documentation, docs-completed, kind/enhancement, release-note-required

#3084 Use calicoctl patch rather than get/sed/apply
  master/getting-started/kubernetes/installation/app-layer-policy.md
Labels: area/documentation, docs-pr-required, release-note-not-required

#3083 Enable ALP
  _data/master/navbars/getting-started.yml
  master/getting-started/kubernetes/installation/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#3085 Updates for v3.11 release
  AUTHORS.md
  _data/versions.yml
  _includes/v3.11/release-notes/v3.11.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3088 Update for v3.11.1
  _data/versions.yml
  _includes/v3.11/release-notes/v3.11.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#3091 fix docs: Wrong description in get-started-ip-addresses.md
  v3.11/networking/get-started-ip-addresses.md
Labels: docs-not-required, release-note-not-required
