Repository projectcalico/calico, pull requests merged in 2019-05, with the labels that each got.

#2578 Update releasing procedure
  RELEASING.md
Labels: docs-not-required, release-note-not-required

#2589 Fix manifests for calico policy only
  master/manifests/calico-policy-only.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico.yaml
  v3.7/manifests/calico-policy-only.yaml
Labels: docs-not-required, release-note-not-required

#2590 Tweaks to RELEASING.md
  RELEASING.md
Labels: docs-not-required, release-note-not-required

#2574 rename datastore option from 'kdd' to 'kubernetes'
  _includes/master/manifests/calico-config.yaml
  _includes/master/manifests/calico-node.yaml
  _includes/master/manifests/calico-typha.yaml
  _includes/master/manifests/kdd-crds.yaml
  _includes/master/manifests/rbac.yaml
  _includes/v3.6/manifests/calico-config.yaml
  _includes/v3.6/manifests/calico-node.yaml
  _includes/v3.6/manifests/calico-typha.yaml
  _includes/v3.6/manifests/kdd-crds.yaml
  _includes/v3.6/manifests/rbac.yaml
  _includes/v3.7/manifests/calico-config.yaml
  _includes/v3.7/manifests/calico-node.yaml
  _includes/v3.7/manifests/calico-typha.yaml
  _includes/v3.7/manifests/kdd-crds.yaml
  _includes/v3.7/manifests/rbac.yaml
  _plugins/lib.rb
  helm-tests/validate_typha_test.go
  master/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
  master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico-node.yaml
  master/manifests/alp/node-canal.yaml
  master/manifests/alp/node-policy-only.yaml
  master/manifests/alp/node.yaml
  master/manifests/calico-policy-only.yaml
  master/manifests/calico-typha.yaml
  master/manifests/calico.yaml
  master/manifests/canal-alp.yaml
  master/manifests/canal.yaml
  v3.6/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/canal.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico.yaml
  v3.7/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v3.7/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  v3.7/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
  v3.7/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  v3.7/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml
  v3.7/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/calico-node.yaml
  v3.7/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico-node.yaml
  v3.7/manifests/alp/node-canal.yaml
  v3.7/manifests/alp/node-policy-only.yaml
  v3.7/manifests/alp/node.yaml
  v3.7/manifests/calico-policy-only.yaml
  v3.7/manifests/calico-typha.yaml
  v3.7/manifests/calico.yaml
  v3.7/manifests/canal-alp.yaml
  v3.7/manifests/canal.yaml
Labels: docs-not-required, release-note-not-required

#2593 Update calicoctl docs for get/delete
  master/reference/calicoctl/commands/delete.md
  master/reference/calicoctl/commands/get.md
Labels: docs-not-required, release-note-not-required

#2595 Updates for release v3.7.1
  _data/versions.yml
  _includes/v3.7/release-notes/v3.7.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#2598 Use v3.7.0 as default release
  _data/versions.yml
  _includes/v3.7/release-notes/v3.7.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#2603 Update docs to include v3.7.2
  _data/versions.yml
  _includes/v3.7/release-notes/v3.7.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#2602 Fix rbac includes
  master/manifests/rbac/rbac-etcd-calico.yaml
  master/manifests/rbac/rbac-etcd-flannel.yaml
  master/manifests/rbac/rbac-kdd-calico.yaml
  master/manifests/rbac/rbac-kdd-flannel.yaml
  v3.7/manifests/rbac/rbac-etcd-calico.yaml
  v3.7/manifests/rbac/rbac-etcd-flannel.yaml
  v3.7/manifests/rbac/rbac-kdd-calico.yaml
  v3.7/manifests/rbac/rbac-kdd-flannel.yaml
Labels: docs-not-required, release-note-not-required

#2594 Add developer guide and simplify build steps
  .gitignore
  BUILDING_CALICO.md
  CONTRIBUTING_CODE.md
  DEVELOPER_GUIDE.md
  Makefile
  README.md
  _config.yml
  _config_dev.yml
Labels: docs-not-required, release-note-not-required

#2601 move helm charts
  .gitignore
  _includes/master/charts/calico/templates
  _includes/master/charts/calico/templates/_functions.tpl
  _includes/master/charts/calico/templates/calico-config.yaml
  _includes/master/charts/calico/templates/calico-etcd-secrets.yaml
  _includes/master/charts/calico/templates/calico-kube-controllers.yaml
  _includes/master/charts/calico/templates/calico-node.yaml
  _includes/master/charts/calico/templates/calico-typha.yaml
  _includes/master/charts/calico/templates/configure-canal.yaml
  _includes/master/charts/calico/templates/kdd-crds.yaml
  _includes/master/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#2600 Doc ipip vxlan updates
  master/networking/vxlan-ipip.md
Labels: docs-not-required, release-note-not-required

#2569 Update Canal RBAC manifest: Removed calico-node ClusterRoleBinding
  _includes/master/charts/calico/templates/rbac.yaml
  _includes/v3.6/manifests/rbac.yaml
  _includes/v3.7/manifests/rbac.yaml
Labels: docs-not-required, release-note-not-required

#2608 don't build vendor into jekyll
  _config.yml
Labels: docs-not-required, release-note-not-required

#2606 Move 'Resource definitions' out of calicoctl directly under References
  _data/master/navbars/reference.yml
  _includes/master/rule.md
  master/getting-started/bare-metal/bare-metal.md
  master/getting-started/bare-metal/installation/container.md
  master/getting-started/calicoctl/configure/etcd.md
  master/getting-started/calicoctl/configure/kdd.md
  master/getting-started/kubernetes/installation/config-options.md
  master/getting-started/kubernetes/installation/integration.md
  master/maintenance/component-logs.md
  master/maintenance/decommissioning-a-node.md
  master/maintenance/troubleshooting.md
  master/networking/assigning-ip-addresses-topology.md
  master/networking/bgp.md
  master/networking/changing-ip-pools.md
  master/networking/node.md
  master/networking/openstack/multiple-regions.md
  master/networking/routereflector.md
  master/networking/vxlan-ipip.md
  master/reference/calicoctl/apply.md
  master/reference/calicoctl/commands/index.md
  master/reference/calicoctl/convert.md
  master/reference/calicoctl/create.md
  master/reference/calicoctl/delete.md
  master/reference/calicoctl/get.md
  master/reference/calicoctl/index.md
  master/reference/calicoctl/ipam/index.md
  master/reference/calicoctl/ipam/release.md
  master/reference/calicoctl/ipam/show.md
  master/reference/calicoctl/label.md
  master/reference/calicoctl/node/checksystem.md
  master/reference/calicoctl/node/diags.md
  master/reference/calicoctl/node/index.md
  master/reference/calicoctl/node/run.md
  master/reference/calicoctl/node/status.md
  master/reference/calicoctl/replace.md
  master/reference/calicoctl/version.md
  master/reference/cni-plugin/configuration.md
  master/reference/faq.md
  master/reference/felix/configuration.md
  master/reference/node/configuration.md
  master/reference/public-cloud/aws.md
  master/reference/public-cloud/gce.md
  master/reference/resources/bgpconfig.md
  master/reference/resources/bgppeer.md
  master/reference/resources/felixconfig.md
  master/reference/resources/globalnetworkpolicy.md
  master/reference/resources/globalnetworkset.md
  master/reference/resources/hostendpoint.md
  master/reference/resources/index.md
  master/reference/resources/ippool.md
  master/reference/resources/networkpolicy.md
  master/reference/resources/networkset.md
  master/reference/resources/node.md
  master/reference/resources/profile.md
  master/reference/resources/workloadendpoint.md
  master/security/calico-network-policy.md
  master/security/comms/secure-metrics.md
  master/security/defend-dos-attack.md
  master/security/host-endpoints/forwarded.md
  master/security/host-endpoints/index.md
Labels: docs-not-required, release-note-not-required

#2611 fix missing calico-node clusterrolebinding for 3.6/3.7 policy-only
  _includes/master/charts/calico/templates/rbac.yaml
  _includes/v3.6/manifests/rbac.yaml
  _includes/v3.7/manifests/rbac.yaml
Labels: docs-pr-required, release-note-required

#2613 update openstack requirements doc
  master/getting-started/openstack/requirements.md
  v3.7/getting-started/openstack/requirements.md
Labels: docs-not-required, release-note-not-required

#2614 Updates for release v3.6.2
  _data/versions.yml
  _includes/v3.6/release-notes/v3.6.2-release-notes.md
Labels: docs-pr-required, release-note-required

#2605 Helm/move charts
  _includes/v3.6/charts/calico/templates
  _includes/v3.6/charts/calico/templates/_functions.tpl
  _includes/v3.6/charts/calico/templates/calico-config.yaml
  _includes/v3.6/charts/calico/templates/calico-etcd-secrets.yaml
  _includes/v3.6/charts/calico/templates/calico-kube-controllers.yaml
  _includes/v3.6/charts/calico/templates/calico-node.yaml
  _includes/v3.6/charts/calico/templates/calico-typha.yaml
  _includes/v3.6/charts/calico/templates/configure-canal.yaml
  _includes/v3.6/charts/calico/templates/kdd-crds.yaml
  _includes/v3.6/charts/calico/templates/rbac.yaml
  _includes/v3.7/charts/calico/templates
  _includes/v3.7/charts/calico/templates/_functions.tpl
  _includes/v3.7/charts/calico/templates/calico-config.yaml
  _includes/v3.7/charts/calico/templates/calico-etcd-secrets.yaml
  _includes/v3.7/charts/calico/templates/calico-kube-controllers.yaml
  _includes/v3.7/charts/calico/templates/calico-node.yaml
  _includes/v3.7/charts/calico/templates/calico-typha.yaml
  _includes/v3.7/charts/calico/templates/configure-canal.yaml
  _includes/v3.7/charts/calico/templates/kdd-crds.yaml
  _includes/v3.7/charts/calico/templates/rbac.yaml
  v3.6/manifests/rbac-etcd-calico.yaml
  v3.6/manifests/rbac-etcd-flannel.yaml
  v3.6/manifests/rbac-kdd-calico.yaml
  v3.6/manifests/rbac-kdd-flannel.yaml
Labels: docs-not-required, release-note-not-required

#2615 Updates for release v3.5.5
  _data/versions.yml
  _includes/v3.5/release-notes/v3.5.5-release-notes.md
Labels: docs-pr-required, release-note-required

#2616 Fix networking-calico version for 3.5 releases.
  _data/versions.yml
Labels: docs-pr-required, release-note-required

#2618 Split out the values.yaml generation by version
  _plugins/helm.rb
  _plugins/lib.rb
  _plugins/master/values.rb
  _plugins/v3.6/values.rb
  _plugins/v3.7/values.rb
  hack/gen_values_yml.rb
  release-scripts/do_release.py
Labels: docs-not-required, release-note-not-required

#2610 Backported NAT outgoing filter docs from master to directories v3.0 through v3.5.
  v3.0/reference/calicoctl/resources/felixconfig.md
  v3.0/reference/felix/configuration.md
  v3.1/reference/calicoctl/resources/felixconfig.md
  v3.1/reference/felix/configuration.md
  v3.2/reference/calicoctl/resources/felixconfig.md
  v3.2/reference/felix/configuration.md
  v3.3/reference/calicoctl/resources/felixconfig.md
  v3.3/reference/felix/configuration.md
  v3.4/reference/calicoctl/resources/felixconfig.md
  v3.4/reference/felix/configuration.md
  v3.5/reference/calicoctl/resources/felixconfig.md
  v3.5/reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#2623 Calico v3.7.2 includes networking-calico 3.7.2
  _data/versions.yml
Labels: docs-pr-required, release-note-required

#2619 Istio 1.1 configmaps
  _includes/master/non-helm-manifests/dikastes-container
  _includes/master/non-helm-manifests/istio-inject-configmap.yaml
  _includes/master/non-helm-manifests/istio-proxy-volume-mounts
  _includes/master/non-helm-manifests/istio-volumes
  master/getting-started/kubernetes/installation/app-layer-policy.md
  master/getting-started/kubernetes/installation/config-options.md
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/etcd/calico-networking/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/istio-app-layer-policy.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/istio-inject-configmap.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico-node.yaml
  master/maintenance/kubernetes-upgrade.md
  master/manifests/alp/istio-inject-configmap-1.0.6.yaml
  master/manifests/alp/istio-inject-configmap-1.0.7.yaml
  master/manifests/alp/istio-inject-configmap-1.1.0.yaml
  master/manifests/alp/istio-inject-configmap-1.1.1.yaml
  master/manifests/alp/istio-inject-configmap-1.1.2.yaml
  master/manifests/alp/istio-inject-configmap-1.1.3.yaml
  master/manifests/alp/istio-inject-configmap-1.1.4.yaml
  master/manifests/alp/istio-inject-configmap-1.1.5.yaml
  master/manifests/alp/istio-inject-configmap-1.1.6.yaml
  master/manifests/alp/istio-inject-configmap-1.1.7.yaml
  master/manifests/alp/istio-inject-configmap.yaml
Labels: docs-pr-required, release-note-required

#2625 calicoctl cmds use stdin
  _includes/master/ctl-container-install.md
  _includes/v3.6/ctl-container-install.md
  _includes/v3.7/ctl-container-install.md
Labels: docs-not-required, release-note-not-required

#2626 Fix Istio 1.0.x config maps
  master/manifests/alp/istio-inject-configmap-1.0.6.yaml
  master/manifests/alp/istio-inject-configmap-1.0.7.yaml
Labels: docs-not-required, release-note-not-required

#2629 update calico.yaml apiversions
  _includes/master/charts/calico/templates/calico-kube-controllers.yaml
  _includes/master/charts/calico/templates/calico-node.yaml
  _includes/master/charts/calico/templates/calico-typha.yaml
  _includes/master/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-required

#2631 Troubleshooting updates
  master/maintenance/troubleshooting.md
Labels: docs-not-required, release-note-not-required

#2637 Adding selector to kube-controller for kdd
  _includes/master/charts/calico/templates/calico-kube-controllers.yaml
Labels: docs-not-required, release-note-not-required

#2633 ALP without daemonset redeploy
  _includes/master/charts/calico/templates/calico-node.yaml
  _plugins/master/values.rb
  master/getting-started/kubernetes/installation/app-layer-policy.md
  master/manifests/alp/node-canal.yaml
  master/manifests/alp/node-etcd.yaml
  master/manifests/alp/node-policy-only.yaml
  master/manifests/alp/node.yaml
  master/manifests/canal-alp.yaml
Labels: docs-not-required, release-note-required

#2636 Doc for IPAM utilization reporting
  master/reference/calicoctl/ipam/index.md
  master/reference/calicoctl/ipam/show.md
Labels: docs-pr-required, release-note-required

#2639 Fix showing IPS IN USE from a large pool as 0
  master/reference/calicoctl/ipam/show.md
Labels: docs-pr-required, release-note-not-required

#2642 Also add selector to typha for v1 update
  _includes/master/charts/calico/templates/calico-typha.yaml
Labels: docs-not-required, release-note-not-required
