Repository projectcalico/calico, pull requests merged in 2019-04, with the labels that each got.

#2537 Bump Istio to 1.0.7
  master/getting-started/kubernetes/installation/app-layer-policy.md
  v3.2/getting-started/kubernetes/installation/app-layer-policy.md
  v3.3/getting-started/kubernetes/installation/app-layer-policy.md
  v3.4/getting-started/kubernetes/installation/app-layer-policy.md
  v3.5/getting-started/kubernetes/installation/app-layer-policy.md
  v3.6/getting-started/kubernetes/installation/app-layer-policy.md
Labels: docs-pr-required, release-note-required

#2550 Update master and v3.6 URLs for stars demo YAMLs
  master/security/stars-policy/index.md
  v3.6/security/stars-policy/index.md
Labels: docs-completed, release-note-not-required

#2547 Update docs for VXLAN.
  _data/master/navbars/networking.yml
  master/getting-started/kubernetes/installation/config-options.md
  master/networking/mtu.md
  master/networking/vxlan.md
  master/reference/calicoctl/resources/felixconfig.md
  master/reference/calicoctl/resources/ippool.md
  master/reference/felix/configuration.md
  master/reference/node/configuration.md
Labels: docs-completed, release-note-required

#2552 Fix flannel image templating
  v3.0/getting-started/kubernetes/installation/hosted/canal/canal-etcd.yaml
  v3.0/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v3.1/getting-started/kubernetes/installation/hosted/canal/canal-etcd.yaml
  v3.1/getting-started/kubernetes/installation/hosted/canal/canal.yaml
Labels: docs-not-required, release-note-not-required

#2554 VXLAN doc tweaks.
  master/networking/changing-ip-pools.md
  master/networking/vxlan.md
Labels: docs-not-required, release-note-not-required

#2555 Calico network policy
  _data/master/navbars/security.yml
  master/security/calico-network-policy.md
Labels: docs-not-required, release-note-not-required

#2526 Add liveness and readiness probes to Dikastes
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/istio-inject-configmap.yaml
Labels: docs-not-required, release-note-required

#2560 Bmckercher defend dos attack
  _data/master/navbars/security.yml
  master/security/defend-dos-attack.md
Labels: docs-completed, release-note-not-required

#2545 rename 'calico_ipam' to 'ipam' in helm options
  _includes/master/charts/calico/values.yaml
  _includes/master/manifests/calico-config.yaml
  master/getting-started/kubernetes/installation/hosted/calico.yaml
  master/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
  master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/etcd/calico-networking/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/etcd/calico-networking/calico.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/canal.yaml
  master/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico.yaml
Labels: docs-completed, release-note-not-required

#2563 Fix node container count
  master/getting-started/kubernetes/index.md
  v3.6/getting-started/kubernetes/index.md
Labels: docs-not-required, release-note-not-required

#2562 Use new IPAM changes in v3.6
  _includes/v3.6/charts/calico/values.yaml
  _includes/v3.6/manifests/calico-config.yaml
  master/getting-started/kubernetes/installation/hosted/canal/canal-etcd.yaml
  v3.6/getting-started/kubernetes/installation/hosted/calico.yaml
  v3.6/getting-started/kubernetes/installation/hosted/canal/canal-etcd.yaml
  v3.6/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
  v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/etcd/calico-networking/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/etcd/calico-networking/calico.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/flannel/canal.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico-node.yaml
  v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/policy-only/calico.yaml
Labels: docs-not-required, release-note-required

#2504 Add basic Helm test framework
  .gitignore
  Makefile
  _includes/master/charts/calico/values.yaml
  _plugins/lib.rb
  glide.lock
  glide.yaml
  helm-tests/helm_suite_test.go
  helm-tests/render_test.go
  helm-tests/validate_typha_test.go
Labels: docs-not-required, release-note-not-required

#2565 Docs and manifests changes for host-local IPAM
  _includes/master/manifests/calico-node.yaml
  _includes/master/manifests/calico-typha.yaml
  master/reference/cni-plugin/configuration.md
  master/reference/node/configuration.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2567 use export flag while modifying felixconfig resource
  master/reference/felix/configuration.md
  v3.0/reference/felix/configuration.md
  v3.1/reference/felix/configuration.md
  v3.2/reference/felix/configuration.md
  v3.3/reference/felix/configuration.md
  v3.4/reference/felix/configuration.md
  v3.5/reference/felix/configuration.md
  v3.6/reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#2546 felix: document new Felix configuration options
  master/reference/calicoctl/resources/felixconfig.md
  master/reference/felix/configuration.md
Labels: docs-completed, release-note-required

#2564 Assign calico components critical priority
  _includes/master/manifests/calico-kube-controllers.yaml
  _includes/master/manifests/calico-node.yaml
  _includes/master/manifests/calico-typha.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2571 Move node-typha.yaml -> node.yaml
  master/getting-started/kubernetes/installation/app-layer-policy.md
  master/manifests/alp/node.yaml
  v3.7/getting-started/kubernetes/installation/app-layer-policy.md
  v3.7/manifests/alp/node.yaml
Labels: docs-not-required, release-note-not-required

#2566 Add read access to canal cluster role for namespaces
  _includes/master/manifests/calico-node.yaml
  _includes/v3.7/manifests/calico-node.yaml
Labels: docs-not-required, release-note-required

#2573 Restore sanity
  Makefile
  _config_dev.yml
Labels: docs-not-required, release-note-not-required

#2577 Vxlan doc
  _data/master/navbars/networking.yml
  master/getting-started/kubernetes/installation/config-options.md
  master/networking/ip-in-ip.md
  master/networking/node.md
  master/networking/vxlan-ipip.md
  master/networking/vxlan.md
  master/reference/calicoctl/resources/ippool.md
  master/reference/public-cloud/aws.md
  master/reference/public-cloud/gce.md
  master/reference/public-cloud/ibm.md
Labels: docs-not-required, release-note-not-required

#2580 Add XDP parameters documentation to v3.7
  v3.7/reference/calicoctl/resources/felixconfig.md
  v3.7/reference/felix/configuration.md
Labels: docs-pr-required, release-note-required

#2582 Add missing RBAC for NetworkSets
  _includes/master/non-helm-manifests/calicoctl.yaml
  _includes/v3.7/non-helm-manifests/calicoctl.yaml
  master/reference/etcd-rbac/calico-etcdv3-paths.md
  v3.7/reference/etcd-rbac/calico-etcdv3-paths.md
Labels: docs-not-required, release-note-not-required

#2581 Copy new VXLAN doc from master to v3.7
  _data/v3_7/navbars/networking.yml
  v3.7/getting-started/kubernetes/installation/config-options.md
  v3.7/networking/ip-in-ip.md
  v3.7/networking/node.md
  v3.7/networking/vxlan-ipip.md
  v3.7/networking/vxlan.md
  v3.7/reference/calicoctl/resources/ippool.md
  v3.7/reference/public-cloud/aws.md
  v3.7/reference/public-cloud/gce.md
  v3.7/reference/public-cloud/ibm.md
Labels: docs-not-required, release-note-not-required

#2583 Mention IPv6 router ID calculation
  master/networking/ipv6.md
  v3.7/networking/ipv6.md
Labels: docs-not-required, release-note-not-required

#2584 Release v3.7.0
  AUTHORS.md
  _data/versions.yml
  _includes/component_url
  _includes/v3.7/release-notes/v3.7.0-pre-release-notes.md
  _includes/v3.7/release-notes/v3.7.0-release-notes.md
Labels: docs-not-required, release-note-not-required
