Repository projectcalico/calico, pull requests merged in 2019-06, with the labels that each got.

#2640 Removed incorrect text that service accounts is only for application …
  _includes/master/entityrule.md
  _includes/v3.7/entityrule.md
Labels: docs-not-required, release-note-not-required

#2572 Fix variable mismatch
  v3.3/usage/configuration/as-service.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2525 Add configurable ENV variables for use with Helm
  _includes/master/charts/calico/templates/calico-kube-controllers.yaml
  _includes/master/charts/calico/templates/calico-node.yaml
  _includes/master/charts/calico/templates/calico-typha.yaml
  _includes/v3.6/charts/calico/templates/calico-kube-controllers.yaml
  _includes/v3.6/charts/calico/templates/calico-node.yaml
  _includes/v3.6/charts/calico/templates/calico-typha.yaml
  _includes/v3.6/charts/calico/values.yaml
  _includes/v3.7/charts/calico/templates/calico-kube-controllers.yaml
  _includes/v3.7/charts/calico/templates/calico-node.yaml
  _includes/v3.7/charts/calico/templates/calico-typha.yaml
  _plugins/master/values.rb
  _plugins/v3.6/values.rb
  _plugins/v3.7/values.rb
Labels: docs-not-required, release-note-not-required

#2647 Improve output for IP attributes
  master/reference/calicoctl/ipam/show.md
Labels: docs-not-required, release-note-not-required

#2643 Add etcd DNS discovery documentation
  master/getting-started/calicoctl/configure/etcd.md
  master/reference/cni-plugin/configuration.md
  master/reference/kube-controllers/configuration.md
  master/reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#2641 Add "related issues/PRs" section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs-not-required, release-note-not-required

#2649 Add NATOutgoingAddress documentation
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
Labels: docs-pr-required, release-note-required

#2657 Move critical annotation on kube-controller to correct location
  _includes/master/charts/calico/templates/calico-kube-controllers.yaml
  _includes/v3.3/manifests/calico-kube-controllers.yaml
  _includes/v3.4/manifests/calico-kube-controllers.yaml
  _includes/v3.5/manifests/calico-kube-controllers.yaml
  _includes/v3.6/charts/calico/templates/calico-kube-controllers.yaml
  _includes/v3.7/charts/calico/templates/calico-kube-controllers.yaml
Labels: docs-not-required, release-note-not-required

#2653 Fix Calico master docs for Istio 1.1
  master/getting-started/kubernetes/installation/app-layer-policy.md
  master/security/app-layer-policy/index.md
Labels: docs-pr-required, release-note-required

#2645 Doc pre dnat new
  _data/master/navbars/security.yml
  master/security/kubernetes-node-ports.md
Labels: docs-pr-required, release-note-required

#2654 felix: document Felix sockmap configuration options
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
Labels: docs-pr-required, release-note-required

#2658 Doc levelset how tos
  master/networking/vxlan-ipip.md
  master/security/calico-network-policy.md
  master/security/defend-dos-attack.md
  master/security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#2604 Doc high connection workloads
  _data/master/navbars/security.yml
  master/security/high-connection-workloads.md
  master/security/host-endpoints/donottrack.md
Labels: docs-not-required, release-note-not-required

#2655 Added vxlan MAC and IP parameters for node resource.
  master/reference/felix/configuration.md
  master/reference/resources/node.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2663 Rename SockmapEnabled to SidecarAccelerationEnabled.
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
  v3.8/reference/felix/configuration.md
  v3.8/reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#2662 Docs PR for v3.7.3
  _data/versions.yml
  _includes/v3.7/release-notes/v3.7.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#2664 Update docs to use v3.6.3
  _data/versions.yml
  _includes/v3.6/release-notes/v3.6.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#2666 Update docs to include v3.5.6
  _data/versions.yml
  _includes/v3.5/release-notes/v3.5.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#2667 Doc: Sidecar Acceleration How To
  _data/master/navbars/networking.yml
  master/networking/sidecar-acceleration.md
Labels: docs-not-required, release-note-not-required

#2668 Components versions update
  _includes/v3.8/charts/calico/templates/calico-config.yaml
  _includes/v3.8/charts/calico/templates/calico-typha.yaml
  _includes/v3.8/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#2674 Doc-Bug-Kubernetes-Install
  master/getting-started/kubernetes/installation/calico.md
Labels: docs-not-required, release-note-not-required

#2677 Replace right single quotes with regular single quotes
  master/networking/service-advertisement.md
  v3.4/usage/service-advertisement.md
  v3.5/usage/service-advertisement.md
  v3.6/networking/service-advertisement.md
  v3.7/networking/service-advertisement.md
  v3.8/networking/service-advertisement.md
Labels: docs-not-required, release-note-not-required

#2670 Doc-HTTP-Methods
  _data/master/navbars/security.yml
  master/security/http-methods.md
Labels: docs-not-required, release-note-not-required

#2679 Backport sidecar accel docs to v3.8
  _data/v3_8/navbars/networking.yml
  v3.8/networking/sidecar-acceleration.md
Labels: docs-not-required, release-note-not-required

#2669 Doc app layer tutorial updates
  master/security/app-layer-policy/index.md
Labels: docs-not-required, release-note-not-required

#2680 Doc-Extreme-High-Connection-Workloads
  _data/master/navbars/security.yml
Labels: docs-not-required, release-note-not-required

#2684 Temporarily remove docs for features based on XDP
  _data/v3_8/navbars/networking.yml
  v3.7/reference/calicoctl/resources/felixconfig.md
  v3.7/reference/felix/configuration.md
  v3.7/security/defend-dos-attack.md
  v3.8/networking/sidecar-acceleration.md
  v3.8/reference/felix/configuration.md
  v3.8/reference/resources/felixconfig.md
  v3.8/security/defend-dos-attack.md
Labels: docs-not-required, release-note-not-required

#2682 use Hash.fetch when accessing version data in helm
  _plugins/master/values.rb
Labels: docs-not-required, release-note-not-required

#2688 Fix wrong variable ETCD_CERT_FILE
  master/getting-started/as-service.md
  v3.4/usage/configuration/as-service.md
  v3.5/usage/configuration/as-service.md
  v3.6/getting-started/as-service.md
  v3.7/getting-started/as-service.md
  v3.8/getting-started/as-service.md
Labels: docs-not-required, release-note-not-required

#2683 Add documentation for missing felix parameters
  master/reference/felix/configuration.md
  v3.6/reference/felix/configuration.md
  v3.7/reference/felix/configuration.md
  v3.8/reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#2689 Fix the order of tasks in the "patch" release section
  RELEASING.md
Labels: docs-pr-required, release-note-not-required

#2693 Fix bad URL for upgrade manifest
  master/maintenance/kubernetes-upgrade.md
  v3.7/maintenance/kubernetes-upgrade.md
  v3.8/maintenance/kubernetes-upgrade.md
Labels: docs-not-required, release-note-not-required
