Repository projectcalico/calico, pull requests merged in 2019-08, with the labels that each got.

#2767 Adjust formatting of hardway documentation to match style guide
  master/getting-started/kubernetes/installation/hardway/configure-bgp-peering.md
  master/getting-started/kubernetes/installation/hardway/configure-ip-pools.md
  master/getting-started/kubernetes/installation/hardway/end-user-rbac.md
  master/getting-started/kubernetes/installation/hardway/index.md
  master/getting-started/kubernetes/installation/hardway/install-cni-plugin.md
  master/getting-started/kubernetes/installation/hardway/install-node.md
  master/getting-started/kubernetes/installation/hardway/install-typha.md
  master/getting-started/kubernetes/installation/hardway/standing-up-kubernetes.md
  master/getting-started/kubernetes/installation/hardway/test-network-policy.md
  master/getting-started/kubernetes/installation/hardway/test-networking.md
  master/getting-started/kubernetes/installation/hardway/the-calico-datastore.md
Labels: docs-not-required, release-note-not-required

#2766 Apply policy to host forwarded traffic
  _data/master/navbars/security.yml
  images/host-forward-traffic.png
  master/security/host-forwarded-traffic.md
Labels: docs-not-required, release-note-not-required

#2768 Security left nav reordering
  _data/master/navbars/security.yml
  images/host-forward-traffic.png
  master/getting-started/kubernetes/index.md
  master/getting-started/kubernetes/installation/hardway/istio-integration.md
  master/getting-started/kubernetes/installation/hardway/test-network-policy.md
  master/security/adopt-zero-trust.md
  master/security/calico-network-policy.md
  master/security/comms/crypto-auth.md
  master/security/comms/reduce-nodes.md
  master/security/comms/secure-metrics.md
  master/security/defend-dos-attack.md
  master/security/external-ips-policy.md
  master/security/high-connection-workloads.md
  master/security/host-forwarded-traffic.md
  master/security/icmp-ping.md
  master/security/kubernetes-default-deny.md
  master/security/kubernetes-node-ports.md
  master/security/monitor-component-metrics.md
  master/security/namespace-policy.md
  master/security/network-policy-openstack.md
  master/security/service-accounts.md
  master/security/tutorials/app-layer-policy/enforce-policy-istio.md
  master/security/tutorials/app-layer-policy/manifests/10-yaobank.yaml
  master/security/tutorials/app-layer-policy/manifests/20-attack-pod.yaml
  master/security/tutorials/app-layer-policy/manifests/30-policy.yaml
  master/security/tutorials/kubernetes-policy-advanced.md
  master/security/tutorials/kubernetes-policy-basic.md
  master/security/tutorials/kubernetes-policy-demo/kubernetes-demo.md
  master/security/tutorials/kubernetes-policy-demo/manifests/00-namespace.yaml
  master/security/tutorials/kubernetes-policy-demo/manifests/01-management-ui.yaml
  master/security/tutorials/kubernetes-policy-demo/manifests/02-backend.yaml
  master/security/tutorials/kubernetes-policy-demo/manifests/03-frontend.yaml
  master/security/tutorials/kubernetes-policy-demo/manifests/04-client.yaml
  master/security/tutorials/kubernetes-policy-demo/policies/allow-ui-client.yaml
  master/security/tutorials/kubernetes-policy-demo/policies/allow-ui.yaml
  master/security/tutorials/kubernetes-policy-demo/policies/backend-policy.yaml
  master/security/tutorials/kubernetes-policy-demo/policies/default-deny.yaml
  master/security/tutorials/kubernetes-policy-demo/policies/frontend-policy.yaml
  master/security/tutorials/kubernetes-policy-demo/reset.sh
  master/security/tutorials/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#2772 More restrictive etcdv3 paths for RBAC
  master/reference/etcd-rbac/calico-etcdv3-paths.md
  master/reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#2778 Fix building of release-archive on earlier releases
  Makefile
Labels: docs-not-required, release-note-not-required

#2779 Document deviceRouteSourceAddress Felix configuration option
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
Labels: docs-pr-required, release-note-required

#2775 Use specific ip
  _data/master/navbars/networking.yml
  master/networking/use-specific-ip.md
Labels: docs-not-required, release-note-not-required

#2773 Add floating ip
  _data/master/navbars/networking.yml
  master/networking/add-floating-ip.md
Labels: docs-not-required, release-note-not-required

#2774 Restrict pod ip range
  _data/master/navbars/networking.yml
  master/networking/legacy-firewalls.md
Labels: docs-not-required, release-note-not-required

#2781 Updates for new packaging automation
  RELEASING.md
Labels: docs-not-required, release-note-not-required

#2783 refactor intro page
  images/intro/best-practices.png
  images/intro/deployed.png
  images/intro/interoperability.png
  images/intro/looks-familiar.png
  images/intro/performance.png
  images/intro/policy.png
  images/intro/scale.png
  images/intro/tigera.png
  master/introduction/index.md
Labels: docs-not-required, release-note-not-required

#2780 Move Calico the hard way docs
  _data/master/navbars/getting-started.yml
  master/getting-started/kubernetes/hardway/configure-bgp-peering.md
  master/getting-started/kubernetes/hardway/configure-ip-pools.md
  master/getting-started/kubernetes/hardway/end-user-rbac.md
  master/getting-started/kubernetes/hardway/index.md
  master/getting-started/kubernetes/hardway/install-cni-plugin.md
  master/getting-started/kubernetes/hardway/install-node.md
  master/getting-started/kubernetes/hardway/install-typha.md
  master/getting-started/kubernetes/hardway/istio-integration.md
  master/getting-started/kubernetes/hardway/standing-up-kubernetes.md
  master/getting-started/kubernetes/hardway/test-network-policy.md
  master/getting-started/kubernetes/hardway/test-networking.md
  master/getting-started/kubernetes/hardway/the-calico-datastore.md
Labels: docs-not-required, release-note-not-required

#2748 switch calico (the repo) to go modules from glide
  Makefile
Labels: docs-not-required, release-note-not-required

#2788 Fix markdown formatting
  master/reference/felix/configuration.md
Labels: area/documentation, docs-completed, release-note-required

#2782 Reflect different names in apply statement
  master/getting-started/kubernetes/installation/calico.md
  v3.8/getting-started/kubernetes/installation/calico.md
Labels: docs-not-required, release-note-not-required

#2790 Fixed typo on "trtaffic"
  master/security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#2792 Updates for v3.5.8
  _data/versions.yml
  _includes/v3.5/release-notes/v3.5.8-release-notes.md
Labels: docs-not-required, release-note-not-required

#2786 add doc explaining relative/absolute links
  CONTRIBUTING_DOCS.md
Labels: docs-not-required, release-note-not-required

#2793 Updates for v3.6.5
  _data/versions.yml
  _includes/v3.6/release-notes/v3.6.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#2794 Updates for v3.7.5
  _data/versions.yml
  _includes/v3.7/release-notes/v3.7.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#2795 Updates for v3.8.2
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#2799 Fix version skew between Dikastes and calico-node in Hardway
  master/getting-started/kubernetes/hardway/istio-integration.md
Labels: docs-not-required, release-note-not-required

#2801 Update networking-calico tag to 3.8.2
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#2806 align imageNames with component names
  _config.yml
  _data/versions.yml
  _includes/component_url
  _includes/master/ctl-container-install.md
  _includes/master/docker-container-service.md
  _includes/master/non-helm-manifests/calicoctl-etcd.yaml
  _includes/master/non-helm-manifests/calicoctl.yaml
  _includes/master/non-helm-manifests/dikastes-container
  _includes/master/rkt-container-service.md
  _plugins/master/values.rb
  master/getting-started/bare-metal/installation/binary.md
  master/getting-started/bare-metal/installation/container.md
  master/getting-started/kubernetes/installation/calico-kube-controllers.yaml
  master/getting-started/kubernetes/installation/integration.md
  master/reference/calicoctl/node/run.md
  master/reference/kube-controllers/configuration.md
  master/release-notes/index.md
Labels: docs-pr-required, release-note-required

#2808 Updates for v3.0.12
  _data/versions.yml
  _includes/v3.0/release-notes/v3.0.12-release-notes.md
Labels: docs-not-required, release-note-not-required

#2809 Fix v3.0 release page
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#2807 Updates for v3.1.7
  _data/versions.yml
  _includes/v3.1/release-notes/v3.1.7-release-notes.md
Labels: docs-not-required, release-note-not-required

#2803 Updates for v3.2.8
  _data/versions.yml
  _includes/v3.2/release-notes/v3.2.8-release-notes.md
Labels: docs-not-required, release-note-not-required

#2802 Updates for v3.3.7
  _data/versions.yml
  _includes/v3.3/release-notes/v3.3.7-release-notes.md
Labels: docs-not-required, release-note-not-required

#2800 Document DeviceRouteProtocol and RemoveExternalRoutes options
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#2810 Added default host deny behavior to reference for Host Endpoint. Per …
  master/reference/resources/hostendpoint.md
  v3.0/reference/calicoctl/resources/hostendpoint.md
  v3.1/reference/calicoctl/resources/hostendpoint.md
  v3.2/reference/calicoctl/resources/hostendpoint.md
  v3.3/reference/calicoctl/resources/hostendpoint.md
  v3.4/reference/calicoctl/resources/hostendpoint.md
  v3.5/reference/calicoctl/resources/hostendpoint.md
  v3.6/reference/calicoctl/resources/hostendpoint.md
  v3.7/reference/calicoctl/resources/hostendpoint.md
  v3.8/reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#2823 Add update permission to node/status for calicoctl
  _includes/master/non-helm-manifests/calicoctl.yaml
  _includes/v3.8/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#2824 btn-copy-code: set position absolute
  css/style.scss
Labels: docs-pr-required, release-note-required

#2820 Update intro graphics
  _layouts/docwithnav.html
  css/intro.css
  images/intro/deployed.png
  images/intro/policy.png
  images/intro/scale.png
  master/introduction/index.md
Labels: docs-not-required, release-note-not-required

#2825 backport updated intro page to v3.8
  v3.8/introduction/index.md
Labels: docs-pr-required, release-note-required
