Repository projectcalico/calico, pull requests merged in 2019-11, with the labels that each got.

#2970 bug fix pod-cidr-sed.md to make kubernetes/installation/calico.md have a right network config
  _includes/v3.10/pod-cidr-sed.md
  _includes/v3.8/pod-cidr-sed.md
  _includes/v3.9/pod-cidr-sed.md
Labels: docs-pr-required, release-note-required

#2972 Update active OpenStack version support
  _includes/master/reqs-sys.md
  master/getting-started/openstack/requirements.md
Labels: docs-not-required, release-note-required

#2983 Updates for v3.9.3 and v3.10.1
  _data/versions.yml
  _includes/v3.10/release-notes/v3.10.1-release-notes.md
  _includes/v3.9/release-notes/v3.9.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#2985 Fix networking-calico versions
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#2986 Add docs for MANAGE_CNI
  master/reference/node/configuration.md
  v3.10/reference/node/configuration.md
  v3.8/reference/node/configuration.md
  v3.9/reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#2987 Use current master of etcd3-gateway code
  master/getting-started/openstack/installation/ubuntu.md
Labels: docs-not-required, release-note-not-required

#2957 Add metadescriptions to Networking topics for SEO
  master/networking/add-floating-ip.md
  master/networking/advertise-service-ips.md
  master/networking/assign-ip-addresses-topology.md
  master/networking/bgp.md
  master/networking/get-started-ip-addresses.md
  master/networking/ipv6.md
  master/networking/legacy-firewalls.md
  master/networking/migrate-pools.md
  master/networking/mtu.md
  master/networking/openstack/dev-machine-setup.md
  master/networking/sidecar-acceleration.md
  master/networking/use-specific-ip.md
  master/networking/vxlan-ipip.md
Labels: docs-not-required, release-note-not-required

#2831 Configure MTU
  _data/master/navbars/networking.yml
  _data/v3_10/navbars/networking.yml
  _data/v3_9/navbars/networking.yml
  images/tunnel.png
  master/networking/get-started-ip-addresses.md
  master/networking/mtu.md
  v3.10/networking/mtu.md
  v3.9/networking/mtu.md
Labels: docs-not-required, release-note-not-required

#2989 Doc for etcd authentication in an OpenStack cluster
  _includes/master/openstack-etcd-auth.md
  master/getting-started/openstack/installation/redhat.md
  master/getting-started/openstack/installation/ubuntu.md
  master/reference/etcd-rbac/calico-etcdv3-paths.md
Labels: docs-not-required, release-note-not-required

#2994 Kind local-up-cluster from source implementation, for linux native de…
  hack/development-environment/.gitignore
  hack/development-environment/README.md
  hack/development-environment/kind-local-up.sh
Labels: docs-not-required, release-note-not-required

#3006 Revert "add banner for calicon (#2958)"
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#2995 New How to
  _data/master/navbars/networking.yml
  _data/v3_10/navbars/networking.yml
  master/networking/determine-best-networking.md
  v3.10/networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3005 New TOCs
  _data/master/navbars/networking.yml
  _data/master/navbars/security.yml
  master/networking/openstack/configuration.md
  master/networking/openstack/dev-machine-setup.md
  master/networking/sidecar-acceleration.md
  master/networking/vxlan-ipip.md
Labels: docs-pr-required, release-note-required

#3011 Adding -bird-live option to the liveness check
  _includes/master/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-required

#3002 Update index.md with missing whitespace
  v3.10/introduction/index.md
Labels: docs-pr-required, release-note-required
