Repository projectcalico/calico, pull requests merged in 2019-07, with the labels that each got.

#2697 Updates for Calico v3.8.0
  AUTHORS.md
  RELEASING.md
  _config_dev.yml
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#2634 Changes to support configurable healthport in node
  _includes/master/charts/calico/templates/calico-node.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2705 Document new iptablesBackend parameter.
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
Labels: docs-pr-required, release-note-required

#2694 Update Istio links
  master/getting-started/kubernetes/installation/app-layer-policy.md
  v3.8/getting-started/kubernetes/installation/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#2707 Don't indicate that externalTrafficPolicy is required
  master/networking/service-advertisement.md
  v3.4/usage/service-advertisement.md
  v3.5/usage/service-advertisement.md
  v3.6/networking/service-advertisement.md
  v3.7/networking/service-advertisement.md
  v3.8/networking/service-advertisement.md
Labels: docs-not-required, release-note-not-required

#2708 Backport docs for iptables 1.8 support to v3.8
  v3.8/reference/felix/configuration.md
  v3.8/reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#2701 Clarify that USE_POD_CIDR is required when using host-local IPAM
  master/reference/cni-plugin/configuration.md
  master/reference/node/configuration.md
  master/reference/typha/configuration.md
  v3.7/reference/cni-plugin/configuration.md
  v3.8/reference/cni-plugin/configuration.md
Labels: docs-not-required, release-note-not-required

#2648 add docs for skip-interface autodetection
  master/reference/node/configuration.md
  v3.7/reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#2676 Doc icmp ping how to
  _data/master/navbars/security.yml
  master/security/icmp-ping.md
Labels: docs-not-required, release-note-not-required

#2673 Doc-service-accounts-How-to
  _data/master/navbars/security.yml
  master/security/service-accounts.md
Labels: docs-not-required, release-note-not-required

#2717 Fix build and adjust wording re: selectors
  master/security/icmp-ping.md
Labels: docs-not-required, release-note-not-required

#2686 Add undocumented Felix and Typha Options
  master/reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#2718 Fix policy name in service account doc
  master/security/service-accounts.md
Labels: docs-not-required, release-note-not-required

#2716 Doc-Bug-Http-methods
  _data/master/navbars/security.yml
  master/reference/felix/configuration.md
  master/reference/typha/configuration.md
Labels: docs-not-required, release-note-not-required

#2710 Remove references to libnetwork, which is no longer shipped with cali…
  master/getting-started/as-service.md
  master/getting-started/kubernetes/installation/integration.md
  master/maintenance/component-logs.md
  master/reference/calicoctl/node/run.md
  master/reference/involved.md
  release-scripts/generate-release-notes.py
  v3.0/reference/involved.md
  v3.0/reference/repo-structure.md
  v3.0/usage/configuration/mtu.md
  v3.1/reference/involved.md
  v3.1/reference/repo-structure.md
  v3.1/usage/configuration/mtu.md
  v3.2/getting-started/kubernetes/installation/integration.md
  v3.2/reference/calicoctl/commands/node/run.md
  v3.2/reference/involved.md
  v3.2/reference/node/configuration.md
  v3.2/reference/repo-structure.md
  v3.2/usage/configuration/as-service.md
  v3.2/usage/configuration/mtu.md
  v3.2/usage/troubleshooting/logging.md
  v3.3/getting-started/kubernetes/installation/integration.md
  v3.3/reference/calicoctl/commands/node/run.md
  v3.3/reference/involved.md
  v3.3/reference/node/configuration.md
  v3.3/usage/configuration/as-service.md
  v3.3/usage/configuration/mtu.md
  v3.3/usage/troubleshooting/logging.md
  v3.4/getting-started/kubernetes/installation/integration.md
  v3.4/reference/calicoctl/commands/node/run.md
  v3.4/reference/involved.md
  v3.4/reference/node/configuration.md
  v3.4/usage/configuration/as-service.md
  v3.4/usage/configuration/mtu.md
  v3.4/usage/troubleshooting/logging.md
  v3.5/getting-started/kubernetes/installation/integration.md
  v3.5/reference/calicoctl/commands/node/run.md
  v3.5/reference/involved.md
  v3.5/reference/node/configuration.md
  v3.5/usage/configuration/as-service.md
  v3.5/usage/configuration/mtu.md
  v3.5/usage/troubleshooting/logging.md
  v3.6/getting-started/as-service.md
  v3.6/getting-started/kubernetes/installation/integration.md
  v3.6/maintenance/component-logs.md
  v3.6/networking/mtu.md
  v3.6/reference/calicoctl/commands/node/run.md
  v3.6/reference/involved.md
  v3.6/reference/node/configuration.md
  v3.7/getting-started/as-service.md
  v3.7/getting-started/kubernetes/installation/integration.md
  v3.7/maintenance/component-logs.md
  v3.7/reference/calicoctl/commands/node/run.md
  v3.7/reference/involved.md
  v3.8/getting-started/as-service.md
  v3.8/getting-started/kubernetes/installation/integration.md
  v3.8/maintenance/component-logs.md
  v3.8/reference/calicoctl/node/run.md
  v3.8/reference/involved.md
Labels: docs-pr-required, release-note-required

#2725 Clarify cluster IP documentation
  master/networking/service-advertisement.md
Labels: docs-not-required, release-note-not-required

#2724 updated developer-guide.md to mention cni-plugin as dependency
  DEVELOPER_GUIDE.md
Labels: docs-not-required, release-note-not-required

#2690 Doc: Enforce network policy using istio
  _data/master/navbars/security.yml
  master/security/enforce-policy-istio.md
Labels: docs-not-required, release-note-not-required

#2687 Doc: Kubernetes default deny
  _data/master/navbars/security.yml
  master/security/calico-network-policy.md
  master/security/kubernetes-default-deny.md
Labels: docs-not-required, release-note-not-required

#2726 Make some tweaks to default-deny how-to
  master/security/kubernetes-default-deny.md
Labels: docs-not-required, release-note-not-required

#2729 Move "fixes" and "documents" prompts inside comment block in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs-not-required, release-note-not-required

#2728 Make the Prometheus host a configurable property
  master/reference/felix/configuration.md
  master/reference/resources/felixconfig.md
  master/reference/typha/configuration.md
Labels: docs-not-required, release-note-required

#2734 Fix documentation for time duration fields in FelixConfiguration
  master/reference/resources/felixconfig.md
  v3.5/reference/calicoctl/resources/felixconfig.md
  v3.6/reference/calicoctl/resources/felixconfig.md
  v3.7/reference/calicoctl/resources/felixconfig.md
  v3.8/reference/resources/felixconfig.md
Labels: docs-pr-required, release-note-required

#2736 Add Managed Cloud Services How to
  _data/master/navbars/getting-started.yml
  master/getting-started/kubernetes/managed-public-cloud/aks.md
  master/getting-started/kubernetes/managed-public-cloud/eks.md
  master/getting-started/kubernetes/managed-public-cloud/gke.md
  master/getting-started/kubernetes/managed-public-cloud/iks.md
Labels: docs-not-required, release-note-not-required

#2742 Network policy open stack
  _data/master/navbars/security.yml
  master/security/network-policy-openstack.md
Labels: docs-pr-required, release-note-required

#2741 Rene typha log spam
  _includes/master/charts/calico/templates/kdd-crds.yaml
  master/getting-started/kubernetes/installation/other.md
Labels: docs-not-required, release-note-not-required

#2743 Fix swapped VM endpoint label values
  master/networking/openstack/labels.md
  v3.6/networking/openstack/labels.md
  v3.7/networking/openstack/labels.md
  v3.8/networking/openstack/labels.md
Labels: docs-not-required, release-note-not-required

#2727 refactor bare-metal docs
  _data/master/navbars/getting-started.yml
  _includes/master/docker-container-service.md
  _includes/master/rkt-container-service.md
  master/getting-started/as-service.md
  master/getting-started/bare-metal/installation/binary.md
  master/getting-started/bare-metal/installation/container.md
Labels: docs-not-required, release-note-not-required

#2691 Doc: Protect Hosts
  _data/master/navbars/security.yml
  master/security/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#2747 Fix some issues with the protect-hosts doc
  master/security/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#2750 Fixed calicoctl not being able to list networkpolicies
  _includes/master/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-required

#2751 Use namespace in policy rules
  _data/master/navbars/security.yml
  master/security/namespace-policy.md
Labels: docs-pr-required, release-note-required

#2752 External ips policy
  _data/master/navbars/security.yml
  master/security/external-ips-policy.md
Labels: docs-not-required, release-note-not-required

#2745 Adopt zero trust
  _data/master/navbars/security.yml
  images/zero-trust-app.png
  images/zero-trust-deploy.png
  master/security/adopt-zero-trust.md
Labels: docs-pr-required, release-note-required

#2756 Added blockaffinities to cluster role
  _includes/master/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#2754 Updates for Calico v3.8.1
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#2755 Doc: Services exposed externally as cluster IPs
  _data/master/navbars/security.yml
  master/security/services-cluster-ips.md
Labels: docs-not-required, release-note-not-required

#2761 Cluster ips policy updates
  master/security/services-cluster-ips.md
Labels: docs-pr-required, release-note-required

#2764 Monitor-Calico-component-metrics
  _data/master/navbars/security.yml
  master/security/monitor-component-metrics.md
Labels: docs-pr-required, release-note-required

#2763 Move host endpoints docs
  _data/master/navbars/reference.yml
  _data/master/navbars/security.yml
  master/reference/host-endpoints/connectivity.md
  master/reference/host-endpoints/conntrack.md
  master/reference/host-endpoints/failsafe.md
  master/reference/host-endpoints/forwarded.md
  master/reference/host-endpoints/index.md
  master/reference/host-endpoints/objects.md
  master/reference/host-endpoints/pre-dnat.md
  master/reference/host-endpoints/selector.md
  master/reference/host-endpoints/summary.md
  master/reference/resources/hostendpoint.md
  master/security/host-endpoints/tutorial.md
  master/security/kubernetes-node-ports.md
Labels: docs-pr-required, release-note-required

#2765 Dikastes runs non-root without privilege escalation
  _includes/master/non-helm-manifests/dikastes-container
Labels: docs-pr-required, release-note-required

#2746 Calico the Hard Way
  _data/master/navbars/getting-started.yml
  master/getting-started/kubernetes/installation/hardway/configure-bgp-peering.md
  master/getting-started/kubernetes/installation/hardway/configure-ip-pools.md
  master/getting-started/kubernetes/installation/hardway/end-user-rbac.md
  master/getting-started/kubernetes/installation/hardway/index.md
  master/getting-started/kubernetes/installation/hardway/install-cni-plugin.md
  master/getting-started/kubernetes/installation/hardway/install-node.md
  master/getting-started/kubernetes/installation/hardway/install-typha.md
  master/getting-started/kubernetes/installation/hardway/istio-integration.md
  master/getting-started/kubernetes/installation/hardway/standing-up-kubernetes.md
  master/getting-started/kubernetes/installation/hardway/test-network-policy.md
  master/getting-started/kubernetes/installation/hardway/test-networking.md
  master/getting-started/kubernetes/installation/hardway/the-calico-datastore.md
  master/manifests/crds.yaml
Labels: area/documentation, docs-pr-required, hold-merge, release-note-not-required
