Repository projectcalico/calico, pull requests merged in 2019-09, with the labels that each got.

#2817 Documentation for migration from flannel
  _data/master/navbars/getting-started.yml
  _includes/master/charts/calico/templates/calico-config.yaml
  _includes/master/charts/calico/templates/calico-node.yaml
  _includes/master/non-helm-manifests/flannel-migration/migration-job.yaml
  master/getting-started/kubernetes/installation/migration-from-flannel.md
  master/manifests/flannel-migration/calico.yaml
  master/manifests/flannel-migration/migration-job.yaml
Labels: docs-not-required, release-note-not-required

#2830 Update migration controller manifests.
  _includes/master/non-helm-manifests/flannel-migration/migration-job.yaml
  master/getting-started/kubernetes/installation/migration-from-flannel.md
Labels: docs-pr-required, release-note-required

#2832 Doc: title change
  _data/master/navbars/networking.yml
Labels: docs-not-required, release-note-not-required

#2833 Replace ippool update role by delete for migration controller.
  _includes/master/non-helm-manifests/flannel-migration/migration-job.yaml
Labels: docs-not-required, release-note-not-required

#2835 Add ippool update clusterrole for migration controller.
  _includes/master/non-helm-manifests/flannel-migration/migration-job.yaml
Labels: docs-pr-required, release-note-required

#2811 Revert versions change
  _config.yml
  _data/versions.yml
  _includes/component_url
  _includes/master/docker-container-service.md
  _includes/master/non-helm-manifests/dikastes-container
  _includes/master/rkt-container-service.md
  _plugins/master/values.rb
  master/getting-started/bare-metal/installation/binary.md
  master/getting-started/bare-metal/installation/container.md
  master/getting-started/kubernetes/installation/calico-kube-controllers.yaml
  master/getting-started/kubernetes/installation/integration.md
  master/reference/calicoctl/node/run.md
  master/reference/kube-controllers/configuration.md
  master/release-notes/index.md
Labels: docs-not-required, release-note-not-required

#2837 Fix versions file
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#2838 Fix build of v3.9
  _includes/v3.9/docker-container-service.md
  _includes/v3.9/non-helm-manifests/dikastes-container
  _includes/v3.9/rkt-container-service.md
  _plugins/v3.9/values.rb
  v3.9/getting-started/bare-metal/installation/binary.md
  v3.9/getting-started/bare-metal/installation/container.md
  v3.9/getting-started/kubernetes/installation/calico-kube-controllers.yaml
  v3.9/getting-started/kubernetes/installation/integration.md
  v3.9/reference/calicoctl/node/run.md
  v3.9/reference/kube-controllers/configuration.md
  v3.9/release-notes/index.md
Labels: docs-not-required, release-note-not-required

#2839 Update flannel migration doc
  master/getting-started/kubernetes/installation/migration-from-flannel.md
  v3.9/getting-started/kubernetes/installation/migration-from-flannel.md
Labels: docs-not-required, release-note-not-required

#2842 Fix rollback steps
  master/getting-started/kubernetes/installation/migration-from-flannel.md
  v3.9/getting-started/kubernetes/installation/migration-from-flannel.md
Labels: docs-not-required, release-note-not-required

#2843 Fix missing cross subnet references
  master/reference/node/configuration.md
  v3.9/reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#2846 Updates for Calico v3.9.0
  AUTHORS.md
  _data/versions.yml
  _includes/v3.9/release-notes/v3.9.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#2851 alert-warning: make colors bolder
  css/style.scss
Labels: docs-not-required, release-note-not-required

#2845 Get started with IP address management
  _data/master/navbars/networking.yml
  master/networking/get-started-ip-addresses.md
Labels: docs-not-required, release-note-not-required

#2852 Migrate ip pools
  _data/master/navbars/networking.yml
  master/networking/changing-ip-pools.md
  master/networking/migrate-pools.md
Labels: docs-not-required, release-note-not-required

#2854 Add CoreOS specific flexvol-driver-host note
  master/getting-started/kubernetes/installation/calico.md
  master/reference/faq.md
  v3.8/getting-started/kubernetes/installation/calico.md
  v3.8/reference/faq.md
  v3.9/getting-started/kubernetes/installation/calico.md
  v3.9/reference/faq.md
Labels: docs-not-required, release-note-not-required

#2863 fix broken link to doc that moved
  master/networking/get-started-ip-addresses.md
Labels: docs-pr-required, release-note-required

#2858 security context for typha non-root
  _includes/master/charts/calico/templates/calico-typha.yaml
Labels: docs-pr-required, release-note-not-required

#2861 Clarify ip versions on net selector
  _includes/master/entityrule.md
Labels: docs-not-required, release-note-not-required

#2864 Rework sitemaps to align better with google and algolia needs
  _config.yml
  sitemap-latest.xml
  sitemap-older.xml
Labels: docs-not-required, release-note-not-required

#2853 create empty release notes dir for master
  _includes/master/release-notes/.gitkeep
Labels: docs-not-required, release-note-not-required

#2840 Move flannel content
  _data/master/navbars/getting-started.yml
Labels: docs-not-required, release-note-not-required

#2867 Add meta description to layout
  _layouts/docwithnav.html
  master/security/calico-network-policy.md
Labels: docs-not-required, release-note-not-required

#2868 Documentation for default BGP Configuration serviceExternalIPs
  master/reference/resources/bgpconfig.md
Labels: docs-pr-required, release-note-required

#2874 Move selector from EntityRule to Spec level
  master/security/kubernetes-node-ports.md
  v3.8/security/kubernetes-node-ports.md
  v3.9/security/kubernetes-node-ports.md
Labels: docs-completed, release-note-not-required

#2872 Enable inertia scrolling on iOS
  css/style.scss
Labels: docs-not-required, release-note-not-required

#2869 Remove meta description from layout
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#2870 Move-Monitor-Calico-Components
  _data/master/navbars/maintenance.yml
  _data/master/navbars/security.yml
  _data/v3_9/navbars/maintenance.yml
  _data/v3_9/navbars/security.yml
  master/maintenance/monitor-component-metrics.md
  v3.9/maintenance/monitor-component-metrics.md
Labels: docs-pr-required, release-note-required

#2882 Fix CNI version to be v0.3.1
  _includes/master/charts/calico/templates/calico-config.yaml
  _includes/v3.9/charts/calico/templates/calico-config.yaml
Labels: docs-not-required, release-note-required

#2883 fix minor typo in felix config reference
  master/reference/felix/configuration.md
  v3.1/reference/felix/configuration.md
  v3.2/reference/felix/configuration.md
  v3.3/reference/felix/configuration.md
  v3.4/reference/felix/configuration.md
  v3.5/reference/felix/configuration.md
  v3.6/reference/felix/configuration.md
  v3.7/reference/felix/configuration.md
  v3.8/reference/felix/configuration.md
  v3.9/reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#2885 remove dated IPVS warning for k8s v1.10
  master/networking/enabling-ipvs.md
  v3.6/networking/enabling-ipvs.md
  v3.7/networking/enabling-ipvs.md
  v3.8/networking/enabling-ipvs.md
  v3.9/networking/enabling-ipvs.md
Labels: docs-pr-required, release-note-not-required

#2856 add calicoctl patch docs
  _data/master/navbars/reference.yml
  master/reference/calicoctl/index.md
  master/reference/calicoctl/patch.md
Labels: docs-not-required, release-note-not-required

#2884 Changes for Calico v3.9.1
  _data/versions.yml
  _includes/v3.9/release-notes/v3.9.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#2892 Fix calicoctl link
  master/reference/calicoctl/patch.md
Labels: docs-not-required, release-note-not-required
