Repository projectcalico/calico, pull requests merged in 2020-08, with the labels that each got.

#3845 Include optional configmap to override k8s endpoint
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3840 Add networking and k8s networking educational pages
  _data/navbars/introduction.yml
  _data/navbars/learn.yml
  about/about-calico.md
  about/about-kubernetes-networking.md
  about/about-networking.md
  about/index.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  images/anatomy-of-a-packet.svg
  images/anatomy-of-an-overlay-packet.svg
  images/osi-network-layers.svg
  index.html
  netlify/_redirects
Labels: docs-not-required, release-note-not-required

#3853 Automated cherry pick of #3840: Add networking and k8s networking educational pages
  _data/navbars/introduction.yml
  _data/navbars/learn.yml
  about/about-calico.md
  about/about-kubernetes-networking.md
  about/about-networking.md
  about/index.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  images/anatomy-of-a-packet.svg
  images/anatomy-of-an-overlay-packet.svg
  images/osi-network-layers.svg
  index.html
  netlify/_redirects
Labels: docs-not-required, release-note-not-required

#3855 Fix dev build
  Makefile
Labels: docs-not-required, release-note-not-required

#3859 Add mention of Calico to overlay section
  about/about-networking.md
Labels: docs-not-required, release-note-not-required

#3863 reverting branch deployment changes - master
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3862 Revert "adding branch deployment changes for calico site - production"
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3775 Plugin to prevent special characters in code blocks
  _plugins/code_block_validator.rb
  networking/bgp.md
  networking/change-block-size.md
Labels: docs-not-required, release-note-not-required

#3852 MicroK8s doc
  _data/navbars/getting-started.yml
  getting-started/kubernetes/microk8s.md
Labels: docs-not-required, release-note-not-required

#3866 Automated cherry pick of #3852: MicroK8s doc
  _data/navbars/getting-started.yml
  getting-started/kubernetes/microk8s.md
Labels: docs-not-required, release-note-not-required

#3861 Automated cherry pick of #3859: Add mention of Calico to overlay section
  about/about-networking.md
Labels: docs-not-required, release-note-not-required

#3850 Automated cherry pick of #3615: Update How to
  _data/navbars/networking.yml
  networking/workloads-outside-cluster.md
Labels: docs-not-required, release-note-not-required

#3839 remove tracking jekyll cache during local website dev
  .gitignore
Labels: docs-not-required, release-note-not-required

#3836 Fix typo
  maintenance/kubernetes-upgrade.md
Labels: docs-not-required, release-note-not-required

#3867 Update docs for keepOriginalNextHop in bgppeer resource
  reference/resources/bgppeer.md
Labels: docs-not-required, release-note-not-required

#3856 release-v3.14 - Cherry-pick Add note on integrating an OpenShift install with OLM (#3826)
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#3685 Update calico-etcdv3-paths.md
  reference/etcd-rbac/calico-etcdv3-paths.md
Labels: docs-not-required, release-note-not-required

#3869 adding changes for site per version
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3870 adding changes for site per version - release v3.12
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3871 adding changes for site per version - release v3.13
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3872 adding changes for site per version - release v3.14
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3842 Remove redundant manifest change
  _includes/charts/calico/templates/calico-node.yaml
  manifests/calico-vxlan.yaml
Labels: docs-not-required, release-note-not-required

#3723 Adjust docker image for yaobank manifest
  security/tutorials/app-layer-policy/manifests/10-yaobank.yaml
Labels: docs-not-required, release-note-not-required

#3879 Automated cherry pick of #3877: add-multiple-dataplanes
  about/about-calico.md
  images/intro/multiple-dataplanes.png
Labels: docs-not-required, release-note-not-required

#3877 Refresh about Calico to include multiple dataplanes
  about/about-calico.md
  images/intro/multiple-dataplanes.png
Labels: docs-not-required, release-note-not-required

#3873 Update flannel to v0.12.0
  _data/versions.yml
Labels: docs-not-required, release-note-required

#3875 adding changes for site per version - master
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3876 adding changes for site per version - production
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3843 add rel attributes to make cross-domain links safer
  _includes/docs_ad.html
  _includes/enterprise_header.html
  _includes/open-new-window.html
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3865 proposal for docs site generation - One site per version with proxy
  RELEASING.md
Labels: docs-not-required, release-note-not-required

#3874 calicoctl directory support
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-tigera-install-script.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  _includes/content/install-openshift-manifests.md
  manifests/ocp/tigera-operator/02-configmap-tigera-install-script.yaml
  reference/calicoctl/apply.md
  reference/calicoctl/create.md
  reference/calicoctl/delete.md
  reference/calicoctl/get.md
  reference/calicoctl/overview.md
  reference/calicoctl/replace.md
Labels: docs-not-required, release-note-not-required

#3883 Replace shell with calicoctl utility
  _includes/non-helm-manifests/calicoctl-etcd.yaml
Labels: docs-not-required, release-note-not-required

#3881 Add documentation for CNI file logging
  _includes/charts/calico/templates/calico-config.yaml
  reference/cni-plugin/configuration.md
Labels: docs-not-required, release-note-not-required

#3677 Include link on releases page to the archive page for latest
  releases.md
Labels: docs-not-required, release-note-not-required

#3882 Update CRDs
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
Labels: docs-not-required, release-note-not-required

#3889 Update redirects for v3.16
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3888 Update redirects for v3.16
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3887 Docs-add-traffic-shaping
  reference/cni-plugin/configuration.md
Labels: docs-not-required, release-note-not-required

#3880 Docs-fix-formatting-issues
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#3891 Add docs for CIDR detection method
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#3892 Automated cherry pick of #3891: Add docs for CIDR detection method
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#3851 Docs-calico-for-windows
  _config.yml
  _data/navbars/getting-started.yml
  getting-started/windows-calico/index.md
  getting-started/windows-calico/kubeconfig.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/maintain.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/requirements.md
  getting-started/windows-calico/standard.md
  getting-started/windows-calico/troubleshoot.md
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#3894 Cherry-pick Docs-calico-for-windows (#3851)
  _config.yml
  _data/navbars/getting-started.yml
  getting-started/windows-calico/index.md
  getting-started/windows-calico/kubeconfig.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/maintain.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/requirements.md
  getting-started/windows-calico/standard.md
  getting-started/windows-calico/troubleshoot.md
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#3893 Docs-add-traffic-shaping (#3887)
  reference/cni-plugin/configuration.md
Labels: docs-not-required, release-note-not-required

#3896 Add about network policy
  _data/navbars/about.yml
  about/about-network-policy.md
  images/example-k8s-calico-policy-mix.svg
  images/example-tiers.svg
Labels: docs-not-required, release-note-not-required

#3897 Automated cherry pick of #3896: Initial notes
  _data/navbars/about.yml
  about/about-network-policy.md
  images/example-k8s-calico-policy-mix.svg
  images/example-tiers.svg
Labels: docs-not-required, release-note-not-required

#3899 Fix windows install script. Zip name should use node version
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#3898 Fix zip file name in windows install script
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#3903 Operator: add patch for migration
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3857 release-v3.15 - Cherry-pick Add note on integrating an OpenShift install with OLM (#3826)
  _data/versions.yml
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#3905 Automated cherry pick of #3903: Operator: add patch for migration
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3904 Automated cherry pick of #3903: Operator: add patch for migration
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3906 Operator: add patch for migration
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3907 DigitalOcean self-managed Kubernetes tutorial
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-public-cloud/do.md
Labels: docs-not-required, release-note-not-required

#3910 Automated cherry pick of #3907: DigitalOcean selfmanaged Kubernetes using Calico
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-public-cloud/do.md
Labels: docs-not-required, release-note-not-required

#3911 Automated cherry pick of #3907: DigitalOcean selfmanaged Kubernetes using Calico
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-public-cloud/do.md
Labels: docs-not-required, release-note-not-required

#3919 Added step to check Calico service for standard install
  getting-started/windows-calico/standard.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3921 BPF mode docs for GA
  _data/navbars/getting-started.yml
  _data/navbars/maintenance.yml
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
  getting-started/kubernetes/trying-ebpf.md
  maintenance/ebpf-and-eks.md
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3920 Merge pull request #3919 from song-jiang/song-win-doc
  getting-started/windows-calico/standard.md
Labels: docs-not-required, release-note-not-required

#3922 Fix up felix config docs for BPF.
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3923 Automated cherry pick of #3921: Manifest updates for BPF mode. #3922: Fix up felix config docs for BPF.
  _data/navbars/getting-started.yml
  _data/navbars/maintenance.yml
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
  getting-started/kubernetes/trying-ebpf.md
  maintenance/ebpf-and-eks.md
  maintenance/enabling-bpf.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3924 Fix missing --patch in calicoctl commands.
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3925 [v3.16] BPF docs fixes
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3926 Updates for v3.15.2
  _data/versions.yml
  _includes/release-notes/v3.15.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#3927 BPF docs tweaks
  maintenance/ebpf-and-eks.md
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3928 [v3.16] BPF docs tweaks.
  maintenance/ebpf-and-eks.md
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3929 Change Unicode apostrophe in YAMLs to ASCII apostrophe
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
Labels: docs-not-required, release-note-not-required

#3931 Add note for managed EKS windows nodes
  getting-started/windows-calico/limitations.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3913 Add network policy intro
  about/about-network-policy.md
Labels: docs-not-required, release-note-not-required

#3917 Add about services
  _data/navbars/about.yml
  about/about-kubernetes-services.md
  images/calico-native-service-handling.svg
  images/k8s-service-concept.svg
  images/kube-proxy-cluster-ip.svg
  images/kube-proxy-load-balancer.svg
  images/kube-proxy-node-port.svg
  images/kube-proxy-service-advertisement.svg
  images/kube-proxy-service-local.svg
Labels: docs-not-required, release-note-not-required

#3933 remove superfluous support link due to missing image
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3932 Automated cherry pick of #3931: wip
  getting-started/windows-calico/limitations.md
Labels: docs-not-required, release-note-not-required

#3918 Automated cherry pick of #3913: Add network policy intro
  about/about-network-policy.md
Labels: docs-not-required, release-note-not-required

#3772 Automated cherry pick of #3761: fix
  CONTRIBUTING_DOCS.md
Labels: docs-not-required, release-note-not-required

#3934 Automated cherry pick of #3896: Initial notes #3917: Add about services
  _data/navbars/about.yml
  about/about-kubernetes-services.md
  about/about-network-policy.md
  images/calico-native-service-handling.svg
  images/example-k8s-calico-policy-mix.svg
  images/example-tiers.svg
  images/k8s-service-concept.svg
  images/kube-proxy-cluster-ip.svg
  images/kube-proxy-load-balancer.svg
  images/kube-proxy-node-port.svg
  images/kube-proxy-service-advertisement.svg
  images/kube-proxy-service-local.svg
Labels: docs-not-required, release-note-not-required

#3935 MicroK8s update
  getting-started/kubernetes/microk8s.md
Labels: docs-not-required, release-note-not-required

#3942 Add more detail to BPF instructions.
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3941 Add more detail to BPF instructions.
  maintenance/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#3937 Automated cherry pick of #3935: minor updates to MicroK8s doc.
  getting-started/kubernetes/microk8s.md
Labels: docs-not-required, release-note-not-required

#3936 Automated cherry pick of #3935: minor updates to MicroK8s doc.
  getting-started/kubernetes/microk8s.md
Labels: docs-not-required, release-note-not-required

#3939 Fix several typos in 'Zero trust networking' page
  security/adopt-zero-trust.md
Labels: docs-not-required, release-note-not-required

#3767 Docs-ipv6-rewrite
  _data/navbars/networking.yml
  networking/advertise-service-ips.md
  networking/dual-stack.md
  networking/ipv6-control-plane.md
  networking/ipv6.md
  networking/openstack/ipv6.md
Labels: docs-not-required, release-note-not-required

#3943 Updates for v3.16.0
  AUTHORS.md
  _data/versions.yml
  _includes/release-notes/v3.16.0-pre-release-release-notes.md
  _includes/release-notes/v3.16.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3944 Fix versions
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3946 Update operator and archive
  _data/archives.yml
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3945 Fix versions
  _data/archives.yml
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3948 Add known cni binary name issue
  _includes/release-notes/v3.16.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3947 Update operator API reference
  reference/installation/_api.html
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3953 Add Windows archive from node release to Calico release
  Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3954 Update operator API reference (#3947)
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required
