Repository projectcalico/calico, pull requests merged in 2020-02, with the labels that each got.

#3211 Auto-detect Pod CIDR on kubeadm
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-completed, release-note-required

#3206 Non-cluster hosts (a.k.a. host-only)
  RELEASING.md
  _data/navbars/getting-started.yml
  _includes/content/docker-container-service.md
  _includes/content/environment-file.md
  _includes/content/felix-init-datastore.md
  getting-started/as-service.md
  getting-started/bare-metal/about.md
  getting-started/bare-metal/bare-metal.md
  getting-started/bare-metal/index.md
  getting-started/bare-metal/installation/binary-mgr.md
  getting-started/bare-metal/installation/binary.md
  getting-started/bare-metal/installation/container.md
  getting-started/bare-metal/installation/overview.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
  reference/host-endpoints/selector.md
  reference/resources/globalnetworkpolicy.md
  security/comms/crypto-auth.md
  security/protect-hosts.md
Labels: area/documentation, docs-pr-required, release-note-required

#3212 Cherry-pick new enterprise awareness docs
  _data/navbars/security.yml
  images/anomaly-detection.png
  images/audit-logs.png
  images/compliance-reporting.png
  images/compliance-reports.png
  images/configuration-compliance.png
  images/dga-detection.png
  images/dns-policy-rules.png
  images/federated-endpoint-identity.png
  images/flow-logs.png
  images/flow-viz.png
  images/operations-dashboard.png
  images/policy-builder.png
  images/policy-federation.png
  images/policy-options.png
  images/policy-recommendation.png
  images/policy-workflow.png
  images/threat-feed.png
  images/tiered-policies.png
  images/tiered-policy-board.png
  security/adopt-zero-trust.md
  security/calico-enterprise/compliance.md
  security/calico-enterprise/egress-access-controls.md
  security/calico-enterprise/federation.md
  security/calico-enterprise/threat-defense.md
  security/calico-enterprise/user-console.md
  security/calico-network-policy.md
  security/external-ips-policy.md
  security/policy-rules-overview.md
Labels: docs-not-required, release-note-not-required

#3214 Delete note to ignore Kubenet, as page now mentions Calico too
  networking/dual-stack.md
Labels: docs-not-required, release-note-not-required

#3218 Include rulemetadata in network policy sample
  reference/resources/globalnetworkpolicy.md
  reference/resources/networkpolicy.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3213 Self-managed on-premises only cleanup
  _data/navbars/getting-started.yml
  _data/navbars/security.yml
  getting-started/kubernetes/flannel/flannel.md
  getting-started/kubernetes/flannel/migration-from-flannel.md
  getting-started/kubernetes/hardway/overview.md
  getting-started/kubernetes/installation/calico.md
  getting-started/kubernetes/installation/config-options.md
  getting-started/kubernetes/installation/integration.md
  getting-started/kubernetes/installation/other.md
  getting-started/kubernetes/installation/overview.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
  maintenance/kubernetes-upgrade.md
  networking/dual-stack.md
  networking/sidecar-acceleration.md
  reference/felix/configuration.md
  reference/public-cloud/azure.md
  reference/resources/felixconfig.md
  reference/resources/globalnetworkpolicy.md
  reference/resources/networkpolicy.md
  reference/resources/profile.md
  security/adopt-zero-trust.md
  security/app-layer-policy.md
  security/enforce-policy-istio.md
  security/http-methods.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
  security/tutorials/kubernetes-policy-basic.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3226 cherry-pick machinery fixes to release-v3.12
  RELEASING.md
  css/style.scss
  js/code-select.js
  netlify.toml
  netlify/_config_latest.yml
  netlify/_redirects
  netlify/build.sh
  netlify/sitemap-index.xml
Labels: docs-not-required, release-note-not-required

#3227 support permalink to latest release
  netlify/build.sh
Labels: docs-not-required, release-note-not-required

#3223 Cherry-pick Add rulemetadata usage to sample policy (#3218)
  reference/resources/globalnetworkpolicy.md
  reference/resources/networkpolicy.md
Labels: docs-not-required, release-note-not-required

#3229 Add geek details
  _includes/geek-details.html
  _includes/geek-details/cni-aws.md
  _includes/geek-details/cni-azure.md
  _includes/geek-details/cni-calico.md
  _includes/geek-details/cni-kubenet.md
  _includes/geek-details/cross-subnet-ipip.md
  _includes/geek-details/cross-subnet-vxlan.md
  _includes/geek-details/datastore-etcd.md
  _includes/geek-details/datastore-kubernetes.md
  _includes/geek-details/info.md
  _includes/geek-details/ipam-aws.md
  _includes/geek-details/ipam-azure.md
  _includes/geek-details/ipam-calico.md
  _includes/geek-details/ipam-host-local.md
  _includes/geek-details/overlay-ipip.md
  _includes/geek-details/overlay-no.md
  _includes/geek-details/overlay-vxlan.md
  _includes/geek-details/policy-calico.md
  _includes/geek-details/policy-none.md
  _includes/geek-details/routing-bgp.md
  _includes/geek-details/routing-static.md
  _includes/geek-details/routing-vpc-native.md
  css/style.scss
  getting-started/kubernetes/flannel/flannel.md
  getting-started/kubernetes/managed-public-cloud/aks.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  getting-started/kubernetes/managed-public-cloud/gke.md
  getting-started/kubernetes/managed-public-cloud/iks.md
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azu.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
Labels: docs-not-required, release-note-not-required

#3235 Fix missing k8s manifests from release artifact
  Makefile
Labels: docs-pr-required, release-note-required

#3237 Replace modal headers with styled div
  _includes/geek-details.html
  css/style.scss
Labels: docs-pr-required, release-note-required

#3239 Use operator v1.1.1, OpenShift multus fix
  _data/versions.yml
Labels: docs-not-required, release-note-required

#3240 fix typo
  networking/calico-enterprise/federation.md
  security/calico-enterprise/federation.md
Labels: docs-not-required, release-note-not-required

#3241 Cherry-pick fix typo (#3240)
  networking/calico-enterprise/federation.md
  security/calico-enterprise/federation.md
Labels: docs-pr-required, release-note-required

#3225 Align OS topic verbs
  _data/navbars/getting-started.yml
  getting-started/calicoctl/configure/etcd.md
  getting-started/calicoctl/configure/kdd.md
  getting-started/calicoctl/configure/overview.md
  getting-started/calicoctl/install.md
  getting-started/index.md
  getting-started/kubernetes/flannel/migration-from-flannel.md
  getting-started/kubernetes/hardway/standing-up-kubernetes.md
  getting-started/openshift/installation.md
  getting-started/openstack/verification.md
Labels: docs-pr-required, release-note-required

#3244 Edits to inline help topics
  _includes/geek-details/cni-aws.md
  _includes/geek-details/cni-azure.md
  _includes/geek-details/cni-calico.md
  _includes/geek-details/cni-kubenet.md
  _includes/geek-details/cross-subnet-ipip.md
  _includes/geek-details/cross-subnet-vxlan.md
  _includes/geek-details/datastore-etcd.md
  _includes/geek-details/datastore-kubernetes.md
  _includes/geek-details/info.md
  _includes/geek-details/ipam-calico.md
  _includes/geek-details/ipam-host-local.md
  _includes/geek-details/overlay-ipip.md
  _includes/geek-details/overlay-no.md
  _includes/geek-details/overlay-vxlan.md
  _includes/geek-details/policy-calico.md
  _includes/geek-details/policy-none.md
  _includes/geek-details/routing-bgp.md
  _includes/geek-details/routing-static.md
Labels: docs-pr-required, release-note-required

#3245 Remove per Alex P.
  _data/navbars/introduction.yml
  introduction/deployments.md
Labels: docs-pr-required, release-note-required

#3250 typos
  _includes/geek-details/policy-calico.md
Labels: docs-pr-required, release-note-required

#3247 Update doc and release process for networking-calico
  RELEASING.md
  _includes/component_url
  getting-started/openstack/installation/devstack.md
  getting-started/openstack/overview.md
  release-scripts/tests/test_openstack_artifacts.py
  release-scripts/tests/test_tags_tars.py
Labels: docs-not-required, release-note-required

#3256 Update filename for SEO
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-public-cloud/azure.md
Labels: docs-not-required, release-note-not-required

#3257 Update enterprise-header to link to trial
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#3238 Add open-new-window.html
  _includes/open-new-window.html
  css/style.scss
  getting-started/kubernetes/managed-public-cloud/gke.md
Labels: docs-not-required, release-note-not-required

#3263 Fix RBAC for configmap query to be for etcd as well
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-pr-required, release-note-required

#3266 Add 'get' permission on nodes to kube-controllers in etcd mode
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3268 New top and bottom navs
  _layouts/docwithnav.html
  images/tigera-badge.png
Labels: docs-pr-required, release-note-required

#3272 Add divider to right toc
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3260 Add video links
  getting-started/kubernetes/managed-public-cloud/aks.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  getting-started/kubernetes/managed-public-cloud/gke.md
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
Labels: docs-not-required, release-note-not-required

#3261 Fix AMD64 reference in requirements
  _includes/content/reqs-sys.md
Labels: docs-pr-required, release-note-required

#3252 Get-started-improvements
  _data/navbars/getting-started.yml
  getting-started/kubernetes/flannel/index.md
  getting-started/kubernetes/flannel/migration-from-flannel.md
  getting-started/kubernetes/hardway/index.md
  getting-started/kubernetes/index.md
  getting-started/kubernetes/installation/config-options.md
  getting-started/kubernetes/managed-public-cloud/index.md
  getting-started/kubernetes/quickstart.md
  getting-started/kubernetes/requirements.md
  getting-started/kubernetes/self-managed-onprem/index.md
  getting-started/kubernetes/self-managed-public-cloud/index.md
Labels: docs-not-required, release-note-not-required

#3279 Add reference doc for calicoctl node run felix config
  reference/calicoctl/node/run.md
Labels: docs-not-required, release-note-not-required

#3277 Update README.md with more documentation links and info
  README.md
Labels: docs-not-required, release-note-not-required

#3280 Bump etcd3gw version
  getting-started/openstack/installation/ubuntu.md
Labels: docs-pr-required, release-note-required

#3283 fix typo
  getting-started/kubernetes/hardway/configure-bgp-peering.md
Labels: docs-pr-required, release-note-required

#3278 Change get started links
  _includes/content/reqs-sys.md
  getting-started/kubernetes/flannel/flannel.md
  getting-started/kubernetes/hardway/istio-integration.md
  getting-started/kubernetes/hardway/overview.md
  getting-started/kubernetes/hardway/the-calico-datastore.md
  getting-started/kubernetes/managed-public-cloud/aks.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  getting-started/kubernetes/managed-public-cloud/iks.md
  getting-started/kubernetes/quickstart.md
  getting-started/kubernetes/requirements.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
  getting-started/openshift/installation.md
  getting-started/openshift/requirements.md
  getting-started/openstack/installation/devstack.md
  getting-started/openstack/installation/redhat.md
  getting-started/openstack/overview.md
  getting-started/openstack/requirements.md
Labels: docs-not-required, release-note-not-required

#3285 Fix missing RBAC permissions for node update
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3273 Switch to vanilla san-serif font
  _sass/bootstrap/bootstrap/_variables.scss
Labels: docs-not-required, release-note-not-required

#3248 networking-calico version for Calico v3.8.6 was actually 3.9.2
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3290 Add install manifest for eBPF mode.
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
  manifests/calico-bpf.yaml
Labels: docs-pr-required, release-note-required

#3286 Change left nav from "Get started" to "Install"
  _data/navbars/getting-started.yml
  getting-started/index.md
  getting-started/kubernetes/quickstart.md
Labels: docs-pr-required, release-note-required

#3284 Update OpenShift install description and fix Quickstart processor
  getting-started/kubernetes/quickstart.md
  getting-started/openshift/installation.md
Labels: docs-pr-required, release-note-required
