Repository projectcalico/calico, pull requests merged in 2020-11, with the labels that each got.

#4132 Update bgp.md
  networking/bgp.md
Labels: docs-not-required, release-note-not-required

#4126 Docs changes for auto-MTU
  _includes/charts/calico/templates/calico-config.yaml
  networking/mtu.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#4135 Minor typo fixes in windows doc
  getting-started/windows-calico/standard.md
Labels: docs-not-required, release-note-not-required

#4136 Docs-update-text
  calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#4089 Add Pod Disruption Budget to Kube Controller
  _includes/charts/calico/templates/calico-kube-controllers.yaml
Labels: docs-not-required, release-note-not-required

#4143 Operator changes for auto-MTU
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required

#4122 Update release tests
  release-scripts/tests/test_projectcalico_docs_updated.py
Labels: docs-not-required, release-note-not-required

#4147 Update release tests
  release-scripts/tests/test_projectcalico_docs_updated.py
Labels: docs-not-required, release-note-not-required

#3983 Add calico/node prerequisites for WG
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#4148 Updates for v3.16.5
  _data/versions.yml
  _includes/release-notes/v3.16.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#4149 Bump operator version
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4145 Update Windows doc for BGP
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#4158 Adding AWS src-dst-check setting to Felix configuration docs
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#4153 Remove aws-src-dst-check setting in the default config
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#4155 Documentation for calico kubectl plugin
  _includes/content/ctl-binary-install.md
  _includes/content/ctl-container-install.md
  _includes/content/ctl-kubectl-plugin-install.md
  getting-started/clis/calicoctl/configure/kdd.md
  getting-started/clis/calicoctl/configure/overview.md
  getting-started/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#4161 Cherry pick PR 4158, adding AWS src-dst-check config to Felix config
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#4165 Fix volume mounts
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#4166 Tuning auto-MTU by disabling encap
  networking/mtu.md
Labels: docs-not-required, release-note-not-required

#4141 ALP manifest update for Istio v1.7 and v1.6 support
  _includes/non-helm-manifests/dikastes-container
  _includes/non-helm-manifests/istio-app-layer-policy-v1.6.12.yaml
  _includes/non-helm-manifests/istio-app-layer-policy-v1.6.13.yaml
  _includes/non-helm-manifests/istio-app-layer-policy-v1.7.3.yaml
  _includes/non-helm-manifests/istio-app-layer-policy-v1.7.4.yaml
  _plugins/tabs.rb
  getting-started/kubernetes/requirements.md
  manifests/alp/istio-app-layer-policy-v1.6.yaml
  manifests/alp/istio-app-layer-policy-v1.7.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  security/app-layer-policy.md
  security/http-methods.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-not-required, release-note-required

#4168 Update CRDs
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-not-required, release-note-not-required

#4167 Update CRDs
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-not-required, release-note-not-required

#4169 Automated cherry pick of #4141: Update ALP manifests to support Istio versions 1.7 and 1.6
  _includes/non-helm-manifests/dikastes-container
  _includes/non-helm-manifests/istio-app-layer-policy-v1.6.12.yaml
  _includes/non-helm-manifests/istio-app-layer-policy-v1.6.13.yaml
  _includes/non-helm-manifests/istio-app-layer-policy-v1.7.3.yaml
  _includes/non-helm-manifests/istio-app-layer-policy-v1.7.4.yaml
  _plugins/tabs.rb
  getting-started/kubernetes/requirements.md
  manifests/alp/istio-app-layer-policy-v1.6.yaml
  manifests/alp/istio-app-layer-policy-v1.7.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  security/app-layer-policy.md
  security/http-methods.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-not-required, release-note-required

#4173 Fix names of config params
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#4175 Support powershell code snippets and update Windows docs
  getting-started/openshift/windows/installation.md
  getting-started/windows-calico/kubernetes/rancher.md
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/maintain.md
  getting-started/windows-calico/openshift/installation.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/troubleshoot.md
  js/code-select.js
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#4180 Improve eBPF docs:
  maintenance/ebpf/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#4182 Mount /var/lib/calico/ in container install doc
  _includes/content/docker-container-service.md
Labels: docs-not-required, release-note-not-required

#4172 Update requirements.md
  getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#4162 Update assign-ip-addresses-topology.md
  networking/assign-ip-addresses-topology.md
Labels: docs-not-required, release-note-not-required

#4176 windows: Support GCE
  scripts/install-calico-windows.ps1
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3743 Remove Flannel with WG MTU explanation
  networking/mtu.md
Labels: docs-not-required, release-note-not-required

#4178 pick: Support powershell code snippets and update Windows docs (#4175)
  getting-started/openshift/windows/installation.md
  getting-started/windows-calico/kubernetes/rancher.md
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/maintain.md
  getting-started/windows-calico/openshift/installation.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/troubleshoot.md
  js/code-select.js
Labels: docs-not-required, release-note-not-required

#4187 Remove EoL Istio-v1.4 references in ALP doc
  security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#4188 Automated cherry pick of #4187: Remove EoL Istio-v1.4 references in ALP doc
  security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#4183 Fix HEP example to include expectedIPs
  security/kubernetes-node-ports.md
Labels: docs-not-required, release-note-not-required

#4193 Set VXLANMode to CrossSubnet
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#4194 Remove config to disable aws-src-dst-check in release v3.17
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-required

#4195 Don't hardcode canal MTU
  _includes/charts/calico/templates/calico-config.yaml
Labels: docs-not-required, release-note-not-required

#4196 Automated cherry pick of #4195: Don't hardcode canal MTU
  _includes/charts/calico/templates/calico-config.yaml
Labels: docs-not-required, release-note-not-required

#4200 fixing 1 missing word
  about/about-kubernetes-networking.md
Labels: docs-not-required, release-note-not-required

#4205 Make deleted an optional field
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_blockaffinities.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-not-required, release-note-not-required

#4207 Updates for v3.17.0
  AUTHORS.md
  _data/versions.yml
  _includes/release-notes/v3.17.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#4208 Fix release notes
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4210 Fix post release tests
  release-scripts/tests/test_images.py
  release-scripts/tests/test_openstack_artifacts.py
  release-scripts/tests/test_projectcalico_docs_updated.py
  release-scripts/tests/test_tags_tars.py
  release-scripts/tests/test_windows_artifacts.py
Labels: docs-not-required, release-note-not-required

#4213 Cherry pick of #4210 to fix tests
  release-scripts/tests/test_images.py
  release-scripts/tests/test_openstack_artifacts.py
  release-scripts/tests/test_projectcalico_docs_updated.py
  release-scripts/tests/test_tags_tars.py
  release-scripts/tests/test_windows_artifacts.py
Labels: docs-not-required, release-note-not-required

#4214 Cleanups for v3.17 release
  RELEASING.md
  _data/archives.yml
  _includes/release-notes/v3.17.0-release-notes.md
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4215 Fix archiving instructions
  RELEASING.md
  _data/archives.yml
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4217 Fix release note typos
  _includes/release-notes/v3.17.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#4204 update helm templating machinery to v3
  Makefile
  _includes/charts/tigera-operator/Chart.yaml
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  _includes/charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml
  _plugins/helm.rb
Labels: docs-not-required, release-note-not-required

#4206 Docs-calico-hardway
  getting-started/kubernetes/hardway/overview.md
Labels: docs-not-required, release-note-not-required

#4230 fix helm v3 rendering bug
  _plugins/helm.rb
Labels: docs-not-required, release-note-not-required

#4228 update Installation crds
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required

#4229 cherry-pick: update Installation crds
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required

#4231 Fix CRD rendering bugs introduced by helm v3
  Makefile
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_blockaffinities.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_clusterinformations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworksets.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_hostendpoints.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamblocks.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamconfigs.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamhandles.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networksets.yaml
  _plugins/helm.rb
Labels: docs-not-required, release-note-not-required
