Repository projectcalico/calico, pull requests merged in 2020-09, with the labels that each got.

#3959 Remove leading space in calicoctl install commands
  _includes/content/ctl-binary-install.md
  _includes/content/ctl-container-install.md
Labels: docs-not-required, release-note-not-required

#3963 Update k8s versions to include v1.19
  getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#3965 Docs-windows-nav-fix
  _data/navbars/getting-started.yml
Labels: docs-not-required, release-note-not-required

#3961 Update felix configuration for encap rule configuration
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3968 Automated cherry pick of #3961: Update felix configuration for encap rule configuration
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3970 Revert "Automated cherry pick of #3961: Update felix configuration for encap rule configuration"
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3964 Add about ingress
  _data/navbars/about.yml
  about/about-kubernetes-ingress.md
  images/ingres-external.svg
  images/ingress-external-direct-to-pods.svg
  images/ingress-external-node-ports.svg
  images/ingress-in-cluster-nlb-local.svg
  images/ingress-in-cluster.svg
Labels: docs-not-required, release-note-not-required

#3974 Automated cherry pick of #3964: Add about ingress
  _data/navbars/about.yml
  about/about-kubernetes-ingress.md
  images/ingres-external.svg
  images/ingress-external-direct-to-pods.svg
  images/ingress-external-node-ports.svg
  images/ingress-in-cluster-nlb-local.svg
  images/ingress-in-cluster.svg
Labels: docs-not-required, release-note-not-required

#3973 Fix about network policy typo
  about/about-network-policy.md
Labels: docs-not-required, release-note-not-required

#3971 Update calicoctl datastore migrate documentation to include KubeControllerConfigurations
  reference/calicoctl/datastore/migrate/export.md
Labels: docs-not-required, release-note-not-required

#3975 Update calicoctl datastore migrate documentation to include KubeControllerConfigurations
  reference/calicoctl/datastore/migrate/export.md
Labels: docs-not-required, release-note-not-required

#3976 Update calicoctl datastore migrate documentation to include KubeControllerConfigurations
  reference/calicoctl/datastore/migrate/export.md
Labels: docs-not-required, release-note-not-required

#3957 Adding OpenShift/EKS instructions for WireGuard installation
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3914 Add simple policy demo for Windows
  _data/navbars/getting-started.yml
  getting-started/windows-calico/demo.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3890 Update docs for calicoctl version --poll
  _includes/non-helm-manifests/calicoctl-etcd.yaml
  _includes/non-helm-manifests/calicoctl.yaml
  reference/calicoctl/version.md
Labels: docs-not-required, release-note-not-required

#3985 Updates for Calico v3.16.1
  _data/versions.yml
  _includes/release-notes/v3.16.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#3984 Updates for Calico v3.15.3
  _data/versions.yml
  _includes/release-notes/v3.15.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#3986 Pick Add Windows archive from node release to Calico release (#3953)
  Makefile
Labels: docs-not-required, release-note-not-required

#3967 Automated cherry pick of #3961: Update felix configuration for encap rule configuration
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3972 Automated cherry pick of #3961: Update felix configuration for encap rule configuration
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3990 operator runs on Linux nodes only
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3991 Cherry-pick operator runs on Linux nodes only
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3978 Automated cherry pick of #3973: Fix about network policy typo
  about/about-network-policy.md
Labels: docs-not-required, release-note-not-required

#3982 Cherry-pick Add simple policy demo for Windows (#3914)
  _data/navbars/getting-started.yml
  getting-started/windows-calico/demo.md
Labels: docs-not-required, release-note-not-required

#4002 Update platforms that are known-working for Calico with OpenStack
  _includes/content/reqs-sys.md
  reference/architecture/overview.md
Labels: docs-not-required, release-note-not-required

#3999 Fix 'Standard install' link
  _data/navbars/getting-started.yml
Labels: docs-not-required, release-note-not-required

#3994 Update operator to v1.10.3
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4007 use fully qualified docker image names
  _config.yml
Labels: docs-not-required, release-note-not-required

#4008 Update multiple dataplanes image
  images/intro/multiple-dataplanes.png
Labels: docs-not-required, release-note-not-required

#4001 Add CNI log host mounts
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3992 Update broken links
  getting-started/windows-calico/standard.md
  networking/determine-best-networking.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#4009 Automated cherry pick of #4008: Update multiple dataplanes image
  images/intro/multiple-dataplanes.png
Labels: docs-not-required, merge-when-ready, release-note-not-required

#3998 feature(Windows): Allow to automatically set up Calico kubeconfig when no platform is identified
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#3997 feature(Windows): Allow to specify etcd TLS filepaths or auto download them in installation script
  getting-started/windows-calico/quickstart.md
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#4011 Update releases latest & nightly presentation
  releases.md
Labels: docs-not-required, release-note-not-required

#4013 Docs-ebpf-toc-missing
  _data/navbars/maintenance.yml
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required, squash-commits

#4014 Automated cherry pick of #4011: Update releases latest & nightly presentation
  releases.md
Labels: docs-not-required, release-note-not-required

#3949 Add post release tests for Windows artifacts
  Makefile
  release-scripts/tests/test_windows_artifacts.py
Labels: docs-not-required, release-note-not-required

#4010 Add about Kubernetes egress
  _data/navbars/about.yml
  about/about-kubernetes-egress.md
Labels: docs-not-required, release-note-not-required

#4018 Automated cherry pick of #4010: Add about Kubernetes egress
  _data/navbars/about.yml
  about/about-kubernetes-egress.md
Labels: docs-not-required, merge-when-ready, release-note-not-required, squash-commits

#4026 Cherry-pick #3392 and #3949
  Makefile
  getting-started/windows-calico/standard.md
  networking/determine-best-networking.md
  release-scripts/tests/test_windows_artifacts.py
Labels: docs-not-required, release-note-not-required

#4032 Update ebpf and eks doc
  maintenance/ebpf-and-eks.md
Labels: docs-not-required, release-note-not-required

#4034 Merge pull request #4032 from lwr20/lwr-ebpf-eks
  maintenance/ebpf-and-eks.md
Labels: docs-not-required, release-note-not-required

#4033 Doc for BGP password
  _data/navbars/security.yml
  reference/resources/bgppeer.md
  security/comms/secure-bgp.md
Labels: docs-pr-required, release-note-required

#4028 Docs-fix-istio
  _data/navbars/reference.yml
  _data/navbars/security.yml
  about/about-kubernetes-egress.md
  security/app-layer-policy.md
  security/enforce-policy-istio.md
Labels: docs-not-required, release-note-not-required
