Repository projectcalico/calico, pull requests merged in 2020-07, with the labels that each got.

#3733 Add enterprise to homepage and update community section
  images/intro/community.png
  introduction/index.md
Labels: docs-not-required, release-note-not-required

#3736 Automated cherry pick of #3733: Add enterprise to homepage
  images/intro/community.png
  introduction/index.md
Labels: docs-not-required, release-note-not-required

#3739 Automated cherry pick of #3738: Add learn more to homepage enterprise section
  introduction/index.md
Labels: docs-not-required, release-note-not-required

#3738 Add learn more to homepage enterprise section
  introduction/index.md
Labels: docs-not-required, release-note-not-required

#3734 Adjust edit-page and breadcrumbs styles
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3730 Automated cherry pick of #3728: Minor style tweaks. Change color of warn box, align
  _sass/bootstrap/bootstrap/_breadcrumbs.scss
  _sass/bootstrap/bootstrap/_type.scss
  _sass/bootstrap/bootstrap/_variables.scss
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3724 Automated cherry pick of #3712: Add in-line tabs and update k3s docs
  _plugins/tabs.rb
  css/style.scss
  getting-started/kubernetes/k3s/multi-node-install.md
  getting-started/kubernetes/k3s/quickstart.md
Labels: docs-not-required, release-note-not-required

#3725 Duplicate entry for FELIX_WIREGUARDMTU
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3753 Automated cherry pick of #3734: Adjust edit-page and breadcrumbs styles
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3755 Automated cherry pick of #3725: Duplicate entry for FELIX_WIREGUARDMTU
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3758 Updates for Calico v3.15.1
  _data/versions.yml
  _includes/release-notes/v3.15.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#3747 adding changes for branch deployment - release-v3.14
  netlify.toml
  netlify/Gemfile
  netlify/_config_noindex.yml
  netlify/_manifests_only.yml
Labels: docs-not-required, release-note-not-required

#3745 adding changes for branch deployment - release-v3.12
  netlify.toml
  netlify/Gemfile
  netlify/_config_noindex.yml
  netlify/_manifests_only.yml
Labels: docs-not-required, release-note-not-required

#3746 adding changes for branch deployment - release-v3.13
  netlify.toml
  netlify/Gemfile
  netlify/_config_noindex.yml
  netlify/_manifests_only.yml
Labels: docs-not-required, release-note-not-required

#3761 Docs-update-contributions
  CONTRIBUTING_DOCS.md
Labels: docs-not-required, release-note-not-required

#3759 K3s documentation and tabs update
  _layouts/docwithnav.html
  _plugins/tabs.rb
  getting-started/kubernetes/k3s/multi-node-install.md
  getting-started/kubernetes/k3s/quickstart.md
  js/tabs.js
Labels: docs-not-required, release-note-not-required

#3771 Added FeatureDetectOverride description.
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3780 Always enable VXLAN
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3781 Automated cherry pick of #3780: Always enable VXLAN
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3782 Automated cherry pick of #3780: Always enable VXLAN
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3768 Replace Linux utils with an Inbuilt application
  _includes/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#3778 whitelist->allow-list, blacklist->deny-list
  DOC_STYLE_GUIDE.md
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  _includes/content/hostendpoints-upgrade.md
  maintenance/kubernetes-upgrade.md
  maintenance/openshift-upgrade.md
  reference/host-endpoints/objects.md
  security/adopt-zero-trust.md
  security/calico-enterprise/egress-access-controls.md
  security/comms/secure-metrics.md
  security/defend-dos-attack.md
  security/external-ips-policy.md
  security/kubernetes-nodes.md
  security/services-cluster-ips.md
Labels: docs-not-required, release-note-not-required

#3790 Update community image
  images/intro/community.png
Labels: docs-not-required, release-note-not-required

#3791 Automated cherry pick of #3790: Update community image
  images/intro/community.png
Labels: docs-not-required, release-note-not-required

#3793 Update to EKS doc
  getting-started/kubernetes/managed-public-cloud/eks.md
Labels: docs-not-required, release-note-not-required

#3796 Automated cherry pick of #3793: EKS doc limitation update. Fix: Typo
  getting-started/kubernetes/managed-public-cloud/eks.md
Labels: docs-not-required, release-note-not-required

#3787 adding destination to build, unforced redirects - release-v3.14
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3744 adding changes for branch deployment - release legacy
  netlify.toml
  netlify/_config_noindex.yml
  netlify/_manifests_only.yml
Labels: docs-not-required, release-note-not-required

#3789 adding destination to build, unforced redirects - release-v3.12
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3788 adding destination to build, unforced redirects - release-v3.13
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3798 Automated cherry pick of #3797: Update optimize anti-flicker ID
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3797 Update optimize anti-flicker ID
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3800 Add docs for BGP communities and ports
  reference/resources/bgpconfig.md
  reference/resources/bgppeer.md
Labels: docs-not-required, release-note-not-required

#3721 Add support for pod security policies to the operator
  _includes/charts/tigera-operator/templates/tigera-operator/02-podsecuritypolicy-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3804 Changes for v3.12.3
  _data/versions.yml
  _includes/release-notes/v3.12.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#3763 adding branch deployment changes for calico site - production
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3807 Revert "adding branch deployment changes for calico site - production"
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3805 Update configure networking
  networking/bgp.md
  networking/configuring.md
  networking/workloads-outside-cluster.md
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#3792 adding changes for calico site branch deployment - nightly/master
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3808 adding branch deployment changes for calico site - production
  netlify.toml
  netlify/Gemfile
  netlify/_redirects
  releases.md
Labels: docs-not-required, release-note-not-required

#3811 adding manifest only build for production
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3813 Update CRDs
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-not-required, release-note-not-required

#3814 [cherry pick] adding manifest only build for production (#3811)
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3803 Change command for cni-plugin
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3817 adding redirect for latest /version to /
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3812 Calico CNI in EKS - manifest changes
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3823 Add OCP operator deployment manifest that excludes initContainer
  manifests/ocp/tigera-operator/02-tigera-operator-no-resource-loading.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3824 Update BGP communities docs
  reference/resources/bgpconfig.md
Labels: docs-not-required, release-note-not-required

#3799 Update operator version to latest release branch
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3652 Doc update for AWS source-destination-check
  _includes/charts/calico/templates/calico-node.yaml
  getting-started/kubernetes/hardway/standing-up-kubernetes.md
  manifests/calico-vxlan.yaml
  reference/faq.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3827 Update readme license description & add enterprise
  README.md
Labels: docs-not-required, release-note-not-required

#3779 Update operator RBAC
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: cherry-pick-candidate, docs-not-required, hold-merge, release-note-not-required

#3826 Add note on integrating an OpenShift install with OLM
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#3829 release-v3.14 - pick operator manifest changes
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-tigera-operator-no-resource-loading.yaml
Labels: docs-not-required, release-note-not-required

#3831 Updates for Calico v3.13.5
  _data/versions.yml
  _includes/release-notes/v3.13.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#3832 Updates for Calico v3.14.2
  _data/versions.yml
  _includes/release-notes/v3.14.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#3830 release-v3.15 - pick operator manifest changes
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-tigera-operator-no-resource-loading.yaml
Labels: docs-not-required, hold-merge, release-note-not-required

#3375 Calico advanced policy tutorial counterpart
  _data/navbars/security.yml
  security/tutorials/calico-policy.md
Labels: docs-not-required, release-note-not-required

#3844 Update operator CRDs
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
Labels: docs-not-required, release-note-not-required
