Repository projectcalico/calico, pull requests merged in 2020-04, with the labels that each got.

#3409 Missing configmap get privs for flannel
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3410 Missing configmap get privs for flannel (apply it to all network modes)
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3385 kubecontrollersconfig resource definition
  _data/navbars/reference.yml
  _includes/charts/calico/crds/kdd/02-crd-kubecontrollersconfiguration.yaml
  reference/resources/kubecontrollersconfig.md
Labels: docs-pr-required, release-note-required

#3411 add redirects to test how google seo reacts
  netlify/_redirects
Labels: docs-not-required, release-note-not-required

#3413 RBAC for calico-kube-controllers to access KubeControllersConfig
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-pr-required, release-note-not-required

#3406 Docs-CLIs-folder
  _data/navbars/getting-started.yml
  getting-started/bare-metal/about.md
  getting-started/bare-metal/installation/binary-mgr.md
  getting-started/bare-metal/installation/binary.md
  getting-started/clis/calicoctl/configure/etcd.md
  getting-started/clis/calicoctl/configure/index.md
  getting-started/clis/calicoctl/configure/kdd.md
  getting-started/clis/calicoctl/configure/overview.md
  getting-started/clis/calicoctl/index.md
  getting-started/clis/calicoctl/install.md
  getting-started/kubernetes/managed-public-cloud/aks.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  getting-started/kubernetes/managed-public-cloud/iks.md
  getting-started/kubernetes/quickstart.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
  maintenance/decommissioning-a-node.md
  maintenance/kubernetes-upgrade.md
  maintenance/openstack-upgrade.md
  maintenance/troubleshooting.md
  networking/bgp.md
  networking/openstack/labels.md
  reference/calicoctl/apply.md
  reference/calicoctl/convert.md
  reference/calicoctl/create.md
  reference/calicoctl/delete.md
  reference/calicoctl/get.md
  reference/calicoctl/ipam/release.md
  reference/calicoctl/ipam/show.md
  reference/calicoctl/label.md
  reference/calicoctl/node/run.md
  reference/calicoctl/overview.md
  reference/calicoctl/patch.md
  reference/calicoctl/replace.md
  reference/calicoctl/version.md
  reference/etcd-rbac/kubernetes-advanced.md
  security/app-layer-policy.md
  security/comms/crypto-auth.md
  security/comms/secure-metrics.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-not-required, release-note-not-required

#3414 Missing configmap get privs for flannel (v3.13)
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3418 Fix typo in network policy manifest
  security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#3417 Fix broken link to Istio documentation
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-not-required, release-note-not-required

#3395 Update instructions for site preview
  CONTRIBUTING_DOCS.md
Labels: docs-not-required, release-note-not-required

#3421 Update calicoctl role to manage kubecontrollersconfigurations
  _includes/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#3364 Small addition to documentation
  security/calico-network-policy.md
Labels: docs-not-required, release-note-not-required

#3430 Fix IPIP comment in calico.yaml
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3400 Update CALICO_IPV4POOL_CIDR default value in docs
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#3433 Fix calicoctl link
  security/calico-network-policy.md
Labels: docs-pr-required, release-note-required

#3441 Document BPFDisableUnprivileged parameter.
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3437 Docs: change TOC for /Maintenance
  _data/navbars/maintenance.yml
  _includes/content/reqs-sys.md
  getting-started/kubernetes/quickstart.md
  maintenance/monitor/index.md
  maintenance/troubleshoot/component-logs.md
  maintenance/troubleshoot/index.md
  maintenance/troubleshoot/troubleshooting.md
Labels: docs-pr-required, release-note-required

#3444 Docs: add reference to canal
  getting-started/kubernetes/flannel/flannel.md
Labels: docs-pr-required, release-note-required

#3447 Update k8s tutorials to work with k8s 1.18
  security/tutorials/kubernetes-policy-advanced.md
  security/tutorials/kubernetes-policy-basic.md
Labels: docs-not-required, release-note-required

#3449 Add reference docs for routesource
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3434 monitor-component-metrics.md complete rewrite.
  maintenance/monitor-component-metrics.md
Labels: docs-not-required, release-note-not-required

#3453 Updates for Calico v3.13.3
  _data/versions.yml
  _includes/release-notes/v3.13.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#3436 Add GlobalNetworkPolicy short name
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkpolicy.yaml
  upgrade/v2.5/manifests/crds.yaml
Labels: docs-not-required, release-note-not-required

#3428 Fixed typo in calicoctl alias
  _includes/content/ctl-container-install.md
Labels: docs-not-required, release-note-not-required

#3464 Add free training button to top nav
  _layouts/docwithnav.html
  css/style.scss
Labels: docs-pr-required, release-note-required

#3465 Add free training button to top nav (#3464)
  _layouts/docwithnav.html
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3429 move archive docs and redirect users to latest
  netlify.toml
  netlify/_manifests_only.yml
  netlify/_redirects
  netlify/build.sh
  releases.md
  robots.txt
Labels: docs-not-required, release-note-not-required

#3462 Improve BPF docs and manifests.
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  getting-started/kubernetes/trying-ebpf.md
Labels: docs-not-required, release-note-not-required

#3474 Fix typo.
  _includes/charts/calico/templates/calico-config.yaml
Labels: docs-not-required, release-note-not-required

#3476 Add note for recent kubectl version
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#3473 Left nav free training
  _layouts/docwithnav.html
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3479 fix baseurl bug for archive releases
  netlify/build.sh
  releases.md
Labels: docs-not-required, release-note-not-required

#3478 use new archive path in links to old releases
  releases.md
Labels: docs-pr-required, release-note-required

#3461 Add kube-controllers deployment to Canal
  _includes/charts/calico/templates/calico-kube-controllers.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3480 Automated cherry pick of #3473: Left nav free training
  _layouts/docwithnav.html
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3477 Add reference doc for RouteTableRange
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3481 Remove duplicate word in cni-plugin configuration readme.
  reference/cni-plugin/configuration.md
Labels: docs-not-required, release-note-not-required

#3471 IPAM configure and show-borrowed/configuration
  _data/navbars/reference.yml
  reference/calicoctl/ipam/configure.md
  reference/calicoctl/ipam/overview.md
  reference/calicoctl/ipam/show.md
Labels: docs-not-required, release-note-not-required

#3483 add optional noindex
  _config.yml
  _layouts/docwithnav.html
  netlify.toml
  netlify/_config_noindex.yml
  netlify/build.sh
Labels: docs-not-required, release-note-not-required

#3482 operator-init container needs to create kubecontrollersconfigurations
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#3459 eBPF use of VXLAN MTU settings.
  networking/mtu.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3485 Fix navbar
  _layouts/docwithnav.html
  css/sidebar.scss
Labels: docs-not-required, release-note-not-required

#3487 Fix navbar (#3485)
  _layouts/docwithnav.html
  css/sidebar.scss
Labels: docs-not-required, release-note-not-required

#3488 Fix navbar (#3485)
  _layouts/docwithnav.html
  css/sidebar.scss
Labels: docs-not-required, release-note-not-required

#3489 Add draft release notes for v3.14.0
  _includes/release-notes/v3.14.0-pre-release-notes.md
Labels: docs-not-required, release-note-not-required

#3490 Remove master redirects
  netlify/_redirects
Labels: docs-not-required, release-note-not-required

#3493 add optional noindex (#3483)
  _config.yml
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#3491 add optional noindex (#3483)
  _config.yml
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3494 noindex v3.12
  _config.yml
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#3486 archives: build latest release
  netlify/build.sh
Labels: docs-not-required, release-note-not-required

#3496 calicoctl ClusterRole: add ipamconfigs permission
  _includes/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-not-required
