Repository projectcalico/calico, pull requests merged in 2020-12, with the labels that each got.

#4236 Allow hostPath volumeMount in tigera-operator PSP
  _includes/charts/tigera-operator/templates/tigera-operator/02-podsecuritypolicy-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#4232 have helm not manage calico crds
  _includes/charts/tigera-operator/crds/calico
  _includes/charts/tigera-operator/templates/crds/calico
  _plugins/helm.rb
  manifests/ocp/crds/calico
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#4238 Automated cherry pick of #4236: Allow hostPath volumeMount in tigera-operator PSP
  _includes/charts/tigera-operator/templates/tigera-operator/02-podsecuritypolicy-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#4225 Docs-add-space
  reference/architecture/overview.md
Labels: docs-not-required, release-note-not-required

#4239 calicoctl --context update
  reference/calicoctl/apply.md
  reference/calicoctl/create.md
  reference/calicoctl/delete.md
  reference/calicoctl/get.md
  reference/calicoctl/label.md
  reference/calicoctl/overview.md
  reference/calicoctl/patch.md
  reference/calicoctl/replace.md
Labels: docs-not-required, release-note-not-required

#4245 Update default datastore documentation
  getting-started/clis/calicoctl/configure/etcd.md
  getting-started/clis/calicoctl/configure/kdd.md
  reference/kube-controllers/configuration.md
  reference/node/configuration.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#4246 Automated cherry pick of #4245: With v3.17.0 the default datastore is kubernetes
  getting-started/clis/calicoctl/configure/etcd.md
  getting-started/clis/calicoctl/configure/kdd.md
  reference/kube-controllers/configuration.md
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#4250 Fix in-cluster ingress with NLB local diagram
  images/ingress-in-cluster-nlb-local.svg
Labels: docs-not-required, release-note-not-required

#4251 Automated cherry pick of #4250: Fix in-cluster ingress with NLB local diagram
  images/ingress-in-cluster-nlb-local.svg
Labels: docs-not-required, release-note-not-required

#4252 Updates for Calico v3.17.1
  _data/versions.yml
  _includes/release-notes/v3.17.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#4191 Fixed doc typo error.
  reference/resources/workloadendpoint.md
Labels: docs-not-required, release-note-not-required

#4253 Add doc for BGPPeer SourceAddress field
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  reference/resources/bgppeer.md
Labels: docs-not-required, release-note-required

#4240 Add K3s Geek details.
  getting-started/kubernetes/k3s/multi-node-install.md
  getting-started/kubernetes/k3s/quickstart.md
Labels: docs-not-required, release-note-not-required

#4199 about-networking.md
  about/about-networking.md
Labels: docs-not-required, release-note-not-required

#4261 Remove bgppeer KeepOriginalNextHop default
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
Labels: docs-not-required, merge-when-ready, release-note-not-required

#4263 update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4269 Automated cherry pick of #4263: update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4268 Automated cherry pick of #4263: update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4267 Automated cherry pick of #4263: update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4266 Automated cherry pick of #4263: update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4265 Automated cherry pick of #4263: update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4264 Automated cherry pick of #4263: update enterprise trial url
  _includes/enterprise_header.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4258 Streamline EKS BPF enablement
  maintenance/ebpf/ebpf-and-eks.md
  maintenance/ebpf/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#4272 Automated cherry pick of #4258: Streamline EKS BPF enablement
  maintenance/ebpf/ebpf-and-eks.md
  maintenance/ebpf/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#4274 Remove bgppeer KeepOriginalNextHop default
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
Labels: docs-not-required, release-note-not-required

#4271 Remove site.prodname from Networking docs section
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#4283 Update authors file
  AUTHORS.md
Labels: docs-not-required, release-note-not-required
