Repository projectcalico/calico, pull requests merged in 2020-05, with the labels that each got.

#3497 calicoctl ClusterRole: add ipamconfigs permission
  _includes/non-helm-manifests/calicoctl.yaml
Labels: docs-not-required, release-note-not-required

#3500 Add note to documentation about nftables incompatibility in Calico legacy.
  v2.6/getting-started/docker/installation/requirements.md
Labels: docs-not-required, release-note-not-required

#3503 split rbac
  _includes/charts/calico/templates/calico-kube-controllers-rbac.yaml
  _includes/charts/calico/templates/calico-node-rbac.yaml
  manifests/rbac/rbac-etcd-calico.yaml
  manifests/rbac/rbac-etcd-flannel.yaml
  manifests/rbac/rbac-kdd-calico.yaml
  manifests/rbac/rbac-kdd-flannel.yaml
Labels: docs-pr-required, release-note-required

#3416 Document auto-heps feature
  _data/navbars/maintenance.yml
  _data/navbars/security.yml
  _includes/content/hostendpoints-upgrade.md
  _includes/content/install-openshift-manifests.md
  getting-started/openshift/installation.md
  maintenance/kubernetes-upgrade.md
  maintenance/openshift-upgrade.md
  maintenance/openstack-upgrade.md
  reference/kube-controllers/configuration.md
  reference/resources/hostendpoint.md
  security/kubernetes-nodes.md
  security/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#3510 release-v3.14 - Cherry-pick Document auto-heps feature (#3416)
  _data/navbars/maintenance.yml
  _data/navbars/security.yml
  _includes/content/hostendpoints-upgrade.md
  _includes/content/install-openshift-manifests.md
  getting-started/openshift/installation.md
  maintenance/kubernetes-upgrade.md
  maintenance/openshift-upgrade.md
  maintenance/openstack-upgrade.md
  reference/kube-controllers/configuration.md
  reference/resources/hostendpoint.md
  security/kubernetes-nodes.md
  security/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#3504 Remove getting-started/kubernetes/installation/index
  getting-started/kubernetes/installation/index.md
  getting-started/kubernetes/quickstart.md
  netlify/_redirects
  security/tutorials/app-layer-policy/enforce-policy-istio.md
  security/tutorials/kubernetes-policy-basic.md
Labels: docs-not-required, release-note-not-required

#3513 Update hostendpoint.md
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#3509 Add FQDN for SEO
  security/calico-enterprise/egress-access-controls.md
Labels: docs-not-required, release-note-not-required

#3511 Fix release notes breadcrumbs path
  _data/navbars/release-notes.yml
Labels: docs-not-required, release-note-not-required

#3516 Upgrade docs fixes
  _includes/content/auto-hostendpoints-migrate.md
  _includes/content/hostendpoints-upgrade.md
  _includes/content/install-openshift-manifests.md
  maintenance/kubernetes-upgrade.md
  maintenance/openshift-upgrade.md
  maintenance/openstack-upgrade.md
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#3518 release-v3.14 - Cherry-pick Upgrade docs fixes (#3516)
  _includes/content/auto-hostendpoints-migrate.md
  _includes/content/hostendpoints-upgrade.md
  _includes/content/install-openshift-manifests.md
  maintenance/kubernetes-upgrade.md
  maintenance/openshift-upgrade.md
  maintenance/openstack-upgrade.md
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#3508 Add top-level Calico Enterprise content [WIP - do not merge]
  _data/navbars/calico-enterprise.yml
  calico-enterprise/index.md
  images/calico-enterprise-logo-64px.png
  images/calico-logo-64px.png
Labels: docs-not-required, release-note-not-required

#3519 cherry-pick calico-enterprise content
  _data/navbars/calico-enterprise.yml
  calico-enterprise/index.md
  images/calico-enterprise-logo-64px.png
  images/calico-logo-64px.png
Labels: docs-not-required, release-note-not-required

#3515 upstream small docs fixes
  _data/navbars/maintenance.yml
  _includes/charts/calico/templates/calico-config.yaml
  _plugins/values.rb
  getting-started/kubernetes/trying-ebpf.md
  maintenance/monitor/monitor-component-metrics.md
  security/tutorials/kubernetes-policy-advanced.md
Labels: docs-not-required, release-note-not-required

#3522 release-v3.14 - Cherry-pick some recent changes from master
  _data/navbars/release-notes.yml
  getting-started/kubernetes/installation/index.md
  getting-started/kubernetes/quickstart.md
  netlify/_redirects
  security/calico-enterprise/egress-access-controls.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
  security/tutorials/kubernetes-policy-basic.md
Labels: docs-not-required, release-note-not-required

#3521 Add top-level Calico Enterprise content [WIP - do not merge] (#3508)
  _data/navbars/calico-enterprise.yml
  calico-enterprise/index.md
  images/calico-enterprise-logo-64px.png
  images/calico-logo-64px.png
Labels: docs-not-required, release-note-not-required

#3524 Update docs for Calico v3.14.0
  AUTHORS.md
  _data/versions.yml
  _includes/release-notes/v3.14.0-pre-release-notes.md
  _includes/release-notes/v3.14.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3525 Promote v3.14 to latest release
  _data/archives.yml
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3527 Fix whitespace on releases page
  releases.md
Labels: docs-not-required, release-note-not-required

#3528 Fix versions yaml
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3526 Fix whitespace on releases page
  releases.md
Labels: docs-not-required, release-note-not-required

#3531 Fix redirects for v3.14
  RELEASING.md
  netlify/_redirects
Labels: docs-not-required, release-note-not-required

#3532 Add v3.13 to archive
  _data/archives.yml
Labels: docs-not-required, release-note-not-required

#3535 require openshift 4.3 or newer
  getting-started/openshift/installation.md
  getting-started/openshift/requirements.md
Labels: docs-not-required, release-note-not-required

#3505 Encryption config settings.
  reference/resources/felixconfig.md
  reference/resources/node.md
Labels: docs-not-required, release-note-not-required

#3537 Cherry-pick #3505 from master into release-v3.14
  reference/resources/felixconfig.md
  reference/resources/node.md
Labels: docs-not-required, release-note-not-required

#3517 Adding WireGuard encryption doc.
  _data/navbars/security.yml
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3546 Cherry-pick #3517 from master into release-v3.14
  _data/navbars/security.yml
  security/try-node-to-node-encryption.md
Labels: docs-pr-required, release-note-not-required

#3555 Make release notes nav clearer
  release-notes/index.md
Labels: docs-not-required, release-note-not-required

#3556 Update Operator CRD and API reference
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3557 Make release notes nav clearer (#3555)
  release-notes/index.md
Labels: docs-not-required, release-note-not-required

#3559 make nav clearer
  v1.5/releases/index.md
  v1.6/releases/index.md
  v2.0/releases/index.md
  v2.1/releases/index.md
  v2.2/releases/index.md
  v2.3/releases/index.md
  v2.4/releases/index.md
  v2.5/releases/index.md
  v2.6/releases/index.md
  v3.0/releases/index.md
  v3.1/releases/index.md
  v3.10/release-notes/index.md
  v3.11/release-notes/index.md
  v3.2/releases/index.md
  v3.3/releases/index.md
  v3.4/releases/index.md
  v3.5/releases/index.md
  v3.6/release-notes/index.md
  v3.7/release-notes/index.md
  v3.8/release-notes/index.md
  v3.9/release-notes/index.md
Labels: docs-not-required, release-note-not-required

#3560 Make release notes nav clearer (#3555)
  release-notes/index.md
Labels: docs-not-required, release-note-not-required

#3558 Make release notes nav clearer (#3555)
  release-notes/index.md
Labels: docs-not-required, release-note-not-required

#3554 Itechart/update instantsearch
  _layouts/docwithnav.html
  css/instantsearch/instantsearch.min.css
  css/search.scss
  js/algoliasearch/algoliasearch.min.js
  js/instantsearch/instantsearch.min.js
  js/searchConfig.js
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3542 Added Kubernetes compatibility to release notes
  _includes/release-notes/v3.12.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3472 How to Visualize metrics using Grafana
  _data/navbars/maintenance.yml
  maintenance/monitor/monitor-component-metrics.md
  maintenance/monitor/monitor-component-visual.md
Labels: docs-not-required, release-note-not-required

#3563 Remove Calico Enterprise only option
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3568 Improve overlay how-to VXLAN vs IPIP clarity
  networking/vxlan-ipip.md
Labels: docs-not-required, release-note-not-required

#3565 Approximately match new www top-nav
  _layouts/docwithnav.html
  _sass/bootstrap/bootstrap/_variables.scss
  css/style.scss
  css/variables.scss
  images/brand.png
Labels: docs-not-required, release-note-not-required

#3573 Automated cherry pick of #3568: Improve overlay how-to VXLAN vs IPIP clarity
  networking/vxlan-ipip.md
Labels: docs-not-required, release-note-not-required

#3572 Apply fixes from master to release-v3.14
  _layouts/docwithnav.html
  css/instantsearch/instantsearch.min.css
  css/search.scss
  js/algoliasearch/algoliasearch.min.js
  js/instantsearch/instantsearch.min.js
  js/searchConfig.js
Labels: docs-pr-required, release-note-required

#3571 Apply fixes from master to release-v3.13
  _layouts/docwithnav.html
  css/instantsearch/instantsearch.min.css
  css/search.scss
  js/algoliasearch/algoliasearch.min.js
  js/instantsearch/instantsearch.min.js
  js/script.js
  js/searchConfig.js
Labels: docs-not-required, release-note-not-required

#3501 Fix templates nits
  _includes/charts/calico/crds/kdd/02-crd-kubecontrollersconfiguration.yaml
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node-rbac.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
Labels: docs-not-required, release-note-not-required

#3574 Automated cherry pick of #3565: Approximately match new www top-nav
  _layouts/docwithnav.html
  _sass/bootstrap/bootstrap/_variables.scss
  css/style.scss
  css/variables.scss
  images/brand.png
Labels: docs-not-required, release-note-not-required

#3570 Apply fixes from master to release-v3.12
  _includes/version_warning.html
  _layouts/docwithnav.html
  _sass/bootstrap/bootstrap/_variables.scss
  css/instantsearch/instantsearch.min.css
  css/search.scss
  css/sidebar.scss
  css/style.scss
  js/algoliasearch/algoliasearch.min.js
  js/instantsearch/instantsearch.min.js
  js/script.js
  js/scrollPage.js
  js/searchConfig.js
Labels: docs-not-required, release-note-not-required

#3506 Update "Hard Way" tutorial to the latest version of Calico
  getting-started/kubernetes/hardway/install-cni-plugin.md
  getting-started/kubernetes/hardway/install-node.md
  getting-started/kubernetes/hardway/standing-up-kubernetes.md
  getting-started/kubernetes/hardway/the-calico-datastore.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3576 Cherry-pick Fix description for landing page (#3575)
  security/kubernetes-nodes.md
Labels: docs-not-required, release-note-not-required

#3580 Add Kubernetes API server port (6443) to failsafes
  reference/felix/configuration.md
  reference/host-endpoints/failsafe.md
  reference/resources/felixconfig.md
  security/protect-hosts.md
Labels: docs-completed, release-note-not-required

#3562 Doc: fix external links
  _data/navbars/security.yml
  security/try-node-to-node-encryption.md
Labels: docs-pr-required, release-note-required

#3586 Update more doc about failsafe ports including 6443
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-completed, release-note-not-required

#3587 Add 6443 to failsafe ports - for release-v3.14
  reference/felix/configuration.md
  reference/host-endpoints/failsafe.md
  reference/resources/felixconfig.md
  security/protect-hosts.md
Labels: docs-completed, release-note-not-required

#3581 Add instructions for Calico networking on EKS
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/geek-details/routing-calico.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  manifests/calico-vxlan.yaml
Labels: docs-not-required, release-note-not-required

#3588 Automated cherry pick of #3581: Add instructions for Calico networking on EKS
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/geek-details/routing-calico.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  manifests/calico-vxlan.yaml
Labels: docs-not-required, release-note-not-required

#3579 Update CRDs with auto-generated files from libcalico-go
  _includes/charts/calico/crds/kdd/02-crd-bgpconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-bgppeer.yaml
  _includes/charts/calico/crds/kdd/02-crd-blockaffinity.yaml
  _includes/charts/calico/crds/kdd/02-crd-clusterinformation.yaml
  _includes/charts/calico/crds/kdd/02-crd-felixconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkpolicy.yaml
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkset.yaml
  _includes/charts/calico/crds/kdd/02-crd-hostendpoint.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamblock.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamconfig.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamhandle.yaml
  _includes/charts/calico/crds/kdd/02-crd-ippool.yaml
  _includes/charts/calico/crds/kdd/02-crd-kubecontrollersconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-networkpolicy.yaml
  _includes/charts/calico/crds/kdd/02-crd-networkset.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_blockaffinities.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_clusterinformations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworksets.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_hostendpoints.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamblocks.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamconfigs.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamhandles.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networksets.yaml
Labels: docs-not-required, release-note-required

#3602 Document BPFKubeProxyEndpointSlicesEnabled config field
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-completed, release-note-not-required

#3592 BPFKubeProxyEndpointSlicesEnabled explained
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3598 Updates for release v3.8.9
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.9-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3599 Updates for release v3.9.6
  _data/versions.yml
  _includes/v3.9/release-notes/v3.9.6-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3600 Updates for release v3.10.4
  _data/versions.yml
  _includes/v3.10/release-notes/v3.10.4-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3601 Updates for release v3.11.3
  _data/versions.yml
  _includes/v3.11/release-notes/v3.11.3-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3596 Updates for release v3.12.2
  _data/versions.yml
  _includes/release-notes/v3.12.2-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3608 Fix manifests location for release archive
  Makefile
Labels: docs-not-required, release-note-not-required

#3595 Updates for release v3.13.4
  _data/versions.yml
  _includes/release-notes/v3.13.4-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3355 fix code formatting typo on kube-controllers reference
  reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#3594 Updates for release v3.14.1
  _data/versions.yml
  _includes/release-notes/v3.14.1-release-notes.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3611 Fix post-release tests for v3.12
  _includes/component_url
  release-scripts/tests/test_openstack_artifacts.py
  release-scripts/tests/test_tags_tars.py
Labels: docs-not-required, release-note-not-required

#3267 How to: change IPPool block size
  _data/navbars/networking.yml
  networking/change-block-size.md
Labels: docs-not-required, release-note-not-required

#3567 Cherry-pick - Fix incorrect documentation of AUTO_HOST_ENDPOINTS
  reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#3603 Fix broken font awesome icons
  _layouts/docwithnav.html
  css/font-awesome/font-awesome.min.css
  fonts/font-awesome/FontAwesome.otf
  fonts/font-awesome/fontawesome-webfont.eot
  fonts/font-awesome/fontawesome-webfont.svg
  fonts/font-awesome/fontawesome-webfont.ttf
  fonts/font-awesome/fontawesome-webfont.woff
  fonts/font-awesome/fontawesome-webfont.woff2
Labels: docs-not-required, release-note-not-required
