Repository projectcalico/calico, pull requests merged in 2020-03, with the labels that each got.

#3293 Fix external links networking
  networking/advertise-service-ips.md
  networking/assign-ip-addresses-topology.md
  networking/determine-best-networking.md
  networking/dual-stack.md
  networking/external-connectivity.md
  networking/get-started-ip-addresses.md
  networking/ipv6.md
  networking/migrate-pools.md
  networking/openstack/multiple-regions.md
  networking/openstack/neutron-api.md
  networking/openstack/semantics.md
  networking/use-ipvs.md
Labels: docs-pr-required, release-note-required

#3289 BPF docs
  _data/navbars/getting-started.yml
  getting-started/kubernetes/trying-ebpf.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, hold-merge, release-note-required

#3297 Security updates
  _data/navbars/security.yml
  security/external-ips-policy.md
  security/get-started.md
  security/icmp-ping.md
  security/kubernetes-policy.md
  security/namespace-policy.md
  security/policy-rules-overview.md
  security/policy-rules.md
  security/service-accounts.md
  security/tutorials/kubernetes-policy-demo/kubernetes-demo.md
Labels: docs-pr-required, release-note-required

#3295 Update training link
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3298 Tweak BPF instructions and manifests:
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-node.yaml
  getting-started/kubernetes/trying-ebpf.md
Labels: docs-pr-required, release-note-required

#3299 Update docs after pod cidr autodetect changes
  _includes/content/pod-cidr-sed.md
  getting-started/kubernetes/flannel/flannel.md
  getting-started/kubernetes/quickstart.md
Labels: docs-not-required, release-note-not-required

#3301 Netlify configuration for v3.13 candidate
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3302 Install-TOC-change
  _data/navbars/getting-started.yml
Labels: docs-pr-required, release-note-required

#3304 Fix incorrect comment in manifest.
  _includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#3305 Cherry pick install toc update (#3302)
  _data/navbars/getting-started.yml
Labels: docs-not-required, release-note-not-required

#3307 Fix 'edit this page' for release-legacy
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#3306 Move doc
  _data/navbars/networking.yml
Labels: docs-pr-required, release-note-required

#3300 Update for Operator v1.1.2
  _data/versions.yml
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3303 calico-kube-controllers manages heps
  _includes/charts/calico/templates/rbac.yaml
Labels: docs-not-required, release-note-not-required

#3310 Updates for Calico v3.13.0
  AUTHORS.md
  Makefile
  _data/versions.yml
  _includes/v3.13/release-notes/v3.13.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3313 Add in calico migration controllers
  _data/versions.yml
Labels: docs-pr-required, release-note-required

#3314 Promote v3.13 to latest
  netlify.toml
Labels: docs-not-required, release-note-not-required

#3318 Add v3.12 to archive
  _data/archives.yml
Labels: docs-not-required, release-note-not-required

#3319 Add release notes
  _includes/release-notes/v3.13.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3320 Fix release note script to use correct location
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#3321 Fix curling master manifest
  getting-started/kubernetes/self-managed-public-cloud/gce.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3324 Automated cherry pick of #3320: Fix release note script to use correct location
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#3323 Automated cherry pick of #3320: Fix release note script to use correct location
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#3325 [r3.13-pick3321] Fix curling master manifest
  getting-started/kubernetes/self-managed-public-cloud/gce.md
Labels: docs-not-required, release-note-not-required

#3322 [r3.12-Pick 3321] Fix curling master manifest
  getting-started/kubernetes/self-managed-public-cloud/gce.md
Labels: docs-not-required, release-note-not-required

#3326 Fix display of release notes
  _data/versions.yml
  _includes/release-notes/v3.13.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3328 Update Operator reference and Install CRD
  _data/versions.yml
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  reference/installation/api.html
Labels: docs-pr-required, release-note-required

#3329 Typo in autodetection doc
  networking/ip-autodetection.md
Labels: docs-pr-required, release-note-required

#3331 Fix archives
  _data/archives.yml
Labels: docs-not-required, release-note-not-required

#3333 Cherry-pick Fix archives
  _data/archives.yml
Labels: docs-not-required, release-note-not-required

#3332 Build non-legacy archive versions correctly
  netlify/build.sh
  releases.md
Labels: docs-not-required, hold-merge, release-note-not-required

#3330 Update Operator CRD and API reference
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3336 Split Calico CRDs into individual files to use in Openshift install
  _includes/charts/calico/crds/kdd/02-crd-bgpconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-bgppeer.yaml
  _includes/charts/calico/crds/kdd/02-crd-blockaffinity.yaml
  _includes/charts/calico/crds/kdd/02-crd-clusterinformation.yaml
  _includes/charts/calico/crds/kdd/02-crd-felixconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkpolicy.yaml
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkset.yaml
  _includes/charts/calico/crds/kdd/02-crd-hostendpoint.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamblock.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamconfig.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamhandle.yaml
  _includes/charts/calico/crds/kdd/02-crd-ippool.yaml
  _includes/charts/calico/crds/kdd/02-crd-networkpolicy.yaml
  _includes/charts/calico/crds/kdd/02-crd-networkset.yaml
  _includes/charts/calico/templates/kdd-crds.yaml
  _includes/charts/tigera-operator/templates/crds/calico
  getting-started/openshift/installation.md
  manifests/ocp/crds/calico
Labels: docs-not-required, release-note-not-required

#3335 Fix whitespace on releases page
  releases.md
Labels: docs-not-required, release-note-not-required

#3343 Fix typo in OS doc
  security/calico-network-policy.md
Labels: docs-pr-required, release-note-required

#3338 Operator: Add initial resource init container for openshift
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-calicoctl-resources.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-tigera-install-script.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  _plugins/values.rb
  getting-started/openshift/installation.md
  manifests/ocp/tigera-operator/02-configmap-calicoctl-resources.yaml
  manifests/ocp/tigera-operator/02-configmap-tigera-install-script.yaml
Labels: docs-not-required, release-note-required

#3348 Align verbs in Maintenance
  _data/navbars/maintenance.yml
  maintenance/decommissioning-a-node.md
  maintenance/kubernetes-upgrade.md
  maintenance/openstack-upgrade.md
  maintenance/upgrading.md
Labels: docs-pr-required, release-note-required

#3350 Updates for Calico v3.13.1
  _data/versions.yml
  _includes/release-notes/v3.13.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#3349 Helmerator: initial commit
  .gitignore
  Makefile
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  _includes/charts/tigera-operator/templates/crs/custom-resources.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/00-namespace-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-calicoctl-resources.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-tigera-install-script.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  _plugins/values.rb
  manifests/ocp/crds/01-crd-installation.yaml
  manifests/ocp/crds/01-crd-tigerastatus.yaml
  manifests/ocp/tigera-operator/00-namespace-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-configmap-calicoctl-resources.yaml
  manifests/ocp/tigera-operator/02-configmap-tigera-install-script.yaml
  manifests/ocp/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-rolebinding-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-serviceaccount-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-tigera-operator.yaml
Labels: docs-pr-required, release-note-required

#3339 Fix copying code block to clipboard
  js/code-select.js
Labels: docs-not-required, release-note-not-required

#3356 release-v3.13 - Cherry-pick Fix copying code block to clipboard
  js/code-select.js
Labels: docs-not-required, release-note-not-required

#3357 release-v3.12 - Cherry-pick Fix copying code block to clipboard
  js/code-select.js
Labels: docs-not-required, release-note-not-required

#3363 Updates for Calico v3.8.7
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.7-release-notes.md
Labels: docs-not-required, release-note-not-required

#3353 Add install time resource for OpenShift [pick 3336, 3338, 3344]
  _includes/charts/calico/crds/kdd/02-crd-bgpconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-bgppeer.yaml
  _includes/charts/calico/crds/kdd/02-crd-blockaffinity.yaml
  _includes/charts/calico/crds/kdd/02-crd-clusterinformation.yaml
  _includes/charts/calico/crds/kdd/02-crd-felixconfiguration.yaml
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkpolicy.yaml
  _includes/charts/calico/crds/kdd/02-crd-globalnetworkset.yaml
  _includes/charts/calico/crds/kdd/02-crd-hostendpoint.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamblock.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamconfig.yaml
  _includes/charts/calico/crds/kdd/02-crd-ipamhandle.yaml
  _includes/charts/calico/crds/kdd/02-crd-ippool.yaml
  _includes/charts/calico/crds/kdd/02-crd-networkpolicy.yaml
  _includes/charts/calico/crds/kdd/02-crd-networkset.yaml
  _includes/charts/calico/templates/kdd-crds.yaml
  _includes/charts/tigera-operator/templates/crds/calico
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-calico-resources.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-configmap-tigera-install-script.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  _plugins/values.rb
  getting-started/openshift/installation.md
  manifests/ocp/crds/calico
  manifests/ocp/tigera-operator/02-configmap-calico-resources.yaml
  manifests/ocp/tigera-operator/02-configmap-tigera-install-script.yaml
Labels: docs-pr-required, release-note-required

#3359 support custom certs for helmerator
  _includes/charts/tigera-operator/templates/certs/certs-node.yaml
  _includes/charts/tigera-operator/templates/certs/certs-typha.yaml
  _plugins/values.rb
Labels: docs-not-required, release-note-not-required

#3367 Include networking-calico in v3.8.7 release
  _data/versions.yml
  _includes/component_url
Labels: docs-not-required, release-note-not-required

#3370 Add Blog link to Value section
  getting-started/kubernetes/trying-ebpf.md
Labels: docs-pr-required, release-note-required

#3373 Add Blog link to Value section (#3370)
  getting-started/kubernetes/trying-ebpf.md
Labels: docs-pr-required, release-note-required

#3340 Search results triggered on input focus
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#3341 Fix displaying content under navbar
  js/script.js
Labels: docs-pr-required, release-note-required

#3345 regenerate values.yaml on changes to values.rb and helm infra
  Makefile
Labels: docs-not-required, release-note-not-required

#3383 Fix operator namespace migration node rbac
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3384 automatically detect release stream
  Makefile
  RELEASING.md
Labels: docs-not-required, release-note-not-required

#3386 Add flexvol to operator api reference
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  reference/installation/api.html
Labels: docs-not-required, release-note-required

#3361 Updates to /Networking and /Security
  _data/navbars/networking.yml
  _data/navbars/security.yml
  networking/legacy-firewalls.md
  networking/openstack/connectivity.md
  networking/openstack/floating-ips.md
  networking/sidecar-acceleration.md
  reference/installation/api.html
  security/app-layer-policy.md
  security/calico-enterprise/egress-access-controls.md
  security/calico-enterprise/federation.md
  security/calico-enterprise/index.md
  security/calico-enterprise/network-visibility.md
  security/calico-enterprise/policy-workflow.md
  security/calico-enterprise/user-console.md
  security/comms/crypto-auth.md
  security/comms/reduce-nodes.md
  security/defend-dos-attack.md
  security/kubernetes-node-ports.md
  security/namespace-policy.md
  security/services-cluster-ips.md
  security/services.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-pr-required, release-note-required

#3391 Fix readme links
  README.md
Labels: docs-not-required, release-note-not-required

#3392 Changes for v3.8.8
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.8-release-notes.md
Labels: docs-not-required, release-note-not-required

#3382 Cleanup
  _includes/content/rkt-container-service.md
  getting-started/kubernetes/hardway/overview.md
Labels: docs-not-required, release-note-not-required

#3396 Fix operator namespace migration node rbac
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#3401 Update images with additional metadata tags
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3403 Update for Operator v1.3.2 release
  _data/versions.yml
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3402 Updates for Calico v3.12.1
  Makefile
  _data/versions.yml
  _includes/release-notes/v3.12.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#3405 Updates for v3.12.2
  Makefile
  _data/versions.yml
  _includes/release-notes/v3.13.2-release-notes.md
Labels: docs-not-required, release-note-not-required
