Repository projectcalico/calico, pull requests merged in 2020-06, with the labels that each got.

#3612 Remove some old manfiests which aren't used any more
  getting-started/kubernetes/installation/hosted/README.md
  getting-started/kubernetes/installation/hosted/calico.yaml
  getting-started/kubernetes/installation/hosted/calicoctl.yaml
  getting-started/kubernetes/installation/hosted/canal/canal-etcd.yaml
  getting-started/kubernetes/installation/hosted/canal/canal.yaml
  getting-started/kubernetes/installation/hosted/etcd.yaml
  getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
  getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
  getting-started/kubernetes/installation/hosted/kubernetes-datastore/calicoctl.yaml
  getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
Labels: docs-not-required, release-note-not-required

#3619 Update v3.12.2 release note
  _includes/release-notes/v3.12.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#3621 Update v3.14.1 release note
  _includes/release-notes/v3.14.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#3620 Update v3.13.4 release note
  _includes/release-notes/v3.13.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#3618 Update release notes
  _includes/v3.10/release-notes/v3.10.4-release-notes.md
  _includes/v3.11/release-notes/v3.11.3-release-notes.md
  _includes/v3.8/release-notes/v3.8.9-release-notes.md
  _includes/v3.9/release-notes/v3.9.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#3545 Fix navbar incorrect top scrolling
  css/style.scss
  js/script.js
Labels: docs-not-required, release-note-not-required

#3605 Fix broken font awesome icons for v.3.13
  _layouts/docwithnav.html
  css/font-awesome/font-awesome.min.css
  fonts/font-awesome/FontAwesome.otf
  fonts/font-awesome/fontawesome-webfont.eot
  fonts/font-awesome/fontawesome-webfont.svg
  fonts/font-awesome/fontawesome-webfont.ttf
  fonts/font-awesome/fontawesome-webfont.woff
  fonts/font-awesome/fontawesome-webfont.woff2
Labels: docs-not-required, release-note-not-required

#3604 Fix broken font awecome icons for v3.12
  _layouts/docwithnav.html
  css/font-awesome/font-awesome.min.css
  fonts/font-awesome/FontAwesome.otf
  fonts/font-awesome/fontawesome-webfont.eot
  fonts/font-awesome/fontawesome-webfont.svg
  fonts/font-awesome/fontawesome-webfont.ttf
  fonts/font-awesome/fontawesome-webfont.woff
  fonts/font-awesome/fontawesome-webfont.woff2
Labels: docs-not-required, release-note-not-required

#3630 Tweak encryption terms
  _data/navbars/security.yml
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3631 Automated cherry pick of #3562: fix links
  _data/navbars/security.yml
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3632 cherry-pick 3630
  _data/navbars/security.yml
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3622 Update quickstart to use the Tigera operator
  _includes/content/non-helm-manifests/custom-resources.yaml
  getting-started/kubernetes/quickstart.md
  manifests/custom-resources.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-required

#3629 Update eksctl nodegroup command
  getting-started/kubernetes/managed-public-cloud/eks.md
Labels: docs-not-required, release-note-not-required

#3625 Docs-update-next-steps
  getting-started/bare-metal/installation/container.md
  getting-started/kubernetes/managed-public-cloud/aks.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  getting-started/kubernetes/managed-public-cloud/gke.md
  getting-started/kubernetes/managed-public-cloud/iks.md
  getting-started/kubernetes/quickstart.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
  getting-started/openshift/installation.md
  getting-started/openstack/installation/ubuntu.md
Labels: docs-not-required, release-note-not-required

#3641 Update to require calicoctl
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3607 Add a note about rebooting in WireGuard installation
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3627 Fix name of calico-config configmap in command
  networking/mtu.md
Labels: docs-not-required, release-note-not-required

#3502 Remove deprecated critical-pod annotation
  _includes/charts/calico/templates/calico-kube-controllers.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
  _includes/non-helm-manifests/flannel-migration/migration-job.yaml
  getting-started/kubernetes/hardway/install-node.md
  getting-started/kubernetes/hardway/install-typha.md
Labels: docs-not-required, release-note-not-required

#3514 Fix Typha configuration.md typo
  reference/typha/configuration.md
Labels: docs-not-required, release-note-not-required

#3435 Last bullet repeated. Update doc for pod annotation
  networking/get-started-ip-addresses.md
Labels: docs-not-required, release-note-not-required

#3454 Docs Fix for (#3271) NetworkManager managing vxlan.calico interface
  _includes/content/reqs-sys.md
  maintenance/troubleshoot/troubleshooting.md
Labels: docs-not-required, release-note-not-required

#3644 Claify datastore types for calicoctl documentation
  getting-started/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#3643 Document the global() selector
  _includes/content/entityrule.md
  _includes/content/selectors.md
Labels: docs-not-required, release-note-not-required

#3460 Add Tip to Global Network Policy Section
  security/calico-network-policy.md
Labels: docs-not-required, release-note-not-required

#3623 Add instructions for datastore migration
  _data/navbars/maintenance.yml
  _data/navbars/reference.yml
  maintenance/datastore-migration.md
  reference/calicoctl/datastore/index.md
  reference/calicoctl/datastore/migrate/export.md
  reference/calicoctl/datastore/migrate/import.md
  reference/calicoctl/datastore/migrate/index.md
  reference/calicoctl/datastore/migrate/lock.md
  reference/calicoctl/datastore/migrate/overview.md
  reference/calicoctl/datastore/migrate/unlock.md
  reference/calicoctl/datastore/overview.md
Labels: docs-not-required, release-note-not-required

#3431 Don't need CALICO_IPV6POOL_CIDR for kubeadm clusters
  networking/ipv6.md
Labels: docs-not-required, release-note-not-required

#3649 Update crds with ones from libcalico-go
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_blockaffinities.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_clusterinformations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
Labels: docs-not-required, release-note-not-required

#3624 Update OpenStack install doc for Python 3 and newer releases
  getting-started/openstack/installation/overview.md
  getting-started/openstack/installation/redhat.md
  getting-started/openstack/installation/ubuntu.md
  getting-started/openstack/requirements.md
  getting-started/openstack/verification.md
  networking/ipv6.md
  networking/openstack/configuration.md
Labels: docs-not-required, release-note-not-required

#3654 Add typha port to the list of default failsafe ports
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3655 Add typha port to the list of default failsafe ports
  _includes/release-notes/release-v3.15-release-notes.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3659 Revert src-dst-check CRD update
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-not-required, release-note-not-required

#3662 Fix a 'pip' that should be 'pip3'
  getting-started/openstack/installation/ubuntu.md
Labels: docs-not-required, release-note-not-required

#3661 Restore doc for older OpenStack releases with Python 2
  getting-started/openstack/installation/redhat.md
  getting-started/openstack/installation/ubuntu.md
  getting-started/openstack/requirements.md
  networking/ipv6.md
  networking/openstack/configuration.md
Labels: docs-not-required, release-note-not-required

#3660 Update Operator CRDs to v1
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  _includes/charts/tigera-operator/templates/crds/01-crd-tigerastatus.yaml
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/ocp/crds/01-crd-installation.yaml
  manifests/ocp/crds/01-crd-tigerastatus.yaml
Labels: docs-not-required, release-note-not-required

#3663 Automated cherry pick of #3660: Update Operator CRDs to v1
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  _includes/charts/tigera-operator/templates/crds/01-crd-tigerastatus.yaml
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/ocp/crds/01-crd-installation.yaml
  manifests/ocp/crds/01-crd-tigerastatus.yaml
Labels: docs-not-required, release-note-not-required

#3648 Improve api render
  reference/installation/README.md
  reference/installation/_api.html
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3664 Some minor updates to datastore migration doc
  maintenance/datastore-migration.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3668 Automated cherry pick of #3664: Some minor updates to datastore migration doc
  maintenance/datastore-migration.md
Labels: docs-not-required, release-note-not-required

#3658 Wireguard docs updates
  _data/navbars/security.yml
  _includes/charts/calico/templates/calico-node.yaml
  netlify/_redirects
  networking/mtu.md
  security/encrypt-cluster-pod-traffic.md
  security/try-node-to-node-encryption.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3669 Remove ignoreLooseRPF param from docs
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3671 Cherry pick #3658 from master to release-v3.15
  _data/navbars/security.yml
  _includes/charts/calico/templates/calico-node.yaml
  netlify/_redirects
  networking/mtu.md
  security/encrypt-cluster-pod-traffic.md
  security/try-node-to-node-encryption.md
Labels: docs-not-required, release-note-not-required

#3674 Update encryption notes
  security/encrypt-cluster-pod-traffic.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3676 Cherry pick #3674 from master to release-v3.15
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#3675 Improve platform notes
  getting-started/openstack/requirements.md
Labels: docs-not-required, release-note-not-required

#3684 Automated cherry pick of #3683: Update Operator API reference
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3683 Update Operator API reference
  _includes/charts/tigera-operator/templates/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required

#3682 Automated cherry pick of #3669: Remove ignoreLooseRPF param from docs
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3686 Add empty v3.15.0 release notes file
  _includes/release-notes/v3.15.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3394 Fix formatting
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#3432 Fix Felix config options: "" is actually ignored, and none must be used to get the same effect
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3377 Felix doc is misleading
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#3688 Updates for v3.15.0
  AUTHORS.md
  _data/versions.yml
  _includes/release-notes/v3.15.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3645 Updated releases page with a bit of descriptive text
  releases.md
Labels: docs-not-required, release-note-not-required

#3690 Promote v3.15 to latest
  _data/archives.yml
  netlify.toml
  netlify/_redirects
Labels: docs-not-required, release-note-not-required

#3693 Use site.baseurl for release note links
  _includes/release-notes/v3.15.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3692 Update supported k8s versions
  getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#3691 Add v3.14 as a previous release on the v3.15 releases page
  _data/archives.yml
Labels: docs-not-required, release-note-not-required

#3695 Cherry-pick Update supported k8s versions (#3692)
  getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#3670 Re-work determine best networking
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3696 Automated cherry pick of #3670: Draft new content
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3697 Automated cherry pick of #3670: Draft new content
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3656 Dashboard Image added to Grafana page
  images/grafana-dashboard.png
  maintenance/monitor/monitor-component-visual.md
Labels: docs-not-required, release-note-not-required

#3647 Prometheus statistic page was missing for Typha in reference section.
  _data/navbars/reference.yml
  reference/typha/prometheus.md
Labels: docs-not-required, release-note-not-required

#3698 Automated cherry pick of #3647: Typha promethouse reference
  _data/navbars/reference.yml
  reference/typha/prometheus.md
Labels: docs-not-required, release-note-not-required

#3699 Automated cherry pick of #3656: Dashboard Image added to Grafana page
  images/grafana-dashboard.png
  maintenance/monitor/monitor-component-visual.md
Labels: docs-not-required, release-note-not-required

#3700 Improve grafana value grammar
  maintenance/monitor/monitor-component-visual.md
Labels: docs-not-required, release-note-not-required

#3582 K3S/Calico Implementation tutorials
  _data/navbars/getting-started.yml
  getting-started/kubernetes/k3s/index.md
  getting-started/kubernetes/k3s/multi-node-install.md
  getting-started/kubernetes/k3s/quickstart.md
Labels: docs-not-required, release-note-not-required

#3702 Automated cherry pick of #3700: Fix grammar
  maintenance/monitor/monitor-component-visual.md
Labels: docs-not-required, release-note-not-required

#3705 Exclude html-tags / modal dialogs content from read-time algorithm
  _includes/read_time.html
  _plugins/regex-replace.rb
Labels: docs-not-required, release-note-not-required

#3707 Add google optimize anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3710 Automated cherry pick of #3707: Add google optimize anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3651 Added additional information on the role and configuration of calico/…
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#3681 Update on-prem deployment with geeky details
  getting-started/kubernetes/self-managed-onprem/index.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
Labels: docs-not-required, release-note-not-required

#3615 Doc-outgoing-NAT
  _data/navbars/networking.yml
  networking/workloads-outside-cluster.md
Labels: docs-not-required, release-note-not-required

#3678 Automated cherry pick of #3669: Remove ignoreLooseRPF param from docs
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3679 Automated cherry pick of #3669: Remove ignoreLooseRPF param from docs
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3680 Automated cherry pick of #3669: Remove ignoreLooseRPF param from docs
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#3703 Automated cherry pick of #3582: Initial structure for K3S tutorials
  _data/navbars/getting-started.yml
  getting-started/kubernetes/k3s/index.md
  getting-started/kubernetes/k3s/multi-node-install.md
  getting-started/kubernetes/k3s/quickstart.md
Labels: docs-not-required, release-note-not-required

#3708 Automated cherry pick of #3705: Exclude html-tags from read-time algorithm
  _includes/read_time.html
  _plugins/regex-replace.rb
Labels: docs-not-required, release-note-not-required

#3714 Automated cherry pick of #3651: Added additional information on the role and configuration of
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#3715 Automated cherry pick of #3681: Update on-prem deployment with geeky details
  getting-started/kubernetes/self-managed-onprem/index.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
Labels: docs-not-required, release-note-not-required

#3720 Fix external links on 'Enforce Calico network policy using Istio' page
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-not-required, release-note-not-required

#3712 K3s documention update
  _plugins/tabs.rb
  css/style.scss
  getting-started/kubernetes/k3s/multi-node-install.md
  getting-started/kubernetes/k3s/quickstart.md
Labels: docs-not-required, release-note-not-required

#3728 Minor style tweaks. Change color of warn box, align breadcrumbs with …
  _sass/bootstrap/bootstrap/_breadcrumbs.scss
  _sass/bootstrap/bootstrap/_type.scss
  _sass/bootstrap/bootstrap/_variables.scss
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3731 Place back blockquote that disapeared.
  css/style.scss
Labels: docs-not-required, release-note-not-required
