Repository projectcalico/calico, pull requests merged in 2020-01, with the labels that each got.

#3076 Extend kernel dependencies in v3.10 doc
  _includes/master/reqs-kernel.md
  _includes/v3.10/reqs-kernel.md
Labels: docs-pr-required, release-note-required

#3042 quiet wget
  Makefile
Labels: docs-pr-required, release-note-required

#2787 WIP: Add docs for traffic shaping with calico
  _includes/master/charts/calico/templates/calico-config.yaml
Labels: docs-not-required, release-note-not-required

#2968 Note that 'ports' has a dependency on 'protocol'
  _includes/v3.10/entityrule.md
Labels: docs-not-required, release-note-not-required

#3062 Render mtu options for Canal/flannel
  _includes/master/charts/calico/templates/calico-config.yaml
  _includes/master/charts/calico/templates/calico-node.yaml
Labels: docs-pr-required, release-note-required

#3099 Add utm strings to Calico Enterprise links
  _includes/enterprise_footer.html
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#3064 Update beta.kubernetes.io/os label
  _includes/master/charts/calico/templates/calico-kube-controllers.yaml
  _includes/master/charts/calico/templates/calico-node.yaml
  _includes/master/charts/calico/templates/calico-typha.yaml
  _includes/master/charts/calico/templates/configure-canal.yaml
  _includes/master/non-helm-manifests/calicoctl-etcd.yaml
  _includes/master/non-helm-manifests/calicoctl.yaml
  _includes/master/non-helm-manifests/flannel-migration/migration-job.yaml
  master/getting-started/kubernetes/hardway/install-node.md
Labels: docs-not-required, release-note-required

#3100 Update enterprise utm strings
  _includes/enterprise_footer.html
  _includes/enterprise_header.html
Labels: docs-pr-required, release-note-required

#3066 Add link to AWS networking blog and video
  v3.10/getting-started/kubernetes/managed-public-cloud/eks.md
Labels: docs-not-required, release-note-not-required

#3104 Updates for v3.8.6
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#3106 Updates for v3.10.3
  _data/versions.yml
  _includes/v3.10/release-notes/v3.10.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#3109 Revert "Updates for v3.8.6"
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#3110 Revert "Updates for v3.10.3"
  _data/versions.yml
  _includes/v3.10/release-notes/v3.10.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#3111 Updates for v3.10.3
  _data/versions.yml
  _includes/v3.10/release-notes/v3.10.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#3112 Updates for v3.8.6
  Makefile
  _data/versions.yml
  _includes/v3.8/release-notes/v3.8.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#3105 Updates for v3.9.5
  _data/versions.yml
  _includes/v3.9/release-notes/v3.9.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#3113 Application Layer Policy and Istio permissive mode
  getting-started/kubernetes/installation/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#3115 Fix absolute links
  CONTRIBUTING_DOCS.md
  _includes/master/ctl-container-install.md
  _includes/master/install-k8s-addons.md
  getting-started/kubernetes/hardway/the-calico-datastore.md
  getting-started/kubernetes/index.md
  getting-started/kubernetes/installation/app-layer-policy.md
  getting-started/kubernetes/installation/calico.md
  getting-started/kubernetes/installation/config-options.md
  getting-started/kubernetes/installation/flannel.md
  getting-started/kubernetes/installation/integration.md
  getting-started/kubernetes/installation/migration-from-flannel.md
  getting-started/kubernetes/installation/other.md
  maintenance/kubernetes-upgrade.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
  security/tutorials/kubernetes-policy-demo/kubernetes-demo.md
Labels: docs-pr-required, release-note-required

#3120 move helm infra to branch-per-version
  Makefile
  _includes/charts/calico/Chart.yaml
  _includes/charts/calico/templates/_functions.tpl
  _includes/charts/calico/templates/calico-config.yaml
  _includes/charts/calico/templates/calico-etcd-secrets.yaml
  _includes/charts/calico/templates/calico-kube-controllers.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
  _includes/charts/calico/templates/configure-canal.yaml
  _includes/charts/calico/templates/kdd-crds.yaml
  _includes/charts/calico/templates/rbac.yaml
  _plugins/helm.rb
  _plugins/lib.rb
  _plugins/values.rb
  hack/gen_values_yml.rb
  helm-tests/render_test.go
Labels: docs-pr-required, release-note-required

#3122 de-version navbars
  _data/navbars/getting-started.yml
  _data/navbars/introduction.yml
  _data/navbars/maintenance.yml
  _data/navbars/networking.yml
  _data/navbars/reference.yml
  _data/navbars/release-notes.yml
  _data/navbars/security.yml
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#3117 Remove vars that aren't actually needed for dual stack
  networking/dual-stack.md
Labels: docs-not-required, release-note-not-required

#3124 Remove vars that aren't actually needed for dual stack
  v3.11/networking/dual-stack.md
Labels: docs-not-required, release-note-not-required

#3114 Minor updates to determine best networking and EKS docs
  getting-started/kubernetes/managed-public-cloud/eks.md
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3119 remove other versions from versions.yml
  Makefile
  _data/versions.yml
  _includes/content/ctl-container-install.md
  _includes/content/docker-container-service.md
  _includes/content/rkt-container-service.md
  _includes/content/testing-data-migration.md
  _includes/non-helm-manifests/calicoctl-etcd.yaml
  _includes/non-helm-manifests/calicoctl.yaml
  _includes/non-helm-manifests/dikastes-container
  _includes/non-helm-manifests/flannel-migration/migration-job.yaml
  _includes/urls
  _plugins/helm.rb
  _plugins/lib.rb
  getting-started/bare-metal/installation/binary.md
  getting-started/bare-metal/installation/container.md
  getting-started/kubernetes/installation/calico-kube-controllers.yaml
  getting-started/kubernetes/installation/integration.md
  hack/gen_values_yml.rb
  reference/calicoctl/node/run.md
  release-notes/index.md
Labels: docs-pr-required, hold-merge, release-note-required

#3116 Added note on AKS doc
  getting-started/kubernetes/managed-public-cloud/aks.md
Labels: docs-pr-required, release-note-required

#3058 Remove IgnoreLooseRPF field from FelixConfiguration
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#3107 Document special projectcalico.org/name label
  _includes/content/entityrule.md
  reference/resources/globalnetworkpolicy.md
  reference/resources/networkpolicy.md
Labels: docs-not-required, release-note-not-required

#3130 Rule metadata docs
  _includes/content/rule.md
Labels: docs-pr-required, release-note-required

#3131 site.url -> site.baseurl + various fixes
  CONTRIBUTING_DOCS.md
  _includes/content/reqs-kernel.md
  _includes/content/reqs-sys.md
  _includes/non-helm-manifests/calicoctl-etcd.yaml
  _includes/non-helm-manifests/calicoctl.yaml
  getting-started/bare-metal/installation/container.md
  getting-started/kubernetes/installation/app-layer-policy.md
  getting-started/kubernetes/installation/calico-kube-controllers.yaml
  getting-started/kubernetes/managed-public-cloud/aks.md
  getting-started/kubernetes/managed-public-cloud/eks.md
  getting-started/kubernetes/managed-public-cloud/gke.md
  getting-started/kubernetes/managed-public-cloud/iks.md
Labels: docs-pr-required, release-note-not-required

#3132 Update felix configuration documentation
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#3139 Updates for release v3.11.2
  AUTHORS.md
  _data/versions.yml
  _includes/v3.11/release-notes/v3.11.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#3135 Add tests for release artifacts
  .gitignore
  Makefile
  release-scripts/tests/Dockerfile
  release-scripts/tests/config.json
  release-scripts/tests/requirements.txt
  release-scripts/tests/test_images.py
  release-scripts/tests/test_openstack_artifacts.py
  release-scripts/tests/test_projectcalico_docs_updated.py
  release-scripts/tests/test_tags_tars.py
Labels: docs-not-required, release-note-not-required

#3127 Improve service advertisement doc to cover IPv6
  networking/advertise-service-ips.md
Labels: docs-not-required, release-note-not-required

#3140 Adding OCP 4.2 install with operator
  Makefile
  _data/navbars/getting-started.yml
  _data/versions.yml
  _includes/charts/tigera-operator/Chart.yaml
  _includes/charts/tigera-operator/templates/_helpers.tpl
  _includes/charts/tigera-operator/templates/crds/01-crd-installation.yaml
  _includes/charts/tigera-operator/templates/crds/01-crd-tigerastatus.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/00-namespace-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-serviceaccount-tigera-operator.yaml
  _includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  _includes/content/reqs-sys.md
  _plugins/helm.rb
  _plugins/lib.rb
  _plugins/values.rb
  getting-started/openshift/dedicated-etcd.md
  getting-started/openshift/installation.md
  getting-started/openshift/requirements.md
  hack/gen_values_yml.rb
  manifests/ocp/01-cr-installation.yaml
  manifests/ocp/crds/01-crd-installation.yaml
  manifests/ocp/crds/01-crd-tigerastatus.yaml
  manifests/ocp/tigera-operator/00-namespace-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-rolebinding-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-serviceaccount-tigera-operator.yaml
  manifests/ocp/tigera-operator/02-tigera-operator.yaml
Labels: docs-pr-required, release-note-required

#3146 Add note to canal docs re: Calico VXLAN capabilities
  getting-started/kubernetes/installation/flannel.md
Labels: docs-not-required, release-note-not-required

#3147 Automated cherry pick of #3146: Add note to canal docs re: Calico VXLAN capabilities
  getting-started/kubernetes/installation/flannel.md
Labels: docs-not-required, release-note-not-required

#3148 Build v3.12 Candidate
  RELEASING.md
  _config.yml
  _includes/version_warning.html
  _layouts/docwithnav.html
  netlify.toml
  netlify/build.sh
Labels: docs-not-required, release-note-not-required

#3150 Fixing release note year for 3.10.3, 3.9.5, 3.8.6
  _includes/v3.10/release-notes/v3.10.3-release-notes.md
  _includes/v3.8/release-notes/v3.8.6-release-notes.md
  _includes/v3.9/release-notes/v3.9.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#3149 fix intro nav scroll
  introduction/index.md
Labels: docs-pr-required, release-note-required

#3151 clean up makefile targets for charts
  Makefile
Labels: docs-pr-required, release-note-required

#3144 Updated self managed on premises
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-onprem/index.md
  getting-started/kubernetes/self-managed-onprem/onpremises.md
Labels: docs-not-required, release-note-not-required

#3153 Setting rp_filter is not needed now
  getting-started/kubernetes/installation/migration-from-flannel.md
Labels: docs-not-required, release-note-not-required

#3154 Cherry-pick docs fix
  getting-started/kubernetes/installation/migration-from-flannel.md
Labels: docs-not-required, release-note-not-required

#3137 Improve GlobalNetworkPolicy reference doc UX
  reference/resources/globalnetworkpolicy.md
Labels: docs-not-required, release-note-not-required

#3155 adjust fonts
  _sass/bootstrap/bootstrap/_variables.scss
  css/search.scss
  css/style.scss
Labels: docs-pr-required, release-note-required

#3157 Add the operator Reference API plus a typo fix
  _data/navbars/reference.yml
  getting-started/openshift/installation.md
  reference/installation/README.md
  reference/installation/api.html
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#3159 Pick #3157 - add Operator API Reference doc
  _data/navbars/reference.yml
  getting-started/openshift/installation.md
  reference/installation/README.md
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#3158 Fix breadcrumbs
  _data/navbars/getting-started.yml
  _data/navbars/introduction.yml
  _data/navbars/maintenance.yml
  _data/navbars/networking.yml
  _data/navbars/reference.yml
  _data/navbars/release-notes.yml
  _data/navbars/security.yml
  _includes/nav-breadcrumbs.html
  _layouts/docwithnav.html
  _plugins/breadcrumbs.rb
  _plugins/drops/breadcrumb_item.rb
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3161 Add rule metadata example
  _includes/content/rule.md
Labels: docs-not-required, release-note-not-required

#3162 Cherry-pick Add rule metadata example (#3161)
  _includes/content/rule.md
Labels: docs-not-required, release-note-not-required

#3160 Minor tweaks to self-managed on-prem
  getting-started/kubernetes/self-managed-onprem/onpremises.md
Labels: docs-not-required, release-note-not-required

#3167 update to newer yq
  Makefile
Labels: docs-not-required, release-note-not-required

#3169 Updates for release v3.12.0
  AUTHORS.md
  Makefile
  RELEASING.md
  _data/versions.yml
  release-notes/v3.12.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#3172 Fix release-notes location
  _data/navbars/getting-started.yml
  _data/navbars/introduction.yml
  _data/navbars/maintenance.yml
  _data/navbars/networking.yml
  _data/navbars/reference.yml
  _data/navbars/release-notes.yml
  _data/navbars/security.yml
  _includes/nav-breadcrumbs.html
  _includes/release-notes/v3.12.0-release-notes.md
  _layouts/docwithnav.html
  _plugins/breadcrumbs.rb
  _plugins/drops/breadcrumb_item.rb
  _sass/bootstrap/bootstrap/_variables.scss
  css/search.scss
  css/style.scss
Labels: docs-not-required, release-note-not-required

#3174 mark latest site at build time
  netlify/_config_latest.yml
  netlify/build.sh
Labels: docs-pr-required, release-note-required

#3175 Fix latest version warning
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#3178 Fix networking-calico version
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#3171 Promote v3.12.0 to latest
  RELEASING.md
  _layouts/docwithnav.html
  netlify.toml
  netlify/_config_latest.yml
  netlify/build.sh
Labels: docs-not-required, release-note-not-required

#3176 Add v3.11 to release archives
  _data/archives.yml
Labels: docs-not-required, release-note-not-required

#3180 cherry-pick fixes from master to v3.12
  _layouts/docwithnav.html
  introduction/index.md
Labels: docs-pr-required, release-note-required

#3179 fix navbar link to release notes
  _layouts/docwithnav.html
Labels: docs-pr-required, release-note-required

#3164 fix sitemap
  netlify/build.sh
  netlify/sitemap-index.xml
Labels: docs-not-required, release-note-not-required

#3185 fix bad underscore in sitemap
  netlify/build.sh
Labels: docs-pr-required, release-note-required

#3184 Fix release note
  _data/versions.yml
  _includes/release-notes/v3.12.0-release-notes.md
Labels: docs-not-required, release-note-not-required, release-note-required

#3186 fixed description
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required, release-note-required

#3189 Cherry-pick fixed description (#3186)
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#3166 Add `Auto` param to IptablesBackend config
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#3165 Add `Auto` param to IptablesBackend config
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#3183 update latest redirects for branch-per-version
  netlify.toml
Labels: docs-not-required, release-note-not-required, release-note-required

#3181 Release archive page lists latest version
  _layouts/docwithnav.html
  releases.md
Labels: docs-not-required, release-note-not-required, release-note-required

#3191 use file-based redirects
  netlify.toml
  netlify/_redirects
  netlify/build.sh
Labels: docs-not-required, release-note-not-required

#3190 Release archive page lists latest version (#3181)
  _layouts/docwithnav.html
  netlify/_config_latest.yml
  netlify/build.sh
  releases.md
Labels: docs-not-required, release-note-not-required

#3193 Add v3.11 to archives on latest release
  _data/archives.yml
Labels: docs-pr-required, release-note-required

#3156 Self managed public cloud
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azu.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
  getting-started/kubernetes/self-managed-public-cloud/index.md
Labels: docs-not-required, release-note-not-required

#3177 Fixed codesnippets scrolling
  css/style.scss
  js/code-select.js
Labels: docs-not-required, release-note-not-required

#3195 Use latest operator release
  _data/versions.yml
Labels: docs-pr-required, release-note-required

#3170 Add two new Calico Enterprise topics
  _data/navbars/security.yml
  images/compliance-reports.png
  images/dns-policy-rules.png
  images/tiered-policies.png
  security/adopt-zero-trust.md
  security/calico-enterprise/compliance.md
  security/calico-enterprise/egress-access-controls.md
  security/external-ips-policy.md
  security/policy-rules-overview.md
Labels: docs-not-required, release-note-not-required

#3197 ipv6 doc incorrectly says kubernetes doesn't support dual stack
  networking/ipv6.md
Labels: docs-not-required, release-note-not-required

#3198 ipv6 doc incorrectly says kubernetes doesn't support dual stack
  networking/ipv6.md
Labels: cherry-pick-candidate, docs-pr-required, release-note-not-required

#3200 Remove compliance doc for now
  images/compliance-reports.png
  images/tiered-policies.png
  security/calico-enterprise/compliance.md
Labels: docs-pr-required, release-note-required

#3201 Fix typo in description for dual stack page
  networking/dual-stack.md
Labels: docs-not-required, release-note-not-required

#3202 Fix typo in description for dual stack page
  networking/dual-stack.md
Labels: docs-not-required, release-note-not-required

#3203 Fixed formatting for DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: docs-pr-required, release-note-required

#3205 Cherry-pick Self managed public cloud (#3156)
  _data/navbars/getting-started.yml
  getting-started/kubernetes/self-managed-public-cloud/aws.md
  getting-started/kubernetes/self-managed-public-cloud/azu.md
  getting-started/kubernetes/self-managed-public-cloud/gce.md
  getting-started/kubernetes/self-managed-public-cloud/index.md
Labels: docs-pr-required, release-note-required

#3199 ALP minor doc changes
  getting-started/kubernetes/installation/app-layer-policy.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-pr-required, release-note-required

#3207 Enterprise awareness docs
  _data/navbars/security.yml
  images/anomaly-detection.png
  images/audit-logs.png
  images/compliance-reporting.png
  images/compliance-reports.png
  images/configuration-compliance.png
  images/dga-detection.png
  images/federated-endpoint-identity.png
  images/flow-logs.png
  images/flow-viz.png
  images/operations-dashboard.png
  images/policy-builder.png
  images/policy-federation.png
  images/policy-options.png
  images/policy-recommendation.png
  images/policy-workflow.png
  images/threat-feed.png
  images/tiered-policy-board.png
  security/adopt-zero-trust.md
  security/calico-enterprise/compliance.md
  security/calico-enterprise/egress-access-controls.md
  security/calico-enterprise/federation.md
  security/calico-enterprise/threat-defense.md
  security/calico-enterprise/user-console.md
  security/calico-network-policy.md
  security/policy-rules-overview.md
Labels: docs-pr-required, release-note-required
