Repository projectcalico/calico, pull requests merged in 2021-07, with the labels that each got.

#4716 Fix namespace for configmap
  maintenance/ebpf/ebpf-and-eks.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#4720 [cherry-pick] public helm chart repo
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4735 update helm installation docs
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#4738 Publish APIServer CRD
  _includes/content/install-openshift-manifests.md
  manifests/ocp/crds/01-crd-apiserver.yaml
Labels: docs-not-required, release-note-not-required

#4740 Create API server in an OpenShift install
  _includes/content/install-openshift-manifests.md
  manifests/ocp/01-cr-apiserver.yaml
Labels: docs-not-required, release-note-not-required

#4742 Add support for istio 1.9 and 1.10 and remove support for istio 1.6 and 1.7
  _includes/non-helm-manifests/dikastes-container-indented
  _includes/non-helm-manifests/istio-app-layer-policy-envoy-v3.yaml
  _includes/non-helm-manifests/istio-proxy-volume-mounts-indented
  _includes/non-helm-manifests/istio-volumes-indented
  manifests/alp/istio-app-layer-policy-envoy-v3.yaml
  manifests/alp/istio-inject-configmap-1.10.yaml
  manifests/alp/istio-inject-configmap-1.9.yaml
  security/app-layer-policy.md
Labels: docs-not-required, release-note-required

#4734 Update styles for header
  _config.yml
  _includes/enterprise_navbar.html
  _includes/open_source_navbar.html
  _layouts/docwithnav.html
  _sass/bootstrap/bootstrap/_navbar.scss
  _sass/bootstrap/bootstrap/_variables.scss
  css/style.scss
  images/calico-logo.svg
  images/icon-calico-cloud-hover.svg
  images/icon-calico-cloud.svg
  images/icon-calico-enterprise-hover.svg
  images/icon-calico-enterprise.svg
  images/icon-calico-os-hover.svg
  images/icon-calico-os.svg
  images/tigera-logo.png
Labels: docs-not-required, release-note-not-required

#4746 Automated cherry pick of #4734: Update some styles for header
  _config.yml
  _includes/enterprise_navbar.html
  _includes/open_source_navbar.html
  _layouts/docwithnav.html
  _sass/bootstrap/bootstrap/_navbar.scss
  _sass/bootstrap/bootstrap/_variables.scss
  css/style.scss
  images/calico-logo.svg
  images/icon-calico-cloud-hover.svg
  images/icon-calico-cloud.svg
  images/icon-calico-enterprise-hover.svg
  images/icon-calico-enterprise.svg
  images/icon-calico-os-hover.svg
  images/icon-calico-os.svg
  images/tigera-logo.png
Labels: docs-not-required, release-note-not-required

#4745 Added WireGuard install steps for AKS
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#4749 Update table styles and table rows
  calico-enterprise/index.md
  css/style.scss
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4750 Automated cherry pick of #4749: Updated styles and table rows
  calico-enterprise/index.md
  css/style.scss
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4753 openshift: use release-vX.Y channel for OLM integration
  getting-started/openshift/installation.md
Labels: docs-not-required, release-note-not-required

#4760 Add maxRestartTime configuration documentation to BGP peer
  reference/resources/bgppeer.md
Labels: docs-not-required, release-note-not-required

#4764 Update api.html
  reference/installation/api.html
Labels: docs-not-required, release-note-not-required

#4765 Add maxRestartTime field to bgppeers CRD yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
Labels: docs-not-required, release-note-not-required

#4766 Cherry pick maxRestartTime changes to v3.20
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  reference/resources/bgppeer.md
Labels: docs-not-required, release-note-not-required

#4741 Cherrypick-non-cluster-host
  _includes/content/environment-file.md
  getting-started/bare-metal/about.md
  getting-started/bare-metal/installation/binary-mgr.md
  getting-started/bare-metal/installation/binary.md
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4767 Update configuration.md
  reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#4768 Update configuration.md
  reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#4769 Add RBAC for endpointslices
  _includes/charts/calico/templates/calico-node-rbac.yaml
Labels: docs-not-required, release-note-not-required

#4770 Automated cherry pick of #4769: Add RBAC for endpointslices
  _includes/charts/calico/templates/calico-node-rbac.yaml
Labels: docs-not-required, release-note-not-required

#4771 IPAM GC RBAC update
  _includes/charts/calico/templates/calico-kube-controllers-rbac.yaml
Labels: docs-not-required, release-note-not-required

#4772 Automated cherry pick of #4771: IPAM GC RBAC update
  _includes/charts/calico/templates/calico-kube-controllers-rbac.yaml
Labels: docs-not-required, release-note-not-required

#4759 Doc updates for use of XDP in BPF mode
  about/about-ebpf.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#4725 [cherry-pick] Merge pull request #4716
  maintenance/ebpf/ebpf-and-eks.md
Labels: docs-not-required, release-note-not-required

#4774 Add Service NetworkPolicy docs
  _data/navbars/security.yml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  _includes/content/entityrule.md
  _includes/content/servicematch.md
  reference/resources/globalnetworkpolicy.md
  reference/resources/networkpolicy.md
  security/service-policy.md
Labels: docs-not-required, release-note-not-required

#4777 Automated cherry pick of #4774: Add Service NetworkPolicy docs
  _data/navbars/security.yml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  _includes/content/entityrule.md
  _includes/content/servicematch.md
  reference/resources/globalnetworkpolicy.md
  reference/resources/networkpolicy.md
  security/service-policy.md
Labels: docs-not-required, release-note-not-required

#4714 Update calico-network-policy.md
  security/calico-network-policy.md
Labels: docs-not-required, release-note-not-required

#4775 Update defend-dos-attack.md
  security/defend-dos-attack.md
Labels: docs-not-required, release-note-not-required

#4711 fix markdown
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#4576 NetworkManager shouldn't manage wireguard interface
  maintenance/troubleshoot/troubleshooting.md
Labels: docs-not-required, release-note-not-required

#4781 Add --allow-version-mismatch to docs
  reference/calicoctl/overview.md
Labels: docs-not-required, release-note-not-required

#4784 Add --allow-version-mismatch to docs
  reference/calicoctl/overview.md
Labels: docs-not-required, release-note-not-required

#4783 Merge pull request #4759 from neiljerram/xdp-bpf
  about/about-ebpf.md
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#4785 add docs for wireguard basic prometheus stats and its config flag
  reference/felix/configuration.md
  reference/felix/prometheus.md
Labels: docs-not-required, release-note-not-required

#4650 Streamline instructions for running calico-bpf tool.
  maintenance/troubleshoot/troubleshoot-ebpf.md
Labels: docs-not-required, release-note-not-required

#4717 Update kubernetes-upgrade.md
  maintenance/kubernetes-upgrade.md
Labels: docs-not-required, release-note-not-required

#4786 Add documentation to add back Istio 1.7 support
  security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#4787 Add documentation to add back Istio 1.7 support
  security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#4788 Increase timeout on liveness/readiness probes.
  _includes/charts/calico/templates/calico-kube-controllers.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
Labels: docs-not-required, release-note-not-required

#4789 [v3.20] Backport liveness timeout
  _includes/charts/calico/templates/calico-kube-controllers.yaml
  _includes/charts/calico/templates/calico-node.yaml
  _includes/charts/calico/templates/calico-typha.yaml
Labels: docs-not-required, release-note-not-required

#4792 Add clusterinformations 'get' permissions to operator for openshift
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, merge-when-ready, release-note-not-required

#4793 Add clusterinformations 'get' permissions to operator for openshift
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, merge-when-ready, release-note-not-required

#4795 Automated cherry pick of #4773: Add a page about Calico API
  _data/navbars/reference.yml
  reference/api.md
Labels: docs-not-required, release-note-not-required

#4794 Updates for v3.20.0
  AUTHORS.md
  Makefile
  _data/archives.yml
  _data/versions.yml
  _includes/release-notes/v3.20.0-release-notes.md
Labels: docs-not-required, release-note-not-required
