Repository projectcalico/calico, pull requests merged in 2021-12, with the labels that each got.

#5130 [EU-668] Add download ebook banner
  about/about-calico.md
  css/style.scss
  images/oreilly-book-mockup.png
Labels: docs-not-required, release-note-not-required

#5127 [EU-663] Update projectcalico menu bars
  _includes/open_source_navbar.html
  _layouts/docwithnav.html
  css/style.scss
  js/dropdown.js
Labels: docs-not-required, release-note-not-required

#5132 Automated cherry pick of #5127: Changed menu bars, added sub menu
  _includes/open_source_navbar.html
  _layouts/docwithnav.html
  css/style.scss
  js/dropdown.js
Labels: docs-not-required, release-note-not-required

#5131 Automated cherry pick of #5130: Added ebook banner
  about/about-calico.md
  css/style.scss
  images/oreilly-book-mockup.png
Labels: docs-not-required, release-note-not-required

#5133 Revert "Automated cherry pick of #5130: Added ebook banner"
  about/about-calico.md
  css/style.scss
  images/oreilly-book-mockup.png
Labels: docs-not-required, release-note-not-required

#5136 Remove form from footer navbar
  _includes/open_source_navbar.html
Labels: docs-not-required, release-note-not-required

#5137 Automated cherry pick of #5136: Removed form from footer navbar
  _includes/open_source_navbar.html
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#5138 [EU-668] Change ebook banner style
  about/about-calico.md
  css/style.scss
  images/oreilly-book-mockup.png
Labels: docs-not-required, release-note-not-required

#5139 Added ebook banner to release v3.21
  about/about-calico.md
  css/style.scss
  images/oreilly-book-mockup.png
Labels: docs-not-required, release-note-not-required

#5134 Use semaphore job to update helm index
  .gitignore
  Makefile
  glide.lock
  glide.yaml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#5142 Fix version errors while uploading helm charts and a release tagging bug
  Makefile
  RELEASING.md
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#5141 Fix version errors while uploading helm charts and a release tagging bug
  Makefile
  RELEASING.md
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#5140 Fix version errors while uploading helm charts and a release tagging bug
  Makefile
  RELEASING.md
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#5105 [EV-1366] adding redirects for domain change
  netlify.toml
  netlify/_redirects_v3.21
Labels: docs-not-required, release-note-not-required

#5144 Automated cherry pick of #5134: Use semaphore job to update helm index
  .gitignore
  Makefile
  glide.lock
  glide.yaml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#5151 Updates for release v3.21.2
  _data/versions.yml
  _includes/release-notes/v3.21.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#5160 [EU-675] Changed ebook banner and added link to top menu (release-v3.21)
  _includes/open_source_navbar.html
  about/about-calico.md
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#5159 [EU-675] Changed ebook banner and added link to top menu
  _includes/open_source_navbar.html
  about/about-calico.md
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#5163 Make the helm chart version follow the Calico version
  Makefile
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#5174 Make the helm chart version follow the Calico version
  Makefile
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#5175 Make the helm chart version follow the Calico version
  .gitignore
  Makefile
  getting-started/kubernetes/helm.md
  glide.lock
  glide.yaml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#5166 windows: replace install-calico-windows.ps1 template
  Makefile
  scripts/install-calico-windows.ps1
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#5239 Limit semaphore jobs based on changeset
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#5238 respect apiserver enablement in helm chart
  calico/_includes/charts/tigera-operator/templates/crs/custom-resources.yaml
Labels: docs-not-required, release-note-not-required

#5212 Updating documentation for new autodetection method kubernetes-internal-ip
  calico/networking/ip-autodetection.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5210 Dikastes: use gRPC graceful shutdown to exit cleanly after getting signal
  app-policy/cmd/dikastes/dikastes.go
Labels: release-note-required, docs-not-required

#5241 Clean up issue templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  api/.github/ISSUE_TEMPLATE.md
  api/.github/PULL_REQUEST_TEMPLATE.md
  apiserver/.github/ISSUE_TEMPLATE.md
  apiserver/.github/PULL_REQUEST_TEMPLATE.md
  app-policy/.github/CODEOWNERS
  app-policy/.github/ISSUE_TEMPLATE.md
  app-policy/.github/PULL_REQUEST_TEMPLATE.md
  calico/.github/CODEOWNERS
  calico/.github/ISSUE_TEMPLATE.md
  calicoctl/.github/ISSUE_TEMPLATE.md
  calicoctl/.github/PULL_REQUEST_TEMPLATE.md
  cni-plugin/.github/ISSUE_TEMPLATE.md
  cni-plugin/.github/PULL_REQUEST_TEMPLATE.md
  felix/.github/CODEOWNERS
  felix/.github/ISSUE_TEMPLATE.md
  felix/.github/PULL_REQUEST_TEMPLATE.md
  kube-controllers/.github/ISSUE_TEMPLATE.md
  kube-controllers/.github/PULL_REQUEST_TEMPLATE.md
  libcalico-go/.github/PULL_REQUEST_TEMPLATE.md
  node/.github/ISSUE_TEMPLATE.md
  node/.github/PULL_REQUEST_TEMPLATE.md
  pod2daemon/.github/ISSUE_TEMPLATE.md
  pod2daemon/.github/PULL_REQUEST_TEMPLATE.md
  typha/.github/CODEOWNERS
  typha/.github/ISSUE_TEMPLATE.md
  typha/.github/PULL_REQUEST_TEMPLATE.md
Labels: docs-not-required, release-note-not-required

#5213 Add semaphore promotion to publish images
  .gitignore
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/typha.yml
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#5242 Checkout the code for CD
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/typha.yml
Labels: docs-not-required, release-note-not-required

#5042 Fix canal etcd CNI config use of unsupported replace variable
  calico/_includes/charts/calico/templates/calico-config.yaml
Labels: docs-not-required, release-note-not-required

#5271 Update Windows FVs to use 20H2
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#5272 Add semaphore block to run docs tests
  .semaphore/semaphore.yml
  calico/Makefile
Labels: docs-not-required, release-note-not-required

#5240 Add node ST for switching from full-mesh to route reflectors
  node/tests/st/bgp/test_switch_route_reflector.py
  node/tests/st/utils/workload.py
Labels: docs-not-required, release-note-not-required

#5278 Added Windows HNS support to Readme
  README.md
Labels: docs-not-required, release-note-not-required

#5275 Misc typo fixes
  apiserver/pkg/storage/calico/policy_storage_test.go
  app-policy/syncher/syncserver_test.go
  calico/CONTRIBUTING_DOCS.md
  calico/_data/navbars/maintenance.yml
  calico/_includes/non-helm-manifests/apiserver.yaml
  calico/_plugins/code_block_validator.rb
  calico/_plugins/tabs.rb
  calico/getting-started/clis/calicoctl/install.md
  calico/getting-started/windows-calico/openshift/installation.md
  calico/maintenance/clis/calicoctl/install.md
  calico/maintenance/install-apiserver.md
  calico/maintenance/monitor/monitor-component-visual.md
  calico/maintenance/troubleshoot/vpp.md
  calico/netlify.toml
  calico/networking/openstack/service-ips.md
  calico/reference/calicoctl/node/checksystem.md
  calico/reference/felix/configuration.md
  calico/reference/installation/_api.html
  calico/reference/node/configuration.md
  calico/reference/resources/bgppeer.md
  calico/reference/resources/felixconfig.md
  calico/security/calico-enterprise/policy-workflow.md
  calico/security/calico-network-policy.md
  calico/upgrade/v2.5/script/upgrade.sh
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/internal/pkg/testutils/utils_windows.go
  cni-plugin/pkg/dataplane/windows/dataplane_windows.go
  cni-plugin/pkg/install/install_test.go
  cni-plugin/win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5172 Add new LogDebugFilenameRegex felix parameter.
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#5273 Misc typo fix in flexvoldriver
  pod2daemon/flexvol/flexvoldriver.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5281 update docs site references to projectcalico.docs.tigera.io
  calico/CONTRIBUTING_DOCS.md
  calico/Makefile
  calico/README.md
  calico/RELEASING.md
  calico/_config.yml
  calico/getting-started/kubernetes/helm.md
  calico/getting-started/windows-calico/quickstart.md
  calico/netlify.toml
  calico/netlify/sitemap-index.xml
  calico/reference/calicoctl/get.md
  calico/release-scripts/tests/test_helm_artifacts.py
  calico/release-scripts/tests/test_projectcalico_docs_updated.py
Labels: docs-not-required, release-note-not-required

#5276 Misc typo fixes - III
  kube-controllers/pkg/cache/cache.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
  kube-controllers/pkg/controllers/node/node_deleter.go
  kube-controllers/pkg/controllers/pod/pod_controller.go
  kube-controllers/tests/fv/flannel_migration_test.go
  kube-controllers/tests/fv/kdd_ipam_gc_test.go
  kube-controllers/tests/fv/kdd_node_ipam_test.go
  kube-controllers/tests/fv/metrics_test.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block_reader_writer_test.go
  node/Dockerfile.arm64
  node/pkg/status/populators/peers.go
  node/tests/st/utils/docker_host.py
  node/tests/st/utils/log_analyzer.py
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5274 Misc typo fixes in calicoctl dir
  calicoctl/calicoctl/commands/node/checksystem.go
  calicoctl/calicoctl/commands/node/run.go
  calicoctl/calicoctl/commands/node/status.go
  calicoctl/tests/fv/multi_context_test.go
  calicoctl/tests/st/manifests/mock-node.yaml
  calicoctl/tests/st/utils/data.py
  pod2daemon/binder/watcher.go
  pod2daemon/flexvol/flexvoldriver.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5209 cni: pass grpc dataplane options to the actual dataplane
  cni-plugin/pkg/dataplane/grpc/grpc_dataplane.go
  cni-plugin/pkg/dataplane/grpc/proto/cnibackend.pb.go
  cni-plugin/pkg/dataplane/grpc/proto/cnibackend.proto
  cni-plugin/tests/calico_cni_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5283 Make test_bgp.py:TestDisableBGPExport in node 'IP block agnostic'
  node/tests/st/bgp/test_bgp.py
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5284 Remove go.mod / go.sum in calico directory
  app-policy/Makefile
  calico/Makefile
  calico/go.mod
  calico/go.sum
  go.mod
Labels: docs-not-required, release-note-not-required

#5243 Fix autopromotion for image pushing
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/typha.yml
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#5286 Misc typo fixes in felix directory
  felix/README.md
  felix/bpf/conntrack/cleanup.go
  felix/bpf/proxy/health_check_nodeport_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/calc/l3_route_resolver.go
  felix/dataplane/linux/wireguard_mgr.go
  felix/etc/bird/calico-bird.conf.template
  felix/etc/bird/calico-bird6.conf.template
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
  felix/fv/policysync_test.go
  felix/wireguard/wireguard.go
Labels: docs-not-required, release-note-not-required

#5282 Added Calico printer for CalicoNodeStatus to apiserver
  apiserver/pkg/printers/projectcalico/caliconodestatus_printer.go
  apiserver/pkg/printers/projectcalico/utils.go
  apiserver/pkg/registry/projectcalico/caliconodestatus/storage.go
Labels: docs-not-required, release-note-not-required

#5296 Give more resources to calicoctl and node image builds
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/node.yml
Labels: docs-not-required, release-note-not-required

#5294 Docs-fix-broken-link
  calico/calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#5301 For node CD, only build amd64 for now to speed things up
  .semaphore/push-images/node.yml
Labels: docs-not-required, release-note-not-required

#5305 Split out windows-upgrade image publishing
  .semaphore/push-images/node.yml
Labels: docs-not-required, release-note-not-required

#5304 Cherrypick fixes broken link release v3.21
  calico/calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#5306 Run build command in the correct directory
  .semaphore/push-images/node.yml
Labels: docs-not-required, release-note-not-required

#5302 bpf named ports FV flake workaround
  felix/fv/connectivity/conncheck.go
  felix/fv/named_ports_test.go
Labels: docs-not-required, release-note-not-required

#5293 Kick off builds with changes to key root files
  .gitignore
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#5300 Run tests for calicoctl, pod2daemon, and app-policy
  .semaphore/semaphore.yml
  calicoctl/Makefile
  calicoctl/tests/fv/multi_context_test.go
  calicoctl/tests/fv/utils/calicoctl.go
  cni-plugin/Makefile
  cni-plugin/pkg/dataplane/grpc/proto/cnibackend.pb.go
Labels: docs-not-required, release-note-not-required

#5298 Add test reporting to node, felix, typha
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#5310 Fix handling of CRDs in calicoctl repo
  calicoctl/Makefile
  calicoctl/calicoctl/commands/crds/crds.go
  calicoctl/calicoctl/commands/crds/decode.go
  calicoctl/scripts/importcrds.go
  calicoctl/tests/st/manifests/crd.projectcalico.org_clusterinformations.yaml
Labels: docs-not-required, release-note-not-required

#5314 Add missing error return value in GetNumTyphas.
  typha/pkg/k8s/lookup.go
  typha/pkg/k8s/rebalance.go
  typha/pkg/k8s/rebalance_test.go
Labels: docs-not-required, release-note-not-required

#5320 Fix git history for image pushing / tagging in semaphore
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/typha.yml
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#5184 Return rule conversion errors from K8sNetworkPolicyToCalico()
  kube-controllers/pkg/converter/networkpolicy_converter.go
  libcalico-go/lib/backend/k8s/conversion/conversion.go
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/resources/kubenetworkpolicy.go
  libcalico-go/lib/errors/errors.go
  libcalico-go/lib/errors/errors_test.go
Labels: docs-not-required, release-note-not-required

#5315 Rev dependency patch versions
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  networking-calico/requirements.txt
Labels: docs-not-required, release-note-not-required

#5322 Collection of cherry-picks from master post-monorepo
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/typha.yml
  .semaphore/semaphore.yml
  Makefile
  README.md
  api/.github/ISSUE_TEMPLATE.md
  api/.github/PULL_REQUEST_TEMPLATE.md
  apiserver/.github/ISSUE_TEMPLATE.md
  apiserver/.github/PULL_REQUEST_TEMPLATE.md
  app-policy/.github/CODEOWNERS
  app-policy/.github/ISSUE_TEMPLATE.md
  app-policy/.github/PULL_REQUEST_TEMPLATE.md
  app-policy/Makefile
  calico/.github/CODEOWNERS
  calico/.github/ISSUE_TEMPLATE.md
  calico/Makefile
  calico/_includes/charts/calico/templates/calico-config.yaml
  calico/go.mod
  calico/go.sum
  calicoctl/.github/ISSUE_TEMPLATE.md
  calicoctl/.github/PULL_REQUEST_TEMPLATE.md
  calicoctl/Makefile
  calicoctl/calicoctl/commands/crds/crds.go
  calicoctl/calicoctl/commands/crds/decode.go
  calicoctl/scripts/importcrds.go
  calicoctl/tests/fv/multi_context_test.go
  calicoctl/tests/fv/utils/calicoctl.go
  calicoctl/tests/st/manifests/crd.projectcalico.org_clusterinformations.yaml
  cni-plugin/.github/ISSUE_TEMPLATE.md
  cni-plugin/.github/PULL_REQUEST_TEMPLATE.md
  cni-plugin/Makefile
  felix/.github/CODEOWNERS
  felix/.github/ISSUE_TEMPLATE.md
  felix/.github/PULL_REQUEST_TEMPLATE.md
  go.mod
  kube-controllers/.github/ISSUE_TEMPLATE.md
  kube-controllers/.github/PULL_REQUEST_TEMPLATE.md
  libcalico-go/.github/PULL_REQUEST_TEMPLATE.md
  node/.github/ISSUE_TEMPLATE.md
  node/.github/PULL_REQUEST_TEMPLATE.md
  pod2daemon/.github/ISSUE_TEMPLATE.md
  pod2daemon/.github/PULL_REQUEST_TEMPLATE.md
  typha/.github/CODEOWNERS
  typha/.github/ISSUE_TEMPLATE.md
  typha/.github/PULL_REQUEST_TEMPLATE.md
  typha/pkg/k8s/lookup.go
  typha/pkg/k8s/rebalance.go
  typha/pkg/k8s/rebalance_test.go
Labels: docs-not-required, release-note-not-required

#5319 Release block affinities using the exact block
  kube-controllers/pkg/controllers/node/fake_client.go
  kube-controllers/pkg/controllers/node/ipam.go
Labels: docs-not-required, release-note-not-required

#5317 Don't mask error in felix endpoint_mgr
  felix/dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required

#5326 Cherry-pick felix UT fixes
  felix/fv/connectivity/conncheck.go
  felix/fv/named_ports_test.go
Labels: docs-not-required, release-note-not-required

#5324 Pin client-go to version with fix for #5173
  go.mod
  go.sum
  libcalico-go/lib/backend/k8s/k8s_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#5285 Rev go-build to v0.65 and update x/net library for compliance
  Makefile
  api/hack/check-copyright.sh
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/apis/projectcalico/v3/zz_generated.defaults.go
  api/pkg/openapi/openapi_generated.go
  apiserver/cmd/apiserver/tools.go
  app-policy/Makefile
  calicoctl/calicoctl/commands/file/iter_test.go
  calicoctl/tests/st/utils/v1_data.py
  confd/pkg/resource/template/fileStat_posix.go
  felix/Makefile
  felix/bpf/bpf_syscall_stub.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/apply_on_forward_test.go
  felix/fv/aws_test.go
  felix/fv/bpf_test.go
  felix/fv/config_update_test.go
  felix/fv/donottrack_test.go
  felix/fv/etcd_restart_test.go
  felix/fv/forward_drop_test.go
  felix/fv/fv_infra_test.go
  felix/fv/fv_suite_test.go
  felix/fv/health_test.go
  felix/fv/host_port_test.go
  felix/fv/hostendpoints_test.go
  felix/fv/ingress_egress_test.go
  felix/fv/ipip_test.go
  felix/fv/iptables_cleanup_test.go
  felix/fv/iptables_lock_test.go
  felix/fv/latency_test.go
  felix/fv/mtu_test.go
  felix/fv/named_ports_test.go
  felix/fv/nat_outgoing_test.go
  felix/fv/netsets_test.go
  felix/fv/policysync_test.go
  felix/fv/pre_dnat_test.go
  felix/fv/rule_metadata_test.go
  felix/fv/service_loop_prevention_test.go
  felix/fv/service_policy_test.go
  felix/fv/spoof_test.go
  felix/fv/vxlan_test.go
  felix/fv/wireguard_test.go
  felix/logutils/dump.go
  go.mod
  go.sum
  libcalico-go/lib/apis/v1/openapi_generated.go
  libcalico-go/lib/apis/v3/openapi_generated.go
  libcalico-go/lib/apis/v3/zz_generated.deepcopy.go
  libcalico-go/lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  libcalico-go/test/kind_pin.go
  libcalico-go/tools.go
  metadata.mk
  node/pkg/lifecycle/startup/autodetection/ipv4/poolselector.go
  node/pkg/lifecycle/startup/autodetection/ipv4/poolselector_test.go
  node/pkg/lifecycle/startup/autodetection/ipv4/poolselector_windows.go
  node/tests/k8st/kind_pin.go
Labels: docs-not-required, release-note-not-required

#5328 Rev go-build to v0.65 and update x/net library for compliance
  Makefile
  api/hack/check-copyright.sh
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/apis/projectcalico/v3/zz_generated.defaults.go
  api/pkg/openapi/openapi_generated.go
  apiserver/cmd/apiserver/tools.go
  app-policy/Makefile
  calicoctl/calicoctl/commands/file/iter_test.go
  calicoctl/tests/st/utils/v1_data.py
  confd/pkg/resource/template/fileStat_posix.go
  felix/Makefile
  felix/bpf/bpf_syscall_stub.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/apply_on_forward_test.go
  felix/fv/aws_test.go
  felix/fv/bpf_test.go
  felix/fv/config_update_test.go
  felix/fv/donottrack_test.go
  felix/fv/etcd_restart_test.go
  felix/fv/forward_drop_test.go
  felix/fv/fv_infra_test.go
  felix/fv/fv_suite_test.go
  felix/fv/health_test.go
  felix/fv/host_port_test.go
  felix/fv/hostendpoints_test.go
  felix/fv/ingress_egress_test.go
  felix/fv/ipip_test.go
  felix/fv/iptables_cleanup_test.go
  felix/fv/iptables_lock_test.go
  felix/fv/latency_test.go
  felix/fv/mtu_test.go
  felix/fv/named_ports_test.go
  felix/fv/nat_outgoing_test.go
  felix/fv/netsets_test.go
  felix/fv/policysync_test.go
  felix/fv/pre_dnat_test.go
  felix/fv/rule_metadata_test.go
  felix/fv/service_loop_prevention_test.go
  felix/fv/service_policy_test.go
  felix/fv/spoof_test.go
  felix/fv/vxlan_test.go
  felix/fv/wireguard_test.go
  felix/logutils/dump.go
  go.mod
  go.sum
  libcalico-go/lib/apis/v1/openapi_generated.go
  libcalico-go/lib/apis/v3/openapi_generated.go
  libcalico-go/lib/apis/v3/zz_generated.deepcopy.go
  libcalico-go/lib/upgrade/migrator/clients/v1/k8s/custom/zz_generated.deepcopy.go
  libcalico-go/test/kind_pin.go
  libcalico-go/tools.go
  metadata.mk
  node/pkg/lifecycle/startup/autodetection/ipv4/poolselector.go
  node/pkg/lifecycle/startup/autodetection/ipv4/poolselector_test.go
  node/pkg/lifecycle/startup/autodetection/ipv4/poolselector_windows.go
  node/tests/k8st/kind_pin.go
Labels: docs-not-required, release-note-not-required

#5331 Fix dependencies around libbpf.
  felix/Makefile
Labels: docs-not-required, release-note-not-required

#5332 V3.21 fix stale typha issue
  go.mod
  go.sum
  libcalico-go/lib/backend/k8s/k8s_test.go
Labels: docs-not-required, release-note-not-required
