Repository projectcalico/calico, pull requests merged in 2021-11, with the labels that each got.

#4815 IPVS detection only happens at calico-node startup
  networking/use-ipvs.md
Labels: docs-not-required, release-note-not-required

#5025 Add disableBGPExport to IPPool spec
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
  reference/resources/ippool.md
Labels: docs-pr-required, release-note-not-required

#5041 add warning to wireguard EKS/AKS tutorial
  reference/felix/configuration.md
  reference/resources/felixconfig.md
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#5048 Automated cherry pick of #5025: Add disableBGPExport to IPPool spec
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
  reference/resources/ippool.md
Labels: docs-not-required, release-note-not-required

#5049 Cherrypick master commit: add warning to wireguard EKS/AKS tutorial (#5041)
  reference/felix/configuration.md
  reference/resources/felixconfig.md
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#5050 Update CalicoNodeStatus doc
  getting-started/windows-calico/limitations.md
  reference/resources/caliconodestatus.md
Labels: docs-not-required, release-note-not-required

#5051 Merge pull request #5050 from song-jiang/song-node-status
  getting-started/windows-calico/limitations.md
  reference/resources/caliconodestatus.md
Labels: docs-not-required, release-note-not-required

#4983 Automated cherry pick of #4980: Fix typo in networking/determine-best-networking.md
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#4982 Automated cherry pick of #4980: Fix typo in networking/determine-best-networking.md
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#4981 Automated cherry pick of #4980: Fix typo in networking/determine-best-networking.md
  networking/determine-best-networking.md
Labels: docs-not-required, release-note-not-required

#5040 Update service policy docs to reflect ingress rule changes
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  _includes/content/entityrule.md
  security/service-policy.md
Labels: docs-not-required, release-note-not-required

#5053 Update service policy docs to reflect ingress rule changes
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  _includes/content/entityrule.md
  security/service-policy.md
Labels: docs-not-required, release-note-not-required

#5052 Updated felixconf CRD with missing wg flags
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-required, docs-not-required

#5055 Automated cherry pick of #5054: windows docs updates
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#5054 windows: docs updates
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/quickstart.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#5058 Fix Windows AKS install script
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#5059 Merge pull request #5058 from song-jiang/song-win-aks
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#5062 Automated cherry pick of #5061: Add redirects for v3.21
  netlify.toml
Labels: docs-not-required, release-note-not-required

#5061 Add redirects for v3.21
  netlify.toml
Labels: docs-not-required, release-note-not-required

#5064 Update docs for v3.21.0
  AUTHORS.md
  _data/versions.yml
  _includes/release-notes/v3.21.0-release-notes.md
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#5067 Docs-fix-redirects-release-v3.21
  about/about-k8s-networking.md
Labels: docs-not-required, release-note-not-required

#5068 Remove support for Istio 1.7
  getting-started/kubernetes/requirements.md
  security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#5069 Version dropdown links are broken
  releases.md
Labels: docs-not-required, release-note-not-required

#5070 Remove support for Istio 1.7
  getting-started/kubernetes/requirements.md
  security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#5072 [release-v3.21] Auto pick #5069: Fix: Archive require a trailing slash
  releases.md
Labels: docs-not-required, release-note-not-required

#5075 Missing operator permission
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#5076 Temporary fix for docs search.
  RELEASING.md
  netlify/sitemap-index.xml
Labels: docs-not-required, release-note-not-required

#5077 [release-v3.21] Auto pick #5076: Temporary fix for docs search.
  RELEASING.md
  netlify/sitemap-index.xml
Labels: docs-not-required, release-note-not-required

#5078 Bump operator version
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#5081 Updates for release v3.17.6
  _data/versions.yml
  _includes/release-notes/v3.17.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#5084 Updates for release v3.18.6
  _data/versions.yml
  _includes/release-notes/v3.18.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#5066 Docs-fix-redirects-release-v3.20
  about/about-ebpf.md
  about/about-k8s-networking.md
Labels: docs-not-required, release-note-not-required

#5098 Add missing caliconodestatuses resource to apiserver role
  _includes/non-helm-manifests/apiserver.yaml
Labels: docs-not-required, release-note-not-required

#5099 Merge pull request #5098 from ffilippopoulos/apiserver-caliconodestat…
  _includes/non-helm-manifests/apiserver.yaml
Labels: docs-not-required, release-note-not-required

#5087 Non ascii char breaking apply through kubernetes.core ansible collection
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
Labels: docs-not-required, release-note-not-required

#5107 Don't configure src/dst checks for all VXLAN deployments, just on EKS
  _includes/charts/calico/templates/calico-node.yaml
  getting-started/kubernetes/managed-public-cloud/eks.md
Labels: docs-not-required, release-note-not-required

#5085 Add helm-index target
  Makefile
Labels: docs-not-required, release-note-not-required

#5065 Doc-update-cc
  about/about-network-policy.md
  calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#4867 Docs-troubleshooting
  _data/navbars/maintenance.yml
  maintenance/troubleshoot/commands.md
  maintenance/troubleshoot/troubleshooting.md
Labels: docs-not-required, release-note-not-required

#5109 Cherrypick-doc-update-cc (#5065)
  about/about-network-policy.md
  calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#5110 Update to v3.21.1
  _data/versions.yml
  _includes/release-notes/v3.21.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#5111 Remove extra v from GH release note
  Makefile
Labels: docs-not-required, release-note-not-required

#5112 Automated cherry pick of #5111: Remove extra v from GH release note
  Makefile
Labels: docs-not-required, release-note-not-required

#5113 Automated cherry pick of #5111: Remove extra v from GH release note
  Makefile
Labels: docs-not-required, release-note-not-required

#5117 Updates for release v3.20.3
  _data/versions.yml
  _includes/release-notes/v3.20.3-release-notes.md
Labels: docs-not-required, release-note-not-required
