Repository projectcalico/calico, pull requests merged in 2021-06, with the labels that each got.

#4618 [release-v3.19] Update Windows docs (#4581)
  getting-started/clis/calicoctl/install.md
  getting-started/windows-calico/demo.md
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/troubleshoot.md
Labels: docs-not-required, release-note-not-required

#4649 windows: Remove 1903 and 1909
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#4651 Depending on the method you choose, calico-node might be in kube-syst…
  getting-started/kubernetes/minikube.md
Labels: docs-not-required, release-note-not-required

#4652 Bump operator and chart version
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4654 [release-v3.17] Pick: Update OpenShift operator RBAC for certification (#4635)
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#4655 Mount CNI plugin dir into calico/node
  _includes/charts/calico/templates/calico-node.yaml
  reference/node/configuration.md
Labels: docs-not-required, release-note-required

#4660 Dont download host-local.exe on Windows
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#4668 Fix kind-builder
  hack/development-environment/README.md
  hack/development-environment/kind-local-up.sh
Labels: docs-not-required, release-note-not-required

#4674 Docs-update-link
  _layouts/docwithnav.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4675 Automated cherry pick of #4674: Fix footer
  _layouts/docwithnav.html
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4670 Fix builders tag images
  Makefile
  hack/development-environment/README.md
Labels: docs-not-required, release-note-not-required

#4663 Small Grammatical Correction in Zero-Trust Docs
  security/adopt-zero-trust.md
Labels: docs-not-required, release-note-not-required

#4683 Docs-update-hostendpoints
  getting-started/windows-calico/limitations.md
Labels: docs-not-required, release-note-not-required

#4658 Update about-networking.md
  about/about-networking.md
Labels: docs-not-required, release-note-not-required

#4648 Automated cherry pick of #4646: Fix 'Protect Kubernetes nodes' tutorial for
  security/kubernetes-nodes.md
  security/tutorials/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#4646 Fix Protect Kubernetes nodes tutorial
  security/kubernetes-nodes.md
  security/tutorials/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#4684 windows: update limitations page
  getting-started/windows-calico/limitations.md
Labels: docs-not-required, release-note-not-required

#4685 release-v3.19 - pick changes to windows limitations doc
  getting-started/windows-calico/limitations.md
Labels: docs-not-required, release-note-not-required

#4686 Updates for IPAM GC
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  reference/kube-controllers/configuration.md
  reference/resources/kubecontrollersconfig.md
Labels: docs-not-required, release-note-not-required

#4690 add docs for wireguard on aks
  networking/mtu.md
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#4691 correct wireguard site link
  networking/mtu.md
Labels: docs-not-required, release-note-not-required

#4666 Docs-update-noncluster-hosts
  _includes/content/environment-file.md
  getting-started/bare-metal/about.md
  getting-started/bare-metal/installation/binary-mgr.md
  getting-started/bare-metal/installation/binary.md
Labels: docs-not-required, release-note-not-required

#4702 VPP docs for v3.19.1
  getting-started/kubernetes/vpp/getting-started.md
  getting-started/kubernetes/vpp/ipsec.md
  maintenance/troubleshoot/vpp.md
Labels: docs-not-required, release-note-not-required

#4701 VPP docs update
  getting-started/kubernetes/vpp/getting-started.md
Labels: docs-not-required, release-note-not-required

#4696 Small typo fix in BGP docs
  networking/bgp.md
Labels: docs-not-required, release-note-not-required

#4704 Docs-etcd-note
  getting-started/kubernetes/self-managed-onprem/onpremises.md
Labels: docs-not-required, release-note-not-required
