Repository projectcalico/calico, pull requests merged in 2021-02, with the labels that each got.

#4358 require k8s 18-20
  getting-started/kubernetes/requirements.md
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4359 Updates for v3.15.4
  _data/versions.yml
  _includes/release-notes/v3.15.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#4347 Include additional architectures
  _includes/content/reqs-sys.md
  getting-started/kubernetes/quickstart.md
Labels: docs-not-required, release-note-not-required

#4360 Add documentation for changes to calicoctl
  getting-started/clis/calicoctl/configure/kdd.md
Labels: docs-not-required, release-note-not-required

#4366 Patch for v3.16.7
  _data/versions.yml
  _includes/release-notes/v3.16.7-release-notes.md
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#4363 Fix bare metal docs to run policy only.
  _includes/content/docker-container-service.md
  getting-started/bare-metal/installation/container.md
Labels: docs-not-required, release-note-not-required

#4369 Updates for v3.17.2
  _data/versions.yml
  _includes/release-notes/v3.17.2-release-notes.md
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#4137 Wrap each table to be responsive
  js/script.js
Labels: docs-not-required, release-note-not-required

#4377 Document subnet augmentation behavior for node
  reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#4378 Add new fields for service advetisement, metrics port
  reference/resources/bgpconfig.md
  reference/resources/kubecontrollersconfig.md
Labels: docs-not-required, release-note-not-required

#4379 Revert "Wrap each table to be responsive (#4137)"
  js/script.js
Labels: docs-not-required, release-note-not-required

#4376 Update reference page now correctly shows `-A` as the `--all-namespac…
  reference/calicoctl/get.md
Labels: docs-not-required, merge-when-ready, release-note-not-required

#4365 Add helm chart to release
  Makefile
  _data/versions.yml
  release-scripts/tests/test_helm_artifacts.py
Labels: docs-not-required, release-note-required

#4381 Fix nodename description for felixconfig
  maintenance/troubleshoot/component-logs.md
Labels: docs-not-required, release-note-not-required

#4364 windows: Add RBAC for EKS quickstart
  getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#4385 Add RELEASE var to replace the work of CHART_RELEASE
  Makefile
Labels: docs-not-required, release-note-not-required

#4386 Update CRDs
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_hostendpoints.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
Labels: docs-not-required, release-note-not-required

#4387 windows: fix typos and update k8s versions
  getting-started/windows-calico/kubernetes/rancher.md
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#4368 Document IPAM metrics
  _data/navbars/reference.yml
  maintenance/monitor/monitor-component-metrics.md
  reference/kube-controllers/index.md
  reference/kube-controllers/prometheus.md
  security/comms/secure-metrics.md
Labels: docs-not-required, release-note-not-required

#4388 Add watch permissions to kube-controllers on IPAM blocks
  _includes/charts/calico/templates/calico-kube-controllers-rbac.yaml
Labels: docs-not-required, release-note-not-required

#4375 Add IPAM check and release docs
  _data/navbars/reference.yml
  reference/calicoctl/ipam/check.md
  reference/calicoctl/ipam/release.md
Labels: docs-not-required, merge-when-ready, release-note-not-required, squash-commits

#4390 Document host endpoint support for eBPF mode
  about/about-ebpf.md
  maintenance/ebpf/enabling-bpf.md
  reference/felix/configuration.md
Labels: cherry-pick-candidate, docs-not-required, merge-when-ready, release-note-not-required

#4391 [v3.18] BPF support for host endpoints
  about/about-ebpf.md
  maintenance/ebpf/enabling-bpf.md
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#4394 Fix kube-controllers prometheus metrics link
  reference/kube-controllers/configuration.md
  reference/kube-controllers/prometheus.md
Labels: docs-not-required, release-note-not-required

#4395 Update operator CRDs
  _includes/charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  _includes/charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml
Labels: docs-not-required, release-note-not-required

#4396 Automated cherry pick of #4395: Update operator CRDs
  _includes/charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  _includes/charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml
Labels: docs-not-required, release-note-not-required

#4397 Automated cherry pick of #4394: Fix kube-controllers prometheus metrics link
  reference/kube-controllers/configuration.md
  reference/kube-controllers/prometheus.md
Labels: docs-not-required, release-note-not-required

#4398 Update prometheus.md
  reference/kube-controllers/prometheus.md
Labels: docs-not-required, release-note-not-required

#4401 Automated cherry pick of #4398: Update prometheus.md
  reference/kube-controllers/prometheus.md
Labels: docs-not-required, release-note-not-required

#4403 Clarify how to create node-specific Felixconfigs
  reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#4405 Fix typo in NAT section on about-networking.md
  about/about-networking.md
Labels: docs-not-required, release-note-not-required

#4406 Updates for release v3.16.8
  _data/versions.yml
  _includes/release-notes/v3.16.8-release-notes.md
Labels: docs-not-required, release-note-not-required

#4409 Updates for v3.17.3
  _data/versions.yml
  _includes/release-notes/v3.17.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#4402 format calicoctl samples to match one accepted by kubectl
  security/tutorials/protect-hosts.md
Labels: docs-not-required, release-note-not-required

#4413 Updates for v3.18.0
  AUTHORS.md
  Makefile
  _data/archives.yml
  _data/versions.yml
  _includes/release-notes/v3.18.0-release-notes.md
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4414 Redirects for v3.18
  AUTHORS.md
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4415 Fix formatting of release notes
  _includes/release-notes/v3.18.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#4417 Update test_helm_artifacts.py
  release-scripts/tests/test_helm_artifacts.py
Labels: docs-not-required, release-note-not-required

#4418 Merge pull request #4417 from projectcalico/lwr-fix-post-rel-helm
  release-scripts/tests/test_helm_artifacts.py
Labels: docs-not-required, release-note-not-required

#4156 update to make calicoctl installation page multiarch friendly
  _includes/content/ctl-binary-install.md
  _includes/content/ctl-container-install.md
  _includes/content/ctl-kubectl-plugin-install.md
  _includes/urls
  getting-started/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#4399 Moved the entire section "Calico for Windows" to the top level nav tab
  _data/navbars/calico-enterprise.yml
  _data/navbars/calico-for-windows.yml
  _data/navbars/getting-started.yml
  _data/navbars/reference.yml
  _data/navbars/release-notes.yml
  windows-calico/demo.md
  windows-calico/index.md
  windows-calico/kubeconfig.md
  windows-calico/kubernetes/index.md
  windows-calico/kubernetes/rancher.md
  windows-calico/kubernetes/requirements.md
  windows-calico/kubernetes/standard.md
  windows-calico/limitations.md
  windows-calico/maintain.md
  windows-calico/openshift/index.md
  windows-calico/openshift/installation.md
  windows-calico/quickstart.md
  windows-calico/troubleshoot.md
Labels: docs-not-required, release-note-not-required

#4419 Clarify per-node BGPconfig abilities
  reference/resources/bgpconfig.md
Labels: docs-not-required, release-note-not-required

#4424 Added Calico for Windows on AKS
  windows-calico/kubernetes/standard.md
  windows-calico/limitations.md
  windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required
