Repository projectcalico/calico, pull requests merged in 2021-05, with the labels that each got.

#4590 Fix FD.io attribution
  _includes/release-notes/v3.19.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#4591 Updates for Calico v3.18.3
  _data/versions.yml
  _includes/release-notes/v3.18.2-release-notes.md
  _includes/release-notes/v3.18.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#4593 Add docs for operator upgrade
  maintenance/kubernetes-upgrade.md
Labels: docs-not-required, merge-when-ready, release-note-not-required

#4598 Fix optional fields from being required for failsafe rules
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-not-required, release-note-not-required

#4600 Update operator version to v1.17.1
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4601 Fix mistaken removal of required field protocol from failsafe rules
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-not-required, release-note-not-required

#4602 Fix optional cidrs from being required for failsafe rules
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-not-required, release-note-not-required

#4608 Add a NP to ensure Calico API server isn't cut off
  _includes/non-helm-manifests/apiserver.yaml
Labels: docs-not-required, release-note-not-required

#4517 Expand details on kvc-wireguard-kmod conf file
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#4581 Update Windows docs
  getting-started/clis/calicoctl/install.md
  getting-started/windows-calico/demo.md
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/troubleshoot.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#4592 Fix typos in security/encrypt-cluster-pod-traffic document
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#4616 rbac.authorization.k8s.io/v1beta -> v1
  getting-started/kubernetes/hardway/end-user-rbac.md
  maintenance/monitor/monitor-component-metrics.md
Labels: docs-not-required, release-note-not-required

#4619 Adjust enterprise try link to go to calico cloud
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#4624 Automated cherry pick of #4619: Adjust enterprise try link to go to calico cloud [r3.15]
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#4623 Automated cherry pick of #4619: Adjust enterprise try link to go to calico cloud [r3.16]
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#4622 Automated cherry pick of #4619: Adjust enterprise try link to go to calico cloud [r3.17]
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#4621 Automated cherry pick of #4619: Adjust enterprise try link to go to calico cloud [r3.18]
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#4620 Automated cherry pick of #4619: Adjust enterprise try link to go to calico cloud [r3.19]
  _includes/enterprise_header.html
Labels: docs-not-required, release-note-not-required

#4627 Updates for v3.19.1
  _data/versions.yml
  _includes/release-notes/v3.19.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#4628 make release description more clear
  Makefile
Labels: docs-not-required, release-note-not-required

#4636 Updates for v3.18.4
  _data/versions.yml
  _includes/release-notes/v3.18.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#4640 Bump operator version
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4639 Add post-release check to test operator images are correct
  Makefile
  release-scripts/tests/test_images.py
Labels: docs-not-required, release-note-not-required

#4635 Update OpenShift operator RBAC for certification
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: cherry-pick-completed, docs-not-required, release-note-not-required

#4643 Automated cherry pick of #4635: Update OpenShift operator RBAC for certification
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#4642 Automated cherry pick of #4635: Update OpenShift operator RBAC for certification
  _includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#4629 Add helm index to docs
  .gitignore
  Makefile
  RELEASING.md
  getting-started/kubernetes/helm.md
  maintenance/kubernetes-upgrade.md
  netlify.toml
  release-scripts/tests/test_helm_artifacts.py
Labels: docs-completed, release-note-required

#4644 Update operator docs and CRDs
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required

#4645 Update operator docs and CRDs
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required
