Repository projectcalico/calico, pull requests merged in 2021-04, with the labels that each got.

#4501 Switch EKS guide to use operator.
  maintenance/ebpf/ebpf-and-eks.md
Labels: docs-not-required, release-note-not-required

#4504 Fix installation patch instructions for enabling eBPF.
  maintenance/ebpf/ebpf-and-eks.md
  maintenance/ebpf/enabling-bpf.md
Labels: docs-not-required, release-note-not-required

#4507 calicoctl doc update
  _includes/content/reqs-kernel.md
  reference/calicoctl/node/checksystem.md
Labels: docs-not-required, release-note-not-required

#4508 Update istio-inject-configmap-1.7.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
Labels: docs-not-required, release-note-not-required

#4512 Move "Calico for Windows" back to getting-started
  _data/navbars/calico-enterprise.yml
  _data/navbars/calico-for-windows.yml
  _data/navbars/getting-started.yml
  _data/navbars/reference.yml
  _data/navbars/release-notes.yml
  getting-started/windows-calico/demo.md
  getting-started/windows-calico/index.md
  getting-started/windows-calico/kubeconfig.md
  getting-started/windows-calico/kubernetes/index.md
  getting-started/windows-calico/kubernetes/rancher.md
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/limitations.md
  getting-started/windows-calico/maintain.md
  getting-started/windows-calico/openshift/index.md
  getting-started/windows-calico/openshift/installation.md
  getting-started/windows-calico/quickstart.md
  getting-started/windows-calico/troubleshoot.md
Labels: docs-not-required, release-note-not-required

#4465 Update helm.md
  getting-started/kubernetes/helm.md
Labels: docs-not-required, release-note-not-required

#4463 Update encrypt-cluster-pod-traffic.md
  security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#4485 Add API server tech-preview doc
  _config.yml
  _data/navbars/getting-started.yml
  _data/versions.yml
  _includes/non-helm-manifests/apiserver.yaml
  getting-started/kubernetes/apiserver-preview.md
  manifests/apiserver.yaml
  reference/resources/networkpolicy.md
Labels: docs-not-required, release-note-not-required

#4530 Add context to calicoctl install doc
  getting-started/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#4537 Update flannel to v0.13.0
  _data/versions.yml
Labels: docs-not-required, release-note-not-required

#4536 Docs-clarify-ippools
  networking/change-block-size.md
  networking/legacy-firewalls.md
Labels: docs-not-required, release-note-not-required

#4544 windows: document containerd support
  getting-started/windows-calico/kubernetes/requirements.md
  getting-started/windows-calico/kubernetes/standard.md
  getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#4527 Update azure.md
  reference/public-cloud/azure.md
Labels: docs-not-required, release-note-not-required

#4543 Update docs for CIDRs in failsafe ports
  _includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  reference/felix/configuration.md
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#4531 Update reqs-sys.md
  _includes/content/reqs-sys.md
Labels: docs-not-required, release-note-not-required

#4546 Add mtuIfacePattern to FelixConfig
  reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#4547 Add iface regex to other felixconfig page
  reference/felix/configuration.md
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#4548 Clarifying Windows Server 2019 DSR availability build information Update demo.md (#4472)
  getting-started/windows-calico/demo.md
Labels: docs-not-required, release-note-not-required

#4545 Fix apiserver RBAC
  _includes/non-helm-manifests/apiserver.yaml
Labels: docs-not-required, release-note-not-required

#4549 Rename API server doc to be more user-focused
  _data/navbars/getting-started.yml
  getting-started/kubernetes/apiserver-preview.md
Labels: docs-not-required, release-note-not-required

#4550 Fix example openssl command to use a subjectAltName
  getting-started/kubernetes/apiserver-preview.md
Labels: docs-not-required, release-note-not-required

#4552 Updates for release-v3.16.10
  _data/versions.yml
  _includes/release-notes/v3.16.10-release-notes.md
Labels: docs-not-required, release-note-not-required

#4383 Add VPP dataplane docs
  Makefile
  _data/navbars/getting-started.yml
  _data/navbars/maintenance.yml
  _data/navbars/reference.yml
  getting-started/kubernetes/vpp/getting-started.md
  getting-started/kubernetes/vpp/index.md
  getting-started/kubernetes/vpp/ipsec.md
  images/vpp-host-net.svg
  images/vpp-net-arch.svg
  images/vpp-soft-arch.svg
  images/vpp-tracing-net.svg
  maintenance/troubleshoot/vpp.md
  reference/vpp/host-network.md
  reference/vpp/index.md
  reference/vpp/technical-details.md
  reference/vpp/uplink-configuration.md
Labels: docs-not-required, release-note-not-required

#4554 Update release v3.15.5
  _data/versions.yml
  _includes/release-notes/v3.15.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#4555 Automated cherry pick of #4383: Add VPP data plane docs
  Makefile
  _data/navbars/getting-started.yml
  _data/navbars/maintenance.yml
  _data/navbars/reference.yml
  getting-started/kubernetes/vpp/getting-started.md
  getting-started/kubernetes/vpp/index.md
  getting-started/kubernetes/vpp/ipsec.md
  images/vpp-host-net.svg
  images/vpp-net-arch.svg
  images/vpp-soft-arch.svg
  images/vpp-tracing-net.svg
  maintenance/troubleshoot/vpp.md
  reference/vpp/host-network.md
  reference/vpp/index.md
  reference/vpp/technical-details.md
  reference/vpp/uplink-configuration.md
Labels: docs-not-required, release-note-not-required

#4559 Update Kubernetes versions.
  getting-started/kubernetes/requirements.md
Labels: docs-not-required, merge-when-ready, release-note-not-required

#4560 [v3.19] Update Kubernetes versions.
  getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#4565 VPP: Update docs to account for the namespace change
  getting-started/kubernetes/vpp/getting-started.md
  getting-started/kubernetes/vpp/ipsec.md
  maintenance/troubleshoot/vpp.md
  reference/vpp/uplink-configuration.md
Labels: docs-not-required, release-note-not-required

#4566 Automated cherry pick of #4565: VPP: Update docs to account for the namespace change
  getting-started/kubernetes/vpp/getting-started.md
  getting-started/kubernetes/vpp/ipsec.md
  maintenance/troubleshoot/vpp.md
  reference/vpp/uplink-configuration.md
Labels: docs-not-required, release-note-not-required

#4568 Updates for release v3.17.4
  _data/versions.yml
  _includes/release-notes/v3.17.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#4571 Updates for release v3.18.2
  _data/versions.yml
  _includes/release-notes/v3.18.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#4572 vpp: use latest release manifests
  getting-started/kubernetes/vpp/getting-started.md
  getting-started/kubernetes/vpp/ipsec.md
  maintenance/troubleshoot/vpp.md
Labels: docs-not-required, release-note-not-required

#4562 api-server page improvements
  getting-started/kubernetes/apiserver-preview.md
Labels: docs-not-required, release-note-not-required

#4574 Automated cherry pick of #4562: Fix: Change Uninstall address to an absolute url. Add:
  getting-started/kubernetes/apiserver-preview.md
Labels: docs-not-required, release-note-not-required

#4579 Fix label in HEP example
  security/defend-dos-attack.md
Labels: docs-not-required, release-note-not-required

#4584 Create the proper redirects and versions for the v3.19.0 images
  _data/versions.yml
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4586 Create redirects for v3.19
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4587 Adds redirects to v3.19 and fixes a redirect for v3.18
  netlify.toml
Labels: docs-not-required, release-note-not-required

#4582 Updates for release v3.19.0
  AUTHORS.md
  _data/archives.yml
  _includes/release-notes/v3.19.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#4588 Allow the release notes to populate correctly
  _data/versions.yml
Labels: docs-not-required, release-note-not-required
