Repository projectcalico/calico, pull requests merged in 2021-09, with the labels that each got.

#4873 Docs-seo-networking-ebpf
  _data/navbars/about.yml
  about/about-ebpf.md
  about/about-k8s-networking.md
  about/about-network-policy.md
Labels: hold-merge, docs-not-required, release-note-not-required

#4896 Add canonical url for ebpf
  about/about-ebpf.md
  about/about-kubernetes-networking.md
Labels: docs-not-required, release-note-not-required

#4897 Automated cherry pick of #4896: Add canonical url for ebpf Add canonical url and redirect for
  about/about-ebpf.md
  about/about-kubernetes-networking.md
Labels: docs-not-required, release-note-not-required

#4898 Automated cherry pick of #4896: Add canonical url for ebpf Add canonical url and redirect for
  about/about-ebpf.md
  about/about-kubernetes-networking.md
Labels: docs-not-required, release-note-not-required

#4899 Automated cherry pick of #4896: Add canonical url for ebpf Add canonical url and redirect for
  about/about-ebpf.md
  about/about-kubernetes-networking.md
Labels: docs-not-required, release-note-not-required

#4900 Automated cherry pick of #4896: Add canonical url for ebpf Add canonical url and redirect for
  about/about-kubernetes-networking.md
Labels: docs-not-required, release-note-not-required

#4895 Automated cherry pick of #4873: Changed file name for Kubernetes Networking per Laura
  _data/navbars/about.yml
  about/about-ebpf.md
  about/about-k8s-networking.md
  about/about-network-policy.md
Labels: docs-not-required, release-note-not-required

#4891 Add semaphore V2 config
  .semaphore/semaphore.yml
  Makefile
  _data/archives.yml
  _includes/release-notes/v3.19.0-release-notes.md
  getting-started/kubernetes/apiserver-preview.md
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  getting-started/windows-calico/limitations.md
  maintenance/ebpf/ebpf-and-eks.md
  maintenance/monitor/monitor-component-visual.md
  networking/ipv6.md
  reference/architecture/design/l2-interconnect-fabric.md
  reference/vpp/uplink-configuration.md
  security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#4901 Fix hostendpoint reference doc re: policy support
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#4908 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  .semaphore/semaphore.yml
  Makefile
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  reference/architecture/design/l2-interconnect-fabric.md
  reference/resources/hostendpoint.md
  security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#4905 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#4904 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#4903 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#4902 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  reference/resources/hostendpoint.md
Labels: docs-not-required, release-note-not-required

#4906 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  .semaphore/semaphore.yml
  Makefile
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  maintenance/monitor/monitor-component-visual.md
  reference/architecture/design/l2-interconnect-fabric.md
  reference/resources/hostendpoint.md
  security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#4864 Docs-update-architecture
  images/architecture-calico.svg
  reference/architecture/overview.md
Labels: docs-not-required, release-note-not-required

#4928 Remove outdated steps in the Istio tutorial
  security/tutorials/app-layer-policy/enforce-policy-istio.md
  security/tutorials/app-layer-policy/manifests/20-attack-pod.yaml
Labels: docs-not-required, release-note-not-required

#4929 Remove outdated steps in the Istio tutorial
  security/tutorials/app-layer-policy/enforce-policy-istio.md
  security/tutorials/app-layer-policy/manifests/20-attack-pod.yaml
Labels: docs-not-required, release-note-not-required

#4930 Updates for release-v3.19.3
  _data/versions.yml
  _includes/release-notes/v3.19.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#4925 Update Calico the Hard Way guide
  getting-started/kubernetes/hardway/end-user-rbac.md
  getting-started/kubernetes/hardway/install-cni-plugin.md
  getting-started/kubernetes/hardway/install-node.md
  getting-started/kubernetes/hardway/istio-integration.md
  getting-started/kubernetes/hardway/standing-up-kubernetes.md
  getting-started/kubernetes/hardway/the-calico-datastore.md
  security/tutorials/app-layer-policy/enforce-policy-istio.md
Labels: docs-not-required, release-note-not-required

#4933 Add correct path for cloud image
  _includes/cloud_header.html
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#4940 Updates for release v3.20.1
  AUTHORS.md
  _data/versions.yml
  _includes/release-notes/v3.20.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#4941 Fix links in calicoctl install guide
  getting-started/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#4945 Automated cherry pick of #4941: Fix links in calicoctl install guide
  getting-started/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#4948 Add missing release notes from networking-calico
  _includes/release-notes/v3.19.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#4949 Add missing release notes from networking-calico
  _includes/release-notes/v3.20.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#4907 Automated cherry pick of #4901: Fix hostendpoint reference doc re: policy support
  .semaphore/semaphore.yml
  Makefile
  getting-started/kubernetes/self-managed-public-cloud/azure.md
  maintenance/monitor/monitor-component-visual.md
  reference/architecture/design/l2-interconnect-fabric.md
  reference/resources/hostendpoint.md
  security/kubernetes-network-policy.md
Labels: docs-not-required, release-note-not-required

#4939 Use IMDSv2 to fetch instance hostname
  scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#4962 Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4966 [release-v3.20] Auto pick #4962: Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4967 [release-v3.19] Auto pick #4962: Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4968 [release-v3.18] Auto pick #4962: Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4969 [release-v3.17] Auto pick #4962: Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4970 [release-v3.16] Auto pick #4962: Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4971 [release-v3.15] Auto pick #4962: Revert 3707, remove anti-flicker snippet
  _layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required

#4972 Docs-add-comment
  about/about-ebpf.md
  about/about-k8s-networking.md
Labels: docs-not-required, release-note-not-required

#4950 Docs-ebpf-use-cases
  _data/navbars/maintenance.yml
  maintenance/ebpf/use-cases-ebpf.md
Labels: docs-not-required, release-note-not-required

#4960 Docs Typo in Install calicoctl
  getting-started/clis/calicoctl/install.md
  maintenance/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#4973 Add ControlPlaneReplicas in Installations CRD
  _includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  reference/installation/_api.html
Labels: docs-not-required, release-note-not-required
