Repository projectcalico/calico, pull requests merged in 2022-09, with the labels that each got.

#6647 [release v3.24] cherry-pick: Add BPFDisableLinuxConntrack to Calico Api
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  felix/config/config_params_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6646 [release-v3.23] Cherry pick: Add BPFDisableLinuxConntrack to Calico Api
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  felix/config/config_params_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: release-note-required, docs-not-required

#6650 Fix calicoctl IPAM handle release in KDD mode
  calicoctl/calicoctl/commands/ipam/check.go
  calicoctl/calicoctl/commands/ipam/release.go
  calicoctl/test-data/kubeconfig.yaml
  calicoctl/tests/fv/ipam_test.go
  calicoctl/tests/fv/migrate_ipam_test.go
  calicoctl/tests/fv/multi_context_test.go
  calicoctl/tests/fv/namespace_option_test.go
  calicoctl/tests/fv/utils/calicoctl.go
  calicoctl/tests/fv/utils/datastore.go
  calicoctl/tests/fv/utils/env.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6652 Pick: pull request #6650 from fasaxc/fix-handle-release
  calicoctl/calicoctl/commands/ipam/check.go
  calicoctl/calicoctl/commands/ipam/release.go
  calicoctl/test-data/kubeconfig.yaml
  calicoctl/tests/fv/ipam_test.go
  calicoctl/tests/fv/migrate_ipam_test.go
  calicoctl/tests/fv/multi_context_test.go
  calicoctl/tests/fv/namespace_option_test.go
  calicoctl/tests/fv/utils/calicoctl.go
  calicoctl/tests/fv/utils/datastore.go
  calicoctl/tests/fv/utils/env.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6666 Swap Typha's Ctrie for Google's B-Tree library. Add snapshot size gauge
  go.mod
  go.sum
  typha/pkg/daemon/daemon.go
  typha/pkg/snapcache/cache.go
  typha/pkg/snapcache/cache_test.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6668 Containerize OpenStack UT + FV testing
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  networking-calico/.testr.conf
  networking-calico/Dockerfile
  networking-calico/Makefile
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_election.py
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
  networking-calico/test-requirements.txt
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#6658 update golang version
  metadata.mk
Labels: release-note-required, docs-pr-required

#6659 Cherry-pick 6658
  metadata.mk
Labels: release-note-required, docs-pr-required

#6576 Fixing broken nested tab structure.
  calico/reference/cni-plugin/configuration.md
Labels: release-note-required, docs-pr-required

#6676 Always program OpenStack floating IPs
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  felix/config/config_params.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/floating_ip_mgr.go
  felix/dataplane/linux/floating_ip_mgr_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6669 Reinstate DevStack testing (for OpenStack)
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  devstack
  networking-calico/devstack/README.rst
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/plugin.sh
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#6683 DOCS-507: Fixes bad link to typha repo
  calico/reference/architecture/overview.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6672 felix/bpf: simplify programming jump maps
  felix/bpf/bpf_defs.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/tc/defs/defs.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#6678 Automatically build and publish master packages for OpenStack
  .semaphore/push-images/packaging.yaml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  hack/release/packaging/utils/publish-debs.sh
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#6684 Fix shell syntax error in OpenStack packaging YAML
  .semaphore/push-images/packaging.yaml
Labels: docs-not-required, release-note-not-required

#6656 fix: pods lost ip addreses after windows node reboot.
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
Labels: release-note-required, docs-not-required, merge-when-ready

#6690 Remove Features from TC attachpoint
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#6671 felix/encap: ignore vxlanEnabled for ipv6
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6689 [Release v3.23] Cherry-pick: Pass proper EndPointType for l3 ipip devices. (#6373)
  felix/bpf/tc/compiler.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#6699 [release-v3.23] Auto pick #6671: felix/encap: ignore vxlanEnabled for ipv6
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-required, docs-pr-required

#6696 Defer generation of TLS certs in typha FVs.
  typha/fv-tests/server_test.go
Labels: docs-not-required, release-note-not-required

#6700 [release-v3.24] Auto pick #6671: felix/encap: ignore vxlanEnabled for ipv6
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6701 bpf printk gets fmt from .rodata instead of stack
  felix/bpf-gpl/log.h
Labels: release-note-required, docs-pr-required

#6675 Split Typha metrics by syncer type
  calico/reference/typha/prometheus.md
  typha/fv-tests/server_test.go
  typha/pkg/daemon/daemon_test.go
  typha/pkg/k8s/rebalance.go
  typha/pkg/promutils/registration.go
  typha/pkg/snapcache/cache.go
  typha/pkg/syncproto/sync_proto.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-completed

#6724 Move OCP manifest used for past certifications
  manifests/README.md
  manifests/ocp-tigera-operator-no-resource-loading.yaml
Labels: release-note-required, docs-not-required

#6726 Move OCP manifest used for past certifications
  manifests/README.md
  manifests/ocp-tigera-operator-no-resource-loading.yaml
Labels: release-note-required, docs-not-required

#6727 Ensure OCP tarball regenerates on file change
  calico/Makefile
Labels: release-note-required, docs-pr-required

#6728 Ensure OCP tarball regenerates on file change
  calico/Makefile
Labels: release-note-required, docs-pr-required

#6674 fix: update hashToIPV4 method
  confd/pkg/resource/template/template_funcs.go
  confd/pkg/resource/template/template_funcs_test.go
  confd/pkg/resource/template/template_suite_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6720 [release-v3.24] cherry-pick 6719
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#6735 Sync CRDs (v3.24)
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6738 Sync operator CRDs
  charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_apiservers_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6707 [release-v3.22] DOCS-507: Fixes bad link to typha repo
  calico/reference/architecture/overview.md
Labels: release-note-required, docs-pr-required

#6708 [release-v3.23] DOCS-507: Fixes bad link to typha repo
  calico/reference/architecture/overview.md
Labels: docs-not-required, release-note-not-required

#6706 [release-v3.24] DOCS-507: Fixes bad link to typha repo
  calico/reference/architecture/overview.md
Labels: release-note-required, docs-pr-required

#6714 DOCS-673: Fixing bad links
  calico/getting-started/windows-calico/troubleshoot.md
  calico/maintenance/install-apiserver.md
Labels: release-note-required, docs-pr-required

#6637 calico node arm64 dockerfile update
  node/Dockerfile.arm64
Labels: kind/enhancement, docs-not-required, release-note-not-required, area/arm64

#6717 Update golang to v1.18.6
  metadata.mk
Labels: release-note-required, docs-not-required, merge-when-ready

#6743 Deletes unused content in `getting-started/clis` and `networking`
  calico/getting-started/clis/calicoctl/configure/etcd.md
  calico/getting-started/clis/calicoctl/configure/index.md
  calico/getting-started/clis/calicoctl/configure/kdd.md
  calico/getting-started/clis/calicoctl/configure/overview.md
  calico/getting-started/clis/calicoctl/index.md
  calico/getting-started/kubernetes/requirements.md
  calico/networking/enabling-ipvs.md
Labels: docs-not-required, release-note-not-required

#6742 fix: update template test cases
  confd/pkg/resource/template/template_funcs_test.go
  confd/pkg/resource/template/template_suite_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6721 felix/bpf: bpf_attr_setup_load_prog takes prog name
  felix/bpf-gpl/log.h
  felix/bpf/bpf_syscall.go
  felix/bpf/bpf_syscall.h
  felix/bpf/bpf_syscall_stub.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#6718 [release-v3.24] cherry-pick 6717
  metadata.mk
Labels: release-note-required, docs-not-required, merge-when-ready

#6757 upgrade flannel version to v0.16.3
  calico/_config.yml
  calico/_data/versions.yml
  charts/calico/values.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  node/tests/k8st/infra/values.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#6758 Update docs to indicate natOutgoing is needed for Wireguard
  api/pkg/apis/projectcalico/v3/ippool.go
  api/pkg/openapi/openapi_generated.go
  calico/getting-started/windows-calico/limitations.md
  calico/networking/ipv6.md
  calico/networking/workloads-outside-cluster.md
  calico/security/encrypt-cluster-pod-traffic.md
  cni-plugin/internal/pkg/utils/winpol/windows_policy.go
  felix/fv/nat_outgoing_test.go
  libcalico-go/config/crd/crd.projectcalico.org_ippools.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_ippools.yaml
  manifests/tigera-operator.yaml
Labels: docs-completed, release-note-not-required

#6759 [release-v3.24] Auto pick #6758: Update docs to indicate natOutgoing is needed for
  api/pkg/apis/projectcalico/v3/ippool.go
  api/pkg/openapi/openapi_generated.go
  calico/getting-started/windows-calico/limitations.md
  calico/networking/ipv6.md
  calico/networking/workloads-outside-cluster.md
  calico/security/encrypt-cluster-pod-traffic.md
  cni-plugin/internal/pkg/utils/winpol/windows_policy.go
  felix/fv/nat_outgoing_test.go
  libcalico-go/config/crd/crd.projectcalico.org_ippools.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_ippools.yaml
  manifests/tigera-operator.yaml
Labels: docs-completed, release-note-not-required, merge-when-ready

#6725 Calico for OpenStack: Handle changing MTU in the scenarios where Nova and libvirt successfully handle that
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/interface.py
Labels: release-note-required, docs-pr-required

#6763 packaging: unshallow in order to get a reliable git describe
  .semaphore/push-images/packaging.yaml
Labels: docs-not-required, release-note-not-required

#6764 Increment Debian packaging epoch to "2:"
  hack/release/packaging/utils/create-update-packages.sh
Labels: docs-not-required, release-note-not-required

#6679 Fix population of IPAM handle UID field.
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  calicoctl/tests/fv/ipam_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6713 [release-v3.24] Auto pick #6679: Fix population of IPAM handle UID field.
  calicoctl/tests/fv/ipam_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle.go
Labels: docs-not-required, release-note-not-required

#6611 Fix allowed source prefix annotation validation
  libcalico-go/lib/apis/v3/workloadendpoint.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#6771 Allow dnsmasq to start when there's a race with no ports
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
Labels: docs-not-required, release-note-not-required

#6765 Merge pull request #6725 from neiljerram/openstack-watch-mtu
  .semaphore/publish-artifacts
  .semaphore/run-and-monitor
  .semaphore/semaphore.yml
  devstack
  networking-calico/.gitignore
  networking-calico/.semaphore/semaphore.yml
  networking-calico/.testr.conf
  networking-calico/Dockerfile
  networking-calico/Makefile
  networking-calico/devstack/README.rst
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/plugin.sh
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
  networking-calico/networking_calico/agent/linux/interface.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_election.py
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
  networking-calico/test-requirements.txt
Labels: release-note-required, docs-pr-required

#6768 Update getting-started.md
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: docs-not-required, release-note-not-required

#6719 Update dependencies
  go.mod
  go.sum
Labels: release-note-required, docs-not-required, merge-when-ready

#6781 DOCS-716: Added missing title metadata to index files
  calico/getting-started/bare-metal/installation/index.md
  calico/getting-started/kubernetes/hardway/index.md
  calico/getting-started/openstack/index.md
  calico/getting-started/openstack/installation/index.md
  calico/reference/calicoctl/datastore/index.md
  calico/reference/calicoctl/datastore/migrate/index.md
  calico/reference/calicoctl/index.md
  calico/reference/calicoctl/ipam/index.md
  calico/reference/calicoctl/node/index.md
  calico/reference/etcd-rbac/index.md
  calico/reference/host-endpoints/index.md
  calico/reference/resources/index.md
  calico/security/calico-policy.md
  calico/security/kubernetes-policy.md
Labels: docs-not-required, release-note-not-required

#6780 Openstack watch mtu v3.24
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  devstack
  networking-calico/.testr.conf
  networking-calico/Dockerfile
  networking-calico/Makefile
  networking-calico/devstack/README.rst
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/plugin.sh
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
  networking-calico/networking_calico/agent/linux/interface.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_election.py
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
  networking-calico/test-requirements.txt
Labels: release-note-required, docs-not-required

#6779 Merge pull request #6765 from neiljerram/openstack-watch-mtu-v3.22
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  devstack
  networking-calico/.testr.conf
  networking-calico/Dockerfile
  networking-calico/Makefile
  networking-calico/devstack/README.rst
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/plugin.sh
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
  networking-calico/networking_calico/agent/linux/interface.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_election.py
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
  networking-calico/test-requirements.txt
Labels: release-note-required, docs-not-required

#6527 felix/bpf: CTLB workaround for host and nodeports
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/list-objs
  felix/bpf-gpl/reasons.h
  felix/bpf-gpl/routes.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/skb.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf/arp/map.go
  felix/bpf/conntrack/v3/map.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/state/map.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/ut/nat_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/bpf/ut/snat_test.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/fv/bpf_attach_test.go
  felix/fv/bpf_test.go
  felix/fv/ipip_test.go
Labels: release-note-required, docs-pr-required

#6777 [release-v3.23] cherry-pick: Fix allowed source prefix annotation validation
  libcalico-go/lib/apis/v3/workloadendpoint.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6748 Update BIRD version to include memory usage fix
  metadata.mk
Labels: docs-not-required, release-note-not-required

#6782 Fix that dnsmasq was continually restarting when not needed
  networking-calico/networking_calico/agent/dhcp_agent.py
Labels: docs-not-required, release-note-not-required

#6788 DHCP agent: Fix check for linux interface being up
  networking-calico/networking_calico/agent/dhcp_agent.py
Labels: docs-not-required, release-note-not-required

#6796 Regenerate FV test keys and certificates; extend certs to 10 years.
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  hack/test/certs/README.md
  hack/test/certs/admin-key.pem
  hack/test/certs/admin.csr
  hack/test/certs/admin.pem
  hack/test/certs/ca-config.json
  hack/test/certs/ca-key.pem
  hack/test/certs/ca.csr
  hack/test/certs/ca.pem
  hack/test/certs/kube-controller-manager.kubeconfig
  hack/test/certs/kubernetes-key.pem
  hack/test/certs/kubernetes.csr
  hack/test/certs/kubernetes.pem
  hack/test/certs/regenerate.sh
  hack/test/certs/service-account-key.pem
  hack/test/certs/service-account.csr
  hack/test/certs/service-account.pem
Labels: docs-not-required, release-note-not-required

#6797 [v3.23] Fix FV certs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  hack/test/certs/README.md
  hack/test/certs/admin-key.pem
  hack/test/certs/admin.csr
  hack/test/certs/admin.pem
  hack/test/certs/ca-config.json
  hack/test/certs/ca-key.pem
  hack/test/certs/ca.csr
  hack/test/certs/ca.pem
  hack/test/certs/kube-controller-manager.kubeconfig
  hack/test/certs/kubernetes-key.pem
  hack/test/certs/kubernetes.csr
  hack/test/certs/kubernetes.pem
  hack/test/certs/regenerate.sh
  hack/test/certs/service-account-key.pem
  hack/test/certs/service-account.csr
  hack/test/certs/service-account.pem
Labels: docs-not-required, release-note-not-required

#6798 [v3.24] Fix FV certs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  hack/test/certs/README.md
  hack/test/certs/admin-key.pem
  hack/test/certs/admin.csr
  hack/test/certs/admin.pem
  hack/test/certs/ca-config.json
  hack/test/certs/ca-key.pem
  hack/test/certs/ca.csr
  hack/test/certs/ca.pem
  hack/test/certs/kube-controller-manager.kubeconfig
  hack/test/certs/kubernetes-key.pem
  hack/test/certs/kubernetes.csr
  hack/test/certs/kubernetes.pem
  hack/test/certs/regenerate.sh
  hack/test/certs/service-account-key.pem
  hack/test/certs/service-account.csr
  hack/test/certs/service-account.pem
Labels: docs-not-required, release-note-not-required
