Repository projectcalico/calico, pull requests merged in 2022-02, with the labels that each got.

#5540 [release-v3.22] Auto pick #5468: Centralize + update ubi version to 8.5
  apiserver/Makefile
  apiserver/docker-image/Dockerfile.amd64
  apiserver/docker-image/Dockerfile.arm64
  app-policy/Dockerfile.amd64
  app-policy/Makefile
  calicoctl/Dockerfile.amd64
  calicoctl/Dockerfile.arm64
  calicoctl/Makefile
  cni-plugin/Dockerfile.amd64
  cni-plugin/Dockerfile.s390x
  cni-plugin/Makefile
  kube-controllers/Dockerfile.amd64
  kube-controllers/Makefile
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
  lib.Makefile
  metadata.mk
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Makefile
  pod2daemon/Dockerfile.amd64
  pod2daemon/Makefile
  typha/Makefile
  typha/docker-image/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#5554 Switch to centos stream 8 for ARM64
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Makefile
Labels: docs-not-required, release-note-not-required

#5557 Automated cherry pick of #5550: Switch to Centos stream 8 for build container.
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Makefile
Labels: release-note-required, docs-not-required

#5546 [EU-742] Fix button link on the about calico page
  calico/about/about-calico.md
Labels: release-note-required, docs-pr-required

#5561 Merge pull request #5485 from song-jiang/song-ipset
  metadata.mk
  node/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#5552 felix/bpf: ICMP conntrack fix
  felix/bpf-gpl/tc.c
  felix/bpf/ut/icmp_test.go
Labels: docs-not-required, release-note-not-required

#5530 Docs-aks-update
  calico/getting-started/kubernetes/managed-public-cloud/aks.md
Labels: release-note-required, docs-pr-required

#5512 check the correct size of per cpu maps in bpf syscall
  felix/bpf/bpf_syscall.go
  felix/bpf/bpfutils/bpf_utils.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
Labels: docs-not-required, release-note-not-required

#5523 Add DSR loopback support for windows
  cni-plugin/pkg/dataplane/windows/dataplane_windows.go
Labels: release-note-required, docs-pr-required

#5567 Add warning about ALP support in K8s v1.23
  calico/getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#5571 Add warning about ALP support in K8s v1.23
  calico/getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#5432 Routing/multiple table ranges
  .gitignore
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  calico/_includes/content/install-awscni-routetable-issue.md
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/config/param_types.go
  felix/dataplane/driver.go
  felix/idalloc/index_allocator.go
  felix/idalloc/index_allocator_test.go
  felix/routerule/route_rule.go
  felix/routerule/route_rule_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-pr-required

#5574 Clearer Wording for WireGuard Configuration
  calico/security/encrypt-cluster-pod-traffic.md
Labels: release-note-required, docs-pr-required

#5483 Add liveness callback to route tables.
  felix/dataplane/linux/int_dataplane.go
  felix/routetable/route_table.go
Labels: release-note-required, docs-not-required

#5531 Update build-operator-reference make target
  calico/Makefile
Labels: docs-not-required, release-note-not-required

#5573 Removes aws cni manual steps, operator handles this
  calico/_includes/content/install-awscni-routetable-issue.md
  calico/getting-started/kubernetes/managed-public-cloud/eks.md
  calico/getting-started/kubernetes/self-managed-public-cloud/aws.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5459 Fix: IPAMBlock GC breaks flannel migration
  kube-controllers/pkg/controllers/flannelmigration/migration_controller.go
  kube-controllers/pkg/controllers/flannelmigration/network_migrator.go
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#5547 etcdv3: we handle watch errors, so don't log them at Error level
  libcalico-go/lib/backend/etcdv3/watcher.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready, delete-branch

#5548 etcdv3: we handle watch errors, so don't log them at Error level
  libcalico-go/lib/backend/etcdv3/watcher.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#5580 Clarify pool migration example
  calico/networking/migrate-pools.md
Labels: docs-not-required, release-note-not-required

#5521 Don't rebuild remote-deps when we don't need to
  .semaphore/semaphore.yml
  felix/.gitignore
  felix/Makefile
  felix/bpf-gpl/Makefile
  node/.gitignore
  node/Makefile
  node/filesystem/etc/calico/confd/config/.gitkeep
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
  node/tests/k8st/load_images_on_kind_cluster.sh
Labels: docs-not-required, release-note-not-required

#5582 Updates for v3.19.4
  _data/versions.yml
  _includes/release-notes/v3.19.4-release-notes.md
  release-scripts/generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#5584 Fix calicoctl download URL
  calico/maintenance/clis/calicoctl/install.md
Labels: release-note-required, docs-pr-required

#5565 Add release test to test Windows install script uses right zip file
  calico/release-scripts/tests/test_windows_artifacts.py
Labels: release-note-required, docs-pr-required

#5589 remove separate wgtool build, use as stage directly
  felix/Makefile
  felix/fv/Dockerfile.test.amd64
  felix/fv/Dockerfile.wgtool.amd64
Labels: docs-not-required, release-note-not-required

#5583 Stop copying CRDs from libcalico-go
  apiserver/Makefile
  calico/Makefile
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_bgpconfigurations.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_bgppeers.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_blockaffinities.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_caliconodestatuses.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_clusterinformations.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_globalnetworksets.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_hostendpoints.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamblocks.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamconfigs.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_ipamhandles.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_ipreservations.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_networkpolicies.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_networksets.yaml
  calico/_includes/charts/calico/templates/kdd-crds.yaml
  calico/_includes/charts/tigera-operator/crds/calico
  calico/manifests/ocp/crds/calico
  calico/manifests/operator-crds.yaml
  cni-plugin/Makefile
  felix/.gitignore
  felix/Makefile
  felix/fv/infrastructure/infra_k8s.go
  felix/k8sfv/run-test
  kube-controllers/Makefile
Labels: docs-not-required, release-note-not-required

#5409 Use protobuf for Kubernetes client
  libcalico-go/lib/backend/k8s/k8s.go
Labels: release-note-required, docs-not-required

#5471 Remove unused semaphore files, and add some missing jobs
  .semaphore/semaphore.yml
  api/.semaphore/semaphore.yml
  apiserver/.semaphore/semaphore.yml
  apiserver/.semaphore/update_pins.yml
  app-policy/.semaphore/clear_cache.yml
  app-policy/.semaphore/semaphore.yml
  app-policy/.semaphore/update_pins.yml
  calico/.semaphore/semaphore.yml
  calicoctl/.semaphore/clear_cache.yml
  calicoctl/.semaphore/semaphore.yml
  calicoctl/.semaphore/update_pins.yml
  confd/.semaphore/semaphore.yml
  confd/.semaphore/update_pins.yml
  kube-controllers/.semaphore/clear_cache.yml
  kube-controllers/.semaphore/semaphore.yml
  kube-controllers/.semaphore/update_pins.yml
  libcalico-go/.semaphore/semaphore.yml
  libcalico-go/.semaphore/update_pins.yml
  networking-calico/.semaphore/semaphore.yml
  networking-calico/devstack/bootstrap.sh
  node/.semaphore/semaphore.yml
  node/.semaphore/update_pins.yml
  pod2daemon/.semaphore/semaphore.yml
  typha/.semaphore/clear_cache.yml
  typha/.semaphore/semaphore.yml
  typha/.semaphore/update_pins.yml
Labels: docs-not-required, release-note-not-required

#5598 fix: Edit this page link
  calico/_layouts/docwithnav.html
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5564 Update getting-started guides to use operator by default
  calico/_data/navbars/getting-started.yml
  calico/getting-started/kubernetes/installation/config-options.md
  calico/getting-started/kubernetes/managed-public-cloud/eks.md
  calico/getting-started/kubernetes/self-managed-onprem/onpremises.md
  calico/getting-started/kubernetes/self-managed-public-cloud/gce.md
Labels: release-note-required, docs-not-required

#5603 Merge pull request #5579 from song-jiang/song-cni-win
  .semaphore/semaphore.yml
  cni-plugin/.semaphore/run-win-fv.sh
  cni-plugin/internal/pkg/utils/utils.go
Labels: release-note-required, docs-pr-required

#5600 Fix indentation in Windows FV semaphore block
  .semaphore/semaphore.yml
Labels: release-note-required, docs-pr-required

#5591 Standardize docker buildx commands for all images
  apiserver/Makefile
  app-policy/Makefile
  calicoctl/Makefile
  cni-plugin/Makefile
  felix/Makefile
  felix/bpf-gpl/Makefile
  kube-controllers/Makefile
  lib.Makefile
  node/Makefile
  pod2daemon/Makefile
  typha/Makefile
Labels: docs-not-required, release-note-not-required

#5280 WireGuard Startup Bootstrapping (fix hostencryption deadlocking)
  felix/daemon/bootstrap_linux.go
  felix/daemon/bootstrap_windows.go
  felix/daemon/daemon.go
  felix/fv/wireguard_test.go
  felix/wireguard/bootstrap.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#5608 WireGuard Startup Bootstrapping (fix hostencryption deadlocking) (#5280) -> release v3.21 patch
  felix/daemon/bootstrap_linux.go
  felix/daemon/bootstrap_windows.go
  felix/daemon/daemon.go
  felix/fv/wireguard_test.go
  felix/wireguard/bootstrap.go
Labels: release-note-required, docs-pr-required

#5607 WireGuard Startup Bootstrapping (fix hostencryption deadlocking) (#5280) -> release v3.22 patch
  felix/daemon/bootstrap_linux.go
  felix/daemon/bootstrap_windows.go
  felix/daemon/daemon.go
  felix/fv/wireguard_test.go
  felix/wireguard/bootstrap.go
Labels: release-note-required, docs-pr-required

#5596 Docs-link-sysreqs
  calico/calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#5615 Cherrypick-system-reqs
  calico/calico-enterprise/index.md
Labels: docs-not-required, release-note-not-required

#5601 felix/bpf: multiple retries on source port collision
  felix/bpf-gpl/conntrack.h
Labels: docs-not-required, release-note-not-required

#5578 Updating flannel version to v0.16.3
  calico/_data/versions.yml
Labels: release-note-required, docs-not-required

#5616 Combine calico/felix and calico/felix-test
  felix/Makefile
  felix/docker-image/Dockerfile.amd64
  felix/docker-image/Dockerfile.arm64
  felix/fv/Dockerfile.test.amd64
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#5630 List the K8s requirements for our supported Istio versions
  calico/getting-started/kubernetes/requirements.md
Labels: docs-pr-required, release-note-not-required

#5631 List the K8s requirements for our supported Istio versions
  calico/getting-started/kubernetes/requirements.md
Labels: docs-pr-required, release-note-not-required

#5624 Fix endpoint ipsets not updated for labels with empty values
  felix/labelindex/named_port_index.go
  felix/labelindex/named_port_index_test.go
Labels: release-note-required, docs-not-required

#5617 felix/bpf: use correct affinity key for unconnected udp
  felix/bpf-gpl/nat_lookup.h
  felix/bpf/nat/maps.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#5453 proxy_delay setting failure should not be a critical error
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
  felix/dataplane/linux/endpoint_mgr.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#5524 Remove v1 profile labels
  felix/calc/active_rules_calculator.go
  felix/calc/profile_decoder.go
  felix/calc/profile_decoder_test.go
  felix/calc/resources_for_test.go
  felix/calc/states_for_test.go
  felix/labelindex/label_inheritance_index.go
  felix/labelindex/named_port_bench_test.go
  felix/labelindex/named_port_index.go
  felix/labelindex/named_port_index_test.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/backend/model/keys_test.go
  libcalico-go/lib/backend/model/profile.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/profileprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/profileprocessor_test.go
Labels: release-note-required, docs-not-required

#5635 Fix CRDs in the docs
  calico/_includes/charts/calico/crds
  calico/_includes/charts/tigera-operator/crds/calico
  calico/manifests/crds.yaml
  libcalico-go/Makefile
  libcalico-go/config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  libcalico-go/config/crd/crd.projectcalico.org_blockaffinities.yaml
  libcalico-go/config/crd/crd.projectcalico.org_caliconodestatuses.yaml
  libcalico-go/config/crd/crd.projectcalico.org_clusterinformations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  libcalico-go/config/crd/crd.projectcalico.org_globalnetworksets.yaml
  libcalico-go/config/crd/crd.projectcalico.org_hostendpoints.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamblocks.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamconfigs.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamhandles.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ippools.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipreservations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_networkpolicies.yaml
  libcalico-go/config/crd/crd.projectcalico.org_networksets.yaml
Labels: docs-not-required, release-note-not-required

#5618 Jump to tc accepted entry program instead of in-lining the calico_tc_skb_accepted function.
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
Labels: docs-not-required, release-note-not-required

#5640 Revert to version of flannel that exists on quay
  calico/_data/versions.yml
Labels: release-note-required, docs-pr-required

#5611 [EU-707] Add item to navbar menu dropdown list
  calico/_includes/open_source_navbar.html
Labels: release-note-required, docs-pr-required

#5417 Docs update - add operator steps to the metric page
  calico/maintenance/monitor/monitor-component-metrics.md
Labels: release-note-required, docs-pr-required

#5642 app-policy: Remove generated files from list of files to clean
  app-policy/Makefile
Labels: release-note-required, docs-pr-required

#5648 Fix typos in the about-networking doc
  calico/about/about-networking.md
Labels: docs-not-required, release-note-not-required

#5646 Update networking/ docs section to include operator instructions
  calico/_includes/content/determine-ipam.md
  calico/getting-started/kubernetes/installation/config-options.md
  calico/getting-started/kubernetes/managed-public-cloud/eks.md
  calico/getting-started/kubernetes/self-managed-onprem/onpremises.md
  calico/getting-started/windows-calico/demo.md
  calico/getting-started/windows-calico/quickstart.md
  calico/maintenance/monitor/monitor-component-metrics.md
  calico/networking/add-floating-ip.md
  calico/networking/advertise-service-ips.md
  calico/networking/bgp.md
  calico/networking/change-block-size.md
  calico/networking/external-connectivity.md
  calico/networking/ipv6.md
  calico/networking/legacy-firewalls.md
  calico/networking/migrate-pools.md
  calico/networking/mtu.md
  calico/networking/node.md
  calico/networking/sidecar-acceleration.md
  calico/networking/use-specific-ip.md
  calico/networking/vxlan-ipip.md
Labels: docs-not-required, release-note-not-required

#5653 [windows] Revert "windows: set kube-proxy IPv6DualStack=false for VXLAN (#1018)"
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
Labels: release-note-required, docs-not-required

#5609 Add maxRestartTime and BGP password settings to full mesh
  api/pkg/apis/projectcalico/v3/bgpconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/resources/bgpconfig.md
  confd/etc/calico/confd/templates/bird.cfg.template
  confd/etc/calico/confd/templates/bird6.cfg.template
  confd/pkg/backends/calico/client.go
  confd/tests/compiled_templates/mesh/password/step1/bird.cfg
  confd/tests/compiled_templates/mesh/password/step1/bird6.cfg
  confd/tests/compiled_templates/mesh/password/step1/bird6_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step1/bird6_ipam.cfg
  confd/tests/compiled_templates/mesh/password/step1/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step1/bird_ipam.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird6.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird6_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird6_ipam.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird_ipam.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird6.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird6_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird6_ipam.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird_ipam.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird6.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird6_aggr.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird6_ipam.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird_ipam.cfg
  confd/tests/mock_data/calicoctl/mesh/restart-time/delete.yaml
  confd/tests/mock_data/calicoctl/mesh/restart-time/input.yaml
  confd/tests/test_suite_common.sh
  libcalico-go/config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  libcalico-go/lib/clientv3/bgpconfig.go
  libcalico-go/lib/clientv3/bgpconfig_e2e_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: release-note-required, docs-pr-required

#5652 Fix Conversion of Felix RouteTableRange config to string
  libcalico-go/lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
Labels: release-note-required, docs-pr-required

#5662 Fix Typha expected number of connections calculation.
  typha/pkg/daemon/daemon.go
  typha/pkg/k8s/rebalance.go
  typha/pkg/k8s/rebalance_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#5655 Override static-checks target in Felix Makefile to use CGO.
  felix/Makefile
  felix/bpf/libbpf/libbpf.go
Labels: release-note-required, docs-pr-required

#5613 Allow for safer IP address release
  calicoctl/calicoctl/commands/ipam/check.go
  calicoctl/calicoctl/commands/ipam/release.go
  calicoctl/tests/fv/ipam_test.go
  calicoctl/tests/fv/migrate_ipam_test.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/k8s/k8s.go
  kube-controllers/Makefile
  kube-controllers/pkg/controllers/node/fake_client.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_allocation.go
  kube-controllers/tests/fv/flannel_migration_test.go
  kube-controllers/tests/fv/fv_test.go
  kube-controllers/tests/fv/kdd_node_ipam_test.go
  libcalico-go/config.patch
  libcalico-go/config/crd/crd.projectcalico.org_ipamblocks.yaml
  libcalico-go/lib/apis/v3/ipam_block.go
  libcalico-go/lib/apis/v3/openapi_generated.go
  libcalico-go/lib/apis/v3/zz_generated.deepcopy.go
  libcalico-go/lib/backend/k8s/resources/ipam_block.go
  libcalico-go/lib/backend/model/block.go
  libcalico-go/lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
  libcalico-go/lib/clientv3/node.go
  libcalico-go/lib/errors/errors.go
  libcalico-go/lib/ipam/interface.go
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block.go
  libcalico-go/lib/ipam/ipam_block_reader_writer.go
  libcalico-go/lib/ipam/ipam_test.go
  libcalico-go/lib/ipam/ipam_types.go
  libcalico-go/lib/testutils/syncertester.go
  node/pkg/allocateip/allocateip.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, area/ipam

#5654 [release-v3.22] Pick of #5653: Revert "windows: set kube-proxy IPv6DualStack=false for VXLAN
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
Labels: release-note-required, docs-not-required

#5667 Move PodDisruptionBudget from apiVersion policy/v1beta1 to policy/v1
  calico/_includes/charts/calico/templates/calico-kube-controllers.yaml
  calico/_includes/charts/calico/templates/calico-typha.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required

#5668 [release-v3.22] Pick of #5622: wip: unify the windows requirements
  calico/getting-started/windows-calico/kubernetes/requirements.md
  calico/getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required

#5670 fixed install command for linux kubectl plugin
  calico/maintenance/clis/calicoctl/install.md
Labels: release-note-required, docs-pr-required

#5665 [v3.22] Fix Typha expected number of connections calculation.
  typha/pkg/daemon/daemon.go
  typha/pkg/k8s/rebalance.go
  typha/pkg/k8s/rebalance_test.go
Labels: release-note-required, docs-not-required, merge-when-ready
