Repository projectcalico/calico, pull requests merged in 2022-08, with the labels that each got.

#6467 [release-v3.24] Automated cherry pick of #6464: windows: create the calico-node serviceaccount token
  calico/getting-started/windows-calico/quickstart.md
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, hold-merge, docs-not-required

#6478 Fix merge mistake (#6472)
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, docs-pr-required

#6469 Cherry-pick: 6403, 6452 to release v3.24
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#6480 Update docs for v3.20.6
  _data/versions.yml
  _includes/release-notes/v3.20.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#6481 Update manifest generation script to replace image versions for static manifests
  manifests/apiserver.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/csi-driver.yaml
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#6482 Update manifest generation script to replace image versions for static manifests
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#6346 calico-kube-controllers: Run as non-root by default for the arm64 image
  kube-controllers/Dockerfile.arm64
  kube-controllers/Makefile
Labels: release-note-required, docs-not-required

#6420 Add block affinity API
  api/pkg/apis/projectcalico/v3/blockaffinity.go
  api/pkg/apis/projectcalico/v3/register.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/blockaffinity.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_blockaffinity.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_projectcalico_client.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/generated_expansion.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/projectcalico_client.go
  api/pkg/client/informers_generated/externalversions/generic.go
  api/pkg/client/informers_generated/externalversions/projectcalico/v3/blockaffinity.go
  api/pkg/client/informers_generated/externalversions/projectcalico/v3/interface.go
  api/pkg/client/listers_generated/projectcalico/v3/blockaffinity.go
  api/pkg/client/listers_generated/projectcalico/v3/expansion_generated.go
  api/pkg/openapi/openapi_generated.go
  apiserver/pkg/registry/projectcalico/blockaffinity/storage.go
  apiserver/pkg/registry/projectcalico/blockaffinity/strategy.go
  apiserver/pkg/registry/projectcalico/rest/storage_calico.go
  apiserver/pkg/storage/calico/blockAffinity_storage.go
  apiserver/pkg/storage/calico/converter.go
  apiserver/pkg/storage/calico/storage_interface.go
  apiserver/test/integration/clientset_test.go
  calicoctl/calicoctl/commands/datastore/migrate/migrateipam_test.go
  kube-controllers/pkg/controllers/node/fake_client.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity.go
  libcalico-go/lib/backend/model/resource.go
  libcalico-go/lib/clientv3/blockaffinity.go
  libcalico-go/lib/clientv3/blockaffinity_e2e_test.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/interface.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  node/pkg/allocateip/allocateip_test.go
  typha/pkg/daemon/daemon_test.go
Labels: release-note-required, docs-pr-required

#6490 Add block affinity API
  api/pkg/apis/projectcalico/v3/blockaffinity.go
  api/pkg/apis/projectcalico/v3/register.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/blockaffinity.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_blockaffinity.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_projectcalico_client.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/generated_expansion.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/projectcalico_client.go
  api/pkg/client/informers_generated/externalversions/generic.go
  api/pkg/client/informers_generated/externalversions/projectcalico/v3/blockaffinity.go
  api/pkg/client/informers_generated/externalversions/projectcalico/v3/interface.go
  api/pkg/client/listers_generated/projectcalico/v3/blockaffinity.go
  api/pkg/client/listers_generated/projectcalico/v3/expansion_generated.go
  api/pkg/openapi/openapi_generated.go
  apiserver/pkg/registry/projectcalico/blockaffinity/storage.go
  apiserver/pkg/registry/projectcalico/blockaffinity/strategy.go
  apiserver/pkg/registry/projectcalico/rest/storage_calico.go
  apiserver/pkg/storage/calico/blockAffinity_storage.go
  apiserver/pkg/storage/calico/converter.go
  apiserver/pkg/storage/calico/storage_interface.go
  apiserver/test/integration/clientset_test.go
  calicoctl/calicoctl/commands/datastore/migrate/migrateipam_test.go
  kube-controllers/pkg/controllers/node/fake_client.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity.go
  libcalico-go/lib/backend/model/resource.go
  libcalico-go/lib/clientv3/blockaffinity.go
  libcalico-go/lib/clientv3/blockaffinity_e2e_test.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/interface.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  node/pkg/allocateip/allocateip_test.go
  typha/pkg/daemon/daemon_test.go
Labels: release-note-required, docs-pr-required

#6473 Refactor RouteTable interface
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/dataplane/linux/wireguard_mgr.go
  felix/routetable/interface.go
  felix/wireguard/route_table.go
  felix/wireguard/wireguard.go
Labels: docs-not-required, release-note-not-required

#6494 Fix EncapsulationCalculator behavior when encapsulation is empty string
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
Labels: release-note-required, docs-not-required

#6493 Add block affinity reference doc
  calico/_data/navbars/reference.yml
  calico/reference/resources/blockaffinity.md
Labels: docs-not-required, release-note-not-required

#6497 Add block affinity reference doc
  calico/_data/navbars/reference.yml
  calico/reference/resources/blockaffinity.md
Labels: docs-not-required, release-note-not-required

#6500 Add IPAM split command docs
  calico/_data/navbars/reference.yml
  calico/reference/calicoctl/ipam/split.md
Labels: docs-not-required, release-note-not-required

#6501 pod-service-self should not rely on src==dst
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/tc.c
  felix/bpf/conntrack/map.go
  felix/bpf/conntrack/v3/map.go
  felix/bpf/ut/nat_test.go
Labels: release-note-required, docs-not-required, area/bpf

#6505 Fix bug allowing pools to be split into invalid numbers
  calicoctl/calicoctl/commands/ipam/split.go
  calicoctl/tests/st/calicoctl/test_ipam_split.py
  calicoctl/tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#6507 Fix bug allowing pools to be split into invalid numbers
  calicoctl/calicoctl/commands/ipam/split.go
  calicoctl/tests/st/calicoctl/test_ipam_split.py
  calicoctl/tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#6513 kube-controllers health check: timeout, and report any errors
  kube-controllers/cmd/kube-controllers/main.go
Labels: release-note-required, docs-not-required

#6512 Limit rate of logging 'Wireguard is not supported' to fix log spam
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-not-required

#6511 Fix off-by-one error in NthBit() in felix/ip/ip_addr.go
  felix/ip/ip_addr.go
  felix/ip/trie.go
  felix/ip/trie_test.go
Labels: release-note-required, docs-not-required

#6470 Fix gce nodename
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6510 [release-v3.24] Automated cherry pick of #6470: Fix gce nodename quoting
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, docs-pr-required

#6514 [release-v3.24] Auto pick #6513: kube-controllers health check: timeout, and report any errors
  kube-controllers/cmd/kube-controllers/main.go
Labels: release-note-required, docs-not-required

#6515 [release-v3.23] Auto pick #6513: kube-controllers health check: timeout, and report any errors
  kube-controllers/cmd/kube-controllers/main.go
Labels: release-note-required, docs-not-required

#6516 [release-v3.22] Auto pick #6513: kube-controllers health check: timeout, and report any errors
  kube-controllers/cmd/kube-controllers/main.go
Labels: release-note-required, docs-not-required

#6395 Rev netlink to pick up unsafe pointer fix
  felix/k8sfv/pod.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#6519 Replace CoreOS in requirements pages
  calico/_includes/content/reqs-sys.md
Labels: release-note-required, docs-pr-required

#6492 Update tested k8s versions
  calico/getting-started/kubernetes/requirements.md
Labels: cherry-pick-completed, docs-not-required, release-note-not-required

#6520 [release-v3.24] Pick of Update tested k8s versions
  calico/getting-started/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#6466 [release-v3.24] Automated cherry pick of #6257: fix: ErrorActionPreference must continue for kubectl commands
  calico/scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#6518 Fix construction of rateLimitedLogger in wireguard
  felix/wireguard/wireguard.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6523 Wait for BPF programs to be attached to interfaces - FV tests
  felix/bpf/ifstate/map.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#6528 Update windows FV node OS version
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required

#6498 Set IPIPMode and VXLANMode to the default "Never" if they are empty strings
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  libcalico-go/lib/clientv3/ippool.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
Labels: release-note-required, docs-not-required

#6521 [release-v3.24] Auto pick #6498: Set IPIPMode and VXLANMode to the default "Never" if they
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  libcalico-go/lib/clientv3/ippool.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
Labels: release-note-required, docs-pr-required

#6506 Jump to IPv6 prologue program
  felix/bpf-gpl/policy_program.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tcv6.h
  felix/bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#6534 [master] Auto pick #6512: Limit rate of logging 'Wireguard is not supported' to fix log #6518: Fix construction of rateLimitedLogger in wireguard
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-pr-required

#6529 [release-v3.24] Automated cherry pick of #6528: windows: replace eol'd 20H2 with 1809 for FV tests
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6548 Upate Windows installation to use kubectl
  calico/getting-started/windows-calico/kubernetes/rancher.md
  calico/getting-started/windows-calico/kubernetes/requirements.md
  calico/getting-started/windows-calico/kubernetes/standard.md
  calico/getting-started/windows-calico/openshift/installation.md
  calico/getting-started/windows-calico/quickstart.md
Labels: release-note-required, docs-pr-required

#6549 Upate Windows installation to use kubectl (#6548)
  calico/getting-started/windows-calico/kubernetes/rancher.md
  calico/getting-started/windows-calico/kubernetes/requirements.md
  calico/getting-started/windows-calico/kubernetes/standard.md
  calico/getting-started/windows-calico/openshift/installation.md
  calico/getting-started/windows-calico/quickstart.md
Labels: release-note-required, docs-pr-required

#6531 Parse IPv6 fix header
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/icmp.h
  felix/bpf-gpl/ipv6.h
  felix/bpf-gpl/metadata.h
  felix/bpf-gpl/nat.h
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/skb.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tcv6.h
  felix/bpf-gpl/types.h
  felix/bpf-gpl/ut/icmp_port_unreachable.c
  felix/bpf-gpl/ut/icmp_too_big.c
  felix/bpf-gpl/ut/icmp_ttl_exceeded.c
  felix/bpf-gpl/ut/ip_dec_ttl.c
  felix/bpf-gpl/ut/nat_encap_test.c
  felix/bpf-gpl/xdp.c
Labels: docs-not-required, release-note-not-required

#6551 fv: sync more tests with loading BPF programs and disable ipv6 runs
  felix/fv/bpf_test.go
  felix/fv/infrastructure/felix.go
  felix/fv/ipip_test.go
  felix/fv/spoof_test.go
  felix/fv/vxlan_test.go
  felix/fv/workload/workload.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6532 [master] Auto pick #6511: Fix off-by-one error in NthBit() in felix/ip/ip_addr.go
  felix/ip/ip_addr.go
  felix/ip/trie.go
  felix/ip/trie_test.go
Labels: release-note-required, docs-pr-required

#6543 [release-v3.21] Automated cherry pick of #6528: windows: replace eol'd 20H2 with 1809 for FV tests
  .semaphore/semaphore.yml
  cni-plugin/.semaphore/run-win-fv.sh
  felix/.semaphore/publish-artifacts
  felix/.semaphore/run-win-fv
Labels: docs-not-required, release-note-not-required

#6541 [release-v3.23] Automated cherry pick of #6528: windows: replace eol'd 20H2 with 1809 for FV tests
  .semaphore/publish-artifacts
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  cni-plugin/.semaphore/run-win-fv.sh
  felix/.semaphore/publish-artifacts
  felix/.semaphore/run-win-fv
Labels: docs-not-required, release-note-not-required

#6542 [release-v3.22] Automated cherry pick of #6528: windows: replace eol'd 20H2 with 1809 for FV tests
  .semaphore/semaphore.yml
  cni-plugin/.semaphore/run-win-fv.sh
  felix/.semaphore/publish-artifacts
  felix/.semaphore/run-win-fv
Labels: docs-not-required, release-note-not-required

#6533 [release-v3.23] Auto pick #6511: Fix off-by-one error in NthBit() in felix/ip/ip_addr.go
  felix/ip/ip_addr.go
  felix/ip/trie.go
  felix/ip/trie_test.go
Labels: release-note-required, docs-pr-required

#6537 [release-v3.23] Auto pick #6498: Set IPIPMode and VXLANMode to the default "Never" if they
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  libcalico-go/lib/clientv3/ippool.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
Labels: release-note-required, docs-pr-required

#6538 [release-v3.21] Auto pick #6512: Limit rate of logging 'Wireguard is not supported' to fix log #6518: Fix construction of rateLimitedLogger in wireguard
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-pr-required

#6536 [release-v3.22] Auto pick #6512: Limit rate of logging 'Wireguard is not supported' to fix log #6518: Fix construction of rateLimitedLogger in wireguard
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-pr-required

#6535 [release-v3.23] Auto pick #6512: Limit rate of logging 'Wireguard is not supported' to fix log #6518: Fix construction of rateLimitedLogger in wireguard
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-pr-required

#6557 Update the base image for armv7 node-registrar
  pod2daemon/node-driver-registrar-docker/Dockerfile.armv7
Labels: docs-not-required, release-note-not-required

#6558 Update the base image for armv7 node-registrar
  pod2daemon/node-driver-registrar-docker/Dockerfile.armv7
Labels: release-note-required, docs-pr-required

#6559 Update armv7 base images again
  pod2daemon/Dockerfile.arm64
  pod2daemon/Dockerfile.armv7
  pod2daemon/Dockerfile.ppc64le
  pod2daemon/Dockerfile.s390x
  pod2daemon/csidriver/Dockerfile.arm64
  pod2daemon/csidriver/Dockerfile.armv7
  pod2daemon/csidriver/Dockerfile.ppc64le
  pod2daemon/csidriver/Dockerfile.s390x
  pod2daemon/node-driver-registrar-docker/Dockerfile.arm64
  pod2daemon/node-driver-registrar-docker/Dockerfile.ppc64le
  pod2daemon/node-driver-registrar-docker/Dockerfile.s390x
Labels: release-note-required, docs-not-required

#6560 Update armv7 base images again
  pod2daemon/Dockerfile.arm64
  pod2daemon/Dockerfile.armv7
  pod2daemon/Dockerfile.ppc64le
  pod2daemon/Dockerfile.s390x
  pod2daemon/csidriver/Dockerfile.arm64
  pod2daemon/csidriver/Dockerfile.armv7
  pod2daemon/csidriver/Dockerfile.ppc64le
  pod2daemon/csidriver/Dockerfile.s390x
  pod2daemon/node-driver-registrar-docker/Dockerfile.arm64
  pod2daemon/node-driver-registrar-docker/Dockerfile.ppc64le
  pod2daemon/node-driver-registrar-docker/Dockerfile.s390x
Labels: release-note-required, docs-not-required

#6276 support multinet for calicovpp by adding annotations to wep
  felix/calc/event_sequencer.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
  libcalico-go/lib/backend/model/workloadendpoint.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6563 Update image for the node-driver-registrar
  manifests/csi-driver.yaml
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#6564 Update image for the node-driver-registrar
  manifests/csi-driver.yaml
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#6554 Record BPF ruleIDs in state map
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/types.h
  felix/bpf/asm/asm.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/state/map.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#6567 Fix release process to not include location of old helm charts
  hack/release/pkg/builder/builder.go
Labels: release-note-required, docs-pr-required

#6570 Fix release process to not include location of old helm charts
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#6572 Ensure that the release process builds the helm chart
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#6573 Ensure that the release process builds the helm chart
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#5793 Enable s390x image cross platform build Dockerfile.s390x in calico
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  apiserver/docker-image/Dockerfile.s390x
  felix/docker-image/Dockerfile.s390x
  lib.Makefile
  node/Dockerfile.s390x
  typha/docker-image/Dockerfile.s390x
Labels: release-note-required, docs-pr-required

#6565 Updates for v3.24.0
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.24.0-release-notes.md
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  hack/release/generate-release-notes.py
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6578 Promote v3.24.0 to latest
  AUTHORS.md
  calico/_data/archives.yml
Labels: docs-not-required, release-note-not-required

#6579 Promote v3.24 branch to latest
  calico/_data/archives.yml
Labels: docs-not-required, release-note-not-required

#6471 Note not to use kubectl-apply for tigera-operator.yaml.
  calico/getting-started/kubernetes/k3s/multi-node-install.md
  calico/getting-started/kubernetes/k3s/quickstart.md
  calico/getting-started/kubernetes/minikube.md
  calico/getting-started/kubernetes/quickstart.md
  calico/getting-started/kubernetes/rancher.md
  calico/getting-started/windows-calico/kubernetes/rancher.md
  calico/maintenance/operator-migration.md
Labels: docs-not-required, release-note-not-required

#6580 Typo fix
  calico/about/about-ebpf.md
Labels: release-note-required, docs-pr-required

#6582 [3.23]Typo fix
  calico/about/about-ebpf.md
Labels: release-note-required, docs-pr-required

#6583 [3.22]Typo fix
  calico/about/about-ebpf.md
Labels: release-note-required, docs-pr-required

#6584 Fix release notes link
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#6585 [release-v3.24] Auto pick #6584: Fix release notes link
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#6566 Kube controller: Making initialization retry
  kube-controllers/cmd/kube-controllers/main.go
Labels: release-note-required, docs-not-required

#6588 Fix issues with the latest manifests not appearing
  calico/netlify.toml
Labels: docs-not-required, release-note-not-required

#6589 Fix issues with the latest manifests not appearing
  calico/netlify.toml
Labels: release-note-required, docs-pr-required

#6594 Refactor RouteTable interface (#6473)
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/dataplane/linux/wireguard_mgr.go
  felix/routetable/interface.go
  felix/wireguard/route_table.go
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-pr-required

#6593 revise doc of calico-network-policy
  calico/security/calico-network-policy.md
Labels: release-note-required, docs-pr-required

#6595 Kube controller: Making initialization retry [pick #6566]
  kube-controllers/cmd/kube-controllers/main.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6591 feat: add imagePullSecrets to tigera-operator ServiceAccount
  charts/tigera-operator/templates/tigera-operator/02-serviceaccount-tigera-operator.yaml
  manifests/ocp/02-serviceaccount-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required, merge-when-ready

#6586 Fix felix RPM build
  felix/rpm/felix.spec.in
Labels: docs-not-required, release-note-not-required

#6577 BPF rule counters
  felix/bpf-gpl/rule_counters.h
  felix/bpf-gpl/tc.c
  felix/bpf/bpf.go
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/counters/map.go
  felix/bpf/maps.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/bpf_policy_counter_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#6596 Fix installation CRD to reflect operator API changes
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6601 Fix felix RPM build
  felix/rpm/felix.spec.in
Labels: docs-not-required, release-note-not-required

#6600 Do not use cgo for flexvol
  pod2daemon/Makefile
Labels: release-note-required, docs-pr-required

#6605 Automated cherry pick of #6600: Do not use cgo for flexvol
  pod2daemon/Makefile
Labels: release-note-required, docs-not-required

#6602 Fix installation CRD to reflect operator API changes
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6604 Fix RPM builds
  felix/debian/rules
Labels: docs-not-required, release-note-not-required

#6608 Fix RPM builds
  felix/debian/rules
Labels: docs-not-required, release-note-not-required

#6606 Bump K8S_VERSION and KUBECTL_VERSION to v1.24.3 in metadata.mk
  hack/test/kind/kind-single.config
  hack/test/kind/kind.config
  lib.Makefile
  metadata.mk
  node/tests/k8st/infra/apiserver.yaml
  node/tests/k8st/infra/etcd.yaml
  node/tests/k8st/utils/utils.py
Labels: release-note-required, docs-not-required

#6607 [release-v3.24] Auto pick #6606: Bump K8S_VERSION and KUBECTL_VERSION to v1.24.3 in
  hack/test/kind/kind-single.config
  hack/test/kind/kind.config
  lib.Makefile
  metadata.mk
  node/tests/k8st/infra/apiserver.yaml
  node/tests/k8st/infra/etcd.yaml
  node/tests/k8st/utils/utils.py
Labels: release-note-required, docs-not-required

#6603 Remove trailing whitespace from Tigera Operator manifest
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6616 Fix CSI permissions for OCP installs
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6617 Fix CSI permissions for OCP installs
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6598 Include policy counters in policy dump
  felix/bpf/polprog/pol_prog_builder.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/fv/bpf_policy_counter_test.go
Labels: release-note-required, docs-pr-required

#6618 s390x: mtuIfacePattern default value supports s390x worker interfaces
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/config/config_params.go
Labels: release-note-required, docs-completed, merge-when-ready

#6622 Update operator installation reference documentation
  calico/reference/installation/_api.html
Labels: docs-completed, release-note-not-required

#6621 Update operator installation reference documentation
  calico/reference/installation/_api.html
Labels: docs-completed, release-note-not-required, merge-when-ready

#6623 Remove Enterprise-only fields from operator installation API reference
  calico/reference/installation/_api.html
Labels: docs-completed, release-note-not-required

#6610 Adjust how kube-controllers timeout works
  charts/tigera-operator/README.md
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6627 [release-v3.24] Auto pick #6610: Adjust how kube-controllers timeout works
  charts/tigera-operator/README.md
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6612 Config option to specify l3 interfaces for BPF
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6592 Fix misspelling of variant in several places
  calico/reference/installation/_api.html
  charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  manifests/ocp/operator.tigera.io_imagesets_crd.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6631 Fix release-notes link for real this time
  hack/release/pkg/builder/builder.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6632 [release-v3.24] Auto pick #6631: Fix release-notes link for real this time
  hack/release/pkg/builder/builder.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6628 felix/timeshim: do not pull BPF stuff into Windows
  felix/timeshim/time.go
  felix/timeshim/time_linux.go
  felix/timeshim/time_windows.go
Labels: docs-not-required, release-note-not-required

#6613 Updates for v3.24.1
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.24.1-release-notes.md
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6639 Run PrecompiledBinariesAreLoadable ut test for XDP objects
  felix/bpf/ut/precompilation_test.go
Labels: docs-not-required, release-note-not-required

#6574 BPF Policy program for IPv6
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/tcv6.h
  felix/bpf-gpl/types.h
  felix/bpf/asm/asm.go
  felix/bpf/attach.go
  felix/bpf/bpf.go
  felix/bpf/bpf_defs.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/state/map.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/pol_prog_test.go
  felix/bpf/xdp/attach.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/bpf_test.go
  felix/ip/ip_addr.go
Labels: docs-not-required, release-note-not-required

#6641 Add BPFDisableLinuxConntrack to Calico Api
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  felix/config/config_params_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6644 Update AKS BYO CNI doc
  calico/getting-started/kubernetes/managed-public-cloud/aks.md
Labels: release-note-required, docs-pr-required

#6645 Update AKS BYO CNI doc (#6644)
  calico/getting-started/kubernetes/managed-public-cloud/aks.md
Labels: release-note-required, docs-pr-required
