Repository projectcalico/calico, pull requests merged in 2022-12, with the labels that each got.

#7024 Docs-network-design-docs-release-v3.24
  calico/reference/architecture/design/l2-interconnect-fabric.md
  calico/reference/architecture/design/l3-interconnect-fabric.md
Labels: docs-not-required, release-note-not-required

#7037 fix typo from ask-engine to aks-engine
  calico/getting-started/kubernetes/self-managed-public-cloud/azure.md
Labels: release-note-required, docs-pr-required

#7043 Add compression to the Typha protocol.
  go.mod
  go.sum
  libcalico-go/lib/readlogger/readlogger.go
  libcalico-go/lib/writelogger/writelogger.go
  typha/fv-tests/server_harness_test.go
  typha/fv-tests/server_test.go
  typha/fv-tests/state_recorder.go
  typha/pkg/daemon/daemon_test.go
  typha/pkg/jitter/jittered_ticker.go
  typha/pkg/snapcache/cache.go
  typha/pkg/syncclient/sync_client.go
  typha/pkg/syncproto/sync_proto.go
  typha/pkg/syncserver/sync_server.go
  typha/pkg/syncserver/syncserver_test.go
Labels: release-note-required, docs-pr-required

#7054 fv/workload: options for workload.Run/New()
  felix/fv/test-workload/test-workload.go
  felix/fv/wireguard_test.go
  felix/fv/workload/workload.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#7052 [3.14] DOCS-694: Fix bad link
  calico/about/about-k8s-networking.md
Labels: release-note-required, docs-pr-required

#6971 typha: Fix missing nsswitch files causing localhost lookup fails
  typha/docker-image/Dockerfile.amd64
  typha/docker-image/nsswitch.conf
Labels: release-note-required, docs-not-required, merge-when-ready

#6966 Update calico/vpp Getting Started doc to say "kubectl create" instead "kubectl apply"
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7025 refactor: move from `howeyc/fsnotify` to `fsnotify/fsnotify`
  cni-plugin/pkg/install/install.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6741 Tweak TLS config wherever used and make it FIPS compliant.
  apiserver/cmd/apiserver/server/options.go
  crypto/pkg/tls/tls.go
  go.mod
  go.sum
  kube-controllers/cmd/kube-controllers/main.go
  libcalico-go/lib/apiconfig/apiconfig.go
  libcalico-go/lib/backend/etcdv3/etcdv3.go
  typha/pkg/config/config_params.go
  typha/pkg/syncclient/sync_client.go
  typha/pkg/syncclientutils/config.go
  typha/pkg/syncclientutils/config_test.go
  typha/pkg/syncclientutils/startsyncerclient.go
  typha/pkg/syncclientutils/startsyncerclient_suite_test.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-not-required, merge-when-ready

#7006 Add IgnoredInterfaces field to BGPConfiguration
  api/pkg/apis/projectcalico/v3/bgpconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/resources/bgpconfig.md
  confd/etc/calico/confd/templates/bird.cfg.template
  confd/etc/calico/confd/templates/bird6.cfg.template
  confd/pkg/backends/calico/client.go
  confd/pkg/backends/calico/routes_test.go
  confd/tests/compiled_templates/ignored_interfaces/bird.cfg
  confd/tests/compiled_templates/ignored_interfaces/bird6.cfg
  confd/tests/compiled_templates/ignored_interfaces/bird6_aggr.cfg
  confd/tests/compiled_templates/ignored_interfaces/bird6_ipam.cfg
  confd/tests/compiled_templates/ignored_interfaces/bird_aggr.cfg
  confd/tests/compiled_templates/ignored_interfaces/bird_ipam.cfg
  confd/tests/test_suite_common.sh
  libcalico-go/config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_bgpconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-completed, merge-when-ready

#7065 [DOCS] add/fix bpf config options
  calico/reference/felix/configuration.md
Labels: release-note-required, cherry-pick-candidate, docs-pr-required, merge-when-ready, delete-branch

#7064 Docs-move-sys-reqs
  calico/_data/navbars/getting-started.yml
  calico/getting-started/kubernetes/quickstart.md
Labels: docs-not-required, release-note-not-required

#7039 [BPF] no need for src fixup for packets from wl to tunnel
  felix/bpf-gpl/tc.c
  felix/bpf/ut/nat_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/ipip_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6978 [EV-2594] Upgrade go to v1.18.8 (go-build 0.76). UBI to v8.7
  metadata.mk
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7067 [EV-2871] Upgrade go-build to v0.78, go v1.18.9
  metadata.mk
Labels: release-note-required, docs-pr-required

#7042 add info to hostmetadataupdate
  felix/calc/calc_graph.go
  felix/calc/dataplane_passthru.go
  felix/calc/event_sequencer.go
  felix/calc/profile_decoder_test.go
  felix/dataplane/external/ext_dataplane.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: release-note-required, docs-pr-required

#7069 DOCS-436: Docs 436/os 3.24
  calico/security/encrypt-cluster-pod-traffic.md
Labels: release-note-required, docs-pr-required

#7073 Update dependencies (general)
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#6890 update: Calico app policy - Isito 1.15.x
  calico/security/app-layer-policy.md
  manifests/alp/istio-inject-configmap-1.15.yaml
Labels: area/documentation, release-note-required, kind/enhancement, docs-not-required

#7071 [BPF] Do not ledge error for setting accept_local=1
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-not-required, merge-when-ready

#7061 Improvements to Felix liveness/readiness reporting
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/aws/ec2.go
  felix/calc/active_rules_calculator.go
  felix/calc/async_calc_graph.go
  felix/calc/calc_graph.go
  felix/calc/calc_graph_fv_test.go
  felix/calc/calc_graph_test.go
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/calc/l3_route_resolver.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/config/param_types.go
  felix/daemon/daemon.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/mock/mock_dataplane.go
  felix/dataplane/windows/win_dataplane.go
  felix/fv/config_update_test.go
  felix/fv/health_test.go
  felix/labelindex/named_port_index.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/serviceindex/serviceindex.go
  felix/stringutils/parse_keyvalue_list.go
  felix/stringutils/parse_keyvalue_list_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  libcalico-go/lib/health/health.go
  libcalico-go/lib/health/health_suite_test.go
  libcalico-go/lib/health/health_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
  typha/pkg/snapcache/cache.go
  typha/pkg/snapcache/cache_test.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-completed, merge-when-ready

#7047 Typha: share snapshots between clients
  calico/reference/typha/prometheus.md
  libcalico-go/lib/multireadbuf/multireabuf.go
  libcalico-go/lib/multireadbuf/multireadbuf_test.go
  typha/fv-tests/server_test.go
  typha/pkg/syncserver/snap_precalc.go
  typha/pkg/syncserver/sync_server.go
  typha/pkg/syncserver/syncserver_test.go
Labels: release-note-required, docs-completed, merge-when-ready

#7074 [BPF] debug programs patching no more
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/log.h
  felix/bpf-gpl/nat.h
  felix/bpf-gpl/nat_lookup.h
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7078 [v3.24] Add necessary libs to kube controllers
  kube-controllers/Dockerfile.amd64
Labels: release-note-required, docs-not-required, merge-when-ready

#7079 Automated cherry pick of #7078: Add necessary libs to kube controllers
  kube-controllers/Dockerfile.amd64
Labels: release-note-required, docs-not-required, merge-when-ready

#7076 Fix panic while handling invalid spoofed IP ranges
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#7080 [BPF] no need for CALI_SKB_MARK_BYPASS_FWD_SRC_FIXUP mark
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/tc.c
  felix/bpf/tc/defs/defs.go
  felix/bpf/ut/icmp_related_test.go
  felix/bpf/ut/nat_test.go
Labels: docs-not-required, release-note-not-required

#7082 [release-v3.24] Auto pick #7076: Fix panic while handling invalid spoofed IP ranges
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
Labels: release-note-required, docs-pr-required

#6892 beta.kubernetes.io/arch|os haven been deprecated
  calico/getting-started/windows-calico/demo.md
  calico/getting-started/windows-calico/kubernetes/standard.md
  confd/tests/mock_data/kdd/nodes.yaml
  confd/tests/test_suite_common.sh
  kube-controllers/tests/testutils/flannel_migration_utils.go
Labels: release-note-required, docs-pr-required

#7083 Add necessary libs to kube controllers
  kube-controllers/Dockerfile.amd64
Labels: release-note-required, docs-not-required, merge-when-ready

#7084 Automated cherry pick of #7083: Add necessary libs to kube controllers
  kube-controllers/Dockerfile.amd64
Labels: release-note-required, docs-not-required, merge-when-ready

#7089 Fix that Felix FVs failed to wait for Felix restart as expected.
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/topology.go
Labels: release-note-required, docs-pr-required

#7093 [BPF] separate objects for v4/6 programs
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/connect_balancer.c
  felix/bpf-gpl/connect_balancer_v6.c
  felix/bpf-gpl/list-objs
  felix/bpf-gpl/log.h
  felix/bpf-gpl/policy_program.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tc6.c
  felix/bpf-gpl/xdp.c
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/tc/defs/defs.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/ipv6_test.go
  felix/bpf/ut/precompilation_test.go
  felix/fv/infrastructure/topology.go
Labels: release-note-required, docs-not-required

#7102 Fix race in typha FV tests during shutdown of client.
  typha/fv-tests/server_harness_test.go
  typha/fv-tests/server_test.go
  typha/pkg/daemon/daemon_test.go
Labels: docs-not-required, release-note-not-required

#7105 Avoid stringifying large typha messages.
  typha/pkg/syncclient/sync_client.go
  typha/pkg/syncproto/sync_proto.go
Labels: docs-not-required, release-note-not-required

#7095 [Release 3.24] Update golang and base
  metadata.mk
Labels: release-note-required, docs-pr-required

#7087 [BPF] fix CTLB when ipv4 addr is masked as ipv6
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/connect.h
  felix/bpf-gpl/connect_balancer.c
  felix/bpf-gpl/connect_balancer_v6.c
  felix/bpf/nat/connecttime.go
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
  felix/fv/test-connection/test-connection.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#7091 [CHERRY-PICK] [BPF] fix CTLB when ipv4 addr is masked as ipv6
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/connect.h
  felix/bpf-gpl/connect_balancer.c
  felix/bpf-gpl/connect_balancer_v6.c
  felix/bpf/nat/connecttime.go
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
  felix/fv/test-connection/test-connection.go
Labels: release-note-required, docs-not-required

#7098 Add make gen-crds for calicoctl
  Makefile
  calicoctl/Makefile
  calicoctl/calicoctl/commands/crds/crds.go
Labels: release-note-required, docs-pr-required

#7118 Update code dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7119 [Release 3.24] Update code dependencies (Backport 7118)
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7117 [BPF] UTs loaded with libbpf
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/arp.h
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/counters.h
  felix/bpf-gpl/ctlb.h
  felix/bpf-gpl/failsafe.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/ifstate.h
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/list-ut-objs
  felix/bpf-gpl/log.h
  felix/bpf-gpl/nat_types.h
  felix/bpf-gpl/policy_program.h
  felix/bpf-gpl/routes.h
  felix/bpf-gpl/rule_counters.h
  felix/bpf-gpl/sendrecv.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tc6.c
  felix/bpf-gpl/ut/ut.h
  felix/bpf-gpl/xdp.c
  felix/bpf/binary.go
  felix/bpf/bpf.go
  felix/bpf/jump/map.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/icmp_related_test.go
  felix/bpf/ut/ipv6_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/bpf/ut/precompilation_test.go
  felix/bpf/ut/xdp_test.go
  felix/bpf/xdp/attach.go
Labels: release-note-required, docs-pr-required

#7125 Use forked CNI plugin URL and corresponding tagged artifacts
  cni-plugin/Makefile
Labels: release-note-required, docs-pr-required

#7123 Update flannel
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#7128 [Release 3.24] Update CNI (cherry-pick 7123, 7125)
  cni-plugin/Makefile
Labels: release-note-required, docs-pr-required

#7090 pass ipnet to hostmetadatav4v6update
  felix/calc/calc_graph.go
  felix/calc/calc_graph_fv_test.go
  felix/calc/dataplane_passthru.go
  felix/calc/event_sequencer.go
  felix/calc/profile_decoder_test.go
  felix/calc/state_test.go
  felix/calc/states_for_test.go
  felix/dataplane/mock/mock_dataplane.go
Labels: docs-not-required, release-note-not-required

#7075 Reduce log level on spammy VXLAN log
  felix/calc/vxlan_resolver.go
Labels: release-note-required, docs-pr-required

#7045 Skip bridge created by Docker
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-not-required

#7114 add post release tests for manifests archive contents
  hack/postrelease/test_manifests_archives.py
Labels: release-note-required, docs-pr-required
