Repository projectcalico/calico, pull requests merged in 2022-11, with the labels that each got.

#6932 Add hook and IP version to policy program name
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#6933 felix/bpf: load calico_tc_host_ct_conflict only if needed
  felix/bpf-gpl/tc.c
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
Labels: release-note-required, docs-not-required

#6836 felix/bpf: fix switch from FeatureDetectOverrides to FeatureGates
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#6786 Fix syncing calico node labels for Kubernetes CRD mode
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/kubecontrollersconfig.go
  libcalico-go/lib/backend/k8s/resources/kubecontrollersconfig_test.go
Labels: release-note-required, docs-not-required

#6943 Fix Typha endpoints permission in the hard way guide
  calico/getting-started/kubernetes/hardway/install-typha.md
Labels: docs-not-required, release-note-not-required

#6938 FV test for bpf generic counters
  felix/fv/bpf_counters_test.go
Labels: docs-not-required, release-note-not-required

#6882 mark CALI_ST_SKIP_FIB packets on ingress of heps
  felix/bpf-gpl/tc.c
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/icmp_related_test.go
  felix/bpf/ut/nat_test.go
  felix/bpf/ut/whitelist_test.go
Labels: release-note-required, docs-not-required

#6944 Docs-kubecontroller-update
  calico/reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#6939 Updates for v3.24.4
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.24.4-release-notes.md
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6937 Fix SCTP named ports flake
  felix/fv/connectivity/conncheck.go
  felix/fv/test-connection/test-connection.go
  felix/fv/test-workload/test-workload.go
Labels: docs-not-required, release-note-not-required

#6845 bpf pcap filter
  felix/bpf-gpl/jump.h
  felix/bpf/asm/asm.go
  felix/bpf/asm/asm_test.go
  felix/bpf/asm/helpers.go
  felix/bpf/filter/filter.go
  felix/bpf/jump/map.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/defs/defs.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/filter_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/bpf/xdp/attach.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/fv/bpf_test.go
  felix/fv/donottrack_test.go
Labels: release-note-required, docs-pr-required

#6947 Cherrypick-kubecontroller-to-3.24
  calico/reference/kube-controllers/configuration.md
Labels: docs-not-required, release-note-not-required

#6942 Add 'nodelocaldns' to IP auto-detection skipping
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-pr-required

#6948 Updates for v3.23.5
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.23.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#6946 felix/fv: fix cleaning ifstate when iface goes down
  felix/bpf/mock/map.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
Labels: release-note-required, docs-not-required

#6952 Add flag to calico windows uninstall script and pass it from hostprocess install
  node/windows-packaging/CalicoWindows/uninstall-calico.ps1
  node/windows-packaging/host-process-install.ps1
Labels: release-note-required, docs-not-required

#6955 Fix handling unicode kubeconfig file
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, docs-not-required

#6958 [release-v3.23] Auto pick #6952: Add flag to calico windows uninstall script and pass it from
  node/windows-packaging/CalicoWindows/uninstall-calico.ps1
  node/windows-packaging/host-process-install.ps1
Labels: release-note-required, docs-not-required

#6957 [release-v3.24] Auto pick #6952: Add flag to calico windows uninstall script and pass it from
  node/windows-packaging/CalicoWindows/uninstall-calico.ps1
  node/windows-packaging/host-process-install.ps1
Labels: release-note-required, docs-not-required

#6965 DOCS-700: Changing 'else if' to 'elsif'
  calico/_includes/content/reqs-sys.md
Labels: release-note-required, docs-pr-required

#6959 Updates for v3.24.5
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.24.5-release-notes.md
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6967 Add information regarding CSI driver installation to relevant install…
  calico/getting-started/kubernetes/managed-public-cloud/eks.md
  calico/getting-started/kubernetes/self-managed-public-cloud/aws.md
Labels: release-note-required, docs-pr-required, merge-when-ready

#6960 felix/bpf: tc.AttachPoint is always a pointer
  felix/bpf/tc/attach.go
  felix/bpf/xdp/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#6977 bpf/ut: TestNATAffinity flakes because of a too short timeout
  felix/bpf/ut/nat_test.go
Labels: release-note-required, docs-pr-required

#6956 DOCS-945: Removes variable from front matter.
  calico/networking/workloads-outside-cluster.md
Labels: docs-not-required, release-note-not-required

#6970 Fix bug in test_flags.py (calicoctl)
  calicoctl/tests/st/calicoctl/test_flags.py
Labels: docs-not-required, release-note-not-required

#6961 Update golang to 1.18.8
  metadata.mk
Labels: release-note-required, docs-not-required

#6962 [Release 3.24] Cherry-pick 6961 (Update golang to 1.18.8)
  metadata.mk
Labels: release-note-required, docs-not-required

#6982 Collect BPF logs for UTs
  felix/bpf-gpl/bpf.h
  felix/bpf/binary.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/main_test.go
Labels: release-note-required, docs-pr-required

#6991 [release-v3.24] Auto pick #6748: Update BIRD version to include memory usage fix
  metadata.mk
Labels: docs-not-required, release-note-not-required

#6992 [release-v3.23] Auto pick #6748: Update BIRD version to include memory usage fix
  metadata.mk
Labels: docs-not-required, release-note-not-required

#6993 fv/xdp: separate tcp and udp test for clarity
  felix/fv/bpf_attach_test.go
  felix/fv/bpf_map_resize_test.go
  felix/fv/sockmap_test.go
  felix/fv/xdp_test.go
Labels: release-note-required, docs-pr-required

#7005 Use struct for passing data to libbpf
  felix/bpf-gpl/routes.h
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/routes/map.go
  felix/bpf/tc/attach.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#6986 Add more verbiage to imagePullSecrets comment
  charts/tigera-operator/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7009 Docs-openstack-unsupported
  calico/networking/vxlan-ipip.md
Labels: docs-not-required, release-note-not-required

#7016 DOCS-724: Removes links to fix build errors in Docusaurus site
  calico/about/about-kubernetes-egress.md
  calico/networking/determine-best-networking.md
  calico/networking/workloads-outside-cluster.md
  calico/reference/faq.md
  calico/security/adopt-zero-trust.md
  calico/security/calico-network-policy.md
  calico/security/external-ips-policy.md
  calico/security/kubernetes-network-policy.md
  calico/security/policy-rules-overview.md
Labels: release-note-required, docs-pr-required

#6871 Add `Auto` option for `IptablesBackend` to FelixConfiguration
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/resources/felixconfig.md
  felix/config/config_params_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6973 Typha graceful shutdown
  calico/reference/typha/configuration.md
  charts/calico/templates/calico-typha.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  typha/Makefile
  typha/fv-tests/fv_tests_suite_test.go
  typha/fv-tests/server_test.go
  typha/pkg/config/config_params.go
  typha/pkg/daemon/daemon.go
  typha/pkg/syncserver/sync_server.go
  typha/pkg/syncserver/syncserver_test.go
Labels: release-note-required, docs-completed

#6705 Replace encoding/json with jsoniter.
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/json/json.go
  libcalico-go/lib/net/ip.go
  libcalico-go/lib/net/ipnet.go
  libcalico-go/lib/net/mac.go
Labels: release-note-required, docs-not-required, merge-when-ready

#7019 Fix formatting issue with the FelixConfig reference doc
  calico/reference/resources/felixconfig.md
Labels: docs-completed, release-note-not-required

#7020 [BPF] AttachClassifier does not need bpf_tc_query_iface
  felix/bpf/libbpf/libbpf.go
Labels: docs-not-required, release-note-not-required

#7008 [BPF] detach cali programs from devices no longer in regex
  felix/bpf/attach.go
  felix/bpf/bpf.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/docker-image/calico-felix-wrapper
  felix/fv/bpf_attach_test.go
  felix/fv/infrastructure/felix.go
Labels: release-note-required, docs-not-required

#7021 DOCS-835: Doc-fix-network-design
  calico/reference/architecture/design/l2-interconnect-fabric.md
  calico/reference/architecture/design/l3-interconnect-fabric.md
Labels: docs-not-required, release-note-not-required

#6703 Optimise KeyFromDefaultPath.
  libcalico-go/lib/backend/model/block_affinity.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/backend/model/keys_test.go
Labels: release-note-required, docs-not-required

#7038 [BPF/fv] Sync with NAT tables properly in ICMP tests
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#7033 [BPF] simplified bpfEndpointManager.dirtyIfaceNames iteration
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required
