Repository projectcalico/calico, pull requests merged in 2022-10, with the labels that each got.

#6792 Openstack fixes v3.22
  networking-calico/networking_calico/agent/dhcp_agent.py
Labels: docs-not-required, release-note-not-required

#6793 Openstack fixes v3.23
  networking-calico/networking_calico/agent/dhcp_agent.py
Labels: docs-not-required, release-note-not-required

#6794 Openstack fixes v3.24
  networking-calico/networking_calico/agent/dhcp_agent.py
Labels: docs-not-required, release-note-not-required

#6774 Update the ipsec.yaml file's location
  calico/getting-started/kubernetes/vpp/getting-started.md
  calico/getting-started/kubernetes/vpp/ipsec.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6766 BPF support for 3rd party iptables DNAT rules that redirect host->pod
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/tc.c
  felix/fv/bpf_test.go
  felix/rules/static.go
Labels: docs-not-required, release-note-not-required

#6795 Adjust wireguard deflake fix.
  felix/fv/connectivity/conncheck.go
  felix/fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#6818 fixing typo in front matter
  calico/getting-started/kubernetes/hardway/index.md
Labels: release-note-required, docs-pr-required

#6816 Changing redirect paths for 404 links
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#6808 Updates for v3.22.5 and release packaging scripts
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.22.5-release-notes.md
  hack/release/packaging/.gitignore
  hack/release/packaging/LICENSE
  hack/release/packaging/Makefile
  hack/release/packaging/README.md
  hack/release/packaging/docker-build-images/centos7-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/centos7-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/install-centos-build-deps
  hack/release/packaging/docker-build-images/install-ubuntu-build-deps
  hack/release/packaging/docker-build-images/ubuntu-bionic-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-bionic-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-trusty-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-trusty-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-xenial-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-xenial-build.Dockerfile.ppc64le
  hack/release/packaging/etcd3gw/rpm/python-etcd3gw.spec
  hack/release/packaging/rpm/build-rpms
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/lib.sh
  hack/release/packaging/utils/make-packages.sh
  hack/release/packaging/utils/publish-debs.sh
  hack/release/packaging/utils/publish-rpms.sh
Labels: docs-not-required, release-note-not-required

#6822 Move hping into the felix test image.
  felix/docker-image/Dockerfile.amd64
  felix/docker-image/Dockerfile.s390x
  felix/fv/containers/containers.go
  felix/fv/latency_test.go
  felix/fv/utils/utils.go
  felix/fv/xdp_test.go
Labels: docs-not-required, release-note-not-required

#6783 felix/bpf: allow using CTLB workaround just for UDP
  felix/bpf-gpl/connect_balancer.c
  felix/bpf-gpl/connect_balancer_v6.c
  felix/bpf-gpl/ctlb.h
  felix/bpf-gpl/globals.h
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/calc/calc_graph_test.go
  felix/calc/dataplane_passthru.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
  felix/fv/test-connection/test-connection.go
  felix/fv/workload/workload.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: release-note-required, docs-pr-required

#6702 Fix IPAM metrics test flake
  kube-controllers/pkg/controllers/node/metrics_fv_test.go
Labels: docs-not-required, release-note-not-required

#6811 Update kubernetes-upgrade.md
  calico/maintenance/kubernetes-upgrade.md
Labels: docs-not-required, release-note-not-required

#6813 [Release 3.24] Cherry-pick: BPF support for 3rd party iptables DNAT rules that redirect host->pod
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/tc.c
  felix/fv/bpf_test.go
  felix/rules/static.go
Labels: docs-not-required, release-note-not-required

#6814 [Release 3.23] Cherry-pick: BPF support for 3rd party iptables DNAT rules that redirect host->pod
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/tc.c
  felix/fv/bpf_test.go
  felix/rules/static.go
Labels: docs-not-required, release-note-not-required

#6834 DOCS-602: Fixes syntax for a note
  calico/getting-started/openshift/installation.md
Labels: release-note-required, docs-pr-required

#6778 [release-v3.24] cherry-pick: Fix allowed source prefix annotation validation
  libcalico-go/lib/apis/v3/workloadendpoint.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: release-note-required, docs-not-required

#6837 Update multiple dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#6282 Fix announcement of /32 and /128 entries for serviceLoadBalancerIPs.
  confd/pkg/backends/calico/client.go
  confd/pkg/backends/calico/routes.go
  confd/pkg/backends/calico/routes_test.go
Labels: release-note-required, docs-not-required

#6833 Finesse health reports, actually print the table not its string.
  libcalico-go/lib/health/health.go
Labels: release-note-required, docs-not-required

#6824 Update golang to 1.18.7
  metadata.mk
Labels: release-note-required, docs-not-required, merge-when-ready

#6825 [Release 3.24] Cherry-pick 6824
  metadata.mk
Labels: release-note-required, docs-pr-required

#6847 DOCS-854: Removes extra toc
  calico/reference/architecture/design/l3-interconnect-fabric.md
  calico/reference/faq.md
Labels: release-note-required, docs-pr-required

#6817 Add CSI node-driver-registrar to image list for private registry use
  calico/_config.yml
  calico/_data/versions.yml
Labels: release-note-required, docs-completed

#6812 Add CSI node-driver-registrar to image list for private registry use
  calico/_config.yml
  calico/_data/versions.yml
Labels: release-note-required, cherry-pick-candidate, docs-completed

#6835 Let calico-bpf decide whether to fail when some counters error - XDP counters may not be present
  calico/maintenance/ebpf/troubleshoot-ebpf.md
  felix/bpf/counters/counters.go
  felix/cmd/calico-bpf/commands/counters.go
Labels: docs-not-required, release-note-not-required

#6850 Update kubernetes-upgrade.md
  calico/maintenance/kubernetes-upgrade.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6854 DOCS-871: Fixes table header formatting
  calico/networking/mtu.md
Labels: docs-not-required, release-note-not-required

#6852 Retain OpenSSL FIPS dependent files in calico-node image
  node/clean-up-filesystem.sh
Labels: release-note-required, docs-not-required

#6861 Update nssm version
  node/Makefile
Labels: release-note-required, docs-pr-required

#6856 Updates for v3.24.2
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.24.2-release-notes.md
  charts/calico/values.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6842 Disable VXLAN checksum offload by default.
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6840 Tweak newly added test
  confd/pkg/backends/calico/routes_test.go
Labels: docs-not-required, release-note-not-required

#6868 Fix incorrect versions for operator
  charts/tigera-operator/values.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#6870 Assert manifest versions as part of release
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#6791 Fix patch commands overwriting metadata
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
Labels: release-note-required, docs-not-required

#6873 Fix patch commands overwriting metadata
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
Labels: release-note-required, docs-not-required

#6874 Fix patch commands overwriting metadata
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
Labels: release-note-required, docs-not-required

#6875 Fix patch commands overwriting metadata
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
Labels: release-note-required, docs-not-required

#6879 [Backport 3.23] Match full interface names to exclude
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/filtered.go
  node/pkg/lifecycle/startup/autodetection/interfaces.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
  node/pkg/lifecycle/startup/autodetection/reachaddr.go
  node/pkg/lifecycle/startup/startup.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6878 [Backport 3.24] Match full interface names to exclude
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/filtered.go
  node/pkg/lifecycle/startup/autodetection/interfaces.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
  node/pkg/lifecycle/startup/autodetection/reachaddr.go
  node/pkg/lifecycle/startup/startup.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6881 Updates for v3.23.4
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.23.4-release-notes.md
Labels: release-note-required, docs-pr-required

#6885 [release-v3.24] Retain OpenSSL FIPS dependent files in calico-node image
  node/clean-up-filesystem.sh
Labels: release-note-required, docs-not-required

#6888 Updates for v3.24.3
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.24.3-release-notes.md
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6889 Cleanup cni-plugin UT temp dir after each test case
  cni-plugin/pkg/install/install_test.go
Labels: docs-not-required, release-note-not-required

#6902 Skip vxlan.calico in IP auto-detection
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-not-required

#6904 [release-v3.23] Auto pick #6902: Skip vxlan.calico in IP auto-detection
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-not-required

#6903 [release-v3.24] Auto pick #6902: Skip vxlan.calico in IP auto-detection
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-not-required

#6911 DOCS-888: Removes unwanted admonition tag
  calico/reference/faq.md
Labels: docs-not-required, release-note-not-required

#6872 Docs-add-training-tab
  calico/_data/navbars/training.yml
  calico/training/index.md
Labels: docs-not-required, release-note-not-required

#6913 Docs-remove-MKE-unsupported
  calico/maintenance/ebpf/install.md
Labels: release-note-required, docs-not-required

#6914 Cherrypick-docs-mke-update-release-v3.24
  calico/maintenance/ebpf/install.md
Labels: release-note-required, docs-pr-required

#6916 Fix nssm path
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, docs-pr-required

#6918 Update the way to download and package nssm
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  node/Makefile
  node/windows-packaging/CalicoWindows/kubernetes/install-kube-services.ps1
  node/windows-packaging/CalicoWindows/kubernetes/uninstall-kube-services.ps1
  node/windows-packaging/CalicoWindows/libs/calico/calico.psm1
  node/windows-packaging/nssm-2.24.zip
  node/windows-packaging/nssm.sha256sum
Labels: release-note-required, docs-pr-required

#6917 Fix BPF enablement flake
  felix/bpf/asm/asm.go
  felix/bpf/maps.go
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
Labels: release-note-required, docs-pr-required

#6925 Revert "Fix BPF enablement flake"
  felix/bpf/asm/asm.go
  felix/bpf/maps.go
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
Labels: release-note-required, docs-pr-required

#6926 Fix BPF enablement flakes
  felix/bpf/asm/asm.go
  felix/bpf/maps.go
  felix/fv/bpf_test.go
  felix/fv/connectivity/conncheck.go
Labels: release-note-required, docs-pr-required

#6912 Remove problematic terminology: whitelist and blacklist.
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  Makefile
  confd/pkg/backends/calico/routes.go
  confd/pkg/backends/calico/routes_test.go
  felix/bpf-apache/filter.c
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/conntrack_types.h
  felix/bpf/bpf.go
  felix/bpf/bpf_test.go
  felix/bpf/cmd/felix-xdp.go
  felix/bpf/conntrack/conntrack_test.go
  felix/bpf/conntrack/v2/map.go
  felix/bpf/conntrack/v3/map.go
  felix/bpf/ut/nat_test.go
  felix/bpf/ut/whitelist_test.go
  felix/check-licenses/check_licenses.go
  felix/dataplane/linux/xdp_state.go
  felix/fv/bpf_test.go
  felix/fv/netsets_test.go
  felix/fv/vxlan_test.go
  felix/fv/xdp_test.go
  felix/ipsets/ipsets.go
  felix/iptables/table_test.go
  felix/rules/static.go
  hack/banned-regexps-exceptions.txt
  hack/banned-regexps.txt
  hack/check-language.sh
  node/tests/k8st/tests/test_bgp_advert.py
  node/tests/k8st/tests/test_bgp_advert_v6.py
  node/tests/st/policy/test_profile.py
  typha/check-licenses/check_licenses.go
Labels: release-note-required, docs-not-required

#6839 networking_calico: Prime project cache at startup
  networking-calico/networking_calico/plugins/ml2/drivers/calico/endpoints.py
Labels: release-note-required, docs-pr-required

#6857 networking_calico: Do not checksum DHCP packets
  networking-calico/networking_calico/agent/linux/dhcp.py
Labels: release-note-required, docs-not-required

#6929 Add 'vxlan-v6.calico', 'wireguard.cali', 'wg-v6.cali' to IP auto-detection skipping
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-not-required

#6931 [release-v3.23] Auto pick #6929: Add 'vxlan-v6.calico', 'wireguard.cali', 'wg-v6.cali' to IP
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-pr-required

#6930 [release-v3.24] Auto pick #6929: Add 'vxlan-v6.calico', 'wireguard.cali', 'wg-v6.cali' to IP
  node/pkg/lifecycle/startup/autodetection/autodetection_linux.go
  node/pkg/lifecycle/startup/autodetection/interfaces_linux_test.go
Labels: release-note-required, docs-pr-required
