Repository projectcalico/calico, pull requests merged in 2022-03, with the labels that each got.

#5644 Cherry-pick Windows loopback DSR support
  cni-plugin/pkg/dataplane/windows/dataplane_windows.go
  cni-plugin/pkg/types/types.go
  node/windows-packaging/CalicoWindows/cni.conf.template
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  node/windows-packaging/CalicoWindows/libs/calico/calico.psm1
Labels: release-note-required, docs-pr-required

#5679 Discourage use of Profile rules
  calico/reference/resources/profile.md
Labels: docs-completed, release-note-not-required

#5681 Add missing License notice text
  cni-plugin/internal/pkg/utils/winpol/windows_policy.go
  cni-plugin/internal/pkg/utils/winpol/windows_policy_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5685 Switch to CERN's Centos mirror.
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/centos.repo
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#5687 windows: update EKS support
  calico/getting-started/windows-calico/kubernetes/requirements.md
Labels: docs-not-required, release-note-not-required

#5688 Cherry-pick centos mirror fix
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/centos.repo
Labels: docs-not-required, release-note-not-required

#5689 Switch to CERN's Centos mirror.
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/centos.repo
Labels: release-note-required, docs-pr-required

#5692 Fix IP pool nat outgoing doc
  calico/reference/resources/ippool.md
Labels: release-note-required, docs-pr-required

#5693 Fix felix release logic
  felix/Makefile
Labels: docs-not-required, release-note-not-required

#5694 Fix felix release logic
  app-policy/Makefile
  felix/Makefile
Labels: docs-not-required, release-note-not-required

#5695 Reinstate streaming of v1 ProfileLabels (alongside v3 Profile)
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/backend/model/keys_test.go
  libcalico-go/lib/backend/model/profile.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/profileprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/profileprocessor_test.go
Labels: docs-not-required, release-note-not-required

#5657 adding algolia suggestions for search fix
  calico/robots.txt
Labels: release-note-required, docs-pr-required

#5656 adding algolia suggestions for search fix
  calico/robots.txt
Labels: release-note-required, docs-pr-required

#5699 remove all bot disallow
  calico/robots.txt
Labels: release-note-required, docs-pr-required

#5698 remove all bot disallow
  calico/robots.txt
Labels: release-note-required, docs-pr-required

#5700 Updates for v3.22.1
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.22.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#5701 Fix referenced flannel version
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.22.1-release-notes.md
Labels: release-note-required, docs-pr-required

#5649 Remove hardcoded namespace from helm chart
  calico/_includes/charts/tigera-operator/templates/tigera-operator/00-namespace-tigera-operator.yaml
  calico/_includes/charts/tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml
  calico/_includes/charts/tigera-operator/templates/tigera-operator/02-configmap-calico-resources.yaml
  calico/_includes/charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator.yaml
  calico/_includes/charts/tigera-operator/templates/tigera-operator/02-serviceaccount-tigera-operator.yaml
  calico/_includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  calico/_plugins/helm.rb
  calico/getting-started/kubernetes/helm.md
  calico/maintenance/kubernetes-upgrade.md
  calico/manifests/ocp/tigera-operator/00-namespace-tigera-operator.yaml
  calico/manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#5703 Add to helm README regarding install / upgrade
  calico/_includes/charts/tigera-operator/README.md
  calico/getting-started/kubernetes/helm.md
Labels: release-note-required, docs-pr-required

#5536 Add terraform logic for building a release VM
  .semaphore/release/release.yml
  hack/release/.gitignore
  hack/release/Makefile
  hack/release/pkg/builder/builder.go
  hack/release/remote-execute.sh
  hack/release/terraform.tf
  hack/release/variables.tf
Labels: docs-not-required, release-note-not-required

#5708 Add missing secret to release config
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#5647 Copy data from old map to the new map when config changes
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/conntrack/map.go
  felix/bpf/maps.go
  felix/bpf/mock/map.go
  felix/bpf/nat/connecttime.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/maps_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_map_resize_test.go
Labels: release-note-required, docs-pr-required

#5714 Skip CNI multiple network test for Windows
  cni-plugin/win_tests/calico_cni_k8s_windows_test.go
Labels: release-note-required, docs-pr-required

#5718 Migrate search to new application
  calico/js/searchConfig.js
Labels: release-note-required, docs-pr-required

#5719 Automated cherry pick of #5718: Migrate search to new application
  calico/js/searchConfig.js
Labels: release-note-required, docs-pr-required

#5716 Doc updates for configurable map sizes.
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/fv/bpf_map_resize_test.go
Labels: release-note-required, docs-pr-required

#5720 felix/bpf: iptable rules use incorrect masks
  felix/bpf/tc/defs/defs.go
Labels: docs-not-required, release-note-not-required

#5722 Update Calico v3.21.4 to use operator v1.23.6
  calico/_data/versions.yml
Labels: docs-not-required, release-note-not-required

#5726 Fix logging filename lookup.
  libcalico-go/lib/logutils/logutils.go
Labels: release-note-required, docs-not-required, merge-when-ready

#5634 node: enable UTs
  node/Makefile
  node/pkg/winupgrade/upgrade_test.go
  node/windows-packaging/tests/calico_suite_test.go
  node/windows-packaging/tests/cni_conf_test.go
Labels: docs-not-required, release-note-not-required

#5658 adding rule for robots.txt to not redirect on docs.projectcalico.org
  calico/netlify/_redirects_v3.21
Labels: docs-not-required, release-note-not-required

#5730 Update security/ docs section to include operator instructions
  calico/security/comms/crypto-auth.md
  calico/security/comms/reduce-nodes.md
  calico/security/comms/secure-bgp.md
  calico/security/non-privileged.md
  calico/security/tutorials/app-layer-policy/enforce-policy-istio.md
  calico/security/tutorials/calico-policy.md
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#5675 Introduce patchMode for pod annotations
  cni-plugin/pkg/k8s/k8s.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/patchmode.go
  libcalico-go/lib/backend/k8s/resources/patchmode_test.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint_test.go
Labels: docs-not-required, release-note-not-required

#5732 Destroy VM after release
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#5736 Add option for turning off BGP loop prevention and specifying a number of local AS numbers to allow in routes
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/resources/bgppeer.md
  confd/etc/calico/confd/templates/bird.cfg.template
  confd/etc/calico/confd/templates/bird6.cfg.template
  confd/pkg/backends/calico/client.go
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird.cfg
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird6.cfg
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird6_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird6_ipam.cfg
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird_ipam.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird6.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird6_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird6_ipam.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird_ipam.cfg
  confd/tests/mock_data/calicoctl/explicit_peering/local-as-global/delete.yaml
  confd/tests/mock_data/calicoctl/explicit_peering/local-as-global/input.yaml
  confd/tests/mock_data/calicoctl/explicit_peering/local-as/delete.yaml
  confd/tests/mock_data/calicoctl/explicit_peering/local-as/input.yaml
  confd/tests/test_suite_common.sh
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
Labels: release-note-required, docs-pr-required

#5733 felix/bpf/ut: patch in skb marks
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/list-ut-objs
  felix/bpf-gpl/tc.c
  felix/bpf/binary.go
  felix/bpf/ut/bpf_prog_test.go
Labels: release-note-required, docs-pr-required

#5676 Prevent GC when IPAM datstore migrate lock
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_test.go
  kube-controllers/pkg/controllers/node/syncer.go
Labels: release-note-required, docs-not-required

#5484 Add configuration knob for dataplane readiness timeout.
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/health_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#5515 Build pod2daemon as a static binary
  pod2daemon/Makefile
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#5750 windows: fix the install zip file version
  calico/scripts/install-calico-windows.ps1
Labels: docs-not-required, release-note-not-required

#5751 Automated cherry pick of #5515: Build pod2daemon binary statically
  pod2daemon/Makefile
Labels: release-note-required, docs-not-required

#5744 Docs update - Stars demo multiarch
  calico/security/tutorials/kubernetes-policy-demo/manifests/01-management-ui.yaml
  calico/security/tutorials/kubernetes-policy-demo/manifests/02-backend.yaml
  calico/security/tutorials/kubernetes-policy-demo/manifests/03-frontend.yaml
  calico/security/tutorials/kubernetes-policy-demo/manifests/04-client.yaml
Labels: docs-not-required, release-note-not-required

#5754 Add OpenStack packaging scripts to monorepo
  .semaphore/push-images/packaging.yaml
  felix/.gitignore
  hack/release/RELEASING.md
  hack/release/packaging/.gitignore
  hack/release/packaging/LICENSE
  hack/release/packaging/Makefile
  hack/release/packaging/README.md
  hack/release/packaging/docker-build-images/centos7-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/centos7-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/install-centos-build-deps
  hack/release/packaging/docker-build-images/install-ubuntu-build-deps
  hack/release/packaging/docker-build-images/ubuntu-bionic-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-bionic-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-trusty-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-trusty-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-xenial-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-xenial-build.Dockerfile.ppc64le
  hack/release/packaging/etcd3gw/rpm/python-etcd3gw.spec
  hack/release/packaging/rpm/build-rpms
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/lib.sh
  hack/release/packaging/utils/make-packages.sh
  hack/release/packaging/utils/publish-debs.sh
  hack/release/packaging/utils/publish-rpms.sh
  networking-calico/.gitignore
Labels: docs-not-required, release-note-not-required

#5748 [release-v3.22] Pick of #5710: Update install-calico-windows.ps1.tpl
  calico/getting-started/windows-calico/quickstart.md
  calico/scripts/install-calico-windows.ps1
  node/windows-packaging/install-calico-windows.ps1.tpl
Labels: docs-not-required, release-note-not-required

#5753 Fix for performance drop with BPF dataplane
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/nat.h
Labels: release-note-required, docs-pr-required

#5758 Update policy program to jump to drop program
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/policy_program.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tcv6.h
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#5729 Fix flake with multiple concurrent calls to map
  felix/dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5765 fix wireguard pkg files' build flags (#5746)
  felix/wireguard/bootstrap.go
  felix/wireguard/metrics_linux.go
  felix/wireguard/metrics_windows.go
  felix/wireguard/wireguard.go
Labels: docs-not-required, release-note-not-required

#5755 Add String() method to set.mapSet so it pretty-prints more nicely.
  libcalico-go/lib/set/set.go
  libcalico-go/lib/set/set_test.go
Labels: release-note-required, docs-pr-required

#5756 Fix some test flakes - use unique name for workloads in STs
  cni-plugin/tests/calico_cni_k8s_test.go
  node/tests/st/utils/docker_host.py
Labels: docs-not-required, release-note-not-required

#5475 add detail log when failed to create calico client
  cni-plugin/pkg/plugin/plugin.go
Labels: docs-not-required, release-note-not-required

#5663 Removed unwanted `pass` statement
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
Labels: docs-not-required, release-note-not-required

#5768 felix/bpf: fix post nat ip/port when enforcing policy on SYN without NAT
  felix/bpf-gpl/tc.c
  felix/bpf/ut/nat_test.go
Labels: release-note-required, docs-pr-required

#5773 [v3.22] Fix post-NAT IP port on SYN without NAT
  felix/bpf-gpl/tc.c
  felix/bpf/ut/nat_test.go
Labels: release-note-required, docs-not-required

#5757 Docs-clarify-WireGuard-support
  calico/security/encrypt-cluster-pod-traffic.md
Labels: docs-not-required, release-note-not-required

#5776 Rework interface monitor to fix various issues
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/ifacemonitor/iface_monitor.go
  felix/ifacemonitor/ifacemonitor_test.go
  felix/wireguard/wireguard.go
Labels: release-note-required, docs-not-required

#5782 Fix that second call to shutdown hook would block.
  felix/daemon/daemon.go
  felix/fv/config_update_test.go
Labels: docs-not-required, release-note-not-required

#5673 calicoctl: remove reference for transfer.sh
  calicoctl/calicoctl/commands/node/diags.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#5784 Use Packet struct to define a test packet
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/ipv6_test.go
  felix/bpf/ut/malformed_packets_test.go
Labels: docs-not-required, release-note-not-required

#5787 Use the correct calicoctl download link for v3.21
  calico/maintenance/clis/calicoctl/install.md
Labels: release-note-required, docs-pr-required

#5739 Fix minor issue on Windows calico lib
  node/windows-packaging/CalicoWindows/libs/calico/calico.psm1
Labels: release-note-required, docs-not-required

#5780 fix the panic of SetupRoutes in csi-plugin
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, docs-not-required

#5783 Fix skb_is_gso for CO-RE capable kernels.
  felix/Makefile
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/list-objs
  felix/bpf-gpl/skb.h
  felix/bpf/bpfutils/bpf_utils.go
  felix/bpf/nat/connecttime.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/ut/precompilation_test.go
Labels: release-note-required, docs-pr-required

#5791 felix/fv: dead be test need to wait for the be being programmed
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#5792 felix/bpf: ICMP conntrack fix part 2
  felix/bpf-gpl/conntrack.h
Labels: cherry-pick-candidate, docs-pr-required, release-note-not-required

#5796 Updates to operations content for operator installs
  calico/maintenance/clis/calicoctl/configure/etcd.md
  calico/maintenance/clis/calicoctl/configure/kdd.md
  calico/maintenance/clis/calicoctl/configure/overview.md
  calico/maintenance/datastore-migration.md
  calico/maintenance/troubleshoot/commands.md
  calico/maintenance/troubleshoot/component-logs.md
  calico/maintenance/troubleshoot/troubleshooting.md
Labels: docs-not-required, release-note-not-required

#5771 Report health detail
  felix/fv/health_test.go
  felix/fv/winfv/policy_test.go
  libcalico-go/lib/health/health.go
  libcalico-go/lib/health/health_test.go
Labels: docs-not-required, release-note-not-required

#5706 Pool-based IPAM Metrics
  calico/_includes/charts/calico/templates/calico-kube-controllers-rbac.yaml
  calico/maintenance/monitor/monitor-component-metrics.md
  calico/reference/kube-controllers/prometheus.md
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_allocation.go
  kube-controllers/pkg/controllers/node/ipam_test.go
  kube-controllers/pkg/controllers/node/pool_manager.go
  kube-controllers/pkg/controllers/node/syncer.go
  kube-controllers/tests/fv/metrics_test.go
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-pr-required

#5788 windows: move install script tool to calico directory and add install script to release artifacts
  calico/scripts/install-calico-windows.ps1
  hack/release/pkg/builder/builder.go
  node/Makefile
  node/hack/gen-install-calico-windows-script/main.go
  node/windows-packaging/install-calico-windows.ps1.tpl
Labels: release-note-required, docs-pr-required

#5785 felix/bpf: xdp does not use fib
  felix/bpf-gpl/xdp.c
Labels: release-note-required, docs-pr-required

#5795 Remove unnecessary branching
  confd/pkg/resource/template/util.go
Labels: docs-not-required, release-note-not-required

#5798 Added build steps for darwin-arm64
  calicoctl/Makefile
  calicoctl/README.md
Labels: docs-not-required, release-note-not-required

#5804 felix/bpf: when reusing TCP entries, delete them first
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/tc.c
  felix/bpf/conntrack/map.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/nat_test.go
  felix/bpf/ut/tcp_test.go
  felix/bpf/ut/to_host_allowed_test.go
Labels: release-note-required, docs-pr-required

#5808 Fix github credentials for release promotion
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#5811 Fix typo in release semaphore config
  .semaphore/release/release.yml
Labels: release-note-required, docs-pr-required

#5821 Upstream Felix FV enhancements from Enterprise.
  felix/.semaphore/run-tests-on-vms
  felix/fv/bpf_attach_test.go
  felix/fv/bpf_map_resize_test.go
  felix/fv/fv_suite_test.go
  felix/fv/policysync_test.go
  felix/fv/sockmap_test.go
  felix/fv/xdp_test.go
Labels: release-note-required, docs-pr-required

#5814 bpf some cleanup
  felix/bpf-gpl/nat_lookup.h
  felix/bpf-gpl/tc.c
  felix/dataplane/linux/endpoint_mgr.go
Labels: release-note-required, docs-pr-required

#5816 bpf/ut: more whitelist tests - from host
  felix/bpf/ut/whitelist_test.go
Labels: release-note-required, docs-pr-required

#5562 Add backoff to watchercache resync loop.
  libcalico-go/lib/backend/watchersyncer/watchercache.go
Labels: release-note-required, docs-not-required

#5812 Wait for grace period before deleting blocks
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_allocation.go
  kube-controllers/tests/fv/kdd_ipam_gc_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#5815 felix: ManagerWithRouteRules
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/int_dataplane.go
Labels: release-note-required, docs-pr-required

#5817 Bump go-build
  metadata.mk
Labels: release-note-required, docs-pr-required, merge-when-ready

#5576 Have Felix use IP pools to determine enabled encaps
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/calc/calc_graph.go
  felix/calc/calc_graph_fv_test.go
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  felix/calc/event_sequencer.go
  felix/calc/resources_for_test.go
  felix/calc/state_test.go
  felix/calc/states_for_test.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/config/param_types.go
  felix/daemon/daemon.go
  felix/dataplane/driver.go
  felix/dataplane/driver_windows.go
  felix/dataplane/external/ext_dataplane.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/int_dataplane_test.go
  felix/dataplane/mock/mock_dataplane.go
  felix/fv/ipip_test.go
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/rules/rule_defs.go
  kube-controllers/pkg/controllers/flannelmigration/ipam_migrator.go
  kube-controllers/tests/fv/flannel_migration_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/client/ippool.go
  libcalico-go/lib/clientv3/ippool.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
  node/Makefile
  node/pkg/allocateip/allocateip.go
  node/tests/st/bgp/test_ipip.py
Labels: release-note-required, docs-pr-required

#5825 small fixes and improvements
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tc.h
  felix/bpf/attach.go
  felix/fv/bpf_attach_test.go
  felix/fv/workload/workload.go
Labels: release-note-required, docs-pr-required

#5824 felix/bpf: backwards compatible 16bit ct flags
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/conntrack_types.h
  felix/bpf/conntrack/map.go
  felix/bpf/ut/nat_test.go
  go.sum
Labels: release-note-required, docs-pr-required
