Repository projectcalico/calico, pull requests merged in 2022-07, with the labels that each got.

#6305 Make sure cgroup2 fs default mount point exists on host
  node/cmd/mountns/main.go
  node/pkg/nodeinit/calico-init_linux.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6317 felix/bpf: another FV test needs sync with NAT tables
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#6320 felix/bpf: fix for WG no longer uses failsafes
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/wireguard_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6302 Fix serviceaccount token generation for canal
  charts/calico/templates/calico-node.yaml
  cni-plugin/pkg/install/install.go
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  node/pkg/cni/token_watch.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6313 [release-v3.23] cherry-pick: Make sure cgroup2 fs default mount point exists on host
  node/cmd/mountns/main.go
  node/pkg/nodeinit/calico-init_linux.go
Labels: docs-not-required, release-note-not-required

#6314 [release-v3.22] cherry-pick: Make sure cgroup2 fs default mount point exists on host
  node/cmd/mountns/main.go
  node/pkg/nodeinit/calico-init_linux.go
Labels: docs-not-required, release-note-not-required

#6325 Update operator CRDs to include RKE2 option
  calico/_includes/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6261 Use GitHub links for manifests referenced in the docs
  calico/_data/versions.yml
  calico/_includes/content/calico-windows-install.md
  calico/_includes/content/install-k8s-addons.md
  calico/getting-started/kubernetes/flannel/flannel.md
  calico/getting-started/kubernetes/flannel/migration-from-flannel.md
  calico/getting-started/kubernetes/hardway/istio-integration.md
  calico/getting-started/kubernetes/hardway/the-calico-datastore.md
  calico/getting-started/kubernetes/installation/config-options.md
  calico/getting-started/kubernetes/installation/manifests/kubedns.yaml
  calico/getting-started/kubernetes/k3s/multi-node-install.md
  calico/getting-started/kubernetes/k3s/quickstart.md
  calico/getting-started/kubernetes/managed-public-cloud/aks.md
  calico/getting-started/kubernetes/managed-public-cloud/eks.md
  calico/getting-started/kubernetes/minikube.md
  calico/getting-started/kubernetes/quickstart.md
  calico/getting-started/kubernetes/rancher.md
  calico/getting-started/kubernetes/self-managed-onprem/onpremises.md
  calico/getting-started/kubernetes/self-managed-public-cloud/gce.md
  calico/getting-started/kubernetes/vpp/getting-started.md
  calico/getting-started/windows-calico/kubernetes/rancher.md
  calico/getting-started/windows-calico/quickstart.md
  calico/maintenance/clis/calicoctl/install.md
  calico/maintenance/install-apiserver.md
  calico/maintenance/kubernetes-upgrade.md
  calico/maintenance/monitor/monitor-component-visual.md
  calico/maintenance/operator-migration.md
  calico/reference/etcd-rbac/kubernetes.md
  calico/security/app-layer-policy.md
Labels: release-note-required, docs-not-required

#6316 Add /proc and /var/run/calico to mount-bpffs volumes
  node/pkg/nodeinit/calico-init_linux.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, needs-operator-pr

#6321 felix/bpf: make programming failsafes more verbose
  felix/bpf/failsafes/failsafes.go
  felix/bpf/failsafes/failsafes_map.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6215 generic caching map
  felix/bpf/cachingmap/caching_map.go
  felix/bpf/cachingmap/caching_map_test.go
  felix/bpf/maps.go
  felix/bpf/nat/maps.go
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/lb_src_range_test.go
  felix/bpf/proxy/proxy_bench_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_bench_test.go
  felix/bpf/proxy/syncer_test.go
Labels: docs-not-required, release-note-not-required

#6198 Add counters to bpf dataplane
  calico/maintenance/ebpf/troubleshoot-ebpf.md
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/counters.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/icmp.h
  felix/bpf-gpl/nat.h
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/reasons.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf-gpl/ut/icmp_port_unreachable.c
  felix/bpf-gpl/ut/icmp_too_big.c
  felix/bpf-gpl/ut/icmp_ttl_exceeded.c
  felix/bpf-gpl/ut/ip_dec_ttl.c
  felix/bpf-gpl/ut/nat_encap_test.c
  felix/bpf-gpl/xdp.c
  felix/bpf/bpf.go
  felix/bpf/bpf_syscall.go
  felix/bpf/counters/counters.go
  felix/bpf/counters/counters_test.go
  felix/bpf/counters/map.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/libbpf/libbpf_test.go
  felix/bpf/maps.go
  felix/bpf/mock/map.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/cmd/calico-bpf/commands/counters.go
  felix/cmd/calico-bpf/commands/nat.go
  felix/cmd/calico-bpf/commands/root.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#6295 Update netlink library to pick up fix for unsafe pointer panic.
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#6268 Adding HTTP /terminate path to Dikastes for graceful termination
  app-policy/cmd/dikastes/dikastes.go
  app-policy/cmd/dikastes/dikastes_test.go
  calico/reference/architecture/overview.md
Labels: release-note-required, docs-pr-required

#6334 [release-v3.22] Auto pick #6326: Include hostname configuration from UBI base image where
  apiserver/docker-image/Dockerfile.amd64
  app-policy/Dockerfile.amd64
  calicoctl/Dockerfile.amd64
  cni-plugin/Dockerfile.amd64
  kube-controllers/Dockerfile.amd64
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
  pod2daemon/Dockerfile.amd64
  typha/docker-image/Dockerfile.amd64
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6335 [release-v3.21] Auto pick #6326: Include hostname configuration from UBI base image where
  apiserver/docker-image/Dockerfile.amd64
  app-policy/Dockerfile.amd64
  calicoctl/Dockerfile.amd64
  cni-plugin/Dockerfile.amd64
  kube-controllers/Dockerfile.amd64
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
  pod2daemon/Dockerfile.amd64
  typha/docker-image/Dockerfile.amd64
Labels: release-note-required, docs-not-required

#6283 BPF policy dump
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  felix/bpf/asm/asm.go
  felix/bpf/asm/asm_test.go
  felix/bpf/asm/example_test.go
  felix/bpf/bpf.go
  felix/bpf/bpf_defs.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/polprog/pol_prog_builder_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_policy_dump_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-completed

#6328 Fix for BPF UT map repinning flake
  felix/bpf/maps.go
  felix/bpf/ut/map_upgrade_test.go
Labels: docs-not-required, release-note-not-required

#6339 [release-v3.23] cherry-pick: Add /proc and /var/run/calico to mount-bpffs volumes
  node/pkg/nodeinit/calico-init_linux.go
Labels: docs-not-required, release-note-not-required, needs-operator-pr

#6340 [release-v3.22] cherry-pick: Add /proc and /var/run/calico to mount-bpffs volumes
  node/pkg/nodeinit/calico-init_linux.go
Labels: docs-not-required, release-note-not-required, needs-operator-pr

#6327 bpf fix tunnels default drop
  felix/dataplane/linux/int_dataplane.go
  felix/fv/wireguard_test.go
Labels: release-note-required, docs-not-required

#6298 Fix L3RouteResolver "some nodes share IP address" log messages
  felix/calc/l3_route_resolver.go
  felix/calc/l3_route_resolver_test.go
Labels: release-note-required, docs-not-required

#6347 Update to use ubi-minimal:8.6 base images
  metadata.mk
Labels: release-note-required, docs-not-required

#6349 [release-v3.22] Auto pick #6347: Update to use ubi-minimal:8.6 base images
  metadata.mk
Labels: release-note-required, docs-pr-required

#6356 Try to improve robustness of veth deletion.
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6241 bpf fix attach gap
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/ifstate.h
  felix/bpf-gpl/reasons.h
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/ifstate/map.go
  felix/bpf/maps.go
  felix/bpf/mock/map.go
  felix/bpf/ut/maps_test.go
  felix/cmd/calico-bpf/commands/ifstate.go
  felix/config/config_params.go
  felix/daemon/daemon.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/health_test.go
  felix/fv/infrastructure/felix.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6366 [release-v3.21] Auto pick #6356: Try to improve robustness of veth deletion.
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, docs-pr-required

#6364 [release-v3.23] Auto pick #6356: Try to improve robustness of veth deletion.
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6350 [release-v3.21] Update to use ubi-minimal:8.6 base image
  apiserver/docker-image/Dockerfile.amd64
  app-policy/Dockerfile.amd64
  calicoctl/Dockerfile.amd64
  calicoctl/Dockerfile.arm64
  cni-plugin/Dockerfile.amd64
  kube-controllers/Dockerfile.amd64
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
  node/Dockerfile.arm64
  pod2daemon/Dockerfile.amd64
  typha/docker-image/Dockerfile.amd64
Labels: release-note-required, docs-not-required

#6348 [release-v3.23] Auto pick #6347: Update to use ubi-minimal:8.6 base images
  metadata.mk
Labels: release-note-required, docs-not-required

#6330 [release-v3.23] Auto pick #6295: Update netlink library to pick up fix for unsafe pointer
  go.mod
  go.sum
Labels: release-note-required, docs-not-required, merge-when-ready

#6368 Fix hard-to-hit race in the BPF proxy syncer.
  felix/bpf/proxy/syncer.go
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#6351 [release-v3.23] Auto pick #6298: Fix L3RouteResolver "some nodes share IP address" log
  felix/calc/l3_route_resolver.go
  felix/calc/l3_route_resolver_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6242 Set preserveUnknownFields to false in order to allow updating from th…
  libcalico-go/config.patch
  libcalico-go/config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  libcalico-go/config/crd/crd.projectcalico.org_blockaffinities.yaml
  libcalico-go/config/crd/crd.projectcalico.org_caliconodestatuses.yaml
  libcalico-go/config/crd/crd.projectcalico.org_clusterinformations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  libcalico-go/config/crd/crd.projectcalico.org_globalnetworksets.yaml
  libcalico-go/config/crd/crd.projectcalico.org_hostendpoints.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamblocks.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamconfigs.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamhandles.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ippools.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipreservations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_networkpolicies.yaml
  libcalico-go/config/crd/crd.projectcalico.org_networksets.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_bgpconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_bgppeers.yaml
  manifests/ocp/crd.projectcalico.org_blockaffinities.yaml
  manifests/ocp/crd.projectcalico.org_caliconodestatuses.yaml
  manifests/ocp/crd.projectcalico.org_clusterinformations.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_globalnetworkpolicies.yaml
  manifests/ocp/crd.projectcalico.org_globalnetworksets.yaml
  manifests/ocp/crd.projectcalico.org_hostendpoints.yaml
  manifests/ocp/crd.projectcalico.org_ipamblocks.yaml
  manifests/ocp/crd.projectcalico.org_ipamconfigs.yaml
  manifests/ocp/crd.projectcalico.org_ipamhandles.yaml
  manifests/ocp/crd.projectcalico.org_ippools.yaml
  manifests/ocp/crd.projectcalico.org_ipreservations.yaml
  manifests/ocp/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_networkpolicies.yaml
  manifests/ocp/crd.projectcalico.org_networksets.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6373 Pass proper EndPointType for l3 ipip devices.
  felix/bpf/tc/compiler.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#6374 Add missing DNS libraries to typha image
  typha/docker-image/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#6337 cachingmap pkg
  felix/bpf/maps.go
  felix/bpf/mock/map.go
  felix/bpf/nat/maps.go
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/lb_src_range_test.go
  felix/bpf/proxy/proxy_bench_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_bench_test.go
  felix/bpf/proxy/syncer_test.go
  felix/cachingmap/caching_map.go
  felix/cachingmap/caching_map_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#6379 Tune conntrack timeout behaviour
  felix/fv/connectivity/conncheck.go
  felix/fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#6375 felix/netlinkshim: separate MockNetlinkDataplane and MockWireguard
  felix/netlinkshim/mocknetlink/wireguard.go
Labels: release-note-required, docs-pr-required

#6380 Include UBI repos for CVE fixes
  node/Dockerfile.amd64
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready, squash-commits

#6388 [release-v3.23] Auto pick #6380: Include UBI repos for CVE fixes
  node/Dockerfile.amd64
Labels: release-note-required, cherry-pick-completed, docs-not-required, merge-when-ready, squash-commits

#6389 [release-v3.22] Auto pick #6380: Include UBI repos for CVE fixes
  metadata.mk
  node/Dockerfile.amd64
Labels: release-note-required, cherry-pick-completed, docs-not-required

#6397 Fix serviceaccount RBAC for flannel and etcd mode
  calico/_includes/charts/calico/templates/calico-node-rbac.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#6396 Fix serviceaccount RBAC for flannel and etcd mode
  charts/calico/templates/calico-node-rbac.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#6391 Configure default IP pools `disableBGPExport` via env variables
  node/pkg/lifecycle/startup/startup.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, docs-pr-required

#6360 [release-v3.23] cherry-pick: Sync node manifests with operator ones
  calico/_includes/charts/calico/templates/calico-node.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#6401 Updates for v3.23.3
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.23.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#6402 Updates for v3.22.4
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.22.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#6359 [release-v3.22] cherry-pick: Sync node manifests with operator ones
  calico/_includes/charts/calico/templates/calico-node.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: hold-merge, docs-not-required, release-note-not-required

#6370 chore: add k8s 1.24+ taints
  charts/calico/templates/calico-kube-controllers.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required, merge-when-ready, needs-operator-pr

#6404 Change prog ID to int and define hooks in BPF
  felix/bpf/attach.go
  felix/bpf/bpf.go
  felix/bpf/counters/counters.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/precompilation_test.go
  felix/bpf/xdp/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#6408 Updates for v3.21.6
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.21.6-release-notes.md
  hack/release/RELEASING.md
  hack/release/pkg/builder/commands.go
Labels: docs-not-required, release-note-not-required

#6308 Add command to split IP pools
  calicoctl/calicoctl/commands/common/resources.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/calicoctl/commands/datastore/migrate/import.go
  calicoctl/calicoctl/commands/datastore/migrate/lock.go
  calicoctl/calicoctl/commands/ipam.go
  calicoctl/calicoctl/commands/ipam/split.go
  calicoctl/tests/st/calicoctl/test_ipam_split.py
  calicoctl/tests/st/utils/data.py
  calicoctl/tests/st/utils/utils.py
  libcalico-go/lib/clientv3/ippool.go
Labels: release-note-required, docs-pr-required

#6345 Fix broken link
  kube-controllers/README.md
Labels: release-note-required, docs-pr-required

#6019 libcalico: prettify test outputs
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6354 fix calico_apiserver pod won't start Error: unknown shorthand flag
  apiserver/cmd/apiserver/apiserver.go
Labels: release-note-required, docs-not-required

#6427 Update operator CRDs
  charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/ocp/operator.tigera.io_apiservers_crd.yaml
  manifests/ocp/operator.tigera.io_imagesets_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6426 Update the doc for routeSyncDisabled parameter
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#6280 Fix WorkloadSourceSpoofing validation in felix configuration
  api/pkg/apis/projectcalico/v3/felixconfig.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6415 Remove defaulting for FloatingIPs field - use code default instead
  api/pkg/apis/projectcalico/v3/felixconfig.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#6416 Properly refcount routes, fix accidental withdrawal of routes
  confd/pkg/backends/calico/client.go
  confd/pkg/backends/calico/routes.go
  confd/pkg/backends/calico/routes_test.go
Labels: release-note-required, docs-not-required

#6429 [release-v3.23] Auto pick #6415: Remove defaulting for FloatingIPs field - use code default
  api/pkg/apis/projectcalico/v3/felixconfig.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#6431 Update api reference
  calico/reference/installation/_api.html
  calico/reference/installation/config.json
Labels: docs-not-required, release-note-not-required

#6433 Make sure clean removes bin/ dir
  Makefile
Labels: docs-not-required, release-note-not-required

#6411 Changes to tigera-operator ClusterRole to allow csidrivers actions
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-pr-required, release-note-not-required

#6393 Added IPAMConfiguration to public API
  api/pkg/apis/projectcalico/v3/ipamconfig.go
  api/pkg/apis/projectcalico/v3/register.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_ipamconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_projectcalico_client.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/generated_expansion.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/ipamconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/projectcalico_client.go
  api/pkg/client/informers_generated/externalversions/generic.go
  api/pkg/client/informers_generated/externalversions/projectcalico/v3/interface.go
  api/pkg/client/informers_generated/externalversions/projectcalico/v3/ipamconfiguration.go
  api/pkg/client/listers_generated/projectcalico/v3/expansion_generated.go
  api/pkg/client/listers_generated/projectcalico/v3/ipamconfiguration.go
  api/pkg/openapi/openapi_generated.go
  apiserver/cmd/apiserver/apiserver.go
  apiserver/pkg/registry/projectcalico/ipamconfig/storage.go
  apiserver/pkg/registry/projectcalico/ipamconfig/strategy.go
  apiserver/pkg/registry/projectcalico/rest/storage_calico.go
  apiserver/pkg/storage/calico/converter.go
  apiserver/pkg/storage/calico/ipamconfig_storage.go
  apiserver/pkg/storage/calico/storage_interface.go
  apiserver/test/integration/clientset_test.go
  calicoctl/calicoctl/commands/datastore/migrate/migrateipam_test.go
  charts/calico/templates/calico-node-rbac.yaml
  kube-controllers/pkg/controllers/node/fake_client.go
  libcalico-go/lib/apis/v3/ipam_config.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_config.go
  libcalico-go/lib/backend/model/resource.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/interface.go
  libcalico-go/lib/clientv3/ipamconfig.go
  libcalico-go/lib/clientv3/ipamconfig_e2e_test.go
  libcalico-go/lib/ipam/ipam.go
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/flannel-migration/calico.yaml
  node/pkg/allocateip/allocateip_test.go
  node/tests/k8st/infra/apiserver.yaml
  node/tests/k8st/infra/calico-kdd.yaml
  typha/pkg/daemon/daemon_test.go
Labels: release-note-required, docs-pr-required, needs-operator-pr

#6435 Fix a couple if apiserver CI issues
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  apiserver/Makefile
  node/Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6387 Add IPv6 wireguard to docs
  calico/_includes/content/reqs-sys.md
  calico/about/about-ebpf.md
  calico/maintenance/troubleshoot/troubleshooting.md
  calico/networking/mtu.md
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  calico/reference/resources/node.md
  calico/security/encrypt-cluster-pod-traffic.md
Labels: docs-pr-required, release-note-not-required

#6437 Update CRDs used in manifests
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_caliconodestatuses.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml
  calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_ippools.yaml
Labels: docs-not-required, release-note-not-required

#6377 felix/bpf: service routes maintenance fixed
  felix/cachingmap/caching_map.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/routetable/route_table.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6440 Update redirects on master
  calico/netlify.toml
  hack/release/RELEASING.md
Labels: release-note-required, docs-pr-required

#6444 Add reference doc for IPAMConfiguration
  calico/_data/navbars/reference.yml
  calico/reference/resources/ipamconfig.md
Labels: docs-not-required, release-note-not-required

#6445 Fix up values.yaml comments
  charts/tigera-operator/values.yaml
Labels: docs-not-required, release-note-not-required

#6446 [release-v3.24] Auto pick #6444: Add reference doc for IPAMConfiguration
  calico/_data/navbars/reference.yml
  calico/reference/resources/ipamconfig.md
Labels: docs-not-required, release-note-not-required

#6447 [release-v3.24] Auto pick #6445: Fix up values.yaml comments
  charts/tigera-operator/values.yaml
Labels: docs-not-required, release-note-not-required

#6448 Update OpenShift manifest download instructions
  calico/_includes/content/install-openshift-manifests.md
Labels: release-note-required, docs-pr-required

#6449 [release-v3.24] Automated cherry pick of #6448: Update OpenShift manifest download instructions
  calico/_includes/content/install-openshift-manifests.md
Labels: docs-not-required, release-note-not-required

#6403 Bump dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6363 Add annotations to load, store, jump and call instructions.
  felix/bpf/asm/asm.go
  felix/bpf/asm/helpers.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/cmd/calico-bpf/commands/policy_debug.go
Labels: release-note-required, docs-pr-required

#6371 Enhance XDP programs
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/connect_balancer.c
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/policy.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/xdp.c
  felix/bpf/counters/counters.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/bpf/ut/xdp_test.go
  felix/bpf/xdp/attach.go
  felix/cmd/calico-bpf/commands/counters.go
Labels: release-note-required, hold-merge, docs-not-required

#6453 helm: add support for providing APIServer.Spec
  charts/tigera-operator/templates/crs/custom-resources.yaml
Labels: cherry-pick-completed, docs-not-required, release-note-not-required

#6455 [release-v3.24] Automated cherry pick of #6453: helm: add support for providing APIServer.Spec
  charts/tigera-operator/templates/crs/custom-resources.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6454 Fix validation for maxblocksperhost
  libcalico-go/config/crd/crd.projectcalico.org_ipamconfigs.yaml
  libcalico-go/lib/apis/v3/ipam_config.go
  libcalico-go/lib/clientv3/ipamconfig.go
  libcalico-go/lib/clientv3/ipamconfig_e2e_test.go
  libcalico-go/lib/validator/v3/validator.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_ipamconfigs.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6457 [release-v3.24] Auto pick #6454: Fix validation for maxblocksperhost
  libcalico-go/config/crd/crd.projectcalico.org_ipamconfigs.yaml
  libcalico-go/lib/apis/v3/ipam_config.go
  libcalico-go/lib/clientv3/ipamconfig.go
  libcalico-go/lib/clientv3/ipamconfig_e2e_test.go
  libcalico-go/lib/validator/v3/validator.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_ipamconfigs.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6456 Only publish amd64 apiserver as part of CI
  .semaphore/push-images/apiserver.yml
Labels: docs-not-required, release-note-not-required

#6458 [release-v3.24] Auto pick #6456: Only publish amd64 apiserver as part of CI
  .semaphore/push-images/apiserver.yml
Labels: docs-not-required, release-note-not-required

#6257 fix: ErrorActionPreference must continue for kubectl commands Issue #6127
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6460 Properly round-trip metadata on internal IPAMConfig API
  apiserver/pkg/storage/calico/converter.go
  apiserver/pkg/storage/calico/ipamconfig_storage.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/ipam_config.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/model/ipam_config.go
  libcalico-go/lib/clientv3/ipamconfig_e2e_test.go
  libcalico-go/lib/clientv3/resources.go
Labels: docs-not-required, release-note-not-required

#6452 Bump dependencies - general
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#6468 [release-v3.24] Auto pick #6460: Properly round-trip metadata on internal IPAMConfig API
  apiserver/pkg/storage/calico/converter.go
  apiserver/pkg/storage/calico/ipamconfig_storage.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/ipam_config.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/model/ipam_config.go
  libcalico-go/lib/clientv3/ipamconfig_e2e_test.go
  libcalico-go/lib/clientv3/resources.go
Labels: docs-not-required, release-note-not-required

#6464 windows: create calico-node serviceaccount token secret if it doesn't exist
  calico/getting-started/windows-calico/quickstart.md
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6472 Fix bad merge
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, docs-pr-required
