Repository projectcalico/calico, pull requests merged in 2022-05, with the labels that each got.

#5981 Do full RPF check in BPF
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/rules/static.go
Labels: release-note-required, docs-not-required

#6000 Bump go-build to pick up go version update to 1.17.9
  metadata.mk
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6006 Add reject logic for IPv6 VXLAN IP pools to bird templates
  confd/etc/calico/confd/templates/bird6_ipam.cfg.template
  confd/tests/compiled_templates/mesh/vxlan-always/bird6.cfg
  confd/tests/compiled_templates/mesh/vxlan-always/bird6_ipam.cfg
  confd/tests/mock_data/calicoctl/mesh/vxlan-always/delete.yaml
  confd/tests/mock_data/calicoctl/mesh/vxlan-always/input.yaml
Labels: docs-not-required, release-note-not-required

#6005 Have Felix set VXLAN MTU independently for the IPv4 and IPv6 VXLAN devices
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/fv/containers/containers.go
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/infrastructure/topology.go
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-not-required, release-note-not-required

#6008 Remove separate eBPF EKS docs
  calico/_data/navbars/maintenance.yml
  calico/maintenance/ebpf-and-eks.md
  calico/maintenance/ebpf/ebpf-and-eks.md
  calico/maintenance/ebpf/enabling-bpf.md
Labels: release-note-required, docs-not-required

#6011 [master] Auto pick #6005: Have Felix set VXLAN MTU independently for the IPv4 and IPv6 #6006: Add reject logic for IPv6 VXLAN IP pools to bird templates
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  confd/etc/calico/confd/templates/bird6_ipam.cfg.template
  confd/tests/compiled_templates/mesh/vxlan-always/bird6.cfg
  confd/tests/compiled_templates/mesh/vxlan-always/bird6_ipam.cfg
  confd/tests/mock_data/calicoctl/mesh/vxlan-always/delete.yaml
  confd/tests/mock_data/calicoctl/mesh/vxlan-always/input.yaml
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/fv/containers/containers.go
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/infrastructure/topology.go
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: docs-not-required, release-note-not-required

#6014 Upstreaming route_table changes to OS Felix
  felix/routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#6010 windows: update the backend auto-detection
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6016 Operator needs to list / watch BGP configurations
  calico/_includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6017 [release-v3.23] Auto pick #6016: Operator needs to list / watch BGP configurations
  calico/_includes/charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
Labels: release-note-required, docs-not-required

#6002 Automated cherry pick of #6000: Bump go-build to pick up go version update to 1.17.9
  metadata.mk
Labels: release-note-required, docs-not-required, merge-when-ready

#6023 Fix iptables action for connmark
  felix/iptables/actions.go
  felix/iptables/actions_test.go
Labels: docs-not-required, release-note-not-required

#5985 updates to calico/vpp doc
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6015 [release-v3.23] Automated cherry pick of #6010: windows: update the backend auto-detection
  calico/scripts/install-calico-windows.ps1
Labels: release-note-required, docs-not-required

#5994 Update the EKS DPDK install section in the calico/vpp Getting Started
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: cherry-pick-completed, docs-not-required, release-note-not-required, merge-when-ready

#6026 calico/vpp doc updates for Release v3.23
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6018 Update generated manifests
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  manifests/ocp/tigera-operator/02-role-tigera-operator.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6025 IPv6 VXLAN: Decouple v4 / v6 VXLAN enablement, fix route programming loop for IPv6 blackholes
  felix/calc/calc_graph.go
  felix/calc/calc_graph_fv_test.go
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  felix/calc/event_sequencer.go
  felix/calc/states_for_test.go
  felix/config/config_params.go
  felix/daemon/daemon.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/routetable/route_table.go
  felix/rules/rule_defs.go
Labels: docs-not-required, release-note-not-required

#6028 Automated cherry pick of #6025: Only filter by OIF if an interface index was given
  felix/calc/calc_graph.go
  felix/calc/calc_graph_fv_test.go
  felix/calc/encapsulation_resolver.go
  felix/calc/encapsulation_resolver_test.go
  felix/calc/event_sequencer.go
  felix/calc/states_for_test.go
  felix/config/config_params.go
  felix/daemon/daemon.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/routetable/route_table.go
  felix/rules/rule_defs.go
Labels: docs-not-required, release-note-not-required

#6030 Reduce log level on spammy VXLAN logs
  felix/calc/vxlan_resolver.go
Labels: release-note-required, docs-pr-required

#6031 Automated cherry pick of #6030: Reduce log level on spammy VXLAN logs
  felix/calc/vxlan_resolver.go
Labels: docs-not-required, release-note-not-required

#6034 Fix handling of VXLAN blackhole routes in route table
  felix/routetable/route_table.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6036 Update docs to include VXLAN IPv6 support
  calico/networking/ipv6.md
  calico/networking/mtu.md
  calico/networking/vxlan-ipip.md
  calico/reference/resources/felixconfig.md
Labels: release-note-required, docs-pr-required

#6038 [release-v3.23] Automated cherry pick of #6036: Update docs to include VXLAN IPv6 support
  calico/networking/ipv6.md
  calico/networking/mtu.md
  calico/networking/vxlan-ipip.md
  calico/reference/resources/felixconfig.md
Labels: docs-not-required, release-note-not-required

#6039 windows: add prerequisite for manual install on k8s 1.24+
  calico/getting-started/windows-calico/kubeconfig.md
  calico/getting-started/windows-calico/quickstart.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#6037 Automated cherry pick of #6034: Fix handling of VXLAN blackhole routes in route table
  felix/routetable/route_table.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6040 [master] Automated cherry pick of #6039: windows: add prerequisite for manual install on k8s 1.24+
  calico/getting-started/windows-calico/kubeconfig.md
  calico/getting-started/windows-calico/quickstart.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6033 Add IPv6 VXLAN static rules to iptables
  calico/reference/felix/configuration.md
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/dataplane/driver.go
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: release-note-required, docs-completed, merge-when-ready

#6042 [master] Auto pick #6033: Add static IPv6 VXLAN iptables rules
  calico/reference/felix/configuration.md
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/dataplane/driver.go
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6035 Bumps github.com/prometheus/client_golang from 1.11.0 to 1.12.1.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#6046 bump github.com/distribution/distribution from 2.7.1 to 2.8.1
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6050 Automated cherry pick of #5670: fixed install command for linux kubectl plugin
  calico/maintenance/clis/calicoctl/install.md
Labels: docs-not-required, release-note-not-required

#5993 Fix conversion
  felix/fv/pktgen/pktgen.go
  felix/ipsets/ipset_defs.go
  libcalico-go/lib/testutils/createRule.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#6049 Bump github.com/spf13/viper from 1.8.1 to 1.11.0
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6054 Rebuild felix/node when Cgo files change
  felix/Makefile
  node/Makefile
Labels: docs-not-required, release-note-not-required

#6044 Updates for v3.23.0
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.23.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#6058 Promote v3.23.0 to latest
  calico/AUTHORS.md
  calico/_data/archives.yml
Labels: docs-not-required, release-note-not-required

#6059 Promote v3.23.0 to latest
  calico/_data/archives.yml
Labels: docs-not-required, release-note-not-required

#6056 [release-v3.22] Auto pick #5498: felix/bpf: fix err handling in bpf_program_attach_cgroup
  felix/Makefile
  felix/bpf/libbpf/libbpf_api.h
  felix/fv/bpf_attach_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6061 Fix publishing of debs
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/publish-debs.sh
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#6066 Updates for calico/vpp release v3.23.0
  calico/_config.yml
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: docs-not-required, release-note-not-required

#6064 Add version checking compatibility.
  calicoctl/calicoctl/commands/common/version_mismatch.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6068 Update calico/vpp Getting Started doc to reflect the switch from tech preview to beta
  calico/getting-started/kubernetes/vpp/getting-started.md
Labels: release-note-required, docs-pr-required, docs-not-required, release-note-not-required

#6060 Enable IPv6 on docker for Felix FVs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  felix/.semaphore/create-test-vm
  felix/fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#6073 Skip ipv6 vxlan route update with wireguard manager
  felix/dataplane/linux/wireguard_mgr.go
  felix/routetable/route_table.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6012 Reserve 3 bits in libbpf global flags for EE features
  felix/bpf-gpl/globals.h
  felix/bpf/libbpf/libbpf_stub.go
Labels: docs-not-required, release-note-not-required

#6057 [release-v3.22] Auto pick #5552: felix/bpf: ICMP conntrack fix #5792: felix/bpf: ICMP conntrack fix part 2
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/tc.c
  felix/bpf/ut/icmp_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6076 Add calico-windows and csi to the list of images not managed by the operator
  calico/release-scripts/tests/test_images.py
Labels: docs-not-required, release-note-not-required

#6077 Add calico-windows and csi to the list of images not managed by the operator
  calico/release-scripts/tests/test_images.py
Labels: docs-not-required, release-note-not-required

#6045 Fix bug in handling of RV too old errors
  libcalico-go/lib/backend/k8s/resources/errors.go
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready, squash-commits

#6080 Fix warning message from importing hns.psm1
  calico/getting-started/windows-calico/limitations.md
  calico/getting-started/windows-calico/troubleshoot.md
  calico/scripts/PrepareNode.ps1
  calico/scripts/install-calico-windows.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  node/windows-packaging/CalicoWindows/node/node-service.ps1
Labels: docs-not-required, release-note-not-required

#6081 Merge pull request #6073 from song-jiang/song-fix-ipv6
  felix/dataplane/linux/wireguard_mgr.go
  felix/routetable/route_table.go
Labels: release-note-required, docs-pr-required

#6079 Automated cherry pick of #6045: Fix bug in handling of RV too old errors
  libcalico-go/lib/backend/k8s/resources/errors.go
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, squash-commits

#6071 [release-v3.23] Auto pick #6060: Enable IPv6 on docker for Felix FVs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  felix/.semaphore/create-test-vm
  felix/fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6082 felix/routetable: add target types
  felix/routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#6089 Added a closing tag `%>` to fix broken tab structure
  calico/reference/node/configuration.md
Labels: docs-not-required, release-note-not-required

#6090 [release-v3.23] Added a closing tag `%>` to fix broken tab structure
  calico/reference/node/configuration.md
Labels: release-note-required, docs-pr-required

#6084 Fix image pull secrets in helm chart
  calico/_includes/charts/tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6093 Automated cherry pick of #6084: Fix image pull secrets in helm chart
  calico/_includes/charts/tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6094 Automated cherry pick of #6075: Fixes for flannel migration
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/pkg/controllers/flannelmigration/ipam_migrator.go
  kube-controllers/pkg/controllers/flannelmigration/migration_controller.go
  kube-controllers/pkg/controllers/flannelmigration/network_migrator.go
  kube-controllers/tests/fv/flannel_migration_test.go
Labels: release-note-required, docs-not-required

#6095 Automated cherry pick of #6094: Fixes for flannel migration
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/pkg/controllers/flannelmigration/ipam_migrator.go
  kube-controllers/pkg/controllers/flannelmigration/migration_controller.go
  kube-controllers/pkg/controllers/flannelmigration/network_migrator.go
  kube-controllers/tests/fv/flannel_migration_test.go
Labels: release-note-required, docs-not-required

#6024 Minor BPF UT improvements
  felix/bpf/bpf_syscall.go
  felix/bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#6091 Improve eBPF documentation.
  calico/_data/navbars/maintenance.yml
  calico/_includes/content/ebpf-value.md
  calico/about/about-ebpf.md
  calico/about/about-kubernetes-services.md
  calico/maintenance/ebpf/enabling-bpf.md
  calico/maintenance/ebpf/enabling-ebpf.md
  calico/maintenance/ebpf/index.md
  calico/maintenance/ebpf/install.md
  calico/maintenance/ebpf/troubleshoot-ebpf.md
  calico/maintenance/ebpf/use-cases-ebpf.md
  calico/maintenance/enabling-bpf.md
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
Labels: docs-completed, release-note-not-required

#6109 [v3.23] Upstream eBPF docs improvements
  calico/_data/navbars/maintenance.yml
  calico/_includes/content/ebpf-value.md
  calico/about/about-ebpf.md
  calico/about/about-kubernetes-services.md
  calico/maintenance/ebpf/enabling-bpf.md
  calico/maintenance/ebpf/enabling-ebpf.md
  calico/maintenance/ebpf/index.md
  calico/maintenance/ebpf/install.md
  calico/maintenance/ebpf/troubleshoot-ebpf.md
  calico/maintenance/ebpf/use-cases-ebpf.md
  calico/maintenance/enabling-bpf.md
  calico/maintenance/troubleshoot/troubleshoot-ebpf.md
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
Labels: docs-completed, release-note-not-required

#6110 Updates for v3.23.1
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.23.1-release-notes.md
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
Labels: docs-not-required, release-note-not-required

#6114 Fix openstack build
  hack/release/packaging/utils/create-update-packages.sh
Labels: release-note-required, docs-pr-required

#6116 Automated cherry pick of #6114: Fix openstack build
  hack/release/packaging/utils/create-update-packages.sh
Labels: docs-not-required, release-note-not-required

#6117 Fix helm upgrade instructions so they don't delete other charts
  calico/_includes/charts/tigera-operator/README.md
  calico/maintenance/kubernetes-upgrade.md
Labels: release-note-required, docs-not-required, merge-when-ready

#6118 Automated cherry pick of #6117: Fix helm upgrade instructions so they don't delete other
  calico/_includes/charts/tigera-operator/README.md
  calico/maintenance/kubernetes-upgrade.md
Labels: release-note-required, docs-not-required, merge-when-ready

#6083 Set shopt nullglob in the .semaphore/publish-artifacts script
  .semaphore/publish-artifacts
  cni-plugin/.semaphore/run-win-fv.sh
  felix/.semaphore/publish-artifacts
  felix/.semaphore/run-win-fv
Labels: docs-not-required, release-note-not-required

#6072 Fix a bunch of typos.
  felix/bpf-apache/sockops.c
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6111 Updates for v3.22.3
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.22.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#6102 Update netlink pin
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#6112 Add assertion that generated code is up-to-date as part of CI
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  Makefile
  calico/_plugins/helm.rb
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  manifests/rbac/rbac-kdd-calico.yaml
  manifests/rbac/rbac-kdd-flannel.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#6088 IPv6 VXLAN: Add IPv6 support to flannel migration
  calico/getting-started/kubernetes/flannel/migration-from-flannel.md
  kube-controllers/pkg/controllers/flannelmigration/config.go
  kube-controllers/pkg/controllers/flannelmigration/config_test.go
  kube-controllers/pkg/controllers/flannelmigration/ipam_migrator.go
Labels: release-note-required, docs-completed

#6126 Add badges and quick links to README
  README.md
Labels: docs-not-required, release-note-not-required

#6125 Reduced amount of libraries included in several container images.
  cni-plugin/Dockerfile.amd64
  kube-controllers/Dockerfile.amd64
  typha/docker-image/Dockerfile.amd64
Labels: release-note-required, docs-not-required

#6135 Fixed code block markup
  calico/maintenance/troubleshoot/commands.md
Labels: docs-not-required, release-note-not-required

#6138 [release-v3.22] DOCS-442: Fixed misformatted command (OS)
  calico/maintenance/troubleshoot/commands.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6143 add total table count checks to routeTableRanges option for apiserver
  api/pkg/apis/projectcalico/v3/felixconfig.go
  calico/reference/resources/felixconfig.md
  felix/config/param_types.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#6149 BPF FV Tests: only flush workload conntrack entries
  felix/fv/bpf_test.go
  felix/fv/containers/containers.go
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/workload/workload.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#6147 Clean up the Istio docs a little
  calico/security/app-layer-policy.md
Labels: docs-not-required, release-note-not-required

#6153 Update quickstart.md
  calico/getting-started/kubernetes/quickstart.md
Labels: docs-not-required, release-note-not-required

#6154 Update dependencies
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#6145 Document Wireguard network requirements
  calico/_includes/content/reqs-sys.md
Labels: docs-not-required, release-note-not-required

#6163 Make sure we seed the random number generator (once).
  apiserver/cmd/apiserver/apiserver.go
  apiserver/test/integration/framework.go
  app-policy/cmd/dikastes/dikastes.go
  calicoctl/calicoctl/calicoctl.go
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/plugin/plugin.go
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/win_tests/calico_cni_k8s_windows_test.go
  confd/confd.go
  felix/cmd/calico-bpf/commands/root.go
  felix/daemon/daemon.go
  kube-controllers/cmd/kube-controllers/main.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/seedrng/seed_rng.go
  node/cmd/calico-node/main.go
  typha/cmd/typha-client/typha-client.go
  typha/pkg/daemon/daemon.go
  typha/pkg/discovery/discovery.go
  typha/pkg/discovery/discovery_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#5879 felix/bpf: host does not require CTLB to access cluster IPs
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/list-objs
  felix/bpf-gpl/list-ut-objs
  felix/bpf-gpl/nat.h
  felix/bpf-gpl/skb.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf/conntrack/map.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/compiler.go
  felix/bpf/tc/defs/defs.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/icmp_related_test.go
  felix/bpf/ut/snat_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/infrastructure/topology.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/netlinkshim/netlink.go
  felix/routetable/route_table.go
Labels: release-note-required, docs-not-required
