Repository projectcalico/calico, pull requests merged in 2022-06, with the labels that each got.

#6164 Cherry-pick: Update dependencies
  felix/fv/pktgen/pktgen.go
  felix/ipsets/ipset_defs.go
  felix/k8sfv/pod.go
  go.mod
  go.sum
  libcalico-go/lib/testutils/createRule.go
Labels: release-note-required, docs-not-required

#6187 Call context cancel() func on error
  apiserver/pkg/storage/calico/watcher.go
  libcalico-go/lib/clientv3/resources.go
Labels: release-note-required, docs-pr-required

#6166 fix doc of change-block-size
  calico/networking/change-block-size.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6189 Update release notes to include CVE link
  calico/_includes/release-notes/v3.22.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#6190 Update release notes to include CVE link
  calico/_includes/release-notes/v3.21.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#6191 Update release notes to include CVE link
  _includes/release-notes/v3.20.5-release-notes.md
Labels: docs-not-required, release-note-not-required

#6176 Update image path in app-policy README to use relative path
  app-policy/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6171 Uprev influxdb and gobgp to remove CVE-2018-17572 and PRISMA-2021-0108
  cni-plugin/tests/calico_cni_ipam_test.go
  go.mod
  go.sum
  kube-controllers/tests/fv/fv_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, squash-commits

#6155 Add handle cleanup to calicoctl ipam check/release.
  calicoctl/Makefile
  calicoctl/calicoctl/commands/ipam/check.go
  calicoctl/calicoctl/commands/ipam/release.go
  calicoctl/tests/fv/ipam_test.go
  libcalico-go/lib/ipam/ipam.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6003 Treat pending block affinities as if they did not exist
  confd/pkg/backends/calico/client.go
  confd/tests/compiled_templates/explicit_peering/global-external/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/global-ipv6/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/global/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/keepnexthop-global/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/keepnexthop/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local-as-global/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local-as/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/route_reflector/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/route_reflector_v6_by_ip/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/selectors/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/selectors/step2/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/specific_node/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/bgp-export/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/communities/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/communities/step2/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/hash/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/ipip-always/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/ipip-cross-subnet/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/ipip-off/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step1/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step2/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/password/step3/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/restart-time/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/route-reflector-mesh-enabled/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/static-routes-exclude-node/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/static-routes-exclude-node/step2/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/static-routes-no-ipv4-address/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/static-routes/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/static-routes/step2/bird_aggr.cfg
  confd/tests/compiled_templates/mesh/vxlan-always/bird_aggr.cfg
Labels: release-note-required, docs-not-required

#6184 felix/bpf: API to relax strict RPF to loose
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#6195 cni-plugin: dump stack trace of panic on recover
  cni-plugin/pkg/plugin/plugin.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#6158 helm/tigera-operator: use supplied tolerations/nodeSelector
  charts/tigera-operator/README.md
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#6203 Merge pull request #6201 from song-jiang/song-aks-byo
  calico/getting-started/kubernetes/managed-public-cloud/aks.md
Labels: release-note-required, docs-pr-required

#6207 Re-add accidentally deleted kube-controllers tests
  kube-controllers/Makefile
  kube-controllers/cmd/kube-controllers/fv_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#6202 Fix an incorrect recent spelling "correction"
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#6214 Specify lib and lib64 lib dependencies for apiserver
  apiserver/docker-image/Dockerfile.amd64
  apiserver/docker-image/Dockerfile.arm64
Labels: release-note-required, docs-pr-required

#6181 Infra for upgrading map from one version to the other.
  felix/.gitignore
  felix/bpf/bpfmap/upgrade/upgrade.go
  felix/bpf/maps.go
  felix/bpf/mock/multiversion/map.go
  felix/bpf/mock/multiversion/v2/map.go
  felix/bpf/mock/multiversion/v3/map.go
  felix/bpf/mock/multiversion/v4/map.go
  felix/bpf/mock/multiversion/v5/map.go
  felix/bpf/ut/map_upgrade_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#6217 Trim lib lib64 cni-plugin
  cni-plugin/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#6220 Fixes ICMP port zeroing backport
  felix/bpf-gpl/conntrack.h
Labels: release-note-required, docs-not-required

#6221 EE->OSS cherrypick - Operator CRD sync
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#5935 Enable E2e test arm64
  lib.Makefile
  node/Makefile
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
Labels: docs-not-required, release-note-not-required

#6218 [release-v3.23] Auto pick #5910: Use TokenRequest API instead of calico-nodes service account
  app-policy/config/install/05-calico.yaml
  calico/_includes/charts/calico/templates/calico-node-rbac.yaml
  calico/getting-started/kubernetes/hardway/install-node.md
  cni-plugin/Makefile
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/install/install_test.go
  node/Makefile
  node/pkg/cni/token_watch.go
  node/pkg/cni/token_watch_suite_test.go
  node/pkg/cni/token_watch_test.go
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required

#6131 build with go 1.18
  api/pkg/client/clientset_generated/clientset/clientset.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  confd/pkg/backends/calico/client.go
  confd/tests/test_suite_common.sh
  felix/calc/l3_route_resolver.go
  go.mod
  go.sum
  kube-controllers/pkg/config/runconfig.go
  kube-controllers/tests/testutils/flannel_migration_utils.go
  metadata.mk
  typha/pkg/syncproto/sync_proto_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6224 Reduce log level for warning when no IPs are detected
  node/pkg/lifecycle/startup/startup.go
Labels: docs-not-required, release-note-not-required

#6213 Wireguard fixes v3.23
  felix/dataplane/linux/wireguard_mgr.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/routetable/route_table_test.go
  felix/wireguard/wireguard.go
  felix/wireguard/wireguard_test.go
  node/pkg/allocateip/allocateip.go
  node/pkg/allocateip/allocateip_test.go
Labels: release-note-required, docs-not-required

#6212 Wireguard fixes v3.22
  felix/dataplane/linux/wireguard_mgr.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/routetable/route_table_test.go
  felix/wireguard/wireguard.go
  felix/wireguard/wireguard_test.go
  node/pkg/allocateip/allocateip.go
  node/pkg/allocateip/allocateip_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6228 Fix IP address truncation when using autodetection mode "k8s-internal-ip"
  node/pkg/lifecycle/startup/autodetection/autodetection_methods.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#6211 Support for custom pod labels/annotations for tigera-operator chart
  charts/tigera-operator/README.md
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required

#6225 Trim /lib64 and /lib in typha, dikastes, flexvol, kube-controllers, flannel-migration controller images
  app-policy/Dockerfile.amd64
  kube-controllers/Dockerfile.amd64
  kube-controllers/Makefile
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
  pod2daemon/Dockerfile.amd64
  typha/docker-image/Dockerfile.amd64
Labels: release-note-required, docs-not-required

#6097 Update to Kubernetes v1.24.0
  apiserver/pkg/storage/calico/policy_storage_test.go
  apiserver/pkg/storage/calico/resource.go
  calicoctl/calicoctl/commands/common/resources.go
  calicoctl/calicoctl/commands/convert.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  felix/bpf/proxy/syncer.go
  go.mod
  go.sum
  libcalico-go/lib/testutils/syncertester.go
Labels: release-note-required, docs-not-required

#6233 Fix IP address truncation when using autodetection mode "k8s-internal-ip"
  node/pkg/lifecycle/startup/autodetection/autodetection_methods.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6234 Fix IP address truncation when using autodetection mode "k8s-internal-ip"
  node/pkg/lifecycle/startup/autodetection/autodetection_methods.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6236 Fix ut.test Makefile target in kube-controllers
  kube-controllers/Makefile
Labels: docs-not-required, release-note-not-required

#6229 Update default flannel ds name in migration controller
  calico/getting-started/kubernetes/flannel/migration-from-flannel.md
  kube-controllers/pkg/controllers/flannelmigration/config.go
  kube-controllers/pkg/controllers/flannelmigration/config_test.go
  kube-controllers/pkg/controllers/flannelmigration/flannel_migration_fv_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6223 conntrack map upgrade
  felix/bpf-gpl/conntrack_types.h
  felix/bpf/conntrack/conntrack_test.go
  felix/bpf/conntrack/map.go
  felix/bpf/conntrack/v2/map.go
  felix/bpf/conntrack/v3/map.go
  felix/cmd/calico-bpf/commands/conntrack.go
  felix/fv/bpf_map_upgrade_test.go
Labels: release-note-required, docs-not-required

#6237 Fix AKS BYO with pod cidr option
  calico/getting-started/kubernetes/managed-public-cloud/aks.md
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#6249 Introduce new Pod annotation for assigning specified MAC address to container veth
  calico/_data/navbars/networking.yml
  calico/networking/pod-mac-address.md
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
  cni-plugin/tests/calico_cni_k8s_test.go
Labels: release-note-required, docs-completed

#6245 fix: calico only distribute routes to a Pod if its IP address falls w…
  calico/reference/cni-plugin/configuration.md
Labels: release-note-required, docs-completed, merge-when-ready

#6259 revert changes to calico-node.yaml template
  calico/_includes/charts/calico/templates/calico-node.yaml
Labels: docs-not-required, release-note-not-required

#6264 update ipset for arm64
  node/Dockerfile.arm64
Labels: release-note-required, docs-not-required

#6262 update ipset for arm64
  node/Dockerfile.arm64
Labels: release-note-required, docs-not-required

#6263 update ipset for arm64
  node/Dockerfile.arm64
Labels: release-note-required, docs-not-required

#6274 Updates for v3.23.2
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.23.2-release-notes.md
Labels: docs-not-required, release-note-not-required

#6270 Remove remaining PodSecurityPolicies (removed in k8s 1.25)
  charts/tigera-operator/templates/tigera-operator/02-podsecuritypolicy-tigera-operator.yaml
  manifests/apiserver.yaml
  manifests/tigera-operator.yaml
  node/tests/k8st/infra/apiserver.yaml
  node/tests/k8st/infra/metallb.yaml
Labels: release-note-required, docs-not-required

#6284 Node - trim python from lib and usr lib
  node/clean-up-filesystem.sh
Labels: docs-not-required, release-note-not-required

#5454 Added dummy routetable for network policy only mode
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/routetable/dummy_table.go
  felix/wireguard/config.go
  felix/wireguard/route_table.go
  felix/wireguard/wireguard.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: release-note-required, docs-pr-required

#6250 Add input filter rule for wireguard
  felix/dataplane/driver.go
  felix/fv/wireguard_test.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: release-note-required, docs-not-required

#6290 routeSyncDisabled regenerate
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#6288 Add missing permissions for certificates.k8s.io api
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#6297 [release-v3.23] Auto pick #6296: Fix namespacing of endpoint slice objects
  libcalico-go/lib/namespace/namespace_suite_test.go
  libcalico-go/lib/namespace/resource.go
  libcalico-go/lib/namespace/resource_test.go
Labels: release-note-required, docs-pr-required

#6296 Fix namespacing of endpoint slice objects
  libcalico-go/lib/namespace/namespace_suite_test.go
  libcalico-go/lib/namespace/resource.go
  libcalico-go/lib/namespace/resource_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#6300 felix/fv: fix flake in BPF affinity tests
  felix/cmd/calico-bpf/commands/nat.go
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#6289 felix/bpf: map upgrades do not need caching map
  felix/bpf/bpfmap/upgrade/upgrade.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required
