Repository projectcalico/calico, pull requests merged in 2023-04, with the labels that each got.

#7411 [Release 3.24] Update dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7515 [release-v3.25] Auto pick #7294: Clean up deprecated+removed cmd line flags
  app-policy/config/cluster/master-config.yaml
  app-policy/config/cluster/node-config.yaml
  calico/scripts/PrepareNode.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
Labels: release-note-required, docs-not-required

#7510 Remove unused libraries from node
  node/clean-up-filesystem.sh
Labels: release-note-required, docs-pr-required

#7518 [BPF] BPFEnforceRPF is Loose by default
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/config/config_params.go
  felix/fv/bpf_test.go
  felix/fv/rpf_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, cherry-pick-candidate, docs-pr-required

#7537 fix error formatted
  node/pkg/allocateip/allocateip.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7536 [FIX] defaultRuleRenderer is used incorrectly in linux.InternalDataplane
  felix/dataplane/linux/int_dataplane.go
  felix/iptables/actions.go
  felix/rules/dispatch.go
  felix/rules/endpoints.go
  felix/rules/policy.go
  felix/rules/rule_defs.go
  felix/rules/static.go
Labels: docs-not-required, release-note-not-required

#7540 Merge pull request #7433 from dilyevsky/kube-controllers-node-out-of-sync
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#7541 [release-v3.23] Auto pick #7540: Merge pull request #7433 from
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#7465 Verify cluster CRDs contain all expected CRD set
  kube-controllers/pkg/controllers/node/metrics_fv_test.go
Labels: release-note-required, docs-pr-required

#7525 Fix static-check with golanglint-ci v1.52.2
  cni-plugin/internal/pkg/testutils/utils_linux.go
  typha/pkg/promutils/registration.go
Labels: release-note-required, docs-pr-required

#7549 Add retry to git fetch commands for semaphore builds
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/packaging.yaml
  .semaphore/push-images/typha.yml
  .semaphore/release/release.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  cni-plugin/.semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#7559 fix wrong link.
  cni-plugin/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7562 Update pin to fixed calico/bird image
  metadata.mk
Labels: release-note-required, docs-not-required

#7563 [release-v3.25] Auto pick #7562: Update pin to fixed calico/bird image
  metadata.mk
Labels: release-note-required, docs-not-required

#7564 [release-v3.24] Auto pick #7562: Update pin to fixed calico/bird image
  metadata.mk
Labels: release-note-required, docs-not-required

#7565 [release-v3.23] Auto pick #7562: Update pin to fixed calico/bird image
  metadata.mk
Labels: release-note-required, docs-not-required

#7566 [release-v3.22] Auto pick #7562: Update pin to fixed calico/bird image
  metadata.mk
Labels: release-note-required, docs-not-required

#7546 Upgrade k8s dependencies to v1.26 release train
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
  apiserver/Makefile
  apiserver/cmd/apiserver/server/options.go
  apiserver/docker-image/Dockerfile.amd64
  apiserver/docker-image/Dockerfile.arm64
  apiserver/docker-image/Dockerfile.ppc64le
  apiserver/docker-image/Dockerfile.s390x
  apiserver/test/integration.sh
  app-policy/uds/uds.go
  cni-plugin/pkg/dataplane/grpc/grpc_dataplane.go
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  felix/bpf/proxy/lb_src_range_test.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_bench_test.go
  felix/bpf/proxy/syncer_test.go
  felix/bpf/proxy/topology.go
  felix/bpf/proxy/topology_test.go
  felix/fv/policysync_test.go
  felix/policysync/processor_test.go
  go.mod
  go.sum
  kube-controllers/Dockerfile.amd64
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/ipam_test.go
  kube-controllers/pkg/controllers/pod/pod_controller.go
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  pod2daemon/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#7535 update calicovpp version to v3.25.1
  calico/_config.yml
Labels: release-note-required, docs-not-required, merge-when-ready

#7577 [BPF] remove counters when a device goes down
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
Labels: docs-not-required, release-note-not-required

#7572 Run kind-cluster tests on cloud VMs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  .semaphore/vms/clean-up-vms
  .semaphore/vms/create-test-vm
  .semaphore/vms/create-test-vms
  .semaphore/vms/on-test-vm
  .semaphore/vms/publish-artifacts
  .semaphore/vms/run-tests-on-vms
  .semaphore/vms/scp-from-test-vm
  .semaphore/vms/vm-tests-common.sh
  node/Makefile
  node/tests/k8st/test_base.py
  node/tests/k8st/tests/test_bgp_filter.py
  node/tests/k8st/utils/utils.py
  node/tests/st/bgp/test_ipip.py
  node/tests/st/utils/utils.py
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7516 Update golang to 1.20.3
  api/pkg/client/clientset_generated/clientset/clientset.go
  api/pkg/client/informers_generated/externalversions/factory.go
  cni-plugin/Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7575 Fix divide by zero when shutting down Typha if it has no clients.
  typha/fv-tests/server_test.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-not-required, merge-when-ready

#7250 formate bash shell blank align.
  pod2daemon/flexvol/docker/clean.sh
Labels: docs-not-required, release-note-not-required

#7237 Change Mkdir to MkdirAll
  calicoctl/calicoctl/commands/node/diags.go
Labels: release-note-required, docs-pr-required

#7283 Link to more detailed calicoctl install instructions e.g. for K8s
  calicoctl/README.md
Labels: docs-not-required, release-note-not-required

#7480 Explicitly set kubeletVolumePluginPath in tigera-operator Installatio…
  charts/tigera-operator/README.md
  charts/tigera-operator/templates/crs/custom-resources.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-completed

#7586 Statically link csi-node-driver-registrar when using Tigera build cmd
  pod2daemon/Makefile
Labels: release-note-required, docs-not-required

#7587 [release-v3.26] Auto pick #7586: Statically link csi-node-driver-registrar when using Tigera
  pod2daemon/Makefile
Labels: release-note-required, docs-not-required, merge-when-ready

#7460 Automated cherry pick of #7111: Fix the auto iptables detection if ip_tables.ko preloaded on RHEL/CentOS 8
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#7585 [v3.26] Fix typha divide by 0
  typha/fv-tests/server_test.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-not-required

#7592 [Release 3.25] Update dependencies (cherry-pick 7591)
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7601 [Release 3.26] Update dependencies (cherry-pick 7591)
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7593 [Release 3.24] Update dependencies (cherry-pick 7591)
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7591 Update dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7609 Update registrar tag
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7611 [Release 3.25] Update registrar tag (Cherry-pick 7609)
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7610 [Release 3.26] Update registrar tag (Cherry-pick 7609)
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required
