Repository projectcalico/calico, pull requests merged in 2023-03, with the labels that each got.

#7406 Fix concurrent map race in wireguard tests.
  felix/netlinkshim/mocknetlink/netlink.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#7407 [v3.25] Fix concurrent map race in wireguard tests.
  felix/netlinkshim/mocknetlink/netlink.go
Labels: docs-not-required, release-note-not-required

#7413 Update CNI dependency binaries to go 1.19.6
  cni-plugin/Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7418 Update ginkgo to fix conformance test issues
  e2e/cmd/e2e_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7425 fix: app-policy goboring build
  app-policy/Makefile
Labels: release-note-required, docs-pr-required

#7386 [BPF] Extend syncer to include endpoint slices at Terminating status
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_test.go
Labels: kind/bug, docs-not-required, release-note-not-required, area/bpf

#7432 Automated cherry pick of #7425: fix: app-policy goboring build only for amd64
  app-policy/Makefile
Labels: docs-not-required, release-note-not-required

#7436 Fix log spam from interface monitor.
  felix/ifacemonitor/iface_monitor.go
Labels: docs-not-required, release-note-not-required

#7438 Update node-driver-registrar
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7439 Update node-driver-registrar
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7111 Fix the auto iptables detection if ip_tables.ko preloaded on RHEL/CentOS 8
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
Labels: release-note-required, docs-not-required

#7401 Update the K8s versions
  apiserver/pkg/registry/projectcalico/kubecontrollersconfig/storage.go
  apiserver/pkg/storage/calico/api_object_versioner.go
  apiserver/pkg/storage/calico/bgpConfiguration_storage.go
  apiserver/pkg/storage/calico/bgpPeer_storage.go
  apiserver/pkg/storage/calico/bgpfilter_storage.go
  apiserver/pkg/storage/calico/blockAffinity_storage.go
  apiserver/pkg/storage/calico/caliconodestatus_storage.go
  apiserver/pkg/storage/calico/clusterInformation_storage.go
  apiserver/pkg/storage/calico/felixConfig_storage.go
  apiserver/pkg/storage/calico/globalNetworkPolicy_storage.go
  apiserver/pkg/storage/calico/globalNetworkSet_storage.go
  apiserver/pkg/storage/calico/hostEndpoint_storage.go
  apiserver/pkg/storage/calico/ipamconfig_storage.go
  apiserver/pkg/storage/calico/ippool_storage.go
  apiserver/pkg/storage/calico/ipreservation_storage.go
  apiserver/pkg/storage/calico/kubeControllersConfig_storage.go
  apiserver/pkg/storage/calico/networkSet_storage.go
  apiserver/pkg/storage/calico/policy_storage.go
  apiserver/pkg/storage/calico/profile_storage.go
  calicoctl/tests/st/utils/data.py
  e2e/cmd/e2e_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7451 Fix flake in UDP spoof tests; wait for BPF programs to be ready.
  felix/fv/bpf_test.go
  felix/fv/containers/containers.go
Labels: docs-not-required, release-note-not-required

#7452 Fix yaml linting in manifests
  charts/calico/templates/calico-node-rbac.yaml
  manifests/alp/istio-inject-configmap-1.1.0.yaml
  manifests/alp/istio-inject-configmap-1.1.1.yaml
  manifests/alp/istio-inject-configmap-1.1.10.yaml
  manifests/alp/istio-inject-configmap-1.1.11.yaml
  manifests/alp/istio-inject-configmap-1.1.12.yaml
  manifests/alp/istio-inject-configmap-1.1.13.yaml
  manifests/alp/istio-inject-configmap-1.1.14.yaml
  manifests/alp/istio-inject-configmap-1.1.15.yaml
  manifests/alp/istio-inject-configmap-1.1.16.yaml
  manifests/alp/istio-inject-configmap-1.1.17.yaml
  manifests/alp/istio-inject-configmap-1.1.2.yaml
  manifests/alp/istio-inject-configmap-1.1.3.yaml
  manifests/alp/istio-inject-configmap-1.1.4.yaml
  manifests/alp/istio-inject-configmap-1.1.5.yaml
  manifests/alp/istio-inject-configmap-1.1.6.yaml
  manifests/alp/istio-inject-configmap-1.1.7.yaml
  manifests/alp/istio-inject-configmap-1.1.8.yaml
  manifests/alp/istio-inject-configmap-1.1.9.yaml
  manifests/alp/istio-inject-configmap-1.2.0.yaml
  manifests/alp/istio-inject-configmap-1.2.1.yaml
  manifests/alp/istio-inject-configmap-1.2.2.yaml
  manifests/alp/istio-inject-configmap-1.2.3.yaml
  manifests/alp/istio-inject-configmap-1.2.4.yaml
  manifests/alp/istio-inject-configmap-1.2.5.yaml
  manifests/alp/istio-inject-configmap-1.2.6.yaml
  manifests/alp/istio-inject-configmap-1.2.7.yaml
  manifests/alp/istio-inject-configmap-1.2.8.yaml
  manifests/alp/istio-inject-configmap-1.2.9.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/custom-resources.yaml
  manifests/flannel-migration/calico.yaml
  manifests/grafana-dashboards.yaml
  manifests/windows-kube-proxy.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#7455 Update golang to 1.19.7
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7454 [Release 3.25] Update golang to 1.19.7
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7456 Update k8s version and libs in the API
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#7457 Update k8s version and libs in the API
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#7246 update helm version to match k8s 1.24
  lib.Makefile
Labels: release-note-required, docs-pr-required

#7464 Flannel v0.21.3
  charts/calico/values.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
Labels: docs-not-required, release-note-not-required

#7173 Fix columns in Felix wireguard documentation
  calico/reference/felix/configuration.md
Labels: docs-not-required, release-note-not-required

#7453 Validate RouteReflector IP
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/node_test.go
  libcalico-go/lib/validator/v3/validator.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7466 [BPF] reserve some tc global flags
  felix/bpf-gpl/globals.h
Labels: release-note-required, docs-pr-required, merge-when-ready

#7335 [BPF] Decorate import "C" with CFLAGS and LDFLAGS for libbpf consumption
  felix/bpf/libbpf/libbpf.go
Labels: docs-not-required, release-note-not-required

#7467 [FV] bpf does not support ipv6
  felix/fv/infrastructure/topology.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#7475 Fix feature detection for netlink strict mode.
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
  felix/ifacemonitor/netlink_real.go
  felix/netlinkshim/handlemgr/handle_manager.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#7471 Update tigera-operator installation CRD
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#7476 [v3.25] Fix feature detection for netlink strict mode.
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
  felix/ifacemonitor/netlink_real.go
  felix/netlinkshim/handlemgr/handle_manager.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#7477 Split feature detector by OS. Build a dummy version on Windows.
  felix/environment/feature_detect_common.go
  felix/environment/feature_detect_linux.go
  felix/environment/feature_detect_windows.go
Labels: docs-not-required, release-note-not-required

#7468 Felix: int dataplane main loop cleanups
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/ifacemonitor/iface_monitor.go
  felix/ifacemonitor/ifacemonitor_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7485 Use quay repo for metallb image
  node/tests/k8st/infra/metallb.yaml
Labels: docs-not-required, release-note-not-required

#7484 [BPF] inc jump maps version after increasing size
  felix/bpf-gpl/jump.h
  felix/bpf/maps/maps.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#7483 Merge pull request #7453 from sridhartigera/route-reflector
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/node_test.go
  libcalico-go/lib/validator/v3/validator.go
Labels: release-note-required, docs-pr-required

#7482 Merge pull request #7453 from sridhartigera/route-reflector
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/node_test.go
  libcalico-go/lib/validator/v3/validator.go
Labels: release-note-required, docs-pr-required

#7487 [release-v3.25] Auto pick #7484: inc jump maps version after increasing size
  felix/bpf-gpl/jump.h
  felix/bpf/bpf.go
  felix/bpf/jump/map.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#7449 Tweak bpf Ubuntu image
  felix/.semaphore/create-test-vm
Labels: release-note-required, docs-pr-required, merge-when-ready

#7491 [release-v3.25] Auto pick #7485: Use quay repo for metallb image
  node/tests/k8st/infra/metallb.yaml
Labels: docs-not-required, release-note-not-required

#7493 [release-v3.23] Auto pick #7485: Use quay repo for metallb image
  node/tests/k8st/infra/metallb.yaml
Labels: docs-not-required, release-note-not-required

#7494 [release-v3.22] Auto pick #7485: Use quay repo for metallb image
  node/tests/k8st/infra/metallb.yaml
Labels: docs-not-required, release-note-not-required

#7495 [release-v3.21] Auto pick #7485: Use quay repo for metallb image
  node/tests/k8st/infra/metallb.yaml
Labels: docs-not-required, release-note-not-required

#7492 [release-v3.24] Auto pick #7485: Use quay repo for metallb image
  node/tests/k8st/infra/metallb.yaml
Labels: docs-not-required, release-note-not-required

#7496 [BPF] use libbpf to (re)pin maps
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/maps/maps.go
  felix/bpf/ut/map_upgrade_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7106 Separate calico-node and calico-cni-plugin service accounts
  charts/calico/templates/calico-node-rbac.yaml
  charts/calico/templates/calico-node.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/pkg/cni/token_watch.go
  node/pkg/cni/token_watch_test.go
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required

#6657 Some improved logging in IPAM GC code
  kube-controllers/pkg/controllers/node/ipam.go
  libcalico-go/lib/ipam/ipam_block.go
  libcalico-go/lib/ipam/ipam_block_reader_writer.go
Labels: docs-not-required, release-note-not-required

#7289 Update windows scripts for new docs
  hack/postrelease/test_windows_artifacts.py
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#7504 [BPF] polprog.NewBuilder takes options
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/polprog/pol_prog_builder_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7509 [BPF/fv] fix a flake in Felix bpf test counters
  felix/fv/bpf_counters_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7506 Restores LICENSE
  LICENSE.md
  README.md
Labels: docs-not-required, release-note-not-required

#7514 Use the correct service account for tests
  cni-plugin/pkg/install/install_test.go
Labels: docs-not-required, release-note-not-required

#7408 Removes the remaining docs files
  calico/networking/advertise-service-ips.md
  calico/networking/bgp.md
  calico/networking/ipv6.md
  calico/reference/felix/configuration.md
  calico/reference/resources/bgpfilter.md
  calico/reference/resources/bgppeer.md
  calico/reference/resources/felixconfig.md
  calico/scripts/PrepareNode.ps1
Labels: docs-not-required, release-note-not-required

#7352 Fix the node-driver-registrar binary format for archs
  pod2daemon/Makefile
Labels: release-note-required, docs-pr-required

#7473 DOCS-1347: Fixing dead links in manifests
  calico/reference/kube-controllers/configuration.md
  charts/calico/templates/calico-etcd-secrets.yaml
  charts/calico/templates/calico-node-rbac.yaml
  manifests/calico-etcd.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
Labels: docs-not-required, release-note-not-required

#7419 Wait for server shutdown in app-policy dikastes UT
  app-policy/cmd/dikastes/dikastes_test.go
Labels: docs-not-required, release-note-not-required

#7343 Updated base image from debian slim to UBI for cni to fix s390x build issue.
  cni-plugin/Dockerfile.s390x
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7521 bpf counters fv flake fix
  felix/fv/bpf_counters_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#7444 Build v3.25.1
  .semaphore/release/release.yml
  Makefile
  calico/_data/versions.yml
  calico/_includes/release-notes/v3.25.1-release-notes.md
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  hack/release/check_release_status.py
  hack/release/generate-release-notes.py
  hack/release/pkg/builder/builder.go
  hack/release/pkg/builder/commands.go
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico-windows-bgp.yaml
  manifests/calico-windows-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
  release-notes
Labels: docs-not-required, release-note-not-required
