Repository projectcalico/calico, pull requests merged in 2023-02, with the labels that each got.

#5735 Add support for REJECT instead of DROP as deny action
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calico/reference/resources/felixconfig.md
  calicoctl/calicoctl/commands/crds/crds.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/calicoctl/commands/datastore/migrate/export_test.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/int_dataplane_test.go
  felix/rules/dispatch.go
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  felix/rules/policy.go
  felix/rules/policy_test.go
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-completed

#7249 s390x: enbale apiserver s390x build
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  apiserver/Makefile
Labels: release-note-required, docs-pr-required

#7267 Add logic to release to build a metadata yaml file
  hack/release/cmd/main.go
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#7263 Avoid logging WARNINGs about readiness during initial startup
  felix/.semaphore/create-test-vm
  libcalico-go/lib/health/health.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#7276 Remove unnecessary (for now) creation of docker directory for UT tests
  felix/.semaphore/create-test-vm
Labels: docs-not-required, release-note-not-required

#7277 Pin docker version in test VMs to the last working version
  felix/.semaphore/create-test-vm
Labels: docs-not-required, release-note-not-required

#7278 Pin docker version in test VMs to the last working version
  felix/.semaphore/create-test-vm
Labels: docs-not-required, release-note-not-required

#7279 Pin docker version in test VMs to the last working version
  felix/.semaphore/create-test-vm
Labels: docs-not-required, release-note-not-required

#7280 Pin docker version in test VMs to the last working version
  felix/.semaphore/create-test-vm
Labels: docs-not-required, release-note-not-required

#7195 doc: VXLAN in IPv6 is only supported for kernel versions >= 3.12
  calico/networking/ipv6.md
Labels: release-note-required, docs-pr-required

#7168 DOCS-994: Adds redirect rules for docs.projectcalico.org
  calico/netlify/_redirects_v3.21
  calico/robots.txt
Labels: hold-merge, docs-not-required, release-note-not-required

#7293 DOCS-994: Adds redirects for projectcalico.docs.tigera.io
  calico/netlify/_redirects
  calico/robots.txt
Labels: release-note-required, docs-pr-required

#7295 Troubleshooting redirect fix
  calico/netlify.toml
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7296 Troubleshooting redirects again
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7297 Fixes redirect for high-ranking search result
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7301 [DOCS] Quick fix for charts proxy
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7302 [DOCS] Redirects fix troublshooting
  calico/netlify.toml
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7303 Adds redirect rule to prevent robots.txt from redirecting to docs.tigera.io
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7304 Fix: Project Calico readme icon
  README.md
Labels: release-note-required, docs-pr-required

#7309 Remove docs CI from semaphore config
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required

#7310 [release-v3.25] Auto pick #7309: Remove docs CI from semaphore config
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required

#7311 [release-v3.24] Auto pick #7309: Remove docs CI from semaphore config
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required

#7313 [release-v3.25] Auto pick #7267: Add logic to release to build a metadata yaml file
  hack/release/cmd/main.go
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#7314 [release-v3.24] Auto pick #7267: Add logic to release to build a metadata yaml file
  hack/release/cmd/main.go
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#7307 DevStack test: address flakes when cloning OpenStack repos
  networking-calico/devstack/bootstrap.sh
Labels: docs-not-required, release-note-not-required

#7317 Redirect fix
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7291 Fix UID for v3 resources in KDD mode
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: release-note-required, docs-not-required, merge-when-ready

#7318 Tests forced proxy for v3.23
  calico/netlify.toml
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7319 Fixes redirects for docs.projectcalico.org
  calico/netlify.toml
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7321 Adding later proxies to redirects for docs.projectcalicco
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7322 Fixes blanket redirect
  calico/netlify.toml
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7323 [redirects test] Testing proxy structure for 3.23 manifests
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7324 [redirects test] rm /* to test proxies
  calico/netlify.toml
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7316 Fix some BPF FV flakes
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  felix/bpf/maps/maps.go
  felix/fv/bpf_attach_test.go
Labels: release-note-required, docs-not-required

#7325 [redirects test] Returning blanket redirect
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7327 [test redirects] tests forced proxies for v3.23
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7328 [test redirects] changes blanket redirect rule
  calico/netlify/_redirects_v3.21
Labels: release-note-required, docs-pr-required

#7329 Updates redirect rule for app-layer-policy
  calico/netlify/_redirects
Labels: release-note-required, docs-pr-required

#7320 Fix manifests URL used by Windows FV; also pull in Windows FV testing code from tigera/process
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  cni-plugin/.semaphore/cleanup.yml
  cni-plugin/.semaphore/run-win-fv.sh
  cni-plugin/.semaphore/semaphore.yml
  felix/.semaphore/run-win-fv
  felix/.semaphore/semaphore.yml
  process/testing/winfv/README.md
  process/testing/winfv/cloudformation-simple-vpc.json
  process/testing/winfv/cloudformation-windows-server.json
  process/testing/winfv/create_kubeadm_cluster.sh
  process/testing/winfv/infra/client.yaml
  process/testing/winfv/infra/ee/role.yaml
  process/testing/winfv/infra/egress.yaml
  process/testing/winfv/infra/ingress.yaml
  process/testing/winfv/infra/installation-bgp.yaml
  process/testing/winfv/infra/installation-vxlan.yaml
  process/testing/winfv/infra/nginx.yaml
  process/testing/winfv/infra/porter.yaml
  process/testing/winfv/infra/setup.sh
  process/testing/winfv/restart-felix.ps1
  process/testing/winfv/run-fv-cni-plugin.ps1
  process/testing/winfv/run-fv-full.ps1
  process/testing/winfv/setup-fv.sh
Labels: docs-not-required, release-note-not-required

#7315 s390x: fix image mislabel in cni, typha and kube-controllers
  lib.Makefile
Labels: release-note-required, docs-not-required, merge-when-ready

#7334 Deflake route reflector test. Allow some dropped packets.
  node/tests/st/bgp/test_switch_route_reflector.py
Labels: release-note-required, docs-pr-required

#7326 Felix FVs: fix SCTP tests.
  felix/fv/connectivity/conncheck.go
  felix/fv/containers/containers.go
  felix/fv/workload/workload.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#7333 s390x: fix image mislabel in cni, typha and kube-controllers
  lib.Makefile
Labels: release-note-required, docs-not-required

#7342 Felix FV: Avoid reusing connections when probing the metrics port.
  felix/fv/metrics/metrics.go
Labels: docs-not-required, release-note-not-required

#7294 Clean up deprecated+removed cmd line flags
  app-policy/config/cluster/master-config.yaml
  app-policy/config/cluster/node-config.yaml
  calico/scripts/PrepareNode.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
Labels: release-note-required, docs-not-required

#7346 Felix FV: fix flakes caused by unexpected felix restarts
  felix/fv/bpf_test.go
  felix/fv/rpf_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#7353 Revert "Fix UID for v3 resources in KDD mode"
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: release-note-required, docs-pr-required

#7355 Remove a debug leftover
  felix/bpf/ut/pol_prog_test.go
Labels: docs-not-required, release-note-not-required

#7275 Fix spelling of "overridden"
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calico/reference/felix/configuration.md
  calicoctl/calicoctl/commands/crds/crds.go
  felix/bpf-gpl/include/libbpf/src/libbpf.c
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#7354 BPF FV: Fix flake in BPF enablement tests.
  felix/fv/connectivity/conncheck.go
  felix/fv/test-connection/test-connection.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#7357 Fix that tunnel IP allocator didn't respect allowed uses.
  node/pkg/allocateip/allocateip.go
  node/pkg/allocateip/allocateip_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#7241 [BPF] Topology Aware Hints implementation
  felix/bpf/proxy/options.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_test.go
  felix/bpf/proxy/topology.go
  felix/bpf/proxy/topology_test.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
Labels: release-note-required, kind/enhancement, docs-not-required, area/bpf

#7373 Fix concurrent access to the MockLink object.
  felix/netlinkshim/mocknetlink/netlink.go
Labels: docs-not-required, release-note-not-required

#7368 Increase MTU tests timeout to remove flakes
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#7364 Use kernel-side route filtering for large performance boost
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
  felix/iptables/table.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/netlinkshim/netlink.go
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
  felix/wireguard/wireguard.go
  felix/wireguard/wireguard_test.go
  go.mod
  go.sum
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#7375 Use kernel side route filtering for the interface monitor
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/ifacemonitor/iface_monitor.go
  felix/ifacemonitor/netlink_real.go
  felix/netlinkshim/handle_manager.go
  felix/routetable/route_table.go
Labels: release-note-required, cherry-pick-candidate, docs-pr-required

#7378 Felix FVs: bail out early in IPv6 tests if docker IPv6 is disabled.
  felix/fv/infrastructure/topology.go
  felix/fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7381 [v3.25] Use kernel-side route filtering when listing routes
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/environment/feature_detect.go
  felix/environment/feature_detect_test.go
  felix/ifacemonitor/iface_monitor.go
  felix/ifacemonitor/netlink_real.go
  felix/iptables/table.go
  felix/netlinkshim/handle_manager.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/netlinkshim/netlink.go
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
  felix/wireguard/wireguard.go
  felix/wireguard/wireguard_test.go
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#7379 [v3.25] Fix valueSize when deleting map entry during iteration.
  felix/bpf/maps.go
Labels: release-note-required, docs-not-required

#7347 Update calicovpp version to v3.25.0
  calico/_config.yml
Labels: docs-not-required, release-note-not-required

#7390 Fix concurrent access to the MockLink object.
  felix/netlinkshim/mocknetlink/netlink.go
Labels: docs-not-required, release-note-not-required

#7389 [release-v3.25] Auto pick #7368: Increase MTU tests timeout to remove flakes
  felix/fv/mtu_test.go
  felix/fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#7387 Release documentation update
  hack/release/RELEASING.md
Labels: docs-not-required, release-note-not-required

#7388 [release 3.25] Update dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7391 [release-v3.25] Release documentation update
  hack/release/RELEASING.md
Labels: release-note-required, docs-pr-required

#7385 Update dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7392 Release documentation update pt 2
  hack/release/RELEASING.md
Labels: docs-not-required, release-note-not-required

#7285 Remove Dockerfile symbolic links
  apiserver/docker-image/Dockerfile
  calicoctl/Dockerfile
  cni-plugin/Dockerfile
  felix/Makefile
  felix/docker-image/Dockerfile
  kube-controllers/Dockerfile
  kube-controllers/docker-images/flannel-migration/Dockerfile
  node/Dockerfile
  node/workload/Dockerfile
  typha/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#7255 os.Stat returns nil to judge file exist.
  pod2daemon/binder/binder.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7256 fix pod2daemon-csidriver extractPodInfo funcs.
  pod2daemon/csidriver/driver/node.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7394 Update K8s versions
  apiserver/pkg/registry/projectcalico/kubecontrollersconfig/storage.go
  apiserver/pkg/storage/calico/api_object_versioner.go
  apiserver/pkg/storage/calico/bgpConfiguration_storage.go
  apiserver/pkg/storage/calico/bgpPeer_storage.go
  apiserver/pkg/storage/calico/blockAffinity_storage.go
  apiserver/pkg/storage/calico/caliconodestatus_storage.go
  apiserver/pkg/storage/calico/clusterInformation_storage.go
  apiserver/pkg/storage/calico/felixConfig_storage.go
  apiserver/pkg/storage/calico/globalNetworkPolicy_storage.go
  apiserver/pkg/storage/calico/globalNetworkSet_storage.go
  apiserver/pkg/storage/calico/hostEndpoint_storage.go
  apiserver/pkg/storage/calico/ipamconfig_storage.go
  apiserver/pkg/storage/calico/ippool_storage.go
  apiserver/pkg/storage/calico/ipreservation_storage.go
  apiserver/pkg/storage/calico/kubeControllersConfig_storage.go
  apiserver/pkg/storage/calico/networkSet_storage.go
  apiserver/pkg/storage/calico/policy_storage.go
  apiserver/pkg/storage/calico/profile_storage.go
  calicoctl/tests/st/utils/data.py
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7358 Using the netlink.NewLinkAttrs to bring default values from kernel
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/pkg/dataplane/grpc/test_server_linux.go
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
  felix/bpf/ut/precompilation_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/fv/test-workload/test-workload.go
  felix/ifacemonitor/ifacemonitor_test.go
  felix/ifacemonitor/update_filter_test.go
  felix/k8sfv/pod.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/wireguard/bootstrap_test.go
Labels: release-note-required, docs-not-required

#7404 Add link to VPP data plane release notes in release text
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required
