Repository projectcalico/calico, pull requests merged in 2023-12, with the labels that each got.

#8281 [release-v3.26] Auto pick #7818: Add Makefile utility to pull operator CRD updates
  charts/tigera-operator/.helmignore
  charts/tigera-operator/Makefile
  charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/ocp/operator.tigera.io_apiservers_crd.yaml
  manifests/ocp/operator.tigera.io_imagesets_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#8282 Remove the policy index from the correct jump map
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#8278 Fix data race in BPF endpoint manager test.
  felix/dataplane/linux/bpf_ep_mgr_test.go
Labels: docs-not-required, release-note-not-required

#8286 Only program failsafe rules for IP version of the CIDR
  felix/rules/static.go
  felix/rules/static_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8296 Escape IPv6 with '[]' on BPF nat dumps
  felix/cmd/calico-bpf/commands/nat.go
  felix/fv/containers/containers.go
Labels: docs-not-required, release-note-not-required

#8297 Fix release timeout issues [v3.27]
  .semaphore/release/release.yml
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8298 Fix release timeout issues [cp #8297][master]
  .semaphore/release/release.yml
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8302 Fix --long usage in release versioning
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8301 Fix --long usage in release versioning
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8304 Fix GPG key path for OpenStack publishing
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8303 Update upstream CNI plugins and Flannel downloads to latest golang patches
  cni-plugin/Makefile
Labels: release-note-required, docs-pr-required

#8310 Update GCP VM image name
  hack/release/variables.tf
Labels: docs-not-required, release-note-not-required

#8320 [3.27] libbpf: ignore listing files in build dir
  felix/Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8324 Update release tooling and configuration
  hack/release/Makefile
  hack/release/RELEASING.md
  hack/release/pkg/builder/builder.go
  hack/release/pkg/builder/commands.go
  hack/release/terraform.tf
Labels: docs-not-required, release-note-not-required

#8326 Fix Windows release build/push code
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#8323 Fix bug in '--listen-any-ip' parsing on felix/bin/test-workload
  felix/fv/test-workload/test-workload.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8327 Make node/dist/install-calico-windows.ps1 as part of make release-build
  node/Makefile
Labels: docs-not-required, release-note-not-required

#8328 [master] Auto pick #8327: Make node/dist/install-calico-windows.ps1 as part of make
  node/Makefile
Labels: docs-not-required, release-note-not-required

#8330 Use either VERSION or BRANCH_NAME for 'make release-windows'
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8295 [BPF] don't stumble on unknown prog types passed as int in json
  felix/bpf/bpf.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8332 Add gcloud auth activate-service-account to release VM terraform
  hack/release/terraform.tf
Labels: docs-not-required, release-note-not-required

#8336 [master] Auto pick #8324: Update release tooling and configuration #8326: Fix Windows release build/push code
  hack/release/Makefile
  hack/release/RELEASING.md
  hack/release/pkg/builder/builder.go
  hack/release/pkg/builder/commands.go
  hack/release/terraform.tf
Labels: docs-not-required, release-note-not-required

#8331 [master] Auto pick #8330: Use either VERSION or BRANCH_NAME for 'make release-windows'
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8313 [BPF] when host IPs change kube-proxy replaces only Syncer
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/kube-proxy_test.go
  felix/bpf/proxy/proxy.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8337 Move build to semaphore VM
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8339 Use larger Sem VM
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8340 Try using /mnt to build calico
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8341 Add manual GCR login for now
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8343 Add release notes for v3.27.0
  release-notes/v3.27.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#8347 handle source IP spoofing annotation for etcd datastore mode
  cni-plugin/pkg/k8s/k8s.go
  cni-plugin/tests/calico_cni_k8s_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
Labels: release-note-required, docs-not-required

#8359 hack/release/pkg/builder: fix dropped error
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8356 Register before cross building app-policy images
  app-policy/Makefile
  felix/Makefile
  kube-controllers/Makefile
Labels: docs-not-required, release-note-not-required

#8098 Group common sub-sequences of policies into shared iptables chains
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/calc/rule_scanner.go
  felix/calc/rule_scanner_test.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/mock_iptables_for_test.go
  felix/fv/policysync_test.go
  felix/iptables/table.go
  felix/iptables/table_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  felix/rules/policy.go
  felix/rules/policy_test.go
  felix/rules/rule_defs.go
  libcalico-go/lib/selector/selector.go
Labels: release-note-required, docs-not-required

#8360 cherry pick #8347: handle source IP spoofing annotation for etcd datastore mode
  cni-plugin/pkg/k8s/k8s.go
  cni-plugin/tests/calico_cni_k8s_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8361 [CORE-10002] Add log grepping+printing to Windows FVs
  cni-plugin/.semaphore/run-win-fv.sh
  felix/.semaphore/run-win-fv
Labels: docs-not-required, release-note-not-required

#8365 [CORE-10042] Fix AutoCreateServiceAccountTokenSecret param handling in install-calico-windows.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  node/windows-packaging/install-calico-windows.ps1
Labels: release-note-required, docs-not-required, area/windows

#8364 Move calicoctl binary to standard executable search path
  calicoctl/Dockerfile
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  node/tests/k8st/infra/calicoctl.yaml
  node/tests/k8st/utils/utils.py
  process/testing/winfv/create_kubeadm_cluster.sh
Labels: release-note-required, docs-pr-required

#8338 [BPF] BPFExcludeCIDRsFromNAT allows excluding service IPs from being NATed
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/bpf-gpl/nat_lookup.h
  felix/bpf-gpl/nat_types.h
  felix/bpf-gpl/tc.c
  felix/bpf/nat/maps.go
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/lb_src_range_test.go
  felix/bpf/proxy/options.go
  felix/bpf/proxy/proxy_bench_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_bench_test.go
  felix/bpf/proxy/syncer_test.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/containers/containers.go
  felix/fv/workload/workload.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required, merge-when-ready

#8369 Move certificates permissions out of the else-block.
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#8370 Move per-component licenses to source root
  cni-plugin/Dockerfile-windows
  cni-plugin/README.md
  licenses/Apache-2.0
  licenses/BSD
  licenses/GPLv2
  licenses/ISC
  licenses/MIT
  licenses/Mozilla-public
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/README.md
  node/filesystem/licenses/Apache-2.0
  node/filesystem/licenses/BSD
  node/filesystem/licenses/GPLv2
  node/filesystem/licenses/ISC
  node/filesystem/licenses/MIT
  node/filesystem/licenses/Mozilla-public
  typha/Makefile
  typha/README.md
  typha/docker-image/Dockerfile
  typha/docker-image/licenses/Apache-2.0
  typha/docker-image/licenses/BSD
  typha/docker-image/licenses/GPLv2
  typha/docker-image/licenses/ISC
  typha/docker-image/licenses/MIT
  typha/docker-image/licenses/Mozilla-public
Labels: release-note-required, docs-pr-required

#8351 Update x/crypto
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#8321 [release 3.27] Update dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8352 [release 3.26] Update x/crypto
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#8377 Replace satori/go.uuid with google/uuid
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/tests/calico_cni_ipam_test.go
  go.mod
  go.sum
  kube-controllers/pkg/controllers/pod/pod_controller_fv_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8366 Use host native calico/go-build to do cross compilation
  felix/Makefile
  lib.Makefile
  node/Makefile
Labels: release-note-required, docs-pr-required
