Repository projectcalico/calico, pull requests merged in 2023-09, with the labels that each got.

#7994 [v3.26] move TLS handshake to per-connection goroutine
  typha/fv-tests/server_test.go
  typha/pkg/config/config_params.go
  typha/pkg/daemon/daemon.go
  typha/pkg/syncserver/sync_server.go
  typha/pkg/syncserver/syncserver_test.go
Labels: release-note-required, docs-pr-required

#7995 Create SECURITY.md
  SECURITY.md
Labels: release-note-required, docs-pr-required

#7964 [BPF] ipv6 kube-proxy
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/nat/maps.go
  felix/bpf/nat/maps6.go
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/lb_src_range_test.go
  felix/bpf/proxy/options.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/proxy_bench_test.go
  felix/bpf/proxy/rtcache.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_bench_test.go
  felix/bpf/proxy/syncer_test.go
  felix/bpf/routes/map.go
  felix/bpf/routes/map6.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/maps_test.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7984 calico-node: fix runsv failed start services issue
  node/Dockerfile.armv7
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: release-note-required, docs-pr-required

#7998 DOCS-1722: Fixes outdated docs links in calicoctl README
  calicoctl/README.md
Labels: release-note-required, docs-pr-required

#8009 [3.26] DOCS-1722: Fixes outdated docs links in calicoctl README
  calicoctl/README.md
Labels: release-note-required, docs-pr-required

#8010 [3.25] DOCS-1722: Fixes outdated docs links in calicoctl README
  calicoctl/README.md
Labels: release-note-required, docs-not-required

#8011 [3.24] DOCS-1722: Fixes outdated docs links in calicoctl README
  calicoctl/README.md
Labels: release-note-required, docs-pr-required

#7985 [cherry-pick v3.26] calico-node: fix runsv failed start services issue
  node/Dockerfile.armv7
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: release-note-required, docs-pr-required

#7962 [cherry-pick v3.26] Add LOCAL_CRANE option to lib.Makefile
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#7970 fix: ec2 detection not working with imdsv2
  node/windows-packaging/CalicoWindows/libs/calico/calico.psm1
Labels: release-note-required, docs-not-required

#7523 Add envxx support to MTUIfacePattern for ppc arch
  felix/config/config_params.go
Labels: release-note-required, docs-pr-required

#8028 OpenStack CI fixes
  networking-calico/devstack/bootstrap.sh
  networking-calico/requirements.txt
  networking-calico/test-requirements.txt
  networking-calico/tox.ini
Labels: docs-not-required, release-note-not-required

#8019 Bump llvm to v15
  felix/bpf-apache/Makefile
  felix/bpf-apache/redir.c
  felix/bpf-apache/sockops.c
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/tc.c
  metadata.mk
Labels: hold-merge, docs-not-required, release-note-not-required

#8030 Split kindest/node version into a separate variable
  apiserver/Makefile
  confd/Makefile
  kube-controllers/Makefile
  lib.Makefile
  metadata.mk
Labels: release-note-required, docs-pr-required

#8026 Correct policy for OpenStack sec group with no remote_ip_prefix
  networking-calico/networking_calico/plugins/ml2/drivers/calico/policy.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
Labels: release-note-required, docs-not-required

#8035 OpenStack port spec issue backport to v3.25
  networking-calico/.testr.conf
  networking-calico/Dockerfile
  networking-calico/Makefile
  networking-calico/debian/control
  networking-calico/devstack/bootstrap.sh
  networking-calico/networking_calico/plugins/ml2/drivers/calico/policy.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
  networking-calico/networking_calico/tests/test_dhcp_agent.py
  networking-calico/requirements.txt
  networking-calico/test-requirements.txt
  networking-calico/tox.ini
Labels: release-note-required, docs-pr-required

#8032 [release-v3.26] Split kindest/node version into a separate variable
  apiserver/Makefile
  confd/Makefile
  kube-controllers/Makefile
  lib.Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8027 Windows HPC image publishing
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/node.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  cni-plugin/Makefile
  hack/postrelease/test_images.py
  hack/release/pkg/builder/builder.go
  node/Makefile
Labels: docs-not-required, release-note-not-required

#8040 Windows image publishing fixes
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  cni-plugin/Makefile
  lib.Makefile
  metadata.mk
  node/Makefile
  node/windows-upgrade/Dockerfile
  node/windows-upgrade/calico-upgrade.ps1
Labels: docs-not-required, release-note-not-required

#8042 Fix release builder
  hack/release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#8029 Update golang and k8s versions
  go.mod
  go.sum
  metadata.mk
  typha/fv-tests/server_harness_test.go
Labels: docs-not-required, release-note-not-required

#8043 Sync operator CRDs from master branch
  Makefile
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#8044 Add IPAMConfigurations RBAC to operator ClusterRole
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#8046 Update flannel version
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#8052 Tune iptables/calc graph logging
  felix/calc/rule_scanner.go
  felix/dispatcher/dispatcher.go
  felix/iptables/table.go
  libcalico-go/lib/logutils/ratelimitedlogger.go
  libcalico-go/lib/logutils/ratelimitedlogger_test.go
Labels: release-note-required, docs-pr-required

#8054 Defer and rate limit IP set deletions.
  felix/bpf/ipsets/ipsets.go
  felix/dataplane/common/ipsets_mgr.go
  felix/dataplane/common/mock_ipsets.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/windows/ipsets/ipsets.go
  felix/deltatracker/delta_set.go
  felix/deltatracker/delta_tracker.go
  felix/fv/ipsets_test.go
  felix/ipsets/ipset_defs.go
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_suite_test.go
  felix/ipsets/ipsets_test.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-pr-required

#8062 [3.26] Update dependencies
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8064 Update BIRD to pull in https://github.com/projectcalico/bird/pull/111
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7979 Typha tolerate node.cloudprovider.kubernetes.io/uninitialized taint
  charts/calico/templates/calico-typha.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
Labels: release-note-required, docs-not-required

#8065 [release-v3.26] Auto pick #7979: Typha tolerate
  charts/calico/templates/calico-typha.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
Labels: release-note-required, docs-not-required

#8066 [release-v3.25] Auto pick #7979: Typha tolerate
  charts/calico/templates/calico-typha.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
Labels: release-note-required, docs-not-required

#8067 [release-v3.24] Auto pick #7979: Typha tolerate
  charts/calico/templates/calico-typha.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
Labels: release-note-required, docs-not-required

#8059 update cni to v1.1.1-calico+go-1.21.1
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#8063 Update libraries
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7794 Add VM timeout for releases
  hack/release/terraform.tf
Labels: docs-not-required, release-note-not-required

#8053 Make iptables recheck timer dynamic
  felix/config/config_params.go
  felix/iptables/table.go
  felix/iptables/table_test.go
  felix/iptables/testutils/utils.go
Labels: release-note-required, docs-pr-required

#7912 Add Openstack package publishing to the test build promotion
  .semaphore/release/release.yml
  .semaphore/release/test-release-build.yml
  Makefile
  hack/release/packaging/utils/create-update-packages.sh
Labels: docs-not-required, release-note-not-required

#8068 Add missing break after error in IP sets write logic.
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-pr-required

#8069 Add additional IP set types and tests
  felix/ip/ip_addr.go
  felix/ip/ip_addr_test.go
  felix/ipsets/ipset_defs.go
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/ipsets/utils_for_test.go
  felix/rules/rule_defs.go
Labels: docs-not-required, release-note-not-required, merge-when-ready
