Repository projectcalico/calico, pull requests merged in 2023-05, with the labels that each got.

#7602 Fix: Dikastes required libraries
  app-policy/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#7617 [release-v3.26] Auto pick #7602: Fix: Dikastes required libraries
  app-policy/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7624 [BPF/UT] do not include tc.c in ut objects
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/ut/icmp_port_unreachable.c
  felix/bpf-gpl/ut/icmp_too_big.c
  felix/bpf-gpl/ut/icmp_ttl_exceeded.c
  felix/bpf-gpl/ut/ut.h
  felix/bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#7627 Update golang to 1.20.4
  cni-plugin/Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7595 [BPF] Fix tracking packets that host forwards to devices not managed by calico
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/config/param_types.go
  felix/config/param_types_test.go
  felix/dataplane/driver.go
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, cherry-pick-candidate, docs-pr-required

#7631 [BPF] report error on setting /proc/sys/net... iff dev not present
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#7550 Skip setting node IP annotation if CALICO_NETWORKING_BACKEND=none
  node/pkg/lifecycle/startup/startup.go
Labels: release-note-required, docs-not-required

#7635 Move UID/GID assignment to command-line
  hack/release/packaging/utils/create-update-packages.sh
Labels: release-note-required, docs-pr-required

#7636 [BPF] fix BPFEnabled in NewTestEpMgr to skip unused marks
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#7637 Add delayed restart to FV
  felix/docker-image/calico-felix-wrapper
  felix/fv/infrastructure/felix.go
Labels: docs-not-required, release-note-not-required

#7632 [release-v3.26] Skip settings node IP annotation if CALICO_NETWORKING_BACKEND=none
  node/pkg/lifecycle/startup/startup.go
Labels: release-note-required, docs-not-required

#7640 Create a symlink for libpcap.so.0.8
  node/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#7641 Only use static ldflags for registrar on amd64 on pod2daemon
  app-policy/Dockerfile.amd64
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7648 Update dependencies
  cni-plugin/Makefile
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#7649 Update dependencies
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#7650 Add release notes for v3.24.6
  calico/_includes/release-notes/v3.24.6-release-notes.md
Labels: docs-not-required, release-note-not-required

#7661 Fix automated OpenStack packaging promotion
  .semaphore/push-images/packaging.yaml
Labels: release-note-required, docs-pr-required

#7662 Add FIPS required libraries to cni-plugin image
  cni-plugin/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#7633 [BPF] Disable GRO option for selected interfaces
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/config/config_params.go
  felix/config/param_types_test.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/ethtool/ethtool.go
  felix/fv/ethtool_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/validator/v3/validator.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, kind/enhancement, docs-pr-required, area/bpf

#7670 Add: Dikastes to the list of manifests
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#7672 [release-v3.25] Auto pick #7670: Add: Dikastes to the list of manifests
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#7671 [release-v3.26] Auto pick #7670: Add: Dikastes to the list of manifests
  manifests/generate.sh
Labels: docs-not-required, release-note-not-required

#7646 fix panic due to nil route dst
  felix/ifacemonitor/iface_monitor.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#7668 Call Router() to enact side-effects necessary to work on Yoga
  networking-calico/networking_calico/plugins/calico/plugin.py
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7669 Fix Felix packaging for Ubuntu
  felix/debian/control
Labels: docs-not-required, release-note-not-required

#7675 Update release version for dikastes in manifests
  manifests/alp/istio-inject-configmap-1.1.0.yaml
  manifests/alp/istio-inject-configmap-1.1.1.yaml
  manifests/alp/istio-inject-configmap-1.1.10.yaml
  manifests/alp/istio-inject-configmap-1.1.11.yaml
  manifests/alp/istio-inject-configmap-1.1.12.yaml
  manifests/alp/istio-inject-configmap-1.1.13.yaml
  manifests/alp/istio-inject-configmap-1.1.14.yaml
  manifests/alp/istio-inject-configmap-1.1.15.yaml
  manifests/alp/istio-inject-configmap-1.1.16.yaml
  manifests/alp/istio-inject-configmap-1.1.17.yaml
  manifests/alp/istio-inject-configmap-1.1.2.yaml
  manifests/alp/istio-inject-configmap-1.1.3.yaml
  manifests/alp/istio-inject-configmap-1.1.4.yaml
  manifests/alp/istio-inject-configmap-1.1.5.yaml
  manifests/alp/istio-inject-configmap-1.1.6.yaml
  manifests/alp/istio-inject-configmap-1.1.7.yaml
  manifests/alp/istio-inject-configmap-1.1.8.yaml
  manifests/alp/istio-inject-configmap-1.1.9.yaml
  manifests/alp/istio-inject-configmap-1.10.yaml
  manifests/alp/istio-inject-configmap-1.15.yaml
  manifests/alp/istio-inject-configmap-1.2.0.yaml
  manifests/alp/istio-inject-configmap-1.2.1.yaml
  manifests/alp/istio-inject-configmap-1.2.2.yaml
  manifests/alp/istio-inject-configmap-1.2.3.yaml
  manifests/alp/istio-inject-configmap-1.2.4.yaml
  manifests/alp/istio-inject-configmap-1.2.5.yaml
  manifests/alp/istio-inject-configmap-1.2.6.yaml
  manifests/alp/istio-inject-configmap-1.2.7.yaml
  manifests/alp/istio-inject-configmap-1.2.8.yaml
  manifests/alp/istio-inject-configmap-1.2.9.yaml
  manifests/alp/istio-inject-configmap-1.3.0.yaml
  manifests/alp/istio-inject-configmap-1.3.1.yaml
  manifests/alp/istio-inject-configmap-1.3.2.yaml
  manifests/alp/istio-inject-configmap-1.3.3.yaml
  manifests/alp/istio-inject-configmap-1.3.4.yaml
  manifests/alp/istio-inject-configmap-1.3.5.yaml
  manifests/alp/istio-inject-configmap-1.4.0.yaml
  manifests/alp/istio-inject-configmap-1.4.1.yaml
  manifests/alp/istio-inject-configmap-1.4.2.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  manifests/alp/istio-inject-configmap-1.9.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7674 [Cherry-pick] Call Router() to enact side-effects necessary to work on Yoga
  networking-calico/networking_calico/plugins/calico/plugin.py
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#7678 [master] Auto pick #7677: Fix statically building node-driver-registrar on amd64
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7679 [release-v3.25] Auto pick #7677: Fix statically building node-driver-registrar on amd64
  manifests/alp/istio-inject-configmap-1.1.0.yaml
  manifests/alp/istio-inject-configmap-1.1.1.yaml
  manifests/alp/istio-inject-configmap-1.1.10.yaml
  manifests/alp/istio-inject-configmap-1.1.11.yaml
  manifests/alp/istio-inject-configmap-1.1.12.yaml
  manifests/alp/istio-inject-configmap-1.1.13.yaml
  manifests/alp/istio-inject-configmap-1.1.14.yaml
  manifests/alp/istio-inject-configmap-1.1.15.yaml
  manifests/alp/istio-inject-configmap-1.1.16.yaml
  manifests/alp/istio-inject-configmap-1.1.17.yaml
  manifests/alp/istio-inject-configmap-1.1.2.yaml
  manifests/alp/istio-inject-configmap-1.1.3.yaml
  manifests/alp/istio-inject-configmap-1.1.4.yaml
  manifests/alp/istio-inject-configmap-1.1.5.yaml
  manifests/alp/istio-inject-configmap-1.1.6.yaml
  manifests/alp/istio-inject-configmap-1.1.7.yaml
  manifests/alp/istio-inject-configmap-1.1.8.yaml
  manifests/alp/istio-inject-configmap-1.1.9.yaml
  manifests/alp/istio-inject-configmap-1.10.yaml
  manifests/alp/istio-inject-configmap-1.15.yaml
  manifests/alp/istio-inject-configmap-1.2.0.yaml
  manifests/alp/istio-inject-configmap-1.2.1.yaml
  manifests/alp/istio-inject-configmap-1.2.2.yaml
  manifests/alp/istio-inject-configmap-1.2.3.yaml
  manifests/alp/istio-inject-configmap-1.2.4.yaml
  manifests/alp/istio-inject-configmap-1.2.5.yaml
  manifests/alp/istio-inject-configmap-1.2.6.yaml
  manifests/alp/istio-inject-configmap-1.2.7.yaml
  manifests/alp/istio-inject-configmap-1.2.8.yaml
  manifests/alp/istio-inject-configmap-1.2.9.yaml
  manifests/alp/istio-inject-configmap-1.3.0.yaml
  manifests/alp/istio-inject-configmap-1.3.1.yaml
  manifests/alp/istio-inject-configmap-1.3.2.yaml
  manifests/alp/istio-inject-configmap-1.3.3.yaml
  manifests/alp/istio-inject-configmap-1.3.4.yaml
  manifests/alp/istio-inject-configmap-1.3.5.yaml
  manifests/alp/istio-inject-configmap-1.4.0.yaml
  manifests/alp/istio-inject-configmap-1.4.1.yaml
  manifests/alp/istio-inject-configmap-1.4.2.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  manifests/alp/istio-inject-configmap-1.9.yaml
  pod2daemon/Makefile
Labels: docs-not-required, release-note-not-required

#7570 Fix links in custom-resources.yaml manifest
  manifests/custom-resources.yaml
Labels: release-note-required, docs-pr-required

#7683 Add missing libs to fix flannel-migration image (fallout from updating to go v1.20)
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#7682 Update numBaseFelixConfigs to ensure libcalico-go tests pass
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
Labels: kind/bug, docs-not-required, release-note-not-required

#7580 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  calicoctl/calicoctl/commands/crds/decode.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7665 [Release 3.26]update UBI to 8.8
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7628 [Release 3.26] Update golang to 1.20.4
  cni-plugin/Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#7688 Clean up removed '--container-runtime' kubelet flag
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
Labels: docs-not-required, release-note-not-required

#7689 [release-v3.26] Auto pick #7688: Clean up removed '--container-runtime' kubelet flag
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
Labels: docs-not-required, release-note-not-required

#7690 Add missing libs to fix flannel-migration image (fallout from updating to go v1.20)
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#7557 Make flannel namespace configurable in flannel migration controller
  kube-controllers/pkg/controllers/flannelmigration/config.go
  kube-controllers/pkg/controllers/flannelmigration/migration_controller.go
  kube-controllers/pkg/controllers/flannelmigration/network_migrator.go
  kube-controllers/tests/testutils/flannel_migration_utils.go
Labels: release-note-required, docs-pr-required

#7693 Update distribution libs
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7692 fix flannel-migration-controller failed
  kube-controllers/pkg/controllers/flannelmigration/migration_controller.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7695 Fix OpenStack packaging promotion and add libcap-dev and automatic de…
  .semaphore/push-images/packaging.yaml
  felix/debian/control
Labels: docs-not-required, release-note-not-required

#7657 allow reference to existing secret as imagePullSecret
  charts/test/helm_suite_test.go
  charts/test/tigera_operator_chart_test.go
  charts/tigera-operator/README.md
  charts/tigera-operator/templates/_helpers.tpl
  charts/tigera-operator/templates/crs/custom-resources.yaml
  charts/tigera-operator/templates/tigera-operator/02-serviceaccount-tigera-operator.yaml
  charts/tigera-operator/values.yaml
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#7687 Update issue templates
  .github/ISSUE_TEMPLATE/generate-purpose-issue-template.md
Labels: docs-not-required, release-note-not-required

#7700 Get GitHub UI to recognize contributing guidelines
  CONTRIBUTING.md
  README.md
  node/README.md
Labels: docs-not-required, release-note-not-required

#7703 Add missing libraries preventing builds
  app-policy/Dockerfile.amd64
  cni-plugin/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#7718 Fix release notes location
  hack/release/pkg/builder/builder.go
Labels: release-note-required, docs-pr-required

#7714 Remove remaining node update calls in calico-node startup
  node/filesystem/etc/rc.local
  node/pkg/lifecycle/startup/startup.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, docs-pr-required

#7707 [BPF] clasiffy correctly forwarded traffic
  felix/bpf-gpl/skb.h
  felix/bpf-gpl/tc.c
  felix/bpf/ut/failsafes_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#7716 Fix kubernetes archive GPG key url
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  process/testing/winfv/create_kubeadm_cluster.sh
Labels: docs-not-required, release-note-not-required

#7723 Fix winfv paths for semaphore change detection in semaphore yaml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required

#7724 [release-v3.26] Auto pick #7707: clasiffy correctly forwarded traffic
  felix/bpf-gpl/skb.h
  felix/bpf-gpl/tc.c
  felix/bpf/ut/failsafes_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#7725 [release-v3.25] Auto pick #7707: clasiffy correctly forwarded traffic
  felix/bpf-gpl/skb.h
  felix/bpf-gpl/tc.c
  felix/bpf/ut/failsafes_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready
