Repository projectcalico/calico, pull requests merged in 2023-10, with the labels that each got.

#7663 [Release 3.24] Update UBI to 8.8
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8073 s390x Calico updates
  apiserver/cmd/apiserver/server/watch.go
  calicoctl/Makefile
  calicoctl/tests/fv/utils/calicoctl.go
  confd/Makefile
  kube-controllers/Dockerfile.s390x
  node/calico_test/Dockerfile.s390x.calico_test
Labels: release-note-required, docs-pr-required

#7676 Allow testcases to run on s390x architecture
  calicoctl/Makefile
  calicoctl/tests/fv/utils/calicoctl.go
  confd/Makefile
  kube-controllers/Dockerfile.s390x
  node/calico_test/Dockerfile.s390x.calico_test
Labels: docs-not-required, release-note-not-required

#8015 Felix: Optimise key-value selector indexing
  felix/calc/calc_graph_bench_test.go
  felix/labelindex/labelnamevalueindex/label_name_value_index.go
  felix/labelindex/labelnamevalueindex/label_name_value_index_test.go
  felix/labelindex/labelrestrictionindex/label_restriction_index.go
  felix/labelindex/labelrestrictionindex/label_restriction_index_test.go
  felix/labelindex/named_port_bench_test.go
  felix/labelindex/named_port_index.go
  felix/labelindex/named_port_index_test.go
  libcalico-go/lib/selector/parser/ast.go
  libcalico-go/lib/selector/parser/label_restriction_test.go
  libcalico-go/lib/selector/parser/stringset.go
  libcalico-go/lib/selector/parser/stringset_test.go
  libcalico-go/lib/selector/selector.go
  libcalico-go/lib/set/union.go
  libcalico-go/lib/set/union_test.go
Labels: release-note-required, docs-pr-required

#8081 Improvements to Calico windows building/pushing
  .gitignore
  Makefile
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8079 Tweak selector names in named port index tests.
  felix/labelindex/named_port_index_test.go
Labels: docs-not-required, release-note-not-required

#8082 [BPF] add -6 to calico-bpf command
  felix/cmd/calico-bpf/commands/arp.go
  felix/cmd/calico-bpf/commands/conntrack.go
  felix/cmd/calico-bpf/commands/ipsets.go
  felix/cmd/calico-bpf/commands/nat.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/cmd/calico-bpf/commands/root.go
  felix/cmd/calico-bpf/commands/routes.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8088 [BPF] fix calico-bpf conntrack fill for FVs
  felix/cmd/calico-bpf/commands/conntrack.go
Labels: release-note-required, docs-pr-required

#8086 Fix felix_label_index_strategy_evals prometheus metric
  felix/fv/label_index_metrics_test.go
  felix/fv/metrics/metrics.go
  felix/fv/workload/workload.go
  felix/labelindex/labelnamevalueindex/label_name_value_index.go
  felix/labelindex/labelnamevalueindex/label_name_value_index_test.go
  felix/labelindex/named_port_index.go
Labels: docs-not-required, release-note-not-required

#8089 Change set.Set() to use new clear() built-in.
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/internal/pkg/utils/utils.go
  cni-plugin/pkg/plugin/plugin.go
  cni-plugin/tests/calico_cni_test.go
  felix/bpf/maps/syscall.go
  felix/calc/policy_resolver.go
  go.mod
  libcalico-go/lib/set/set.go
Labels: docs-not-required, release-note-not-required

#8047 Update flannel and docker distribution
  cni-plugin/Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8083 fv infra for runnign full ipv6 tests
  felix/fv/connectivity/conncheck.go
  felix/fv/containers/containers.go
  felix/fv/infrastructure/datastore_describe.go
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/infrastructure/topology.go
  felix/fv/latency_test.go
  felix/fv/pktgen/pktgen.go
  felix/fv/vxlan_test.go
  felix/fv/wireguard_test.go
  felix/fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#8093 [BPF] kube-proxy v6 programs NAT tables
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/syncer.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#8094 Allow windows images to be pushed to private registries
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#7859 Add pre-delete hook for operator to clean up after itself
  charts/tigera-operator/templates/tigera-operator/00-uninstall.yaml
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  manifests/generate.sh
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#8090 Increase IP sets benchmark timeout.
  felix/fv/ipsets_test.go
Labels: docs-not-required, release-note-not-required

#8105 Felix build cleanups
  .semaphore/run-and-monitor
  felix/.semaphore/run-tests-on-vms
  felix/Makefile
  felix/bpf-gpl/list-objs
  felix/utils/run-coverage
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8114 [release-v3.26] Auto pick #8113: Use '--long' arg with 'git describe'
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8115 [release-v3.25] Auto pick #8113: Use '--long' arg with 'git describe'
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8116 [release-v3.24] Auto pick #8113: Use '--long' arg with 'git describe'
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#7778 Delete redundance package for apiserver storage code.
  apiserver/pkg/storage/calico/watcher.go
Labels: docs-not-required, release-note-not-required

#8113 Use '--long' arg with 'git describe'
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#8084 [BPF] ipv6 core programs
  felix/Makefile
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/connect.h
  felix/bpf-gpl/connect_balancer.c
  felix/bpf-gpl/connect_balancer_v46.c
  felix/bpf-gpl/connect_balancer_v6.c
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/failsafe.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/ip_addr.h
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/list-objs
  felix/bpf-gpl/nat6.h
  felix/bpf-gpl/parsing.h
  felix/bpf-gpl/parsing6.h
  felix/bpf-gpl/policy.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/sendrecv.h
  felix/bpf-gpl/tc_preamble.c
  felix/bpf-gpl/types.h
  felix/bpf/ipsets/map6.go
  felix/bpf/nat/connecttime.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/polprog/pol_prog_builder_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/pol_prog_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#8123 [windows] Add windows firewall rule to allow prometheus reporting ports on windows HPC
  felix/daemon/daemon.go
  node/Makefile
Labels: docs-not-required, release-note-not-required

#8128 Update libraries
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8129 [release 3.26] Update libraries
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8130 [release 25] update libraries
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8134 [windows HPC] wrap felix to restart it for config changes
  node/windows-packaging/CalicoWindows/felix/felix-service.ps1
Labels: docs-not-required, release-note-not-required

#8106 Upgrade to k8s v1.27
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
  apiserver/test/integration/framework.go
  apiserver/test/util/util.go
  cni-plugin/pkg/plugin/plugin.go
  confd/pkg/backends/calico/secret_watcher.go
  felix/aws/ec2.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/topology.go
  felix/wireguard/bootstrap.go
  go.mod
  go.sum
  kube-controllers/pkg/controllers/flannelmigration/k8s_resources.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/upgrade/migrator/clients/v1/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#8143 Bump OpenTelemetry-Go libraries to v0.45.0
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8145 Bump semaphore build machine for kube-controller images
  .semaphore/push-images/kube-controllers.yml
Labels: release-note-required, docs-pr-required

#8146 Bump Go dependencies (Oct 2023)
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8005 Update SECURITY.md
  .github/ISSUE_TEMPLATE/generate-purpose-issue-template.md
  .github/REPORT_TEMPLATE.md
  SECURITY.md
Labels: release-note-required, docs-pr-required

#8148 Introducing $(ARCH) for helm
  lib.Makefile
Labels: release-note-required, docs-completed, docs-not-required, merge-when-ready

#8096 chore: slice lopp replace
  libcalico-go/lib/upgrade/converters/workloadendpoint.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8124 Use nginx:1.25.2 in node k8st tests
  node/tests/k8st/tests/test_bgp_advert.py
  node/tests/k8st/tests/test_bgp_advert_v6.py
  node/tests/k8st/tests/test_simple.py
  node/tests/k8st/utils/utils.py
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8158 [release-v3.26] Bump semaphore build machine for kube-controller images
  .semaphore/push-images/kube-controllers.yml
Labels: release-note-required, docs-pr-required

#8133 Fix api golint errors
  api/Makefile
  api/pkg/apis/projectcalico/v3/bgpfilter.go
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/apis/projectcalico/v3/conversion.go
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/ippool.go
  api/pkg/apis/projectcalico/v3/nodestatus.go
  api/pkg/apis/projectcalico/v3/policy_common.go
  apiserver/pkg/printers/projectcalico/printers_test.go
  confd/pkg/resource/template/template_funcs.go
  felix/aws/ec2.go
  felix/aws/ec2_test.go
  felix/dataplane/driver.go
  node/pkg/status/nodestatus_test.go
  node/pkg/status/populators/peers_test.go
Labels: release-note-required, docs-pr-required

#8000 [BPF] basic IPv6 enabled
  felix/bpf/attach.go
  felix/bpf/bpf_syscall.go
  felix/bpf/bpf_syscall.h
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/filter/filter.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/defs/defs.go
  felix/bpf/xdp/attach.go
  felix/config/config_params.go
  felix/dataplane/common/ipsets_mgr.go
  felix/dataplane/common/ipsets_mgr_test.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/windows/win_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/latency_test.go
Labels: docs-not-required, release-note-not-required

#8157 Drop support for OpenStack on Ubuntu Bionic and older
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  hack/release/packaging/README.md
  hack/release/packaging/docker-build-images/docker-bake.hcl
  hack/release/packaging/docker-build-images/install-ubuntu-build-deps
  hack/release/packaging/docker-build-images/ubuntu-bionic-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-bionic-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-trusty-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-trusty-build.Dockerfile.ppc64le
  hack/release/packaging/docker-build-images/ubuntu-xenial-build.Dockerfile.amd64
  hack/release/packaging/docker-build-images/ubuntu-xenial-build.Dockerfile.ppc64le
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/make-packages.sh
  hack/release/packaging/utils/publish-debs.sh
Labels: release-note-required, docs-completed

#8173 Add new 'windowsManageFirewallRules' field to FelixConfig
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/config/config_params.go
  felix/daemon/daemon.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/validator/v3/validator_test.go
  libcalico-go/lib/winutils/winutils.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required
