Repository projectcalico/calico, pull requests merged in 2023-08, with the labels that each got.

#7903 update cni_version to v1.1.1-calico+go-1.20.7
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#7904 update cni_version to v1.1.1-calico+go-1.20.7
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#7905 update cni_version to v1.1.1-calico+go-1.20.7
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#7928 Update renamed windows AMIs
  process/testing/winfv/cloudformation-windows-server.json
  process/testing/winfv/setup-fv.sh
Labels: docs-not-required, release-note-not-required

#7934 [release-v3.26] Auto pick #7928: Update renamed windows AMIs
  process/testing/winfv/cloudformation-windows-server.json
  process/testing/winfv/setup-fv.sh
Labels: docs-not-required, release-note-not-required

#7936 Fix jump map key, value types
  felix/bpf-gpl/jump.h
  felix/bpf/libbpf/libbpf.go
  felix/bpf/ut/bpf_prog_test.go
Labels: release-note-required, docs-pr-required

#7935 Rev go.mod to v1.20.
  go.mod
  go.sum
  typha/fv-tests/server_harness_test.go
Labels: docs-not-required, release-note-not-required

#7933 Remove boxed set.Set
  felix/calc/event_sequencer.go
  felix/calc/l3_route_resolver.go
  felix/calc/policy_resolver.go
  felix/calc/state_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/status_combiner.go
  felix/ipsets/ipsets.go
  felix/iputils/intersect.go
  felix/labelindex/label_inheritance_index.go
  felix/labelindex/named_port_index.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/policysync/ipset.go
  felix/routetable/route_table.go
  felix/statusrep/status_reporter.go
  felix/wireguard/wireguard.go
  libcalico-go/lib/set/boxed.go
  libcalico-go/lib/set/set.go
  libcalico-go/lib/set/set_test.go
Labels: docs-not-required, release-note-not-required

#7932 Generic multidict.
  felix/calc/active_rules_calculator.go
  felix/calc/event_sequencer.go
  felix/calc/policy_resolver.go
  felix/calc/rule_scanner.go
  felix/multidict/multidict.go
  felix/multidict/multidict_test.go
Labels: docs-not-required, release-note-not-required

#7913 Add postrelease test promotion
  .semaphore/release/run-postrelease-tests.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  Makefile
  hack/postrelease/.gitignore
  hack/postrelease/Dockerfile
  hack/postrelease/Makefile
  hack/postrelease/tests/test_images.py
  hack/postrelease/tests/test_manifests_archives.py
  hack/postrelease/tests/variables.py
  hack/postrelease/variables.mk
Labels: docs-not-required, release-note-not-required

#7941 Fix build warnings
  felix/bpf/libbpf/libbpf.go
Labels: docs-not-required, release-note-not-required

#7945 Update libs
  felix/bpf/libbpf/libbpf.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7939 Defer flush of the policy resolver
  felix/calc/async_calc_graph.go
  felix/calc/calc_graph.go
  felix/calc/calc_graph_fv_test.go
  felix/calc/policy_resolver.go
  felix/calc/policy_resolver_test.go
Labels: release-note-required, docs-not-required

#7909 fix: adding timeout to the typha server TLS handshake
  typha/fv-tests/server_test.go
  typha/pkg/config/config_params.go
  typha/pkg/daemon/daemon.go
  typha/pkg/syncserver/sync_server.go
  typha/pkg/syncserver/syncserver_test.go
Labels: release-note-required, docs-pr-required

#7960 Add LOCAL_CRANE option to lib.Makefile
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#7953 Update docker and flannel versions
  cni-plugin/Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#7954 BPF Dump policies without assembly replaced with more condensed rule counters output
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/fv/bpf_counters_test.go
  felix/fv/bpf_policy_dump_test.go
  felix/fv/bpf_test.go
  felix/fv/donottrack_test.go
  felix/fv/ipip_test.go
Labels: release-note-required, docs-pr-required, area/bpf

#7955 calico-kube-controllers: Run as non-root by default for the s390x image
  kube-controllers/Dockerfile.s390x
Labels: release-note-required, docs-not-required

#7956 [cherry-pick v3.26] calico-kube-controllers: Run as non-root by default for the s390x image
  kube-controllers/Dockerfile.s390x
Labels: release-note-required, docs-not-required

#7943 [Cherry-pick] Add postrelease tests and postrelease test promotion (v3.25)
  .pre-commit-config.yaml
  .semaphore/release/run-postrelease-tests.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  Makefile
  hack/postrelease/.gitignore
  hack/postrelease/Dockerfile
  hack/postrelease/Makefile
  hack/postrelease/pytest.ini
  hack/postrelease/requirements.txt
  hack/postrelease/test_helm_artifacts.py
  hack/postrelease/test_images.py
  hack/postrelease/test_manifests_archives.py
  hack/postrelease/test_openstack_artifacts.py
  hack/postrelease/test_projectcalico_docs_updated.py
  hack/postrelease/test_tags_tars.py
  hack/postrelease/test_windows_artifacts.py
  hack/postrelease/tests/conftest.py
  hack/postrelease/tests/test_helm_artifacts.py
  hack/postrelease/tests/test_images.py
  hack/postrelease/tests/test_manifests_archives.py
  hack/postrelease/tests/test_openstack_artifacts.py
  hack/postrelease/tests/test_projectcalico_docs_updated.py
  hack/postrelease/tests/test_tags_tars.py
  hack/postrelease/tests/utilities.py
  hack/postrelease/tests/variables.py
  hack/postrelease/variables.mk
  hack/postrelease/versions.py
Labels: docs-not-required, release-note-not-required

#7973 [BPF] split calico_tc_skb_accepted_entrypoint
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tc.h
  felix/bpf/hook/map.go
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/tc/defs/defs.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#7961 [cherry-pick v3.25] Add LOCAL_CRANE option to lib.Makefile
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#7976 move TLS handshake to per-connection goroutine
  typha/fv-tests/server_test.go
  typha/pkg/config/config_params.go
  typha/pkg/daemon/daemon.go
  typha/pkg/syncserver/sync_server.go
  typha/pkg/syncserver/syncserver_test.go
Labels: release-note-required, docs-not-required

#7982 [release 3.25] Update golang/x/... packages
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
