Repository projectcalico/calico, pull requests merged in 2024-04, with the labels that each got.

#8677 Patch CVEs in go.mod of node-driver-registrar
  pod2daemon/Makefile
  pod2daemon/patches/0001-Update-go.mod-to-patch-CVEs.patch
Labels: release-note-required, hold-merge, docs-not-required, merge-when-ready

#8678 Update versions and add release notes for v3.27.3
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/alp/istio-inject-configmap-1.1.0.yaml
  manifests/alp/istio-inject-configmap-1.1.1.yaml
  manifests/alp/istio-inject-configmap-1.1.10.yaml
  manifests/alp/istio-inject-configmap-1.1.11.yaml
  manifests/alp/istio-inject-configmap-1.1.12.yaml
  manifests/alp/istio-inject-configmap-1.1.13.yaml
  manifests/alp/istio-inject-configmap-1.1.14.yaml
  manifests/alp/istio-inject-configmap-1.1.15.yaml
  manifests/alp/istio-inject-configmap-1.1.16.yaml
  manifests/alp/istio-inject-configmap-1.1.17.yaml
  manifests/alp/istio-inject-configmap-1.1.2.yaml
  manifests/alp/istio-inject-configmap-1.1.3.yaml
  manifests/alp/istio-inject-configmap-1.1.4.yaml
  manifests/alp/istio-inject-configmap-1.1.5.yaml
  manifests/alp/istio-inject-configmap-1.1.6.yaml
  manifests/alp/istio-inject-configmap-1.1.7.yaml
  manifests/alp/istio-inject-configmap-1.1.8.yaml
  manifests/alp/istio-inject-configmap-1.1.9.yaml
  manifests/alp/istio-inject-configmap-1.10.yaml
  manifests/alp/istio-inject-configmap-1.15.yaml
  manifests/alp/istio-inject-configmap-1.2.0.yaml
  manifests/alp/istio-inject-configmap-1.2.1.yaml
  manifests/alp/istio-inject-configmap-1.2.2.yaml
  manifests/alp/istio-inject-configmap-1.2.3.yaml
  manifests/alp/istio-inject-configmap-1.2.4.yaml
  manifests/alp/istio-inject-configmap-1.2.5.yaml
  manifests/alp/istio-inject-configmap-1.2.6.yaml
  manifests/alp/istio-inject-configmap-1.2.7.yaml
  manifests/alp/istio-inject-configmap-1.2.8.yaml
  manifests/alp/istio-inject-configmap-1.2.9.yaml
  manifests/alp/istio-inject-configmap-1.3.0.yaml
  manifests/alp/istio-inject-configmap-1.3.1.yaml
  manifests/alp/istio-inject-configmap-1.3.2.yaml
  manifests/alp/istio-inject-configmap-1.3.3.yaml
  manifests/alp/istio-inject-configmap-1.3.4.yaml
  manifests/alp/istio-inject-configmap-1.3.5.yaml
  manifests/alp/istio-inject-configmap-1.4.0.yaml
  manifests/alp/istio-inject-configmap-1.4.1.yaml
  manifests/alp/istio-inject-configmap-1.4.2.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  manifests/alp/istio-inject-configmap-1.9.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
  release-notes/v3.27.3-release-notes.md
Labels: docs-not-required, release-note-not-required

#8681 Apply recent OpenStack Yoga CI fixes to release-v3.27
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
  networking-calico/devstack/bootstrap.sh
Labels: release-note-required, docs-pr-required

#8673 Restart the node if NodeNetworkCondition cannot be set
  node/pkg/lifecycle/startup/startup.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8680 Enable VXLAN v6 tests in bpf runs
  felix/fv/vxlan_test.go
Labels: release-note-required, docs-pr-required

#8679 Do wep rpf check for icmpv6 if src is not link local
  felix/bpf-gpl/ip_addr.h
  felix/bpf-gpl/tc.c
  felix/fv/bpf_dual_stack_test.go
Labels: release-note-required, cherry-pick-candidate, docs-pr-required

#8686 [release-v3.27] Auto pick #8679: Do wep rpf check for icmpv6 if src is not link local
  felix/bpf-gpl/ip_addr.h
  felix/bpf-gpl/tc.c
Labels: release-note-required, docs-pr-required

#8688 [release-v3.28] Auto pick #8679: Do wep rpf check for icmpv6 if src is not link local
  felix/bpf-gpl/ip_addr.h
  felix/bpf-gpl/tc.c
  felix/fv/bpf_dual_stack_test.go
Labels: release-note-required, docs-pr-required

#8684 Delete old map if they are of the same version but different sizes.
  felix/bpf/maps/maps.go
  felix/bpf/ut/map_upgrade_test.go
Labels: release-note-required, cherry-pick-candidate, docs-pr-required

#6949 felix/bpf: pod->svc->self does not need allow policy
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf/state/map.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8690 Auto pick of #8684 release v3.28
  felix/bpf/maps/maps.go
  felix/bpf/ut/map_upgrade_test.go
Labels: release-note-required, docs-pr-required

#8657 Clean up openstack release promotions
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8696 Add file number to cni-plugin installer log output
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#8698 [release-v3.28] Auto pick #8696: Add file number to cni-plugin installer log output
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#8697 Set log level based on klog level
  apiserver/cmd/apiserver/apiserver.go
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/pkg/storage/calico/resource.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8699 [release-v3.28] Auto pick #8697: Set log level based on klog level
  apiserver/cmd/apiserver/apiserver.go
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/pkg/storage/calico/resource.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8693 Update as the older format bpf_map-def was deprecated
  felix/bpf-apache/sockops.c
Labels: release-note-required, docs-not-required

#8702 [Release v3.27] eBPF: Update map definition in sockops program
  felix/bpf-apache/sockops.c
Labels: release-note-required, docs-not-required

#8703 [Release v3.26] eBPF: Update map definition in sockops program
  felix/bpf-apache/sockops.c
Labels: release-note-required, docs-not-required

#7906 Fix files that import logrus multiple times.
  felix/calc/encapsulation_resolver.go
  felix/dataplane/linux/int_dataplane.go
  felix/serviceindex/serviceindex.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
  kube-controllers/pkg/controllers/node/labels.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8707 [BPF] dual stack for v6 only
  felix/bpf-gpl/tc_preamble.c
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_dual_stack_test.go
  felix/fv/bpf_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#8713 [release-v3.28] Auto pick #8707: Reduce indent in fv/bpf_dual_stack_test.go
  felix/bpf-gpl/tc_preamble.c
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_dual_stack_test.go
  felix/fv/bpf_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#8704 Move to Go 1.22 and rev deps.
  api/pkg/client/informers_generated/externalversions/factory.go
  apiserver/cmd/apiserver/apiserver.go
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/pkg/storage/calico/resource.go
  apiserver/test/integration/framework.go
  app-policy/cmd/dikastes/dikastes.go
  calicoctl/calicoctl/calicoctl.go
  cni-plugin/Makefile
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/plugin/plugin.go
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/win_tests/calico_cni_k8s_windows_test.go
  confd/confd.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/syncer_test.go
  felix/bpf/proxy/topology.go
  felix/bpf/proxy/topology_test.go
  felix/cmd/calico-bpf/commands/root.go
  felix/daemon/daemon.go
  go.mod
  go.sum
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/tests/testutils/flannel_migration_utils.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/seedrng/seed_rng.go
  metadata.mk
  node/cmd/calico-node/main.go
  pod2daemon/Makefile
  typha/cmd/typha-client/typha-client.go
  typha/pkg/daemon/daemon.go
  typha/pkg/discovery/discovery.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8618 [BPF] When lo has IP override it when CTLB is disabled
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8719 [release-v3.28] Auto pick #6949: police MASQed packets from pod->service->self as if
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf/state/map.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8718 [release-v3.28] Auto pick #8618: When lo has IP override it when CTLB is disabled
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8717 [v3.28] Backport #8704: Rev Go and Kubernetes
  api/pkg/client/informers_generated/externalversions/factory.go
  apiserver/cmd/apiserver/apiserver.go
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/pkg/storage/calico/resource.go
  apiserver/test/integration/framework.go
  app-policy/cmd/dikastes/dikastes.go
  calicoctl/calicoctl/calicoctl.go
  cni-plugin/Makefile
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/plugin/plugin.go
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/win_tests/calico_cni_k8s_windows_test.go
  confd/confd.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/syncer_test.go
  felix/bpf/proxy/topology.go
  felix/bpf/proxy/topology_test.go
  felix/cmd/calico-bpf/commands/root.go
  felix/daemon/daemon.go
  go.mod
  go.sum
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/tests/testutils/flannel_migration_utils.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/seedrng/seed_rng.go
  metadata.mk
  node/cmd/calico-node/main.go
  pod2daemon/Makefile
  typha/cmd/typha-client/typha-client.go
  typha/pkg/daemon/daemon.go
  typha/pkg/discovery/discovery.go
Labels: release-note-required, docs-not-required

#8722 Ability to specify additional labels in helm chart
  charts/tigera-operator/templates/_helpers.tpl
  charts/tigera-operator/templates/tigera-operator/00-uninstall.yaml
  charts/tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml
  charts/tigera-operator/templates/tigera-operator/02-configmap-calico-resources.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-serviceaccount-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
  manifests/ocp/02-configmap-calico-resources.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/ocp/02-rolebinding-tigera-operator.yaml
  manifests/ocp/02-serviceaccount-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#7312 update helm chart links
  charts/tigera-operator/Chart.yaml
  charts/tigera-operator/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8710 Avoid failure to add interface when XFRM is not supported by the kernel
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
  cni-plugin/tests/calico_cni_test.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/k8sfv/pod.go
Labels: release-note-required, docs-not-required

#8725 Check if ss or netstat is installed
  calicoctl/calicoctl/commands/node/diags.go
Labels: release-note-required, docs-pr-required

#8729 Add labels to node-driver-registrar.
  pod2daemon/Makefile
  pod2daemon/node-driver-registrar-docker/Dockerfile
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8730 [v3.28] Add labels to node-driver-registrar
  pod2daemon/Makefile
  pod2daemon/node-driver-registrar-docker/Dockerfile
Labels: release-note-required, docs-not-required

#8731 [release 3.28] Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8735 Add license to non-AMD64 docker images.
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: release-note-required, docs-pr-required, merge-when-ready

#8736 Add license to non-AMD64 docker images.
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: release-note-required, docs-not-required

#8738 Use mirror for downloading NSSM.
  node/Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8743 Fix Windows cni-plugin FV.
  cni-plugin/.semaphore/run-win-fv.sh
  process/testing/winfv/cloudformation-windows-server.json
  process/testing/winfv/setup-fv.sh
Labels: release-note-required, docs-pr-required

#8156 better support of ipv6-only clusters: prevent creation of default-ipv4-pool during calico-node startup
  node/pkg/lifecycle/startup/startup.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#8742 fix: close open BPF object file
  felix/bpf/attach.go
Labels: release-note-required, docs-pr-required

#8750 [release-v3.28] Auto pick #8742: fix: close open BPF object file
  felix/bpf/attach.go
Labels: release-note-required, docs-not-required

#8749 [BPF] prettier conntrack dump
  felix/bpf/conntrack/cleanup.go
  felix/bpf/conntrack/map.go
  felix/cmd/calico-bpf/commands/conntrack.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8716 Run go fix, clean up x/net/context.
  apiserver/pkg/storage/calico/bgpConfiguration_storage.go
  apiserver/pkg/storage/calico/bgpPeer_storage.go
  apiserver/pkg/storage/calico/bgpfilter_storage.go
  apiserver/pkg/storage/calico/blockAffinity_storage.go
  apiserver/pkg/storage/calico/caliconodestatus_storage.go
  apiserver/pkg/storage/calico/clusterInformation_storage.go
  apiserver/pkg/storage/calico/felixConfig_storage.go
  apiserver/pkg/storage/calico/globalNetworkPolicy_storage.go
  apiserver/pkg/storage/calico/globalNetworkSet_storage.go
  apiserver/pkg/storage/calico/hostEndpoint_storage.go
  apiserver/pkg/storage/calico/ipamconfig_storage.go
  apiserver/pkg/storage/calico/ippool_storage.go
  apiserver/pkg/storage/calico/ipreservation_storage.go
  apiserver/pkg/storage/calico/kubeControllersConfig_storage.go
  apiserver/pkg/storage/calico/networkSet_storage.go
  apiserver/pkg/storage/calico/policy_storage.go
  apiserver/pkg/storage/calico/policy_storage_test.go
  apiserver/pkg/storage/calico/profile_storage.go
  apiserver/pkg/storage/calico/resource.go
  app-policy/checker/server.go
  app-policy/proto/felixbackend.pb.go
  app-policy/proto/healthz.pb.go
  felix/fv/winfv/policy_test.go
  felix/policysync/processor_test.go
  felix/policysync/server_test.go
  libcalico-go/lib/backend/etcd/etcd.go
  libcalico-go/lib/backend/etcd/syncer.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle_test.go
  pod2daemon/binder/auth.go
  pod2daemon/binder/creds.go
  pod2daemon/protos/udsver_v1/udsver.pb.go
  pod2daemon/workloadapi/workloadapi.go
Labels: release-note-required, docs-pr-required

#8748 Merge pull request #8743 from song-jiang/song-fix-win-fv
  cni-plugin/.semaphore/run-win-fv.sh
  process/testing/winfv/cloudformation-windows-server.json
  process/testing/winfv/setup-fv.sh
Labels: release-note-required, docs-pr-required

#8754 [release-v3.28] Auto pick #8749: clean up stale ICMPv6 conntrack entries
  felix/bpf/conntrack/cleanup.go
  felix/bpf/conntrack/map.go
  felix/cmd/calico-bpf/commands/conntrack.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8712 [BPF] wg6 traffic is allowed even if blocked by policy
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/tc/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/wireguard_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8755 [release-v3.28] Auto pick #8712: wg6 traffic is allowed even if blocked by policy
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/tc/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/wireguard_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8740 Don't store Labels directly on v1 backing CRDs
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: docs-not-required, release-note-not-required

#8758 [release-v3.28] Auto pick #8740: Don't store Labels directly on v1 backing CRDs
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: docs-not-required, release-note-not-required

#8728 Try to get the newest node configuration every poll interval when monitoring IP Address subnets
  node/pkg/lifecycle/startup/startup.go
Labels: release-note-required, docs-pr-required

#8760 [BPF] Do not panic if host route does not have DstNodeIP
  felix/dataplane/linux/bpf_route_mgr.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#8761 [release-v3.28] Auto pick #8760: Do not panic if host route does not have DstNodeIP
  felix/dataplane/linux/bpf_route_mgr.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8762 Maintain projectcalico labels on v1 API
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: docs-not-required, release-note-not-required

#8763 [release-v3.28] Auto pick #8762: Maintain projectcalico labels on v1 API
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: docs-not-required, release-note-not-required

#8766 Also handle our annotations when converting v1 <-> v3
  libcalico-go/lib/backend/k8s/resources/customresource_test.go
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: release-note-required, docs-pr-required

#8768 [release-v3.28] Auto pick #8766: Also handle our annotations when converting v1 <-> v3
  libcalico-go/lib/backend/k8s/resources/customresource_test.go
  libcalico-go/lib/backend/k8s/resources/resources.go
Labels: release-note-required, docs-pr-required

#8769 [3.27] Update x/net
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#8746 Revert "Disable VXLAN checksum offload by default."
  felix/environment/feature_detect_linux.go
  felix/environment/feature_detect_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required
