Repository projectcalico/calico, pull requests merged in 2024-12, with the labels that each got.

#9514 Reduce memory used to store inactive policies/profiles
  felix/calc/active_rules_calculator.go
  felix/calc/event_sequencer.go
  felix/calc/policy_resolver.go
  felix/calc/policy_resolver_test.go
  felix/calc/policy_sorter.go
  felix/calc/policy_sorter_test.go
  libcalico-go/lib/packedmap/packedmap.go
  libcalico-go/lib/packedmap/packedmap_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#9547 [release-v3.29] Auto pick #9518: Remove CRDs from tigera-operator.yaml
  Makefile
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  manifests/generate.sh
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/ocp/crd.projectcalico.org_bgpconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_bgpfilters.yaml
  manifests/ocp/crd.projectcalico.org_bgppeers.yaml
  manifests/ocp/crd.projectcalico.org_blockaffinities.yaml
  manifests/ocp/crd.projectcalico.org_caliconodestatuses.yaml
  manifests/ocp/crd.projectcalico.org_clusterinformations.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_globalnetworkpolicies.yaml
  manifests/ocp/crd.projectcalico.org_globalnetworksets.yaml
  manifests/ocp/crd.projectcalico.org_hostendpoints.yaml
  manifests/ocp/crd.projectcalico.org_ipamblocks.yaml
  manifests/ocp/crd.projectcalico.org_ipamconfigs.yaml
  manifests/ocp/crd.projectcalico.org_ipamhandles.yaml
  manifests/ocp/crd.projectcalico.org_ippools.yaml
  manifests/ocp/crd.projectcalico.org_ipreservations.yaml
  manifests/ocp/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_networkpolicies.yaml
  manifests/ocp/crd.projectcalico.org_networksets.yaml
  manifests/ocp/crd.projectcalico.org_tiers.yaml
  manifests/ocp/operator.tigera.io_apiservers_crd.yaml
  manifests/ocp/operator.tigera.io_imagesets_crd.yaml
  manifests/ocp/operator.tigera.io_installations_crd.yaml
  manifests/ocp/operator.tigera.io_tigerastatuses_crd.yaml
  manifests/ocp/policy.networking.k8s.io_adminnetworkpolicies.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
  metadata.mk
Labels: release-note-required, docs-pr-required

#9548 [release-v3.28] Auto pick #9547: Remove CRDs from tigera-operator.yaml
  Makefile
  charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_tigerastatuses_crd.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
  manifests/generate.sh
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/ocp/crd.projectcalico.org_bgpconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_bgppeers.yaml
  manifests/ocp/crd.projectcalico.org_blockaffinities.yaml
  manifests/ocp/crd.projectcalico.org_caliconodestatuses.yaml
  manifests/ocp/crd.projectcalico.org_clusterinformations.yaml
  manifests/ocp/crd.projectcalico.org_globalnetworksets.yaml
  manifests/ocp/crd.projectcalico.org_hostendpoints.yaml
  manifests/ocp/crd.projectcalico.org_ipamblocks.yaml
  manifests/ocp/crd.projectcalico.org_ipamconfigs.yaml
  manifests/ocp/crd.projectcalico.org_ipamhandles.yaml
  manifests/ocp/crd.projectcalico.org_ippools.yaml
  manifests/ocp/crd.projectcalico.org_ipreservations.yaml
  manifests/ocp/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_networksets.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
  metadata.mk
Labels: release-note-required, docs-pr-required

#9559 Allow disabling ValidatingAdmissionPolicy for clusters that don't hav…
  apiserver/cmd/apiserver/apiserver.go
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/run_server.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/cmd/apiserver/server/server_test.go
Labels: docs-not-required, release-note-not-required

#9558 [release tool] update docker credentials helper for gcloud
  lib.Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9561 [release tool] fix building windows images for nightly hashrelease
  .semaphore/release/hashrelease.yml
  lib.Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9552 Fix coalesce-imports; avoid truncating files after error
  hack/cmd/coalesce-imports/coalesce-imports.go
Labels: docs-not-required, release-note-not-required

#9464 Add support for BaselineAdminNetworkPolicy.
  .gitignore
  Makefile
  api/pkg/apis/projectcalico/v3/tier.go
  apiserver/pkg/storage/calico/tier_storage_test.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/calicoctl/resourcemgr/globalnetworkpolicy.go
  charts/calico/templates/calico-node-rbac.yaml
  libcalico-go/Makefile
  libcalico-go/config/crd/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  libcalico-go/lib/backend/k8s/conversion/adminnetworkpolicy_test.go
  libcalico-go/lib/backend/k8s/conversion/conversion.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/resources/kubebaselineadminnetworkpolicy.go
  libcalico-go/lib/backend/model/kubeadminnetworkpolicy.go
  libcalico-go/lib/backend/model/resource.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/tier_e2e_test.go
  libcalico-go/lib/errors/errors.go
  libcalico-go/lib/names/policy.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  manifests/operator-crds.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#9544 supports custom ipFamilies
  cni-plugin/pkg/k8s/k8s.go
Labels: release-note-required, docs-pr-required

#9553 Don't run operator CRD target as part of CI check
  Makefile
Labels: release-note-required, docs-pr-required

#9554 Check code generation as part of release / hashrelease
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#9560 Split downloading and untarring docker-credential-gcr
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#9566 Use Go stdlib to get user home directory
  felix/cmd/calico-bpf/commands/root.go
  go.mod
Labels: docs-not-required, release-note-not-required

#9567 Use shirou/gopsutil v4 release version
  calicoctl/calicoctl/commands/node/status.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#9568 BANP: Reuse port unpacking logic
  libcalico-go/lib/backend/k8s/conversion/conversion.go
Labels: docs-not-required, release-note-not-required

#9555 fix: docs for upgrades to include CRD upgrade notes
  charts/tigera-operator/README.md
Labels: release-note-required, docs-pr-required

#9569 [BPF] fixed routing from outside the cluster in EKS with aws-cni
  felix/bpf-gpl/fib.h
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9534 [cherry pick] [v3.29] [release tool] Allow building and publishing image in hashrelease
  .gitignore
  .semaphore/release/hashrelease.yml
  Makefile
  apiserver/Makefile
  app-policy/Makefile
  calicoctl/Makefile
  cni-plugin/Makefile
  key-cert-provisioner/Makefile
  kube-controllers/Makefile
  node/Makefile
  release/RELEASING.md
  release/build/main.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/server.go
  release/internal/pinnedversion/pinnedversion.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
  release/pkg/manager/operator/manager.go
  release/pkg/manager/operator/options.go
  release/pkg/tasks/hashrelease.go
  typha/Makefile
Labels: docs-not-required, release-note-not-required

#9565 [release tool] restructure: main.go
  Makefile
  release/Makefile
  release/cmd/branch.go
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/cmd/release.go
Labels: docs-not-required, release-note-not-required

#9580 Add BaselineAdminNetworkPolicies RBAC to operator
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9579 [release tool] remove leftover release-verify reference
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#9506 Reduce get/update node API calls in allocate-tunnel-addrs
  node/pkg/allocateip/allocateip.go
  node/pkg/allocateip/allocateip_test.go
Labels: release-note-required, docs-not-required

#9576 Fix handling of duplicate MACs in VXLAN FDB
  felix/deltatracker/delta_tracker.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/vxlanfdb/vxlan_fdb.go
  felix/vxlanfdb/vxlan_fdb_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9577 Refactor backend API to WatchOptions struct
  calicoctl/calicoctl/commands/datastore/migrate/migrateipam_test.go
  libcalico-go/lib/backend/api/api.go
  libcalico-go/lib/backend/etcdv3/watcher.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/client.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity.go
  libcalico-go/lib/backend/k8s/resources/ipam_block.go
  libcalico-go/lib/backend/k8s/resources/ipam_config.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle.go
  libcalico-go/lib/backend/k8s/resources/k8sservice.go
  libcalico-go/lib/backend/k8s/resources/kubeadminnetworkpolicy.go
  libcalico-go/lib/backend/k8s/resources/kubebaselineadminnetworkpolicy.go
  libcalico-go/lib/backend/k8s/resources/kubeendpointslice.go
  libcalico-go/lib/backend/k8s/resources/kubenetworkpolicy.go
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/profile.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint_test.go
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  libcalico-go/lib/clientv3/resources.go
  libcalico-go/lib/ipam/ipam_block_reader_writer_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#9582 [v3.29] Fix handling of duplicate MACs in VXLAN FDB
  felix/deltatracker/delta_tracker.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/vxlanfdb/vxlan_fdb.go
  felix/vxlanfdb/vxlan_fdb_test.go
Labels: release-note-required, docs-pr-required

#9583 [v3.28] Fix handling of duplicate MACs in VXLAN FDB
  felix/deltatracker/delta_tracker.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/vxlanfdb/vxlan_fdb.go
  felix/vxlanfdb/vxlan_fdb_test.go
Labels: release-note-required, docs-not-required

#9588 Dump felix logs after a k8sfv failure.
  felix/k8sfv/run-test
Labels: docs-not-required, release-note-not-required

#9564 Squash allocations in selector parsing and other hotspots
  felix/calc/active_rules_calculator.go
  felix/calc/validation_filter.go
  felix/dataplane/linux/int_dataplane.go
  felix/iptables/table.go
  libcalico-go/Makefile
  libcalico-go/lib/selector/parser/parser.go
  libcalico-go/lib/selector/parser/parser_test.go
  libcalico-go/lib/selector/selector.go
  libcalico-go/lib/selector/selector_benchmarks_test.go
  libcalico-go/lib/selector/tokenizer/.gitattributes
  libcalico-go/lib/selector/tokenizer/kind_string.go
  libcalico-go/lib/selector/tokenizer/tokenizer.go
  libcalico-go/lib/selector/tokenizer/tokenizer_test.go
  libcalico-go/lib/validator/v1/validator.go
  libcalico-go/lib/validator/v3/validator.go
Labels: release-note-required, docs-not-required, merge-when-ready, squash-commits

#9578 [release tool] remove config package
  .semaphore/release/hashrelease.yml
  release/cmd/branch.go
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/cmd/release.go
  release/cmd/shared.go
  release/internal/command/commands.go
  release/internal/command/git.go
  release/internal/config/ci.go
  release/internal/config/config.go
  release/internal/config/operator.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/server.go
  release/internal/hashreleaseserver/ssh.go
  release/internal/imagescanner/scanner.go
  release/internal/outputs/releasenotes.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/slack/slack.go
  release/internal/utils/git.go
  release/internal/utils/utils.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/operator/manager.go
  release/pkg/manager/operator/options.go
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9594 Fix cross build for node-driver-registrar
  pod2daemon/Makefile
Labels: release-note-required, docs-pr-required

#9571 Regenerate manifests using the latest controller-tools release
  felix/config/metadata.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/Makefile
  libcalico-go/config.patch
  libcalico-go/config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_bgpfilters.yaml
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  libcalico-go/config/crd/crd.projectcalico.org_blockaffinities.yaml
  libcalico-go/config/crd/crd.projectcalico.org_caliconodestatuses.yaml
  libcalico-go/config/crd/crd.projectcalico.org_clusterinformations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_globalnetworkpolicies.yaml
  libcalico-go/config/crd/crd.projectcalico.org_globalnetworksets.yaml
  libcalico-go/config/crd/crd.projectcalico.org_hostendpoints.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamblocks.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamconfigs.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipamhandles.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ippools.yaml
  libcalico-go/config/crd/crd.projectcalico.org_ipreservations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_networkpolicies.yaml
  libcalico-go/config/crd/crd.projectcalico.org_networksets.yaml
  libcalico-go/config/crd/crd.projectcalico.org_tiers.yaml
  libcalico-go/lib/apis/crd.projectcalico.org/v1/clusterinformation_types.go
  libcalico-go/patches/0001-Add-nullable-to-IPAM-block-allocations-field.patch
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9596 [release tool] pass in GitHub token as flag for actual release
  release/cmd/flags.go
  release/cmd/release.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
Labels: docs-not-required, release-note-not-required

#9601 [release-v3.29] Auto pick #9594: Fix cross build for node-driver-registrar
  pod2daemon/Makefile
Labels: release-note-required, docs-pr-required

#9602 [release-v3.28] Auto pick #9594: Fix cross build for node-driver-registrar
  pod2daemon/Makefile
Labels: release-note-required, docs-pr-required

#9606 Bump Go dependency and utility versions
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9600 [EV-5470] unify logging to logrus in calico-apiserver
  apiserver/cmd/apiserver/apiserver.go
  apiserver/cmd/apiserver/server/logging.go
  apiserver/cmd/apiserver/server/logging_test.go
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/run_server.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/pkg/registry/projectcalico/authorizer/authorizer.go
  apiserver/pkg/registry/projectcalico/server/options.go
  apiserver/pkg/storage/calico/converter.go
  apiserver/pkg/storage/calico/policy_storage_test.go
  apiserver/pkg/storage/calico/resource.go
  apiserver/pkg/storage/calico/storage_interface.go
  apiserver/pkg/storage/calico/tier_storage_test.go
  apiserver/test/integration/framework.go
  apiserver/test/util/util.go
Labels: release-note-required, docs-pr-required

#9609 Fix netlink leak
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/tests/calico_cni_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/etcd_restart_test.go
  felix/fv/ipip_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9612 [v3.29] Fix netlink leak (#9609)
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/tests/calico_cni_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/etcd_restart_test.go
  felix/fv/ipip_test.go
Labels: release-note-required, docs-not-required

#9595 [release tool] refactor pinnedversion
  release/cmd/hashrelease.go
  release/cmd/release.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/pinnedversion/templates/calico-versions.yaml.gotmpl
  release/internal/version/version.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9498 Enhance bpf interface autodetection
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/precompilation_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/bpf_attach_test.go
  felix/fv/bpf_test.go
  felix/fv/donottrack_test.go
  felix/netlinkshim/mocknetlink/netlink.go
Labels: release-note-required, docs-pr-required

#9617 use fedora archives url for iptables src rpm
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: docs-not-required, release-note-not-required

#9590 [BPF] extra conntrack counters and stats
  felix/Makefile
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/counters.h
  felix/bpf-gpl/reasons.h
  felix/bpf-gpl/tc.c
  felix/bpf/counters/counters.go
  felix/bpf/counters/counters_test.go
  felix/bpf/counters/map.go
  felix/bpf/ut/nat_test.go
  felix/cmd/calico-bpf/commands/conntrack.go
  felix/fv/bpf_counters_test.go
  node/Makefile
Labels: release-note-required, docs-pr-required

#9629 [release-v3.29] Auto pick #9569: fixe routing from outide the cluster in EKS
  felix/bpf-gpl/fib.h
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9614 Fix name clash in Makefile variables.
  hack/find-parent-release-branch.sh
  hack/format-changed-files.sh
  lib.Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9616 [release-tool] refactor update branch command and manager
  release/cmd/branch.go
  release/cmd/flags.go
  release/internal/version/version.go
  release/pkg/manager/branch/manager.go
Labels: docs-not-required, release-note-not-required

#9545 [BPF] programs profiling
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/profiling.h
  felix/bpf-gpl/tc.c
  felix/bpf/attach.go
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/profiling/map.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
  felix/cmd/calico-bpf/commands/counters.go
  felix/cmd/calico-bpf/commands/profiling.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/bpf_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-not-required

#9633 Add BANP validation
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: docs-not-required, release-note-not-required

#9570 Restrict tigera-operator secret access to namespace only, retain get/…
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator-secrets.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator-secrets.yaml
  manifests/ocp/02-role-tigera-operator-secrets.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/ocp/02-rolebinding-tigera-operator-secrets.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9637 CAPZ Win FVs: use AZ_KUBE_VERSION for kube-proxy-windows
  process/testing/winfv-felix/capz/create-cluster.sh
  process/testing/winfv-felix/capz/export-env.sh
  process/testing/winfv-felix/capz/install-calico.sh
  process/testing/winfv-felix/infra/setup.sh
  process/testing/winfv-felix/run-fv-cni-plugin.ps1
  process/testing/winfv-felix/setup-fv-capz.sh
Labels: docs-not-required, release-note-not-required

#9643 cherry-pick #9570 Restrict tigera-operator secret access to namespace only, retain get/…
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator-secrets.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator-secrets.yaml
  manifests/ocp/02-role-tigera-operator-secrets.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/ocp/02-rolebinding-tigera-operator-secrets.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9639 Bpf build improvements
  felix/.gitignore
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/calculate-flags
  felix/bpf-gpl/list-objs
  felix/bpf-gpl/nat_lookup.h
  felix/bpf/nat/connecttime.go
  felix/bpf/ut/precompilation_test.go
Labels: docs-not-required, release-note-not-required

#9644 CAPZ: add wait for felixconfig before setting debug logging
  process/testing/winfv-felix/setup-fv-capz.sh
Labels: docs-not-required, release-note-not-required

#9626 [cherrypick 3.29] use fedora archives url for iptables src rpm (#9617)
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: docs-not-required, release-note-not-required

#9628 [cherrypick 3.28] use fedora archives url for iptables src rpm (#9617)
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: docs-not-required, release-note-not-required

#9640 Build with semaphore Ubuntu 22.04
  .semaphore/cleanup.yml
  .semaphore/license-scanning/fossa-scan.yml
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/key-cert-provisioner.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/pod2daemon.yml
  .semaphore/push-images/typha.yml
  .semaphore/release/cut-branch.yml
  .semaphore/release/hashrelease.yml
  .semaphore/release/release.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/01-preamble.yml
  .semaphore/semaphore.yml.d/blocks/20-apiserver.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  .semaphore/semaphore.yml.d/blocks/20-kube-controllers.yml
  .semaphore/semaphore.yml.d/blocks/20-node.yml
  .semaphore/semaphore.yml.d/blocks/20-typha.yml
  .semaphore/semaphore.yml.d/blocks/30-key-cert-provisioner.yml
  api/.semaphore/semaphore.yml
  cni-plugin/.semaphore/cleanup.yml
  cni-plugin/.semaphore/semaphore.yml
  cni-plugin/.semaphore/update_pins.yml
  felix/.semaphore/cleanup.yml
  felix/.semaphore/update_pins.yml
Labels: docs-not-required, release-note-not-required

#9649 Update hashrelease operator branch
  .semaphore/release/hashrelease.yml
Labels: docs-not-required, release-note-not-required

#9650 Add suite for ipset mgr
  felix/dataplane/ipsets/ipsets_mgr_ut_suite_test.go
Labels: docs-not-required, release-note-not-required

#9556 fix: docs for upgrades to include CRD upgrade notes
  charts/tigera-operator/README.md
Labels: release-note-required, docs-pr-required

#9634 [release tool] refactor generating hashrelease and release
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/cmd/release.go
  release/internal/hashreleaseserver/server.go
  release/internal/imagescanner/scanner.go
  release/internal/outputs/releasenotes.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/utils/utils.go
  release/internal/version/version.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/operator/manager.go
  release/pkg/manager/operator/options.go
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9655 Revert "cherry-pick #9570 Restrict tigera-operator secret access to namespace only, retain get/…"
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator-secrets.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator-secrets.yaml
  manifests/ocp/02-role-tigera-operator-secrets.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/ocp/02-rolebinding-tigera-operator-secrets.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9659 Load value from metadata.mk in release tool
  release/Makefile
  release/cmd/release.go
Labels: docs-not-required, release-note-not-required

#9660 Load value from metadata.mk in release tool (#9659)
  .semaphore/release/hashrelease.yml
  release/Makefile
Labels: docs-not-required, release-note-not-required

#9661 [release tool] fix hashrelease failure
  release/Makefile
  release/internal/hashreleaseserver/server.go
  release/internal/hashreleaseserver/ssh.go
Labels: docs-not-required, release-note-not-required
