Repository projectcalico/calico, pull requests merged in 2024-09, with the labels that each got.

#9208 Bump flannel to v0.24.4
  charts/calico/values.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#9183 Netlink retry for list APIs in cni-plugin
  cni-plugin/internal/pkg/testutils/utils_linux.go
  cni-plugin/pkg/dataplane/linux/dataplane_linux.go
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/tests/calico_cni_test.go
  felix/fv/etcd_restart_test.go
  felix/fv/ipip_test.go
  felix/fv/netlinkutils/netlinkutils.go
  libcalico-go/lib/netlinkutils/netlinkutils.go
Labels: docs-not-required, release-note-not-required

#9062 Windows: Support running on non-English system
  cni-plugin/pkg/dataplane/windows/dataplane_windows.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#9012 Replace PyTest postrelease tests with Golang postrelease tests
  hack/postrelease/golang/README.md
  hack/postrelease/golang/go.mod
  hack/postrelease/golang/go.sum
  hack/postrelease/golang/pkg/container/container.go
  hack/postrelease/golang/pkg/github/github.go
  hack/postrelease/golang/pkg/helm/helm.go
  hack/postrelease/golang/pkg/openstack/openstack.go
  hack/postrelease/golang/pkg/registry/registry.go
  hack/postrelease/golang/pkg/utils/download.go
  hack/postrelease/golang/pkg/variables/oss_defaults.go
  hack/postrelease/golang/tests/operator/images/images_test.go
  hack/postrelease/golang/tests/oss/github/calico/github_calico_test.go
  hack/postrelease/golang/tests/oss/github/flannel/github_flannel_test.go
  hack/postrelease/golang/tests/oss/helm/helm_test.go
  hack/postrelease/golang/tests/oss/images/images_test.go
  hack/postrelease/golang/tests/oss/openstack/openstack_test.go
Labels: docs-not-required, release-note-not-required

#9214 [releae tool] fix publishing hashrelease
  release/internal/hashrelease/hashrelease.go
  release/internal/slack/templates/success.json.gotmpl
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9134 Remove outdated check-licenses scripts
  felix/check-licenses/.gitignore
  felix/check-licenses/check_licenses.go
  typha/check-licenses/.gitignore
  typha/check-licenses/check_licenses.go
  typha/utils/run-coverage
Labels: docs-not-required, release-note-not-required

#9140 Integrate release and hashrelease logic
  .gitignore
  .semaphore/push-images/packaging.yaml
  .semaphore/release/release.yml
  Makefile
  hack/release/.gitignore
  hack/release/Makefile
  hack/release/cmd/main.go
  hack/release/pkg/builder/builder_test.go
  hack/release/remote-execute.sh
  hack/release/terraform.tf
  hack/release/variables.tf
  lib.Makefile
  metadata.mk
  release/.gitignore
  release/Makefile
  release/RELEASING.md
  release/build/main.go
  release/get-contributors.py
  release/internal/command/commands.go
  release/internal/command/runner.go
  release/internal/config/config.go
  release/internal/hashrelease/pinnedversion.go
  release/internal/outputs/calico.go
  release/internal/outputs/release.go
  release/internal/outputs/releasenotes.go
  release/internal/utils/files.go
  release/internal/utils/git.go
  release/internal/version/version.go
  release/internal/version/version_test.go
  release/packaging/.gitignore
  release/packaging/LICENSE
  release/packaging/Makefile
  release/packaging/README.md
  release/packaging/docker-build-images/centos7-build.Dockerfile.amd64
  release/packaging/docker-build-images/centos7-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/docker-bake.hcl
  release/packaging/docker-build-images/install-centos-build-deps
  release/packaging/docker-build-images/install-ubuntu-build-deps
  release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/ubuntu-jammy-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-jammy-build.Dockerfile.ppc64le
  release/packaging/etcd3gw/rpm/python-etcd3gw.spec
  release/packaging/rpm/build-rpms
  release/packaging/utils/create-update-packages.sh
  release/packaging/utils/lib.sh
  release/packaging/utils/make-packages.sh
  release/packaging/utils/publish-debs.sh
  release/packaging/utils/publish-rpms.sh
  release/pkg/builder/builder.go
  release/pkg/builder/builder_suite_test.go
  release/pkg/builder/options.go
  release/pkg/tasks/hashrelease.go
  release/pkg/tasks/operator.go
  release/pkg/tasks/release.go
Labels: docs-not-required, release-note-not-required

#9225 [release tool] hashrelease: fix sending images to ISS
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9227 [release tool] halt hash release process early if already published
  release/build/main.go
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9082 Remove the unnecessary check of non-calico ipsets in resynIPSet
  felix/ipsets/ipsets.go
Labels: docs-not-required, release-note-not-required

#9230 Ignore empty CIDRs in BGPConfiguration
  confd/pkg/backends/calico/client.go
  confd/tests/mock_data/calicoctl/mesh/static-routes/input.yaml
  felix/calc/event_sequencer.go
Labels: release-note-required, docs-not-required

#9224 [v3.28] Update go to v1.22.7
  felix/fv/service_loop_prevention_test.go
  kube-controllers/cmd/kube-controllers/fv_test.go
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/tests/testutils/policy_controller_utils.go
  metadata.mk
  node/tests/k8st/infra/calicoctl.yaml
Labels: release-note-required, docs-not-required

#9234 Don't run release validation on hashreleases
  release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#9178 Configure Certificate Rotation for the Kubelet
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
Labels: release-note-required, docs-not-required, area/windows

#9206 Add AdminNetworkPolicy
  Makefile
  api/pkg/apis/projectcalico/v3/tier.go
  apiserver/pkg/storage/calico/policy_storage.go
  apiserver/pkg/storage/calico/tier_storage_test.go
  calicoctl/calicoctl/commands/convert.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/calicoctl/commands/datastore/migrate/import.go
  calicoctl/calicoctl/resourcemgr/globalnetworkpolicy.go
  calicoctl/calicoctl/resourcemgr/networkpolicy.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
  charts/calico/templates/calico-node-rbac.yaml
  e2e/Makefile
  e2e/cmd/adminpolicy/e2e_test.go
  e2e/cmd/k8s/e2e_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/infrastructure/infra_k8s.go
  felix/rules/endpoints.go
  go.mod
  go.sum
  kube-controllers/pkg/controllers/networkpolicy/policy_controller.go
  libcalico-go/Makefile
  libcalico-go/config/crd/policy.networking.k8s.io_adminnetworkpolicies.yaml
  libcalico-go/lib/backend/k8s/conversion/adminnetworkpolicy_test.go
  libcalico-go/lib/backend/k8s/conversion/constants.go
  libcalico-go/lib/backend/k8s/conversion/conversion.go
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/kubeadminnetworkpolicy.go
  libcalico-go/lib/backend/model/kubeadminnetworkpolicy.go
  libcalico-go/lib/backend/model/resource.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/globalnetworkpolicyprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/networkpolicyprocessor_test.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/tier.go
  libcalico-go/lib/clientv3/tier_e2e_test.go
  libcalico-go/lib/errors/errors.go
  libcalico-go/lib/names/policy.go
  libcalico-go/lib/names/policy_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/policy.networking.k8s.io_adminnetworkpolicies.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
  node/tests/k8st/infra/calico-kdd.yaml
  node/tests/st/policy/test_tiered_policy.py
Labels: release-note-required, docs-pr-required

#9213 [BPF] Use bpf_redirect_peer when CALI_CT_ESTABLISHED_BYPASS
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/nat_test.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#9232 Introduce default action in tiers
  api/pkg/apis/projectcalico/v3/tier.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/calc/event_sequencer.go
  felix/calc/policy_resolver.go
  felix/calc/policy_sorter.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/fv/tiered_policy_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  libcalico-go/config/crd/crd.projectcalico.org_tiers.yaml
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/model/tier.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/tierprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/tierprocessor_test.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/tier_e2e_test.go
  libcalico-go/lib/resources/tier.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_tiers.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#9242 log csidriver root error when failing to retrieve pod info
  pod2daemon/csidriver/driver/node.go
Labels: docs-not-required, release-note-not-required

#9240 Add configuration for publishing a release in parts
  release/build/main.go
  release/pkg/builder/builder.go
  release/pkg/builder/options.go
Labels: docs-not-required, release-note-not-required

#9241 [release tool] setup hashrelease for v3.29
  .semaphore/release/hashrelease.yml
Labels: docs-not-required, release-note-not-required

#9247 Build windows in correct dir
  release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#9248 Fix release notes output dir
  release/internal/outputs/releasenotes.go
Labels: docs-not-required, release-note-not-required

#9249 [release-v3.29] Auto pick #9248: Fix release notes output dir
  release/internal/outputs/releasenotes.go
Labels: docs-not-required, release-note-not-required

#9250 publishing fixes
  release/build/main.go
  release/internal/hashrelease/pinnedversion.go
  release/internal/imagescanner/scanner.go
  release/internal/version/version.go
  release/pkg/tasks/hashrelease.go
  release/pkg/tasks/release.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#9245 [Release v3.29] Introduce default action in tiers
  api/pkg/apis/projectcalico/v3/tier.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/calc/event_sequencer.go
  felix/calc/policy_resolver.go
  felix/calc/policy_sorter.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/fv/tiered_policy_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  libcalico-go/config/crd/crd.projectcalico.org_tiers.yaml
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/model/tier.go
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/tierprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/tierprocessor_test.go
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/tier_e2e_test.go
  libcalico-go/lib/resources/tier.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_tiers.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#9251 Fix building of image tar file
  release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#9252 publishing fixes (#9250)
  release/build/main.go
  release/internal/hashrelease/pinnedversion.go
  release/internal/imagescanner/scanner.go
  release/internal/version/version.go
  release/pkg/tasks/hashrelease.go
  release/pkg/tasks/release.go
Labels: docs-not-required, release-note-not-required

#9253 [release-v3.29] Auto pick #9251: Fix building of image tar file
  release/pkg/builder/builder.go
Labels: docs-not-required, release-note-not-required

#9246 Various fixes to (hash)release builder
  cni-plugin/Makefile
  release/README.md
  release/build/main.go
  release/internal/config/config.go
  release/internal/hashrelease/pinnedversion.go
  release/pkg/builder/builder.go
  release/pkg/builder/options.go
  release/pkg/tasks/hashrelease.go
  release/pkg/tasks/operator.go
Labels: docs-not-required, release-note-not-required

#9261 fix hashrelease for v3.29
  release/internal/hashrelease/hashrelease.go
  release/internal/hashrelease/pinnedversion.go
  release/internal/slack/slack.go
  release/internal/slack/templates/failure.json.gotmpl
  release/internal/slack/templates/success.json.gotmpl
  release/pkg/tasks/hashrelease.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#9257 Add key-cert-provisioner to tested calico images [v3.29]
  hack/postrelease/golang/tests/oss/github/calico/github_calico_test.go
  hack/postrelease/golang/tests/oss/helm/helm_test.go
  hack/postrelease/golang/tests/oss/images/images_test.go
  hack/postrelease/golang/tests/oss/openstack/openstack_test.go
Labels: docs-not-required, release-note-not-required

#9256 Add key-cert-provisioner to tested calico images
  hack/postrelease/golang/tests/oss/github/calico/github_calico_test.go
  hack/postrelease/golang/tests/oss/helm/helm_test.go
  hack/postrelease/golang/tests/oss/images/images_test.go
  hack/postrelease/golang/tests/oss/openstack/openstack_test.go
Labels: docs-not-required, release-note-not-required

#9263 fix manifest generation
  manifests/generate.sh
Labels: release-note-required, cherry-pick-candidate, docs-pr-required

#9262 [cherry-pick] fix hashrelease for v3.29
  release/internal/hashrelease/hashrelease.go
  release/internal/hashrelease/pinnedversion.go
  release/internal/slack/slack.go
  release/internal/slack/templates/failure.json.gotmpl
  release/internal/slack/templates/success.json.gotmpl
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9258 [BPF] ipsets debug enhancements
  felix/bpf-gpl/globals.h
  felix/bpf/ipsets/map.go
  felix/bpf/ipsets/map6.go
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#9264 Dump ipset IDs in bpf policy dump
  felix/bpf/polprog/pol_prog_builder.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/fv/bpf_policy_dump_test.go
Labels: docs-not-required, release-note-not-required

#9273 [release-v3.29] Auto pick #9264: Dump ipset IDs in bpf policy dump
  felix/bpf/polprog/pol_prog_builder.go
  felix/cmd/calico-bpf/commands/policy_debug.go
  felix/fv/bpf_policy_dump_test.go
Labels: docs-not-required, release-note-not-required

#9270 Use Golang v1.23.1
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
  apiserver/pkg/registry/projectcalico/authorizer/authorizer.go
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/calicoctl/commands/delete.go
  calicoctl/calicoctl/commands/get.go
  calicoctl/calicoctl/commands/node/run.go
  calicoctl/calicoctl/commands/patch.go
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  cni-plugin/internal/pkg/azure/network.go
  cni-plugin/pkg/plugin/plugin.go
  confd/Makefile
  felix/aws/ec2_test.go
  felix/config/config_params.go
  felix/iptables/restore_buffer.go
  go.mod
  go.sum
  kube-controllers/Makefile
  kube-controllers/pkg/controllers/node/node_controller_fv_test.go
  kube-controllers/tests/testutils/node_controller_utils.go
  lib.Makefile
  libcalico-go/Makefile
  libcalico-go/lib/backend/k8s/conversion/conversion.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle.go
  libcalico-go/lib/backend/model/block.go
  libcalico-go/lib/backend/model/resource.go
  libcalico-go/lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/bgpnodeprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/felixnodeprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/profileprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/profileprocessor_test.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  libcalico-go/lib/client/node.go
  libcalico-go/lib/clientv3/common_test.go
  libcalico-go/lib/clientv3/node_e2e_test.go
  libcalico-go/lib/errors/errors.go
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block_reader_writer_test.go
  libcalico-go/lib/testutils/resources.go
  libcalico-go/lib/testutils/syncertester.go
  libcalico-go/lib/upgrade/converters/node.go
  libcalico-go/lib/upgrade/converters/workloadendpoint_test.go
  libcalico-go/lib/upgrade/migrator/migrate_test.go
  metadata.mk
  node/pkg/health/health.go
  release/internal/registry/dockerrunner.go
Labels: release-note-required, docs-pr-required

#9274 Adjust operator for deletion and possible creation of mutatingwebhooks
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
  process/testing/winfv-felix/capz/install-calico.sh
  process/testing/winfv-felix/setup-fv-capz.sh
  process/testing/winfv-felix/setup-fv.sh
Labels: cherry-pick-completed, docs-not-required, release-note-not-required

#9275 [release-v3.29] Auto pick #9274: Adjust operator for deletion and possible creation of
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
  process/testing/winfv-felix/capz/install-calico.sh
  process/testing/winfv-felix/setup-fv-capz.sh
  process/testing/winfv-felix/setup-fv.sh
Labels: cherry-pick-completed, docs-not-required, release-note-not-required

#9266 [cherry-pick] [v3.28] fix manifest generation
  manifests/flannel-migration/migration-job.yaml
  manifests/generate.sh
Labels: release-note-required, docs-pr-required

#9267 [cherry-pick] [v3.27] fix manifest generation
  manifests/flannel-migration/migration-job.yaml
  manifests/generate.sh
Labels: release-note-required, docs-pr-required

#9265 [cherry-pick] [v3.29] fix manifest generation
  manifests/generate.sh
Labels: release-note-required, docs-pr-required

#9280 semaphore rebuild failed job
  .semaphore/rerun_failed_jobs.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/03-promotions.yml
Labels: docs-not-required, release-note-not-required

#9282 remove unnecessary namespace param
  libcalico-go/lib/backend/k8s/conversion/conversion.go
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
Labels: docs-not-required, release-note-not-required

#9281 Add KSP to release building
  hack/release/pkg/builder/builder.go
  key-cert-provisioner/Makefile
Labels: docs-not-required, release-note-not-required

#9283 [release tool] security fixes
  go.mod
  go.sum
  release/internal/command/ssh.go
  release/internal/imagescanner/scanner.go
Labels: docs-not-required, release-note-not-required

#9233 Felix FVs: Periodically log system stats.
  felix/fv/fv_suite_test.go
Labels: docs-not-required, release-note-not-required

#9269 felix/ifacemonitor: use `regexp.MatchString` to reduce allocs
  felix/config/param_types.go
  felix/ifacemonitor/iface_monitor.go
Labels: docs-not-required, release-note-not-required
