Repository projectcalico/calico, pull requests merged in 2024-05, with the labels that each got.

#8658 Clean up openstack release promotions [cp 8657]
  .semaphore/release/release.yml
Labels: docs-not-required, release-note-not-required

#8779 Updates for 3.28.0
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/alp/istio-inject-configmap-1.1.0.yaml
  manifests/alp/istio-inject-configmap-1.1.1.yaml
  manifests/alp/istio-inject-configmap-1.1.10.yaml
  manifests/alp/istio-inject-configmap-1.1.11.yaml
  manifests/alp/istio-inject-configmap-1.1.12.yaml
  manifests/alp/istio-inject-configmap-1.1.13.yaml
  manifests/alp/istio-inject-configmap-1.1.14.yaml
  manifests/alp/istio-inject-configmap-1.1.15.yaml
  manifests/alp/istio-inject-configmap-1.1.16.yaml
  manifests/alp/istio-inject-configmap-1.1.17.yaml
  manifests/alp/istio-inject-configmap-1.1.2.yaml
  manifests/alp/istio-inject-configmap-1.1.3.yaml
  manifests/alp/istio-inject-configmap-1.1.4.yaml
  manifests/alp/istio-inject-configmap-1.1.5.yaml
  manifests/alp/istio-inject-configmap-1.1.6.yaml
  manifests/alp/istio-inject-configmap-1.1.7.yaml
  manifests/alp/istio-inject-configmap-1.1.8.yaml
  manifests/alp/istio-inject-configmap-1.1.9.yaml
  manifests/alp/istio-inject-configmap-1.10.yaml
  manifests/alp/istio-inject-configmap-1.15.yaml
  manifests/alp/istio-inject-configmap-1.2.0.yaml
  manifests/alp/istio-inject-configmap-1.2.1.yaml
  manifests/alp/istio-inject-configmap-1.2.2.yaml
  manifests/alp/istio-inject-configmap-1.2.3.yaml
  manifests/alp/istio-inject-configmap-1.2.4.yaml
  manifests/alp/istio-inject-configmap-1.2.5.yaml
  manifests/alp/istio-inject-configmap-1.2.6.yaml
  manifests/alp/istio-inject-configmap-1.2.7.yaml
  manifests/alp/istio-inject-configmap-1.2.8.yaml
  manifests/alp/istio-inject-configmap-1.2.9.yaml
  manifests/alp/istio-inject-configmap-1.3.0.yaml
  manifests/alp/istio-inject-configmap-1.3.1.yaml
  manifests/alp/istio-inject-configmap-1.3.2.yaml
  manifests/alp/istio-inject-configmap-1.3.3.yaml
  manifests/alp/istio-inject-configmap-1.3.4.yaml
  manifests/alp/istio-inject-configmap-1.3.5.yaml
  manifests/alp/istio-inject-configmap-1.4.0.yaml
  manifests/alp/istio-inject-configmap-1.4.1.yaml
  manifests/alp/istio-inject-configmap-1.4.2.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  manifests/alp/istio-inject-configmap-1.9.yaml
  manifests/apiserver.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/calicoctl-etcd.yaml
  manifests/calicoctl.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/csi-driver.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator.yaml
  release-notes/v3.28.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#8793 Update release notes for v3.28.0
  release-notes/v3.28.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#8781 Increase some wg fv timeouts
  felix/fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8792 Set mount type to DirectoryOrCreate for hostPath needed by Calico
  charts/calico/templates/calico-node.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#8797 [Release v3.27] Set mount type to DirectoryOrCreate for hostPath needed by Calico
  charts/calico/templates/calico-node.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required

#8800 Update go in cni
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8799 [release-v3.28] Use correct calico/go-build arch when cross-compiling felix
  felix/Makefile
  lib.Makefile
  node/Makefile
Labels: release-note-required, docs-pr-required

#8801 Automated cherry pick of #8800: Update go in cni
  cni-plugin/Makefile
Labels: docs-not-required, release-note-not-required

#8802 Bump go version in release notes
  release-notes/v3.28.0-release-notes.md
Labels: release-note-required, docs-pr-required

#8798 Fix flake in CNI readiness_gates test
  cni-plugin/tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#8795 Address some bpf fv flakes
  felix/bpf/bpf.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#8806 Add qemu emulated arm64 node image build
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: release-note-required, docs-pr-required

#8807 [release-v3.28] Add qemu emulated arm64 node image build
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: release-note-required, docs-pr-required

#8809 Release scripts fixes for FIPS and Openstack
  .semaphore/push-images/node.yml
  .semaphore/release/release.yml
  apiserver/Makefile
  app-policy/Makefile
  cni-plugin/Makefile
  felix/Makefile
  hack/postrelease/test_images.py
  hack/release/pkg/builder/builder.go
  key-cert-provisioner/Makefile
  kube-controllers/Makefile
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Makefile
  pod2daemon/Makefile
  release-notes/v3.28.0-release-notes.md
  typha/Makefile
Labels: docs-not-required, release-note-not-required

#8813 Use oracle.com repo for iptables-epel-1.8.8
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: docs-not-required, release-note-not-required

#8796 [Release v3.28] Set mount type to DirectoryOrCreate for hostPath needed by Calico
  charts/calico/templates/calico-node.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: hold-merge, docs-not-required, release-note-not-required

#8816 Skip parsing empty service address
  confd/pkg/backends/calico/routes.go
Labels: docs-not-required, release-note-not-required

#8820 [BPF] .d files for ut objs so that uts recompile correctly
  felix/bpf-gpl/Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8711 chore: fix function names in comment
  api/pkg/lib/numorstring/protocol.go
  apiserver/cmd/apiserver/server/server.go
  apiserver/pkg/storage/calico/resource.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#8827 [CORE-10412] Improve cni-plugin binary install verification
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-not-required

#8814 Update postrelease tests for v3.28
  Makefile
  hack/postrelease/.gitignore
  hack/postrelease/Dockerfile
  hack/postrelease/Makefile
  hack/postrelease/pytest.ini
  hack/postrelease/requirements.txt
  hack/postrelease/test_helm_artifacts.py
  hack/postrelease/test_images.py
  hack/postrelease/test_manifests_archives.py
  hack/postrelease/test_openstack_artifacts.py
  hack/postrelease/test_projectcalico_docs_updated.py
  hack/postrelease/test_tags_tars.py
  hack/postrelease/test_windows_artifacts.py
  hack/postrelease/tests/conftest.py
  hack/postrelease/tests/test_helm_artifacts.py
  hack/postrelease/tests/test_images.py
  hack/postrelease/tests/test_manifests_archives.py
  hack/postrelease/tests/test_openstack_artifacts.py
  hack/postrelease/tests/test_projectcalico_docs_updated.py
  hack/postrelease/tests/test_tags_tars.py
  hack/postrelease/tests/utilities.py
  hack/postrelease/tests/variables.py
  hack/postrelease/variables.mk
  hack/postrelease/versions.py
Labels: docs-not-required, release-note-not-required

#8830 upgrade libbpf to 1.4.2
  felix/bpf-gpl/include/libbpf/BPF-CHECKPOINT-COMMIT
  felix/bpf-gpl/include/libbpf/CHECKPOINT-COMMIT
  felix/bpf-gpl/include/libbpf/README.md
  felix/bpf-gpl/include/libbpf/ci/diffs/0001-arch-Kconfig-Move-SPECULATION_MITIGATIONS-to-arch-Kc.patch
  felix/bpf-gpl/include/libbpf/ci/diffs/0002-xdp-bonding-Fix-feature-flags-when-there-are-no-slav.patch
  felix/bpf-gpl/include/libbpf/ci/vmtest/configs/ALLOWLIST-5.5.0
  felix/bpf-gpl/include/libbpf/ci/vmtest/configs/DENYLIST
  felix/bpf-gpl/include/libbpf/ci/vmtest/configs/DENYLIST-5.5.0
  felix/bpf-gpl/include/libbpf/ci/vmtest/configs/DENYLIST-latest
  felix/bpf-gpl/include/libbpf/ci/vmtest/configs/DENYLIST-latest.s390x
  felix/bpf-gpl/include/libbpf/ci/vmtest/run_selftests.sh
  felix/bpf-gpl/include/libbpf/docs/conf.py
  felix/bpf-gpl/include/libbpf/docs/program_types.rst
  felix/bpf-gpl/include/libbpf/docs/sphinx/requirements.txt
  felix/bpf-gpl/include/libbpf/include/linux/filter.h
  felix/bpf-gpl/include/libbpf/include/linux/kernel.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/bpf.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/fcntl.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/if_link.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/if_xdp.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/netdev.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/perf_event.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/pkt_cls.h
  felix/bpf-gpl/include/libbpf/include/uapi/linux/pkt_sched.h
  felix/bpf-gpl/include/libbpf/scripts/build-fuzzers.sh
  felix/bpf-gpl/include/libbpf/scripts/mailmap-update.sh
  felix/bpf-gpl/include/libbpf/scripts/sync-kernel.sh
  felix/bpf-gpl/include/libbpf/src/Makefile
  felix/bpf-gpl/include/libbpf/src/bpf.c
  felix/bpf-gpl/include/libbpf/src/bpf.h
  felix/bpf-gpl/include/libbpf/src/bpf_core_read.h
  felix/bpf-gpl/include/libbpf/src/bpf_helper_defs.h
  felix/bpf-gpl/include/libbpf/src/bpf_helpers.h
  felix/bpf-gpl/include/libbpf/src/bpf_tracing.h
  felix/bpf-gpl/include/libbpf/src/btf.c
  felix/bpf-gpl/include/libbpf/src/btf_dump.c
  felix/bpf-gpl/include/libbpf/src/elf.c
  felix/bpf-gpl/include/libbpf/src/features.c
  felix/bpf-gpl/include/libbpf/src/gen_loader.c
  felix/bpf-gpl/include/libbpf/src/hashmap.h
  felix/bpf-gpl/include/libbpf/src/libbpf.c
  felix/bpf-gpl/include/libbpf/src/libbpf.h
  felix/bpf-gpl/include/libbpf/src/libbpf.map
  felix/bpf-gpl/include/libbpf/src/libbpf_common.h
  felix/bpf-gpl/include/libbpf/src/libbpf_internal.h
  felix/bpf-gpl/include/libbpf/src/libbpf_probes.c
  felix/bpf-gpl/include/libbpf/src/libbpf_version.h
  felix/bpf-gpl/include/libbpf/src/linker.c
  felix/bpf-gpl/include/libbpf/src/netlink.c
  felix/bpf-gpl/include/libbpf/src/relo_core.c
  felix/bpf-gpl/include/libbpf/src/ringbuf.c
  felix/bpf-gpl/include/libbpf/src/str_error.c
  felix/bpf-gpl/include/libbpf/src/str_error.h
  felix/bpf-gpl/include/libbpf/src/usdt.bpf.h
  felix/bpf-gpl/include/libbpf/src/usdt.c
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8826 Fix libbpf make
  felix/Makefile
Labels: docs-not-required, release-note-not-required

#8844 [release-v3.28] Manual pick #8827: Improve cni-plugin binary install verification
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8841 [release-v3.27] Manual pick #8827: Improve cni-plugin binary install verification
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8842 [release-v3.26] Manual pick #8827: Improve cni-plugin binary install verification
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8845 [release-v3.28] Auto pick #8798: Fix flake CORE-10163: controller-manager GC races with
  cni-plugin/tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#8847 [release-v3.26] Auto pick #8798: Fix flake CORE-10163: controller-manager GC races with
  cni-plugin/tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#8848 [release-v3.27] Auto pick #8798: Fix flake CORE-10163: controller-manager GC races with
  cni-plugin/tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#8815 [release-v3.27] Auto pick #8813: Use oracle.com repo for iptables-epel-1.8.8
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/calico_test/Dockerfile.amd64.calico_test
Labels: docs-not-required, release-note-not-required

#8851 Update CodeQL to v3
  .github/workflows/codeql.yml
  api/go.mod
  go.mod
Labels: release-note-required, docs-pr-required

#8865 fix(charts/tigera-operator/kubernetes-services-endpoint): quote port
  charts/tigera-operator/templates/tigera-operator/01-kubernetes-services-endpoint.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#8863 Use ASO as windows cni-plugin fv infrastructure
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-cni-plugin.yml
  cni-plugin/.semaphore/run-win-fv.sh
  cni-plugin/internal/pkg/testutils/utils_windows.go
  lib.Makefile
  process/testing/winfv-cni-plugin/aso/Makefile
  process/testing/winfv-cni-plugin/aso/README.md
  process/testing/winfv-cni-plugin/aso/asoctl-generated-manifests-v2.6.0.yaml
  process/testing/winfv-cni-plugin/aso/config-minikube
  process/testing/winfv-cni-plugin/aso/create-minikube-cluster.sh
  process/testing/winfv-cni-plugin/aso/export-env.sh
  process/testing/winfv-cni-plugin/aso/get-aso-logs.sh
  process/testing/winfv-cni-plugin/aso/infra/templates/password.yaml
  process/testing/winfv-cni-plugin/aso/infra/templates/resource-group.yaml
  process/testing/winfv-cni-plugin/aso/infra/templates/security-group.yaml
  process/testing/winfv-cni-plugin/aso/infra/templates/vmss-linux.yaml
  process/testing/winfv-cni-plugin/aso/infra/templates/vmss-windows.yaml
  process/testing/winfv-cni-plugin/aso/infra/templates/vnet.yaml
  process/testing/winfv-cni-plugin/aso/install-aso.sh
  process/testing/winfv-cni-plugin/aso/run-fv-cni-plugin.ps1
  process/testing/winfv-cni-plugin/aso/setup-fv.sh
  process/testing/winfv-cni-plugin/aso/utils.sh
  process/testing/winfv-cni-plugin/aso/vmss.sh
  process/testing/winfv-cni-plugin/aso/windows/create-network.ps1
  process/testing/winfv-cni-plugin/aso/windows/enable-containers-with-reboot.ps1
  process/testing/winfv-cni-plugin/aso/windows/install-containerd.ps1
Labels: release-note-required, docs-pr-required
