Repository projectcalico/calico, pull requests merged in 2024-01, with the labels that each got.

#8363 Add FV for policy grouping.
  felix/fv/infrastructure/felix.go
  felix/fv/policy_grouping_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#8380 [BPF] pods in nat-outgoing should not SNAT to local host
  felix/bpf-gpl/tc.c
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8394 Skip apiserver etcd3 healthcheck and disable profiling
  apiserver/cmd/apiserver/server/options.go
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#8392 Update BIRD to pull in https://github.com/projectcalico/bird/pull/113
  metadata.mk
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8401 [release-v3.27] cherry-pick: Update BIRD to pull in https://github.com/projectcalico/bird/pull/113
  metadata.mk
Labels: release-note-required, docs-not-required, merge-when-ready

#7556 Check that BIRD is responsive as part of liveness
  node/pkg/health/health.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8387 Skip non-calico ipsets
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-not-required

#8412 [Release v3.27] Skip non-calico ipsets
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-not-required

#8413 Fixed issues with uninstallation process
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#8388 [BPF] Do not apply normal *-hep policy to wep - align behaviour with iptables
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/ep_to_host_action_test.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/wireguard-available
  felix/rules/static.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8419 Use /readyz for apiserver readiness probe
  apiserver/Dockerfile
  apiserver/Makefile
  apiserver/cmd/apiserver/server/options.go
  apiserver/cmd/apiserver/server/run_server.go
  apiserver/cmd/filecheck/filecheck.go
  manifests/apiserver.yaml
  node/tests/k8st/infra/apiserver.yaml
Labels: release-note-required, docs-pr-required

#8425 update how to build calico-kube-controllers
  kube-controllers/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8429 Fix crypto UT after upgrading to golang v1.21.6
  crypto/Makefile
  crypto/fv/expected-nmap.log
Labels: release-note-required, docs-pr-required

#8422 [release-v3.27] Auto pick #8421: Fix confd on Windows HPC
  confd/pkg/config/config.go
  confd/pkg/resource/template/resource.go
  libcalico-go/lib/winutils/winutils.go
  node/Makefile
  typha/pkg/syncclientutils/config.go
Labels: release-note-required, docs-not-required

#8421 [CORE-10110] Fix confd on Windows HPC
  confd/pkg/config/config.go
  confd/pkg/resource/template/resource.go
  libcalico-go/lib/winutils/winutils.go
  node/Makefile
  typha/pkg/syncclientutils/config.go
Labels: release-note-required, docs-not-required

#8438 [BPF] proxy - syncer must not count not-ready endpoints
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_test.go
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#8445 Mock netlink and test improvements
  felix/netlinkshim/mocknetlink/netlink.go
  felix/netlinkshim/netlink.go
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
  felix/wireguard/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#8420 Add pre-flight check to node STs to verify cgroup v1 is available.
  node/Makefile
Labels: docs-not-required, release-note-not-required

#8440 Make tc preamble program dispatch both IPv4/IPv6 packets.
  felix/Makefile
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/jump.h
  felix/bpf-gpl/log.h
  felix/bpf-gpl/tc_preamble.c
  felix/bpf-gpl/ut/icmp6_port_unreachable.c
  felix/bpf-gpl/ut/icmp_port_unreachable.c
  felix/bpf-gpl/ut/icmp_too_big.c
  felix/bpf-gpl/ut/icmp_ttl_exceeded.c
  felix/bpf-gpl/ut/ip_dec_ttl.c
  felix/bpf-gpl/ut/ip_parse_test.c
  felix/bpf-gpl/ut/ipv4_opts_test.c
  felix/bpf-gpl/ut/nat_encap_test.c
  felix/bpf-gpl/ut/ut.h
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
Labels: release-note-required, docs-pr-required

#8443 feat: support kubernetes-services-endpoint
  charts/tigera-operator/README.md
  charts/tigera-operator/templates/tigera-operator/01-kubernetes-services-endpoint.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required

#8417 Dual stack bpf - BPF endpoint manager refactor
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
Labels: release-note-required, docs-pr-required

#8279 Fix non-encap routes on parent device change
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/environment/feature_detect_common.go
  felix/environment/feature_detect_linux.go
  felix/environment/feature_detect_windows.go
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/topology.go
  felix/fv/routes_test.go
  felix/fv/vxlan_test.go
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
  felix/wireguard/wireguard_test.go
Labels: release-note-required, docs-not-required

#8427 Add PriorityClass for operator pod
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#8460 [release-v3.27] Auto pick #8438: proxy - syncer must not count not-ready endpoints
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8459 [release-v3.27] Auto pick #8388: Add tests for DefaultEndpointToHostAction.
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/ep_to_host_action_test.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/wireguard-available
  felix/rules/static.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8456 [release-v3.27] Auto pick #8295: don't stumble on unknown prog types passed as int in
  felix/bpf/bpf.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8457 [release-v3.27] Auto pick #8313: when host IP change kube-proxy replaces only Syncer
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/kube-proxy_test.go
  felix/bpf/proxy/proxy.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8455 [release-v3.27] Auto pick #8286: Only program failsafe rules for IP version of the CIDR
  felix/rules/static.go
  felix/rules/static_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#8462 [CORE-10127] Add retry mechanism to Windows version retrieval via powershell
  cni-plugin/pkg/install/install_windows.go
Labels: release-note-required, docs-not-required
