Repository projectcalico/calico, pull requests merged in 2024-07, with the labels that each got.

#8966 Fix case of 'AS' in Dockerfile 'FROM' lines
  apiserver/Dockerfile
  app-policy/Dockerfile.amd64
  calicoctl/Dockerfile.amd64
  calicoctl/Dockerfile.arm64
  calicoctl/Dockerfile.armv7
  calicoctl/Dockerfile.ppc64le
  calicoctl/Dockerfile.s390x
  cni-plugin/Dockerfile.amd64
  cni-plugin/Dockerfile.s390x
  felix/docker-image/Dockerfile.amd64
  felix/docker-image/Dockerfile.s390x
  kube-controllers/Dockerfile.amd64
  kube-controllers/Dockerfile.arm64
  kube-controllers/Dockerfile.s390x
  kube-controllers/docker-images/flannel-migration/Dockerfile.amd64
  networking-calico/Dockerfile
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.armv7
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
  pod2daemon/Dockerfile.amd64
  pod2daemon/csidriver/Dockerfile.amd64
  pod2daemon/node-driver-registrar-docker/Dockerfile.amd64
  typha/docker-image/Dockerfile.amd64
  typha/docker-image/Dockerfile.arm64
  typha/docker-image/Dockerfile.ppc64le
  typha/docker-image/Dockerfile.s390x
Labels: docs-not-required, release-note-not-required

#8964 Fix case of 'AS' in Dockerfile 'FROM' lines
  apiserver/Dockerfile
  app-policy/Dockerfile
  calicoctl/Dockerfile
  cni-plugin/Dockerfile
  felix/docker-image/Dockerfile
  key-cert-provisioner/Dockerfile
  key-cert-provisioner/test-signer/Dockerfile
  kube-controllers/Dockerfile
  kube-controllers/docker-image/flannel-migration/Dockerfile
  networking-calico/Dockerfile
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
  pod2daemon/csidriver/Dockerfile
  pod2daemon/flexvol/docker-image/Dockerfile
  pod2daemon/node-driver-registrar-docker/Dockerfile
  typha/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#8965 Fix case of 'AS' in Dockerfile 'FROM' lines
  apiserver/Dockerfile
  app-policy/Dockerfile
  calicoctl/Dockerfile
  cni-plugin/Dockerfile
  felix/docker-image/Dockerfile
  key-cert-provisioner/Dockerfile
  key-cert-provisioner/test-signer/Dockerfile
  kube-controllers/Dockerfile
  kube-controllers/docker-image/flannel-migration/Dockerfile
  networking-calico/Dockerfile
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
  pod2daemon/csidriver/Dockerfile
  pod2daemon/flexvol/docker-image/Dockerfile
  pod2daemon/node-driver-registrar-docker/Dockerfile
  typha/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#8967 Don't run pprof on prometheus port
  kube-controllers/cmd/kube-controllers/fv_test.go
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/tests/testutils/policy_controller_utils.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8933 [BPF] send RST to midflow TCP packets from unknown streams
  felix/dataplane/linux/int_dataplane.go
  felix/fv/pktgen/pktgen.go
  felix/fv/spoof_test.go
  felix/iptables/actions.go
Labels: release-note-required, docs-pr-required

#8972 [release-v3.28] Only patchelf felix for Debian packages
  hack/release/packaging/docker-build-images/install-centos-build-deps
  hack/release/packaging/docker-build-images/install-ubuntu-build-deps
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/make-packages.sh
Labels: release-note-required, docs-pr-required

#8973 [release-v3.27] Only patchelf felix for Debian packages
  hack/release/packaging/docker-build-images/install-centos-build-deps
  hack/release/packaging/docker-build-images/install-ubuntu-build-deps
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/make-packages.sh
Labels: release-note-required, docs-pr-required

#8969 Fix map repin FV
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#8958 [v3.27] Update module versions
  api/go.mod
  api/go.sum
  cni-plugin/Makefile
  go.mod
  go.sum
  pod2daemon/Makefile
  pod2daemon/patches/0001-Update-go.mod-to-patch-CVEs.patch
Labels: docs-not-required, release-note-not-required

#8947 Fix typo for Google Container Registry URL
  process/testing/winfv/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8956 [Release v3.28] BPF: Fix XDP UT test
  felix/bpf/ut/attach_test.go
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#8909 Rebuild containernetworking binaries, so we don't need to create rele…
  cni-plugin/.gitignore
  cni-plugin/Makefile
  metadata.mk
Labels: release-note-required, docs-pr-required

#8984 Automated cherry pick of #8909: Rebuild containernetworking binaries, so we don't need to
  cni-plugin/.gitignore
  cni-plugin/Makefile
  metadata.mk
Labels: release-note-required, docs-pr-required

#8970 [release-v3.28] Auto pick #8933: enable ipv6 spoof tests
  felix/dataplane/linux/int_dataplane.go
  felix/fv/pktgen/pktgen.go
  felix/fv/spoof_test.go
  felix/iptables/actions.go
Labels: release-note-required, docs-pr-required

#8986 [release-v3.27] Fix libpcap patchelf for calico-felix
  hack/release/packaging/utils/create-update-packages.sh
  hack/release/packaging/utils/make-packages.sh
Labels: release-note-required, docs-pr-required

#8945 Add Felix configuration for GOMAXPROCS.
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/openapi_generated.go
  calicoctl/calicoctl/commands/crds/crds.go
  felix/config/config_params.go
  felix/daemon/daemon.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#8905 Fix deprecations in yaml lint workflow
  .github/workflows/yamllint.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.tpl
Labels: docs-not-required, release-note-not-required

#8983 BPF - Fix route add/delete
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#8980 Add API repo update instructions [v3.27]
  hack/release/RELEASING.md
Labels: docs-not-required, release-note-not-required

#8981 Add API repo update instructions [v3.28]
  hack/release/RELEASING.md
Labels: docs-not-required, release-note-not-required

#8982 Add API repo update instructions [master]
  hack/release/RELEASING.md
Labels: docs-not-required, release-note-not-required

#8988 [release-v3.28] Auto pick #8983: In BPF dataplane, we add routes to UDP services, so that
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
Labels: release-note-required, docs-not-required

#8957 [Release v3.27] BPF: Fix XDP UT test
  felix/bpf/ut/attach_test.go
Labels: release-note-required, docs-pr-required

#8990 Rebuild flannel-cni-plugin binaries on demand
  cni-plugin/.gitignore
  cni-plugin/Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8946 Update bird version
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8997 Update v3.27.4 release note
  release-notes/v3.27.4-release-notes.md
Labels: docs-not-required, release-note-not-required

#8993 [release-v3.28] Auto pick #8990: Rebuild flannel-cni-plugin binaries on demand
  cni-plugin/.gitignore
  cni-plugin/Makefile
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8913 Updating the logic for stale endpoint management
  felix/dataplane/windows/endpoint_mgr.go
  felix/dataplane/windows/hns/hns_linux.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#8985 Automated cherry pick of #8909: Rebuild containernetworking binaries, so we don't need to
  cni-plugin/.gitignore
  cni-plugin/Makefile
  metadata.mk
Labels: release-note-required, docs-pr-required

#7856 Issue 7057: Print out the whole failed iptables command in the log for helping debugging
  felix/iptables/table.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9001 [release-v3.27] Auto pick #8990: Rebuild flannel-cni-plugin binaries on demand
  cni-plugin/.gitignore
  cni-plugin/Makefile
  libcalico-go/lib/ipam/ipam_test.go
  metadata.mk
Labels: docs-not-required, release-note-not-required

#8944 Move Felix log level setting earlier
  felix/daemon/daemon.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9002 Remove ApplyOnForward for network policy resource
  libcalico-go/lib/backend/syncersv1/updateprocessors/networkpolicyprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/networkpolicyprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/shared_test.go
Labels: docs-not-required, release-note-not-required

#8979 Rev netlink to pick up RouteListIter
  cni-plugin/tests/calico_cni_k8s_test.go
  cni-plugin/tests/calico_cni_test.go
  felix/ifacemonitor/iface_monitor.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#9004 Add value sanity check and Len to DeltaTracker.
  felix/deltatracker/delta_tracker.go
  felix/deltatracker/delta_tracker_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9006 Remove windows AWS FV tests runner
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
Labels: docs-not-required, release-note-not-required

#8989 Increase ipset creation / deletion test timeouts to allow for slow CI
  felix/fv/ipsets_test.go
Labels: hold-merge, docs-not-required, release-note-not-required

#9009 Publish separate test results for nft FVs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  felix/fv/fv_suite_test.go
Labels: release-note-required, docs-pr-required

#9007 Wrap errors in FVs to give better diags on failure.
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/containers/containers.go
  felix/fv/utils/utils.go
  felix/fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#9016 Fix non-HPC Calico for Windows issues
  node/windows-packaging/CalicoWindows/node/node-service.ps1
  node/windows-packaging/CalicoWindows/upgrade/upgrade-service.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9011 Various cleanups
  felix/dataplane/ipsets/ipsets_mgr.go
  felix/dataplane/ipsets/ipsets_mgr_test.go
  felix/dataplane/ipsets/mock_ipsets.go
  felix/dataplane/linux/hostip_mgr.go
  felix/dataplane/linux/hostip_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/ipip_mgr_test.go
  felix/dataplane/linux/masq_mgr.go
  felix/dataplane/linux/masq_mgr_test.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/dataplane/linux/xdp_state.go
  felix/dataplane/windows/win_dataplane.go
  felix/docker-image/Dockerfile
  felix/iptables/match_builder.go
  felix/nftables/ipsets.go
  felix/nftables/match_builder.go
  felix/nftables/table.go
Labels: docs-not-required, release-note-not-required

#6499 Ensure calico-kube-controllers runs with non root user
  charts/calico/templates/calico-kube-controllers.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#9018 Move dataplane constants to new package.
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/dataplanedefs/dataplane_defs.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/fv/config_update_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8995 [nftables] Handle IP set members of unknown type
  felix/ipsets/ipsets.go
  felix/nftables/ipsets.go
  felix/nftables/ipsets_test.go
  felix/nftables/members.go
Labels: docs-not-required, release-note-not-required

#9028 [release-v3.28] Auto pick #9016: Fix non-HPC Calico for Windows issues
  node/windows-packaging/CalicoWindows/node/node-service.ps1
  node/windows-packaging/CalicoWindows/upgrade/upgrade-service.ps1
Labels: release-note-required, docs-not-required

#9029 [release-v3.27] Auto pick #9016: Fix non-HPC Calico for Windows issues
  node/windows-packaging/CalicoWindows/node/node-service.ps1
  node/windows-packaging/CalicoWindows/upgrade/upgrade-service.ps1
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9026 [release-v3.27] Auto pick #8913: updating the logic for stale endpoint management
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/plugin/plugin.go
  felix/dataplane/windows/endpoint_mgr.go
  felix/dataplane/windows/hns/hns_linux.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#9027 [release-v3.26] Auto pick #8913: updating the logic for stale endpoint management
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/plugin/plugin.go
  felix/bpf/maps/syscall.go
  felix/dataplane/windows/endpoint_mgr.go
  felix/dataplane/windows/hns/hns_linux.go
  felix/dataplane/windows/hns/hns_windows.go
  go.mod
  go.sum
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9030 Update k8s version pins to v1.28.11, node-driver-registrar to v2.11.1
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
  go.mod
  go.sum
  metadata.mk
  pod2daemon/Makefile
Labels: release-note-required, docs-not-required

#9035 Increase capz test timeout
  process/testing/winfv/capz/install-calico.sh
Labels: docs-not-required, release-note-not-required

#9031 Bubble up errors in map size test to avoid early failure.
  felix/fv/bpf_map_resize_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#9022 [CORE-10546] Change rpm install order to fix 'undefined symbol: xtables_strdup'
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: release-note-required, cherry-pick-completed, docs-not-required

#9023 [release-v3.28] Auto pick #9022: Change rpm install order to fix 'undefined
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: release-note-required, docs-not-required

#9024 [release-v3.27] Auto pick #9022: Change rpm install order to fix 'undefined
  node/Dockerfile.amd64
  node/Dockerfile.arm64
Labels: release-note-required, docs-not-required

#9036 Revert "Revert "Disable VXLAN checksum offload by default.""
  felix/environment/feature_detect_linux.go
  felix/environment/feature_detect_test.go
Labels: release-note-required, docs-pr-required

#9037 Revert "[release-v3.28] Auto pick #8746: Revert "Disable VXLAN checksum offload by default.""
  felix/environment/feature_detect_linux.go
  felix/environment/feature_detect_test.go
Labels: release-note-required, docs-pr-required

#9032 VXLAN manager clean-ups.
  felix/dataplane/linux/vxlan_mgr.go
Labels: docs-not-required, release-note-not-required

#9039 Copy labels when converting Pod to WEP.
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9034 Add hash:net,net to nftables
  felix/nftables/actions.go
  felix/nftables/actions_test.go
  felix/nftables/ipsets.go
  felix/nftables/ipsets_test.go
  felix/nftables/match_builder.go
  felix/nftables/members.go
  felix/nftables/renderer.go
Labels: docs-not-required, release-note-not-required

#9040 Update k8s to v1.28.12
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  metadata.mk
Labels: release-note-required, docs-not-required

#8976 bump GO_BUILD_VER from v0.88 to v0.89 to move go from 1.21.9 to 1.21.…
  felix/bpf-apache/Makefile
  felix/bpf-apache/redir.c
  felix/bpf-apache/sockops.c
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/tc.c
  metadata.mk
Labels: release-note-required, docs-pr-required

#9042 Update capz fv timeout for kubectl wait
  process/testing/winfv/capz/install-calico.sh
Labels: docs-not-required, release-note-not-required

#9041 [v3.28] Copy labels when converting Pod to WEP.
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
Labels: release-note-required, docs-not-required, merge-when-ready

#8975 Take latest patch of k8s 1.26
  go.mod
  go.sum
Labels: release-note-required, docs-not-required

#9046 [3.26] Update 3.26 dependencies
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#9044 Use native logrus caller lookup.
  calicoctl/tests/fv/ipam_test.go
  calicoctl/tests/fv/migrate_ipam_test.go
  calicoctl/tests/fv/multi_context_test.go
  calicoctl/tests/fv/namespace_option_test.go
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/plugin/plugin.go
  confd/pkg/log/log.go
  felix/bpf/conntrack/conntrack_suite_test.go
  felix/calc/calc_suite_test.go
  felix/idalloc/idalloc_suite_test.go
  felix/ip/ip_suite_test.go
  felix/ipsets/ipsets_suite_test.go
  felix/logutils/logutils.go
  kube-controllers/cmd/kube-controllers/main.go
  libcalico-go/lib/backend/syncersv1/dedupebuffer/dedupe_buffer_test.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  libcalico-go/lib/logutils/benchmarks_test.go
  libcalico-go/lib/logutils/logutils.go
  libcalico-go/lib/logutils/logutils_test.go
  libcalico-go/lib/testutils/createRule.go
  libcalico-go/lib/testutils/ginkgolog.go
  libcalico-go/lib/testutils/syncertester.go
  node/cmd/calico-node/main.go
  pod2daemon/csidriver/main.go
  typha/pkg/logutils/logutils.go
Labels: release-note-required, docs-not-required

#9051 Fix connmark masking in nftables mode
  felix/nftables/actions.go
  felix/nftables/actions_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9052 [release-v3.28] Auto pick #9050: Add v4 and v6 routes for UDP service when in dual stack mode.
  felix/bpf/proxy/proxy.go
  felix/calc/calc_graph_test.go
  felix/calc/dataplane_passthru.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/bpf_dual_stack_test.go
  felix/fv/bpf_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: release-note-required, docs-not-required

#8971 Export additional resources in migration
  calicoctl/Makefile
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/tests/st/calicoctl/test_migrate.py
  calicoctl/tests/st/utils/data.py
Labels: release-note-required, docs-pr-required

#9056 [release-v3.28] Auto pick #8971: Export additional resources in migration
  calicoctl/Makefile
  calicoctl/calicoctl/commands/datastore/migrate/export.go
  calicoctl/tests/st/calicoctl/test_migrate.py
  calicoctl/tests/st/utils/data.py
Labels: release-note-required, docs-not-required

#9057 Fix bpf log filters
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#9058 [master] Auto pick #9057: Fix bpf log filters
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-pr-required

#9055 Optimise the log formatter
  libcalico-go/lib/logutils/benchmarks_test.go
  libcalico-go/lib/logutils/logutils.go
  libcalico-go/lib/logutils/logutils_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#9005 Run Win FV on capz
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  cni-plugin/internal/pkg/testutils/utils_windows.go
  felix/.semaphore/run-win-fv
  node/Makefile
  process/testing/winfv/calico-node-windows.yaml
  process/testing/winfv/capz/Makefile
  process/testing/winfv/capz/OSS/custom-resources.yaml
  process/testing/winfv/capz/README.md
  process/testing/winfv/capz/create-cluster.sh
  process/testing/winfv/capz/export-env.sh
  process/testing/winfv/capz/generate-helpers.sh
  process/testing/winfv/capz/install-calico.sh
  process/testing/winfv/capz/replace-win-containerd.ps1
  process/testing/winfv/capz/replace-win-containerd.sh
  process/testing/winfv/capz/utils.sh
  process/testing/winfv/create_kubeadm_cluster.sh
  process/testing/winfv/infra/client.yaml
  process/testing/winfv/infra/nginx.yaml
  process/testing/winfv/infra/porter.yaml
  process/testing/winfv/infra/setup.sh
  process/testing/winfv/run-fv-cni-plugin.ps1
  process/testing/winfv/run-fv-full.ps1
  process/testing/winfv/setup-fv-capz.sh
Labels: docs-not-required, release-note-not-required

#9060 Revert hcsshim version bump
  felix/dataplane/windows/endpoint_mgr.go
  felix/dataplane/windows/hns/hns_linux.go
  go.mod
  go.sum
Labels: release-note-required, docs-not-required, merge-when-ready

#9065 [CORE-10548] Revert windows endpoint mgr logic change
  felix/.semaphore/run-win-fv
  felix/dataplane/windows/endpoint_mgr.go
  process/testing/winfv/.gitignore
  process/testing/winfv/capz/.gitignore
  process/testing/winfv/capz/create-cluster.sh
  process/testing/winfv/capz/export-env.sh
  process/testing/winfv/capz/generate-helpers.sh
  process/testing/winfv/capz/install-calico.sh
  process/testing/winfv/capz/utils.sh
  process/testing/winfv/setup-fv-capz.sh
Labels: docs-not-required, release-note-not-required, merge-when-ready

#8977 felix: ensure vxlan udp flows are not tracked in conntrack
  felix/generictables/match_builder.go
  felix/iptables/match_builder.go
  felix/nftables/match_builder.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: release-note-required, docs-not-required

#9067 Quote service host
  charts/tigera-operator/templates/tigera-operator/01-kubernetes-services-endpoint.yaml
Labels: docs-not-required, release-note-not-required

#9054 Build resource lists from registered resources
  calicoctl/calicoctl/commands/apply.go
  calicoctl/calicoctl/commands/create.go
  calicoctl/calicoctl/commands/delete.go
  calicoctl/calicoctl/commands/get.go
  calicoctl/calicoctl/commands/label.go
  calicoctl/calicoctl/commands/patch.go
  calicoctl/calicoctl/commands/replace.go
  calicoctl/calicoctl/resourcemgr/resourcemgr.go
  calicoctl/calicoctl/util/docstring.go
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#9073 Add checksum-offloading-disabling to release notes
  release-notes/v3.28.1-release-notes.md
Labels: docs-not-required, release-note-not-required

#9071 [v3.26] [CORE-10548] Revert windows endpoint mgr logic change
  felix/dataplane/windows/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required

#8952 Increase timout in bpf fv repin test
  felix/fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#9070 [v3.26] Version updates
  api/go.mod
  api/go.sum
  api/pkg/openapi/openapi_generated.go
  cni-plugin/Makefile
  go.mod
  go.sum
  metadata.mk
  pod2daemon/Makefile
Labels: release-note-required, docs-not-required

#9075 Update Win FV semaphore report dir
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
Labels: docs-not-required, release-note-not-required

#9077 Fix broken pipe error when listing temp IP sets
  felix/ipsets/ipsets.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-not-required

#9078 [v3.28] Fix broken pipe error when listing temp IP sets
  felix/ipsets/ipsets.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-not-required

#9079 [v3.27] Fix broken pipe error when listing temp IP sets
  felix/ipsets/ipsets.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-not-required

#9080 [v3.26] Update node-driver-registrar version and x/net lib
  pod2daemon/Makefile
  pod2daemon/patches/0001-Update-x-net.patch
Labels: release-note-required, docs-not-required
