Repository projectcalico/calico, pull requests merged in 2025-01, with the labels that each got.

#9664 Apply CAPZ test fixes from master
  process/testing/winfv-felix/capz/Makefile
  process/testing/winfv-felix/capz/README.md
  process/testing/winfv-felix/capz/bootstrap-cluster-ips.sh
  process/testing/winfv-felix/capz/create-cluster.sh
  process/testing/winfv-felix/capz/export-env.sh
  process/testing/winfv-felix/capz/generate-helpers.sh
  process/testing/winfv-felix/capz/install-calico.sh
  process/testing/winfv-felix/capz/replace-win-containerd.ps1
  process/testing/winfv-felix/capz/replace-win-containerd.sh
  process/testing/winfv-felix/infra/setup.sh
  process/testing/winfv-felix/run-fv-cni-plugin.ps1
  process/testing/winfv-felix/setup-fv-capz.sh
  process/testing/winfv-felix/setup-fv.sh
Labels: docs-not-required, release-note-not-required

#9623 Improve kind setup
  cni-plugin/Makefile
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
Labels: docs-not-required, release-note-not-required

#9671 [v3.29] Fix spammy Tier already exists log
  libcalico-go/lib/clientv3/client.go
Labels: release-note-required, docs-pr-required

#9672 Update x/net to fix CVE alert.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#9673 [release-tool] fix hashrelease local src directory
  release/internal/pinnedversion/pinnedversion.go
Labels: docs-not-required, release-note-not-required

#9676 Remove unnecessary docker restart commands from Semaphore configs
  .semaphore/push-images/alp.yml
  .semaphore/push-images/apiserver.yml
  .semaphore/push-images/calicoctl.yml
  .semaphore/push-images/cni-plugin.yml
  .semaphore/push-images/key-cert-provisioner.yml
  .semaphore/push-images/kube-controllers.yml
  .semaphore/push-images/node.yml
  .semaphore/push-images/pod2daemon.yml
  .semaphore/push-images/typha.yml
  .semaphore/release/hashrelease.yml
  .semaphore/release/release.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/02-global_job_config.yml
Labels: docs-not-required, release-note-not-required

#9581 [BPF] Enhance conntrack map flexibility with CPU-based scaling
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-not-required

#9662 Program connected routes for borrowed VXLAN tunnel addresses
  felix/calc/l3_route_resolver.go
  felix/calc/states_for_test.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/types/update.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9663 Refactor: Use interface to configure libbpf global data when loading bpf programs.
  felix/bpf/bpf.go
  felix/bpf/conntrack/bpf_scanner.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/xdp/attach.go
Labels: docs-not-required, release-note-not-required

#9682 Cleanup after gen-crd target in compatible way
  libcalico-go/Makefile
Labels: docs-not-required, release-note-not-required

#9323 Update dispatch logic in nftables
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/generictables/match_builder.go
  felix/iptables/match_builder.go
  felix/nftables/ipsets.go
  felix/nftables/ipsets_test.go
  felix/nftables/maps.go
  felix/nftables/maps_test.go
  felix/nftables/match_builder.go
  felix/nftables/members.go
  felix/nftables/table.go
  felix/nftables/table_test.go
  felix/rules/dispatch.go
  felix/rules/rule_defs.go
Labels: docs-not-required, release-note-not-required

#9685 Merge pull request #9662 from caseydavenport/casey-vxlan-borrow
  felix/calc/l3_route_resolver.go
  felix/calc/states_for_test.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: release-note-required, docs-not-required

#9681 [release tool] fix hashrelease hanging on image checks
  release/cmd/hashrelease.go
  release/internal/pinnedversion/pinnedversion.go
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#9686 Increase timeout for IPAM tests to 5s from 1s: the test runners are inconsistent and these often fail
  libcalico-go/lib/ipam/ipam_test.go
Labels: docs-not-required, release-note-not-required

#9607 [BPF] make conntrack timeouts configurable
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/bpf-gpl/conntrack_cleanup.c
  felix/bpf-gpl/globals.h
  felix/bpf/conntrack/bpf_scanner.go
  felix/bpf/conntrack/timeouts.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/felixconfigprocessor.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9599 Fix List() calls that didn't fill in revision
  calicoctl/tests/st/calicoctl/test_crud.py
  cni-plugin/pkg/plugin/plugin.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/resources/bgpconfig.go
  libcalico-go/lib/backend/k8s/resources/bgpfilter.go
  libcalico-go/lib/backend/k8s/resources/bgppeer.go
  libcalico-go/lib/backend/k8s/resources/caliconodestatus.go
  libcalico-go/lib/backend/k8s/resources/clusterinfo.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/customresource_test.go
  libcalico-go/lib/backend/k8s/resources/fake_clientset_test.go
  libcalico-go/lib/backend/k8s/resources/felixconfig.go
  libcalico-go/lib/backend/k8s/resources/globalnetworkpolicies.go
  libcalico-go/lib/backend/k8s/resources/globalnetworkset.go
  libcalico-go/lib/backend/k8s/resources/hostendpoint.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_block.go
  libcalico-go/lib/backend/k8s/resources/ipam_block_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_config.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle.go
  libcalico-go/lib/backend/k8s/resources/ippool.go
  libcalico-go/lib/backend/k8s/resources/ipreservation.go
  libcalico-go/lib/backend/k8s/resources/k8sservice.go
  libcalico-go/lib/backend/k8s/resources/k8sservice_test.go
  libcalico-go/lib/backend/k8s/resources/kubecontrollersconfig.go
  libcalico-go/lib/backend/k8s/resources/kubeendpointslice.go
  libcalico-go/lib/backend/k8s/resources/kubenetworkpolicy.go
  libcalico-go/lib/backend/k8s/resources/networkpolicy.go
  libcalico-go/lib/backend/k8s/resources/networkset.go
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/node_test.go
  libcalico-go/lib/backend/k8s/resources/profile.go
  libcalico-go/lib/backend/k8s/resources/profile_test.go
  libcalico-go/lib/backend/k8s/resources/tiers.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint.go
  libcalico-go/lib/backend/k8s/scheme/scheme.go
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/clientv3/profile_e2e_test.go
  libcalico-go/lib/resources/static.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#9636 [release tool] [cherry pick] refactoring changes
  .semaphore/release/hashrelease.yml
  Makefile
  release/Makefile
  release/build/main.go
  release/cmd/branch.go
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/cmd/release.go
  release/cmd/shared.go
  release/internal/command/commands.go
  release/internal/command/git.go
  release/internal/config/ci.go
  release/internal/config/config.go
  release/internal/config/operator.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/server.go
  release/internal/hashreleaseserver/ssh.go
  release/internal/imagescanner/scanner.go
  release/internal/outputs/releasenotes.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/pinnedversion/templates/calico-versions.yaml.gotmpl
  release/internal/slack/slack.go
  release/internal/utils/config.go
  release/internal/utils/git.go
  release/internal/utils/utils.go
  release/internal/version/version.go
  release/pkg/manager/branch/manager.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
  release/pkg/manager/operator/manager.go
  release/pkg/manager/operator/options.go
  release/pkg/tasks/hashrelease.go
Labels: docs-not-required, release-note-not-required

#9440 Add documentation for Wireguard Threaded NAPI
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#9679 Update x/net
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#9696 fix operator version for hashrelease
  release/internal/pinnedversion/pinnedversion.go
  release/internal/version/version.go
Labels: docs-not-required, release-note-not-required

#9700 [cherry-pick] fix operator version for hashrelease (#9696)
  release/internal/pinnedversion/pinnedversion.go
  release/internal/version/version.go
Labels: docs-not-required, release-note-not-required

#9689 [v3.29] Fix List() calls that didn't fill in revision
  calicoctl/calicoctl/commands/datastore/migrate/migrateipam_test.go
  calicoctl/tests/st/calicoctl/test_crud.py
  cni-plugin/pkg/plugin/plugin.go
  libcalico-go/lib/backend/api/api.go
  libcalico-go/lib/backend/etcdv3/watcher.go
  libcalico-go/lib/backend/k8s/k8s.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/bgpconfig.go
  libcalico-go/lib/backend/k8s/resources/bgpfilter.go
  libcalico-go/lib/backend/k8s/resources/bgppeer.go
  libcalico-go/lib/backend/k8s/resources/caliconodestatus.go
  libcalico-go/lib/backend/k8s/resources/client.go
  libcalico-go/lib/backend/k8s/resources/clusterinfo.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/customresource_test.go
  libcalico-go/lib/backend/k8s/resources/fake_clientset_test.go
  libcalico-go/lib/backend/k8s/resources/felixconfig.go
  libcalico-go/lib/backend/k8s/resources/globalnetworkpolicies.go
  libcalico-go/lib/backend/k8s/resources/globalnetworkset.go
  libcalico-go/lib/backend/k8s/resources/hostendpoint.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity.go
  libcalico-go/lib/backend/k8s/resources/ipam_affinity_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_block.go
  libcalico-go/lib/backend/k8s/resources/ipam_block_test.go
  libcalico-go/lib/backend/k8s/resources/ipam_config.go
  libcalico-go/lib/backend/k8s/resources/ipam_handle.go
  libcalico-go/lib/backend/k8s/resources/ippool.go
  libcalico-go/lib/backend/k8s/resources/ipreservation.go
  libcalico-go/lib/backend/k8s/resources/k8sservice.go
  libcalico-go/lib/backend/k8s/resources/k8sservice_test.go
  libcalico-go/lib/backend/k8s/resources/kubeadminnetworkpolicy.go
  libcalico-go/lib/backend/k8s/resources/kubecontrollersconfig.go
  libcalico-go/lib/backend/k8s/resources/kubeendpointslice.go
  libcalico-go/lib/backend/k8s/resources/kubenetworkpolicy.go
  libcalico-go/lib/backend/k8s/resources/networkpolicy.go
  libcalico-go/lib/backend/k8s/resources/networkset.go
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/node_test.go
  libcalico-go/lib/backend/k8s/resources/profile.go
  libcalico-go/lib/backend/k8s/resources/profile_test.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/k8s/resources/tiers.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint.go
  libcalico-go/lib/backend/k8s/resources/workloadendpoint_test.go
  libcalico-go/lib/backend/k8s/scheme/scheme.go
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  libcalico-go/lib/clientv3/profile_e2e_test.go
  libcalico-go/lib/clientv3/resources.go
  libcalico-go/lib/ipam/ipam_block_reader_writer_test.go
  libcalico-go/lib/resources/static.go
Labels: release-note-required, docs-not-required

#9705 Quick fix for formatting of protobuf files.
  hack/format-all-files.sh
  hack/format-changed-files.sh
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9668 [release tool] Slack notifications
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/internal/hashreleaseserver/server.go
  release/internal/imagescanner/scanner.go
  release/internal/outputs/releasenotes.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/slack/message.go
  release/internal/slack/slack.go
  release/internal/slack/templates/failure.json.gotmpl
  release/internal/slack/templates/hashrelease-published.json.gotmpl
  release/internal/slack/templates/missing-images.json.gotmpl
  release/internal/utils/utils.go
  release/internal/version/version.go
  release/pkg/errors/errors.go
  release/pkg/manager/calico/manager.go
  release/pkg/tasks/hashrelease.go
  release/pkg/tasks/notification.go
Labels: docs-not-required, release-note-not-required

#9589 Add sempahore auto go-build workflow
  .semaphore/update-go-build-pins.yml
  Makefile
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#9678 factor-out calico/base image to metadata.mk
  apiserver/Dockerfile
  app-policy/Dockerfile
  calicoctl/Dockerfile
  cni-plugin/Dockerfile
  key-cert-provisioner/Dockerfile
  key-cert-provisioner/test-signer/Dockerfile
  kube-controllers/Dockerfile
  kube-controllers/docker-image/flannel-migration/Dockerfile
  lib.Makefile
  metadata.mk
  pod2daemon/csidriver/Dockerfile
  pod2daemon/flexvol/docker-image/Dockerfile
  pod2daemon/node-driver-registrar-docker/Dockerfile
  typha/docker-image/Dockerfile
Labels: docs-pr-required, release-note-not-required

#9707 [cherry pick] [release tool] Slack notifications (#9668)
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/internal/hashreleaseserver/server.go
  release/internal/imagescanner/scanner.go
  release/internal/outputs/releasenotes.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/slack/message.go
  release/internal/slack/slack.go
  release/internal/slack/templates/failure.json.gotmpl
  release/internal/slack/templates/hashrelease-published.json.gotmpl
  release/internal/slack/templates/missing-images.json.gotmpl
  release/internal/utils/utils.go
  release/internal/version/version.go
  release/pkg/errors/errors.go
  release/pkg/manager/calico/manager.go
  release/pkg/tasks/hashrelease.go
  release/pkg/tasks/notification.go
Labels: docs-not-required, release-note-not-required

#9699 Make operator init container use k8s-svc-configmap if present.
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  manifests/ocp/02-tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9715 Add private keys to go-build auto pin update workflow
  .semaphore/update-go-build-pins.yml
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#9710 Run UBI-minimal FVs in Typha
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-typha.yml
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#9725 Cherry pick parts of #9614 to fix hashrelease
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9716 Update vishvananda/netlink to v1.30.0
  felix/routerule/route_rule_test.go
  felix/routerule/rule_lib.go
  felix/routerule/rule_lib_test.go
  felix/wireguard/wireguard_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#9656 Ensure existing CNI config file has correct permissions
  cni-plugin/pkg/install/install.go
Labels: release-note-required, docs-pr-required

#9717 [master] Semaphore Auto go-build Update
  api/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/bgpconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/bgpfilter.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/bgppeer.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/blockaffinity.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/caliconodestatus.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/clusterinformation.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_bgpconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_bgpfilter.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_bgppeer.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_blockaffinity.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_caliconodestatus.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_clusterinformation.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_felixconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_globalnetworkpolicy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_globalnetworkset.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_hostendpoint.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_ipamconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_ippool.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_ipreservation.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_kubecontrollersconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_networkpolicy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_networkset.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_profile.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/fake/fake_tier.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/felixconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/globalnetworkpolicy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/globalnetworkset.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/hostendpoint.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/ipamconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/ippool.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/ipreservation.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/kubecontrollersconfiguration.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/networkpolicy.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/networkset.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/profile.go
  api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3/tier.go
  api/pkg/client/informers_generated/externalversions/factory.go
  api/pkg/client/listers_generated/projectcalico/v3/bgpconfiguration.go
  api/pkg/client/listers_generated/projectcalico/v3/bgpfilter.go
  api/pkg/client/listers_generated/projectcalico/v3/bgppeer.go
  api/pkg/client/listers_generated/projectcalico/v3/blockaffinity.go
  api/pkg/client/listers_generated/projectcalico/v3/caliconodestatus.go
  api/pkg/client/listers_generated/projectcalico/v3/clusterinformation.go
  api/pkg/client/listers_generated/projectcalico/v3/felixconfiguration.go
  api/pkg/client/listers_generated/projectcalico/v3/globalnetworkpolicy.go
  api/pkg/client/listers_generated/projectcalico/v3/globalnetworkset.go
  api/pkg/client/listers_generated/projectcalico/v3/hostendpoint.go
  api/pkg/client/listers_generated/projectcalico/v3/ipamconfiguration.go
  api/pkg/client/listers_generated/projectcalico/v3/ippool.go
  api/pkg/client/listers_generated/projectcalico/v3/ipreservation.go
  api/pkg/client/listers_generated/projectcalico/v3/kubecontrollersconfiguration.go
  api/pkg/client/listers_generated/projectcalico/v3/networkpolicy.go
  api/pkg/client/listers_generated/projectcalico/v3/networkset.go
  api/pkg/client/listers_generated/projectcalico/v3/profile.go
  api/pkg/client/listers_generated/projectcalico/v3/tier.go
  metadata.mk
Labels: docs-not-required, release-note-not-required

#9727 Use context package from the standard library
  apiserver/pkg/storage/calico/tier_storage.go
  apiserver/pkg/storage/calico/tier_storage_test.go
  go.mod
Labels: docs-not-required, release-note-not-required

#9278 Support for OpenStack Caracal release
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
  networking-calico/Makefile
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/plugin.sh
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
  networking-calico/networking_calico/etcdv3.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
  networking-calico/requirements.txt
  networking-calico/test-requirements.txt
Labels: release-note-required, kind/enhancement, docs-pr-required, area/openstack

#9726 Add nfnetlink package
  felix/nfnetlink/README.md
  felix/nfnetlink/conntrack.go
  felix/nfnetlink/conntrack_linux.go
  felix/nfnetlink/conntrack_test.go
  felix/nfnetlink/nflog.go
  felix/nfnetlink/nflog_linux.go
  felix/nfnetlink/nflog_test.go
  felix/nfnetlink/nfnetlink_suite_test.go
  felix/nfnetlink/nfnl/conntrack_linux.go
  felix/nfnetlink/nfnl/nflog_linux.go
  felix/nfnetlink/nfnl/nflog_netlink_linux.go
  felix/nfnetlink/nfnl/nfnetlink_linux.go
  felix/nfnetlink/pkt/header.go
Labels: docs-not-required, release-note-not-required

#9721 Set default value of EndpointStatusPathPrefix config to /var/run/calico
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/daemon/daemon.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#9730 [master] Semaphore Auto go-build Update
  metadata.mk
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#9734 Upgrade ubuntu version of the Felix FV vms in semaphore
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
Labels: docs-not-required, release-note-not-required

#9654 Don't check every IPAM allocation on every sync.
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_allocation.go
  kube-controllers/pkg/controllers/node/ipam_test.go
  kube-controllers/pkg/controllers/node/node_deleter.go
Labels: release-note-required, docs-not-required

#9735 Remove duplicate ARC registration
  felix/calc/active_rules_calculator.go
Labels: docs-not-required, release-note-not-required

#9736 [Release v3.29] Remove duplicate ARC registration
  felix/calc/active_rules_calculator.go
Labels: docs-not-required, release-note-not-required

#9708 Add initial flow aggregation code and API
  .semaphore/push-images/goldmane.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/03-promotions.yml
  .semaphore/semaphore.yml.d/blocks/20-goldmane.yml
  goldmane/Makefile
  goldmane/README.md
  goldmane/cmd/flowgen/main.go
  goldmane/cmd/main.go
  goldmane/config/testserver-daemonset.yaml
  goldmane/docker/Dockerfile
  goldmane/docker/flowgen/Dockerfile
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/flow.go
  goldmane/pkg/aggregator/options.go
  goldmane/pkg/aggregator/types.go
  goldmane/pkg/aggregator/utils_test.go
  goldmane/pkg/client/client.go
  goldmane/pkg/collector/collector.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/bucket_cache.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/emitter/http_client.go
  goldmane/pkg/emitter/options.go
  goldmane/pkg/flowgen/testserver.go
  goldmane/pkg/internal/flowcache/timed_cache.go
  goldmane/pkg/internal/types/flow.go
  goldmane/pkg/internal/types/flow_test.go
  goldmane/pkg/internal/utils/logging.go
  goldmane/pkg/server/server.go
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
  goldmane/proto/api_grpc.pb.go
  release/internal/pinnedversion/templates/calico-versions.yaml.gotmpl
  release/pkg/manager/calico/manager.go
Labels: release-note-required, docs-pr-required

#9704 [BPF] Automatically adjust to actual max-entries when dumping conntra…
  felix/cmd/calico-bpf/commands/conntrack.go
Labels: release-note-required, docs-not-required

#9733 minor hashrelease updates
  release/cmd/hashrelease.go
  release/internal/command/runner.go
  release/internal/pinnedversion/pinnedversion.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
Labels: docs-not-required, release-note-not-required

#9750 Remove extra flowlog configs options
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/collector/dpstatshelper.go
  felix/config/config_params.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/flow_logs_goladmane_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#9755 Remove redundant flow log FV tests
  felix/fv/flow_logs_goladmane_test.go
Labels: docs-not-required, release-note-not-required

#9756 Use an Index interface for default sort
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/ring_index.go
Labels: docs-not-required, release-note-not-required

#9749 [release-v3.29] Auto pick #9747: fix icmp error delivery to host networked pods
  felix/bpf-gpl/conntrack.h
  felix/bpf/ut/icmp_related_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-not-required

#9757 [release-v3.28] Auto pick #9747: fix icmp error delivery to host networked pods
  felix/bpf-gpl/conntrack.h
  felix/bpf/ut/icmp_related_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-not-required

#9557 fix: include upgrade notes that apply for v3.28+
  charts/tigera-operator/README.md
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9765 Create docker container for serving oss ui backed by nginx
  oss-ui/Makefile
  oss-ui/docker-image/Dockerfile.nginx
  oss-ui/docker-image/default.conf
  oss-ui/docker-image/nginx-start.sh
  oss-ui/docker-image/nginx.conf
  oss-ui/docker-image/nginx.repo
  oss-ui/src/api/index.ts
  oss-ui/src/features/flowLogs/api/index.ts
Labels: docs-not-required, release-note-not-required

#9769 Fix EBUSY errors from netlink operations.
  felix/ifacemonitor/iface_monitor.go
  felix/ifacemonitor/ifacemonitor_test.go
  felix/netlinkshim/mocknetlink/netlink.go
  felix/routetable/route_table_test.go
  go.mod
  go.sum
Labels: release-note-required, docs-pr-required

#8318 libbpf: ignore listing files in build dir
  felix/Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#9732 [BPF] BPFMapSizeConntrackScaling=DoubleIfFull
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/bpf/conntrack/bpf_scanner.go
  felix/bpf/ut/bpf_ct_cleanup_test.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/bpf_map_resize_test.go
  felix/fv/bpf_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-not-required

#9773 [release tool] hashrelease support for multiple products and Google registries
  release/internal/hashreleaseserver/server.go
  release/internal/registry/auth.go
  release/internal/registry/docker.go
  release/internal/registry/dockerrunner.go
  release/internal/registry/gar.go
  release/internal/registry/gcr.go
  release/internal/registry/image.go
  release/internal/registry/quay.go
  release/internal/registry/registry.go
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#9774 Fix the number of argument to conntrack.NewValueNormal in FVs
  felix/fv/bpf_map_resize_test.go
Labels: docs-not-required, release-note-not-required

#9776 update goldmane release targets
  goldmane/Makefile
Labels: docs-not-required, release-note-not-required

#9777 [RS-2319] Map OpenStack-derived policy to the "default" tier
  libcalico-go/lib/names/policy.go
  libcalico-go/lib/names/policy_test.go
Labels: release-note-required, docs-not-required

#9780 UT for BANP policy names
  libcalico-go/lib/names/policy_test.go
Labels: docs-not-required, release-note-not-required

#9744 [CORE-10973] Add QoSControls to WorkloadEndpoint
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  libcalico-go/lib/apis/v3/generated.openapi.go
  libcalico-go/lib/apis/v3/workloadendpoint.go
  libcalico-go/lib/apis/v3/zz_generated.deepcopy.go
  libcalico-go/lib/backend/k8s/conversion/constants.go
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
  libcalico-go/lib/backend/model/workloadendpoint.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
Labels: docs-pr-required, release-note-not-required
