Repository projectcalico/calico, pull requests merged in 2025-03, with the labels that each got.

#9909 [TSLA-8424] whisker omni filter data management
  whisker/package.json
  whisker/src/App.tsx
  whisker/src/api/__tests__/index.test.ts
  whisker/src/api/index.ts
  whisker/src/components/core/ChakraProvider/index.tsx
  whisker/src/components/core/DarkModeGuard/index.tsx
  whisker/src/components/index.tsx
  whisker/src/features/flowLogs/api/__tests__/index.test.tsx
  whisker/src/features/flowLogs/api/index.ts
  whisker/src/features/flowLogs/components/FlowLogDetails/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/OmniFilters/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/hooks/__tests__/omniFilters.test.ts
  whisker/src/hooks/index.ts
  whisker/src/hooks/omniFilters.ts
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/__test__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/__test__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/components/CheckboxLoadingSkeleton/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/styles.ts
  whisker/src/libs/tigera/ui-components/utils/__tests__/index.test.ts
  whisker/src/libs/tigera/ui-components/utils/index.ts
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/theme/components/index.ts
  whisker/src/theme/index.ts
  whisker/src/types/api.ts
  whisker/src/utils/omniFilter.ts
  whisker/test-utils/helper.tsx
  whisker/yarn.lock
Labels: docs-not-required, release-note-not-required

#9903 Fix json tag on config var
  goldmane/pkg/daemon/daemon.go
Labels: docs-not-required, release-note-not-required

#9834 Policy statistics API + implementation
  goldmane/.mockery.yaml
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/stats.go
  goldmane/pkg/aggregator/index.go
  goldmane/pkg/aggregator/utils_test.go
  goldmane/pkg/client/flowservice.go
  goldmane/pkg/client/mocks/FlowServiceClient.go
  goldmane/pkg/client/mocks/FlowsClient.go
  goldmane/pkg/client/statistics_service.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/internal/types/flow.go
  goldmane/pkg/server/flow_service.go
  goldmane/pkg/server/statistics_service.go
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
  goldmane/proto/api_grpc.pb.go
  goldmane/proto/methods.go
  goldmane/proto/mocks/FlowService_StreamClient.go
  goldmane/proto/mocks/Flows_StreamClient.go
  whisker-backend/cmd/main.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows_test.go
Labels: docs-not-required, release-note-not-required

#9918 Update the label controller to wait if we get node syncer update
  kube-controllers/pkg/controllers/node/labels.go
Labels: docs-not-required, release-note-not-required

#9922 [TSLA-8766] pause stream on row click
  whisker/src/features/flowLogs/components/FlowLogsContainer/index.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/theme/colors.ts
  whisker/src/theme/components/Alert.ts
Labels: docs-not-required, release-note-not-required

#9916 [TSLA-8693] virtualisation for flowlogs table
  whisker/src/features/flowLogs/components/FlowLogDetails/styles.ts
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/styles.ts
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/__tests__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/Table/index.tsx
Labels: docs-not-required, release-note-not-required

#9897 Add ctx in PoolAccessorInterface
  libcalico-go/lib/clientv3/client.go
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block_reader_writer.go
  libcalico-go/lib/ipam/ipam_test.go
  libcalico-go/lib/ipam/ipam_win_test.go
  libcalico-go/lib/ipam/pools.go
  node/pkg/allocateip/allocateip_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9923 Exclude ppc64le s390x from whisker arches
  whisker/Makefile
Labels: docs-not-required, release-note-not-required

#9919 Goldmane gRPC API optimizations
  felix/collector/goldmane/client.go
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/stats.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/flowgen/testserver.go
  goldmane/pkg/internal/types/diachronic_flow.go
  goldmane/pkg/internal/types/filters.go
  goldmane/pkg/internal/types/flow.go
  goldmane/pkg/internal/types/flow_test.go
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
  goldmane/proto/methods.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows.go
Labels: docs-not-required, release-note-not-required

#9839 Remove dataplane rules for staged policies
  felix/bpf/polprog/pol_prog_builder.go
  felix/bpf/ut/pol_prog_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/windows/policy_mgr.go
  felix/fv/flow_logs_goldmane_staged_test.go
  felix/fv/tiered_policy_test.go
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  felix/rules/policy.go
  felix/rules/policy_test.go
  felix/rules/rule_defs.go
Labels: docs-not-required, release-note-not-required

#9926 [master] Semaphore Auto go-build Update
  metadata.mk
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#9917 Add GatewayAPI CRD and RBAC to install
  charts/tigera-operator/Makefile
  charts/tigera-operator/crds/operator.tigera.io_gatewayapis.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9842 Calicoctl ipam config support MaxBlocksPerHost
  calicoctl/calicoctl/commands/ipam/configure.go
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#9928 Fix hashrelease task failing to generate Slack notification on failure
  release/Makefile
  release/internal/slack/message.go
  release/internal/slack/message_test.go
  release/internal/version/version_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#9930 Remove stray CRD yamls from manifests/ocp
  manifests/ocp/crd.projectcalico.org_bgpconfigurations.yaml
  manifests/ocp/crd.projectcalico.org_bgppeers.yaml
Labels: release-note-required, docs-not-required, merge-when-ready

#9932 Remove leftover comments
  felix/calc/endpoint_lookup_cache_test.go
  felix/collector/collector.go
  felix/fv/metrics/flow_tester.go
Labels: docs-not-required, release-note-not-required

#9914 Allow users to disable generating pending trace in flowlogs
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/collector/collector.go
  felix/collector/dataplane_info_reader.go
  felix/collector/dpstatshelper.go
  felix/config/config_params.go
  felix/daemon/daemon.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#9936 Read all commands off backlog channel before executing backlog
  guardian/Makefile
  guardian/pkg/asyncutil/async.go
  guardian/pkg/asyncutil/async_test.go
Labels: docs-not-required, release-note-not-required

#9937 make CRD management optional in helm chart
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-pr-required

#9925 Fix label aggregation in Goldmane
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/internal/types/diachronic_flow.go
Labels: docs-not-required, release-note-not-required

#9935 [EV-5459] Define the implicit tier action for staged policies (#8507)
  app-policy/checker/check.go
  app-policy/checker/check_test.go
  felix/calc/endpoint_lookup_cache.go
  felix/calc/endpoint_lookup_cache_test.go
  felix/calc/policy_lookup_cache.go
  felix/collector/collector_test.go
  felix/collector/flowlog/fixtures_test.go
  felix/collector/stats.go
  felix/fv/flow_logs_goldmane_staged_test.go
  libcalico-go/lib/backend/model/policy.go
Labels: docs-not-required, release-note-not-required

#9934 Fix concurrent access panic in DiachronicFlow
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/stream_manager.go
  goldmane/pkg/internal/types/diachronic_flow.go
  goldmane/pkg/internal/types/diachronic_flow_test.go
Labels: docs-not-required, release-note-not-required

#9827 Update host end point flow log
  felix/calc/endpoint_lookup_cache.go
  felix/calc/endpoint_lookup_cache_test.go
  felix/collector/collector.go
  felix/fv/flow_logs_goldmane_test.go
Labels: docs-not-required, release-note-not-required

#9615 Use policy name used during create
  apiserver/pkg/registry/projectcalico/globalpolicy/strategy.go
  apiserver/pkg/registry/projectcalico/networkpolicy/strategy.go
  apiserver/pkg/registry/projectcalico/stagedglobalnetworkpolicy/strategy.go
  apiserver/pkg/registry/projectcalico/stagednetworkpolicy/strategy.go
  apiserver/pkg/storage/calico/policy_storage_test.go
  apiserver/test/integration/clientset_test.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
  libcalico-go/lib/backend/etcdv3/etcdv3.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/clientv3/globalnetworkpolicy.go
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/stagedglobalnetworkpolicy.go
  libcalico-go/lib/clientv3/stagedglobalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/stagednetworkpolicy.go
  libcalico-go/lib/clientv3/stagednetworkpolicy_e2e_test.go
Labels: release-note-required, docs-pr-required

#9938 [CORE-10975] Add QoS packet rate limit
  cni-plugin/Makefile
  felix/bpf/tc/attach.go
  felix/dataplane/driver.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/qos/qos.go
  felix/dataplane/linux/qos_controls.go
  felix/docker-image/Dockerfile
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/qos_controls_test.go
  felix/fv/workload/workload.go
  felix/generictables/actions.go
  felix/iptables/actions.go
  felix/iptables/actions_test.go
  felix/nftables/actions.go
  felix/nftables/actions_test.go
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  felix/rules/rule_defs.go
  manifests/ocp/custom-resources.yaml
Labels: release-note-required, docs-not-required

#9946 Revert "[CORE-10975] Add QoS packet rate limit"
  cni-plugin/Makefile
  felix/bpf/tc/attach.go
  felix/dataplane/driver.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/qos/qos.go
  felix/dataplane/linux/qos_controls.go
  felix/docker-image/Dockerfile
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/qos_controls_test.go
  felix/fv/workload/workload.go
  felix/generictables/actions.go
  felix/iptables/actions.go
  felix/iptables/actions_test.go
  felix/nftables/actions.go
  felix/nftables/actions_test.go
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  felix/rules/rule_defs.go
  manifests/ocp/custom-resources.yaml
Labels: release-note-required, docs-pr-required

#9881 [CORE-10974] Add bandwidth QoS controls
  cni-plugin/Makefile
  felix/bpf/tc/attach.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/qos/qos.go
  felix/dataplane/linux/qos_controls.go
  felix/docker-image/Dockerfile
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/qos_controls_test.go
  felix/fv/workload/workload.go
Labels: release-note-required, docs-pr-required

#9945 [TSLA-8766] expanded row ux
  whisker/src/api/index.ts
  whisker/src/components/layout/AppHeader/index.tsx
  whisker/src/components/layout/AppHeader/styles.ts
  whisker/src/components/layout/AppLayout/styles.ts
  whisker/src/features/flowLogs/components/FlowLogsContainer/index.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableHeader/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/Table/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/index.tsx
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/theme/colors.ts
  whisker/src/theme/components/Alert.ts
Labels: docs-not-required, release-note-not-required

#9950 Remove bandwidth plugin chaining from manifests
  charts/calico/templates/calico-config.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9949 Allow Goldmane access via Guardian
  felix/collector/dpstatshelper.go
  felix/collector/goldmane/client.go
  felix/fv/flow_logs_goldmane_test.go
  goldmane/Makefile
  goldmane/pkg/client/client.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/flowgen/testserver.go
  goldmane/pkg/server/statistics_service.go
  guardian/pkg/config/calico.go
  guardian/pkg/config/config.go
  guardian/pkg/server/proxy.go
  guardian/pkg/server/target.go
  whisker-backend/Makefile
  whisker-backend/cmd/main.go
  whisker-backend/pkg/config/api.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#9952 Fix Goldmane UT flake
  goldmane/pkg/aggregator/aggregator_test.go
Labels: docs-not-required, release-note-not-required

#9953 Fix up clean target in Guardian
  guardian/Makefile
Labels: docs-not-required, release-note-not-required

#9954 Downgrade error log
  release/internal/hashreleaseserver/server.go
Labels: docs-not-required, release-note-not-required

#9958 In release-build target, build envoy images with VERSION tag
  third_party/envoy-gateway/Makefile
  third_party/envoy-proxy/Makefile
  third_party/envoy-ratelimit/Makefile
Labels: docs-not-required, release-note-not-required

#9961 Disable nginx buffering and timeouts (let the server handle it)
  whisker/docker-image/default.conf
Labels: docs-not-required, release-note-not-required

#9963 [TSLA-8766] new row ux
  whisker/package.json
  whisker/src/api/__tests__/index.test.ts
  whisker/src/api/index.ts
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/ExpandedRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/Row/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/TableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedRows/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedTableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/hooks/__tests__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/hooks/index.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/yarn.lock
Labels: docs-not-required, release-note-not-required

#9959 [TSLA-8560] column customizer modal for flow logs table
  whisker/package.json
  whisker/src/features/flowLogs/components/FlowLogsList/flowLogsTable.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/icons/DndIcon.tsx
  whisker/src/icons/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableHeader/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/ReorderableCheckList/__test__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/ReorderableCheckList/index.tsx
  whisker/src/theme/components/ReorderableCheckList.ts
  whisker/src/theme/components/index.ts
  whisker/src/theme/index.ts
  whisker/src/theme/tokens.ts
  whisker/yarn.lock
Labels: docs-not-required, release-note-not-required

#9947 [CORE-10975] Add QoS packet rate limit
  felix/dataplane/linux/endpoint_mgr.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/qos_controls_test.go
  felix/generictables/actions.go
  felix/iptables/actions.go
  felix/iptables/actions_test.go
  felix/nftables/actions.go
  felix/nftables/actions_test.go
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  felix/rules/rule_defs.go
Labels: release-note-required, docs-not-required

#9968 OpenShift needs RBAC for gatewayapis/finalizers
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9970 Add user/group to Whisker/Goldmane Dockerfiles
  goldmane/docker/Dockerfile
  whisker-backend/docker/Dockerfile
Labels: docs-not-required, release-note-not-required

#9964 Enable mTLS with Goldmane
  crypto/pkg/tls/tls.go
  felix/collector/dpstatshelper.go
  felix/collector/goldmane/client.go
  goldmane/pkg/client/client.go
  goldmane/pkg/client/tls.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/flowgen/testserver.go
  guardian/pkg/config/calico.go
  guardian/pkg/config/config.go
  lib/std/cryptoutils/cert.go
  lib/std/go.mod
  whisker-backend/cmd/app/app.go
  whisker-backend/pkg/config/api.go
  whisker-backend/test/fv/goldmaneintegration_test.go
Labels: docs-not-required, release-note-not-required

#9943 Staged policy changes in Calicoctl
  calicoctl/calicoctl/commands/apply.go
  calicoctl/calicoctl/commands/create.go
  calicoctl/calicoctl/commands/delete.go
  calicoctl/calicoctl/commands/get.go
  calicoctl/calicoctl/commands/label.go
  calicoctl/calicoctl/commands/patch.go
  calicoctl/calicoctl/commands/replace.go
  calicoctl/calicoctl/resourcemgr/stagedglobalnetworkpolicy.go
  calicoctl/calicoctl/resourcemgr/stagedkubernetesnetworkpolicy.go
  calicoctl/calicoctl/resourcemgr/stagednetworkpolicy.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
  calicoctl/tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#9973 [CORE-11149] Updating k8s, and golang.org/x/crypto versions
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#9977 Introduce common interface for endpoint datatypes.
  felix/calc/active_rules_calculator.go
  felix/calc/calc_graph.go
  felix/calc/endpoint_lookup_cache.go
  felix/calc/event_sequencer.go
  felix/calc/policy_resolver.go
  felix/calc/policy_resolver_test.go
  libcalico-go/lib/backend/model/endpoints.go
  libcalico-go/lib/backend/model/hostendpoint.go
  libcalico-go/lib/backend/model/workloadendpoint.go
Labels: docs-not-required, release-note-not-required

#9901 AutoHEP Kube-Controller enable custom hostendpoint templates
  api/pkg/apis/projectcalico/v3/kubecontrollersconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  charts/calico/templates/calico-kube-controllers-rbac.yaml
  kube-controllers/pkg/config/config_test.go
  kube-controllers/pkg/config/runconfig.go
  kube-controllers/pkg/controllers/node/auto_hep_fv_test.go
  kube-controllers/pkg/controllers/node/controller.go
  kube-controllers/pkg/controllers/node/etcd_ipam_gc_fv_test.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
  kube-controllers/pkg/controllers/node/metrics_fv_test.go
  kube-controllers/pkg/controllers/utils/syncer.go
  kube-controllers/tests/testutils/node_controller_utils.go
  libcalico-go/config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  libcalico-go/lib/clientv3/kubecontrollersconfig.go
  libcalico-go/lib/clientv3/kubecontrollersconfig_e2e_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  node/tests/k8st/infra/calico-kdd.yaml
Labels: release-note-required, docs-pr-required, Review effort 4/5

#9766 Add mock implementation of calico-node for scale testing.
  .semaphore/push-images/mock-node.yml
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/03-promotions.yml
  .semaphore/semaphore.yml.d/blocks/60-mock-node.yml
  test-tools/mocknode/Dockerfile
  test-tools/mocknode/Makefile
  test-tools/mocknode/cmd/mocknode/main.go
  test-tools/mocknode/hack/patch-cluster
  test-tools/mocknode/mock-node.yaml
Labels: docs-not-required, release-note-not-required

#9978 Add Goldmane to manifests by default
  charts/tigera-operator/crds/operator.tigera.io_goldmanes_crd.yaml
  charts/tigera-operator/templates/crs/custom-resources.yaml
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  charts/tigera-operator/values.yaml
  manifests/custom-resources.yaml
  manifests/generate.sh
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/operator-crds.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#9981 [CORE-11149] Updating golang.org/x/net versions
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#9986 Fix a few bugs in policy hit parsing to/from string, and stop panicking
  felix/collector/goldmane/client.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/proto/methods.go
  goldmane/proto/methods_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#9979 Add basic flow collection FV in Goldmane
  goldmane/fv/flow_collector_test.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/client/client.go
  goldmane/pkg/server/flow_collector_service.go
  goldmane/pkg/testutils/flows.go
Labels: docs-not-required, release-note-not-required

#9982 Goldmane emitter improvements
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/http_client.go
  lib/std/chanutil/chan.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#9993 Add FilterTypeUnspecified for goldmane filter hints
  goldmane/pkg/aggregator/aggregator.go
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
Labels: docs-not-required, release-note-not-required

#9974 Add Filters endpoint
  goldmane/pkg/client/flowservice.go
  goldmane/pkg/client/mocks/FlowsClient.go
  goldmane/pkg/daemon/daemon.go
  lib/httpmachinery/pkg/apiutil/handler.go
  lib/httpmachinery/pkg/apiutil/handler_test.go
  lib/httpmachinery/pkg/apiutil/response.go
  lib/std/chanutil/chan.go
  lib/std/cryptoutils/cert.go
  lib/std/ptr/conversion.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/apis/v1/flows_test.go
  whisker-backend/pkg/apis/v1/testfiles/flow_filters_exact.json
  whisker-backend/pkg/apis/v1/testfiles/flow_filters_fuzzy.json
  whisker-backend/pkg/handlers/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows_test.go
  whisker-backend/pkg/handlers/v1/protoconvert.go
  whisker-backend/test/fv/goldmaneintegration_test.go
  whisker-backend/test/fv/util.go
Labels: docs-not-required, release-note-not-required

#9990 Avoid calls to WithFields in StatsCollector/HealthAggregator
  felix/calc/stats_collector.go
  libcalico-go/lib/health/health.go
Labels: release-note-required, docs-not-required

#9992 CORE-11149: Updating node-driver-registrar version
  pod2daemon/Makefile
  pod2daemon/patches/0001-Update-go.mod-to-patch-CVEs.patch
Labels: docs-not-required, release-note-not-required

#10000 [TSLA-8697] whisker port omni filter
  whisker/package.json
  whisker/src/features/flowLogs/api/__tests__/index.test.tsx
  whisker/src/features/flowLogs/api/index.ts
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/features/flowLogs/components/OmniFilters/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/index.tsx
  whisker/src/hooks/__tests__/omniFilters.test.ts
  whisker/src/hooks/index.ts
  whisker/src/hooks/omniFilters.ts
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ActionMenu/__tests__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/DataTable/NoResults/__tests__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedTableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableHeader/__tests__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/__test__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/parts/OmniFilterContainer/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/parts/OmniFilterTrigger/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/OmniFilter/parts/index.ts
  whisker/src/libs/tigera/ui-components/components/common/Select/styles.ts
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/theme/colors.ts
  whisker/src/theme/components/Button.ts
  whisker/src/theme/components/Popover.ts
  whisker/src/theme/components/Table.ts
  whisker/src/types/api.ts
  whisker/src/utils/__tests__/index.test.ts
  whisker/src/utils/omniFilter.ts
  whisker/yarn.lock
Labels: docs-not-required, release-note-not-required

#9994 Add proper prefix for ANP|BANP policies in flowlogs
  felix/calc/endpoint_lookup_cache.go
  felix/calc/policy_lookup_cache.go
  felix/calc/policy_lookups_cache_test.go
  libcalico-go/lib/names/policy.go
  libcalico-go/lib/upgrade/migrator/migrate.go
Labels: docs-not-required, release-note-not-required

#9995 Add dynamic enable/disable of flow emission
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/sink.go
  goldmane/pkg/aggregator/bucketing/utils.go
  goldmane/pkg/aggregator/options.go
  goldmane/pkg/aggregator/utils_test.go
  goldmane/pkg/daemon/config.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/bucket_cache.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/http_client.go
  goldmane/pkg/internal/utils/files.go
  goldmane/pkg/internal/utils/files_test.go
Labels: docs-not-required, release-note-not-required

#9998 Update Go dependencies Mar. 2025
  .semaphore/vms/create-test-vm
  api/go.mod
  api/go.sum
  felix/.semaphore/create-test-vm
  go.mod
  go.sum
  lib/httpmachinery/go.mod
  lib/httpmachinery/go.sum
  lib/std/go.mod
  metadata.mk
  release/internal/registry/image.go
Labels: docs-not-required, release-note-not-required

#10002 [CORE-11149] Updating k8s version to 1.30.11
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#10005 Fix windows cni-plugin fv
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-cni-plugin.yml
  cni-plugin/.semaphore/run-win-fv.sh
  process/testing/winfv-cni-plugin/aso/Makefile
  process/testing/winfv-cni-plugin/aso/export-env.sh
  process/testing/winfv-cni-plugin/aso/setup-fv.sh
Labels: docs-not-required, release-note-not-required

#9989 [CORE-10976] Add number of connections limiting QoS control
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  felix/Makefile
  felix/docker-image/Dockerfile
  felix/fv/connectivity/conncheck.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/iptables_lock_test.go
  felix/fv/qos_controls_test.go
  felix/fv/run-test
  felix/fv/utils/utils.go
  felix/fv/workload/workload.go
  felix/generictables/actions.go
  felix/iptables/actions.go
  felix/iptables/actions_test.go
  felix/nftables/actions.go
  felix/nftables/actions_test.go
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
Labels: release-note-required, docs-not-required

#10007 CORE-11149: Updating k8s version to 1.30.11
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#10003 kube-controllers don't create autoheps when autoCreate is disabled
  kube-controllers/pkg/controllers/node/auto_hep_fv_test.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
Labels: docs-not-required, release-note-not-required, Review effort 3/5

#10011 Fix Tier hint in end-of-tier policies
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#10010 Update goldmane and whisker crds with overrides
  charts/tigera-operator/crds/operator.tigera.io_goldmanes_crd.yaml
  charts/tigera-operator/crds/operator.tigera.io_whiskers_crd.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#10006 Add basic health check for main loop
  felix/daemon/daemon.go
  goldmane/Makefile
  goldmane/cmd/health/main.go
  goldmane/docker/Dockerfile
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/options.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/options.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#10012 Fix typo
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
Labels: docs-not-required, release-note-not-required

#10009 Add policy filter
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/apis/v1/flows_test.go
  whisker-backend/pkg/apis/v1/testfiles/flow_filters_exact.json
  whisker-backend/pkg/apis/v1/testfiles/flow_filters_fuzzy.json
  whisker-backend/pkg/handlers/v1/flows_test.go
  whisker-backend/pkg/handlers/v1/protoconvert.go
Labels: docs-not-required, release-note-not-required

#10016 Update operator CRDs.
  charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml
  manifests/ocp/custom-resources.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#9876 Improve EndpointLookupsCache occupancy
  felix/calc/endpoint_lookup_cache.go
  felix/calc/endpoint_lookup_cache_test.go
  felix/calc/lookups_cache.go
  felix/calc/networkset_lookup_cache.go
  felix/calc/networkset_lookup_cache_test.go
  felix/collector/collector.go
  felix/collector/collector_test.go
  felix/collector/flowlog/aggregator_test.go
  felix/collector/flowlog/fixtures_test.go
  felix/collector/stats.go
  felix/collector/types/endpoint/endpoint.go
  felix/collector/types/metric/metric.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#10017 [TSLA-8424] Whisker denied flows tab filter
  whisker/.nvmrc
  whisker/Makefile
  whisker/jest.config.js
  whisker/src/App.tsx
  whisker/src/api/__tests__/index.test.ts
  whisker/src/components/index.tsx
  whisker/src/features/flowLogs/api/__tests__/index.test.tsx
  whisker/src/features/flowLogs/api/index.ts
  whisker/src/features/flowLogs/components/FlowLogsList/styles.ts
  whisker/src/features/flowLogs/components/OmniFilters/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/index.tsx
  whisker/src/hooks/__tests__/omniFilters.test.ts
  whisker/src/hooks/omniFilters.ts
  whisker/src/icons/ArrowRightIcon.tsx
  whisker/src/icons/CalicoWhiskerIcon.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedTableRow/index.tsx
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/types/api.ts
  whisker/src/utils/__tests__/index.test.ts
  whisker/src/utils/omniFilter.ts
Labels: docs-not-required, release-note-not-required

#10018 Disable Whisker / Goldmane in OCP auto-generation
  manifests/generate.sh
  manifests/ocp/01-cr-goldmane.yaml
  manifests/ocp/01-cr-whisker.yaml
Labels: docs-not-required, release-note-not-required

#10020 Use buffered channel for service updates
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller.go
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller_ut_test.go
Labels: docs-not-required, release-note-not-required

#9423 [BPF] always use bpf_redir_neigh after FIB lookup
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/fib.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/fib_common.h
  felix/bpf-gpl/fib_legacy.h
  felix/bpf-gpl/tc.c
  felix/bpf/conntrack/v3/map.go
  felix/bpf/conntrack/v3/map6.go
  felix/bpf/ut/nat_test.go
  felix/bpf/ut/pkt_byte_counts_test.go
Labels: docs-not-required, release-note-not-required

#9957 eBPF: Fix cleanup of DSR flows
  felix/bpf-gpl/conntrack_cleanup.c
  felix/bpf/conntrack/cttestdata/ct_data.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready, squash-commits

#10022 Reuse flowlog values in FVs
  felix/collector/flowlog/aggregator_test.go
  felix/collector/flowlog/types.go
  felix/fv/flow_logs_goldmane_staged_test.go
  felix/fv/flow_logs_goldmane_test.go
  felix/fv/metrics/flow_tester.go
Labels: docs-not-required, release-note-not-required

#10021 Watchercache fixes
  libcalico-go/lib/backend/api/api.go
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  libcalico-go/lib/testutils/syncertester.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#9875 Support nested BGP peering with calico-nodes running in local kubevirt VM pods
  api/pkg/apis/projectcalico/v3/bgpconfig.go
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/openapi/generated.openapi.go
  confd/etc/calico/confd/templates/bird.cfg.template
  confd/etc/calico/confd/templates/bird6.cfg.template
  confd/pkg/backends/calico/client.go
  confd/pkg/backends/calico/local_bgp_peer_watcher.go
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird6.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird6_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird6_ipam.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird_aggr.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird_ipam.cfg
  confd/tests/test_suite_common.sh
  felix/calc/active_bpgpeer_calculator.go
  felix/calc/active_bpgpeer_calculator_test.go
  felix/calc/calc_graph.go
  felix/calc/calc_graph_bench_test.go
  felix/calc/endpoint_lookup_cache.go
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/calc/policy_resolver.go
  felix/calc/policy_resolver_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/status_combiner.go
  felix/dataplane/linux/status_combiner_test.go
  felix/fv/pod_setup_wait_test.go
  felix/linkaddrs/link_addrs.go
  felix/linkaddrs/link_addrs_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/statusrep/status_file_reporter.go
  felix/statusrep/status_file_reporter_test.go
  libcalico-go/config/crd/crd.projectcalico.org_bgpconfigurations.yaml
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  libcalico-go/lib/backend/syncersv1/felixsyncer/felixsyncerv1.go
  libcalico-go/lib/epstatusfile/epstatusfile_suite_test.go
  libcalico-go/lib/epstatusfile/status_file_watcher.go
  libcalico-go/lib/epstatusfile/status_file_watcher_test.go
  libcalico-go/lib/epstatusfile/status_file_writer.go
  libcalico-go/lib/epstatusfile/status_file_writer_test.go
  libcalico-go/lib/selector/selector.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/custom-resources.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10001 Generate flow logs for tier's default pass action
  felix/calc/endpoint_lookup_cache.go
  felix/calc/endpoint_lookup_cache_test.go
  felix/collector/collector.go
  felix/collector/collector_test.go
  felix/collector/flowlog/fixtures_test.go
  felix/fv/flow_logs_goldmane_test.go
  felix/fv/tiered_policy_test.go
Labels: docs-not-required, release-note-not-required

#10030 Don't go unready in emitter
  goldmane/pkg/emitter/emitter.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#10035 Refactor key-cert-provisioner to be compatible with felix config
  key-cert-provisioner/cmd/main.go
  key-cert-provisioner/pkg/cfg/config.go
  key-cert-provisioner/pkg/k8s/certificate.go
  key-cert-provisioner/pkg/k8s/certificate_test.go
  key-cert-provisioner/pkg/tls/tls.go
  key-cert-provisioner/pkg/tls/tls_test.go
Labels: docs-not-required, release-note-not-required

#10033 flowlog: Remove original source addresses
  felix/collector/collector.go
  felix/collector/collector_test.go
  felix/collector/flowlog/aggregator.go
  felix/collector/flowlog/aggregator_test.go
  felix/collector/flowlog/fixtures_test.go
  felix/collector/flowlog/reporter_test.go
  felix/collector/flowlog/types.go
  felix/collector/flowlog/types_test.go
  felix/collector/stats.go
  felix/collector/stats_test.go
  felix/collector/types/boundedset/boundedset.go
  felix/collector/types/boundedset/boundedset_suite_test.go
  felix/collector/types/boundedset/boundedset_test.go
  felix/collector/types/metric/metric.go
Labels: docs-not-required, release-note-not-required

#10037 Add basic daemon FV
  goldmane/fv/daemon_test.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/client/tls.go
  goldmane/pkg/emitter/emitter.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#9396 fix: include new fields in cni Add success result
  cni-plugin/pkg/k8s/k8s.go
  cni-plugin/pkg/plugin/plugin.go
  cni-plugin/tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#10034 flowlogs: Remove natoutging fields
  felix/collector/flowlog/aggregator.go
  felix/collector/flowlog/aggregator_test.go
  felix/collector/flowlog/types.go
Labels: docs-not-required, release-note-not-required

#10031 flowlog: Remove all policies trace
  felix/collector/flowlog/aggregator_test.go
  felix/collector/flowlog/fixtures_test.go
  felix/collector/flowlog/reporter_test.go
  felix/collector/flowlog/types.go
  felix/collector/flowlog/types_test.go
Labels: docs-not-required, release-note-not-required

#10039 [Release v3.30] Pick flowlogs cleanup
  felix/collector/flowlog/aggregator.go
  felix/collector/flowlog/aggregator_test.go
  felix/collector/flowlog/fixtures_test.go
  felix/collector/flowlog/reporter_test.go
  felix/collector/flowlog/types.go
  felix/collector/flowlog/types_test.go
Labels: docs-not-required, release-note-not-required

#10042 Adjust default Goldmane endpoint
  guardian/pkg/config/config.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#10051 fix conversion for protobuf to flow response - the BytesOut in the fl…
  whisker-backend/pkg/handlers/v1/protoconvert.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#10052 [release-v3.30] Auto pick #10051: fix conversion for protobuf to flow response - the BytesOut
  whisker-backend/pkg/handlers/v1/protoconvert.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready

#10047 Fix Goldmane historical Flow Streaming
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#10053 [release-v3.30] Auto pick #10047: Fix historical streaming of Flows
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#10057 [release-v3.30] Goldmane / whisker picks
  goldmane/fv/daemon_test.go
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/index.go
  goldmane/pkg/aggregator/index_test.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/pkg/client/flowservice.go
  goldmane/pkg/client/mocks/FlowsClient.go
  goldmane/pkg/client/tls.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/internal/types/list.go
  goldmane/pkg/server/flow_service.go
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
  goldmane/proto/api_grpc.pb.go
  guardian/pkg/config/config.go
  lib/httpmachinery/pkg/apiutil/response.go
  lib/std/chanutil/chan.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/apis/v1/flows_test.go
  whisker-backend/pkg/handlers/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows_test.go
  whisker-backend/test/fv/goldmaneintegration_test.go
  whisker/src/features/flowLogs/api/__tests__/index.test.tsx
  whisker/src/features/flowLogs/api/index.ts
Labels: docs-not-required, release-note-not-required

#10055 [release tool] fix generating release notes
  release/internal/outputs/releasenotes.go
Labels: docs-not-required, release-note-not-required

#10059 Fix flakey whisker -> goldmane integration test
  whisker-backend/test/fv/goldmaneintegration_test.go
  whisker-backend/test/fv/util.go
Labels: docs-not-required, release-note-not-required

#10025 CORE-11195: replace docker.io with quay.io
  charts/calico/values.yaml
  charts/tigera-operator/README.md
  charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  charts/tigera-operator/values.yaml
  hack/postrelease/test_images.py
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/operator-crds.yaml
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
  node/tests/k8st/infra/calicoctl.yaml
  node/tests/k8st/infra/values.yaml
  process/testing/winfv-felix/infra/porter.yaml
Labels: release-note-required, docs-not-required

#10060 fix ci-preflight-checks failing
  calicoctl/Makefile
  metadata.mk
  node/Makefile
Labels: docs-not-required, release-note-not-required

#10063 fix ci-preflight-checks failing (#10060)
  calicoctl/Makefile
  metadata.mk
  node/Makefile
Labels: docs-not-required, release-note-not-required

#10050 k8sst tests for nested BGP
  node/tests/k8st/test_base.py
  node/tests/k8st/tests/test_local_bgp_peer.py
  node/tests/k8st/utils/utils.py
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10064 [release-v3.30] Auto pick #10054: Fix location of gatewayapi CRD
  charts/tigera-operator/crds/operator.tigera.io_gatewayapis_crd.yaml
  manifests/operator-crds.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10068 Update generated files and operator CRDs
  app-policy/proto/healthz.pb.go
  charts/tigera-operator/crds/operator.tigera.io_imagesets_crd.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#10070 [release-v3.30 PICKS] Whisker and Goldmane picks
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/proto/api.pb.go
  goldmane/proto/api.proto
  whisker-backend/test/fv/goldmaneintegration_test.go
  whisker-backend/test/fv/util.go
  whisker/src/utils/omniFilter.ts
Labels: docs-not-required, release-note-not-required

#10065 Update hcsshim to v0.11.8 to fix EndpointState string()
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#10072 [TSLA-9045] improve filtering ux latest
  whisker/src/api/__tests__/index.test.ts
  whisker/src/api/index.ts
  whisker/src/features/flowLogs/api/__tests__/index.test.tsx
  whisker/src/features/flowLogs/api/index.ts
  whisker/src/features/flowLogs/components/FlowLogDetails/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsContainer/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsContainer/index.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/flowLogsTable.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/features/flowLogs/components/OmniFilters/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/index.tsx
  whisker/src/features/flowLogs/hooks/__tests__/index.test.ts
  whisker/src/features/flowLogs/hooks/index.tsx
  whisker/src/features/flowLogs/utils/index.ts
  whisker/src/hooks/__tests__/omniFilters.test.ts
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/__tests__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/TableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedRows/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedTableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/Table/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/hooks/__tests__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/hooks/index.tsx
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/types/api.ts
  whisker/src/types/render.ts
  whisker/src/utils/__tests__/index.test.ts
  whisker/src/utils/omniFilter.ts
Labels: docs-not-required, release-note-not-required

#10062 [TSLA-9045] improve filtering ux 3.30
  whisker/src/api/__tests__/index.test.ts
  whisker/src/api/index.ts
  whisker/src/features/flowLogs/api/__tests__/index.test.tsx
  whisker/src/features/flowLogs/api/index.ts
  whisker/src/features/flowLogs/components/FlowLogDetails/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsContainer/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsContainer/index.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/flowLogsTable.tsx
  whisker/src/features/flowLogs/components/FlowLogsList/index.tsx
  whisker/src/features/flowLogs/components/OmniFilters/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/OmniFilters/index.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/PortOmniFilter/index.tsx
  whisker/src/features/flowLogs/hooks/__tests__/index.test.ts
  whisker/src/features/flowLogs/hooks/index.tsx
  whisker/src/features/flowLogs/utils/index.ts
  whisker/src/hooks/__tests__/omniFilters.test.ts
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/__tests__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/TableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedRows/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/components/VirtualizedTableRow/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/ResizableBody/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/Table/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/hooks/__tests__/index.test.tsx
  whisker/src/libs/tigera/ui-components/components/common/DataTable/hooks/index.tsx
  whisker/src/pages/FlowLogsPage/__tests__/index.test.tsx
  whisker/src/pages/FlowLogsPage/index.tsx
  whisker/src/types/api.ts
  whisker/src/types/render.ts
  whisker/src/utils/__tests__/index.test.ts
  whisker/src/utils/omniFilter.ts
Labels: docs-not-required, release-note-not-required

#10071 Fix race condition in Goldmane UTs
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10043 Use unique.Handle to deduplicate FlowKey fields
  felix/collector/goldmane/client.go
  felix/fv/flowlogs/goldmane_mock.go
  felix/fv/infrastructure/felix.go
  goldmane/fv/daemon_test.go
  goldmane/fv/flow_collector_test.go
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/stats.go
  goldmane/pkg/aggregator/bucketing/utils.go
  goldmane/pkg/aggregator/index.go
  goldmane/pkg/aggregator/index_test.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/pkg/aggregator/stream_manager.go
  goldmane/pkg/client/client.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/flowgen/testserver.go
  goldmane/pkg/internal/flowcache/timed_cache.go
  goldmane/pkg/internal/types/flow.go
  goldmane/pkg/server/flow_collector_service.go
  goldmane/pkg/types/diachronic_flow.go
  goldmane/pkg/types/diachronic_flow_test.go
  goldmane/pkg/types/filters.go
  goldmane/pkg/types/flow.go
  goldmane/pkg/types/flow_test.go
  goldmane/pkg/types/list.go
  goldmane/proto/methods.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10076 Goldmane should emit proto.Flow objects, not type.Flows
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/emitter_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10075 [release-v3.30] Auto pick #10043: Use unique.Handle to deduplicate FlowKey fields
  felix/collector/goldmane/client.go
  felix/fv/flowlogs/goldmane_mock.go
  felix/fv/infrastructure/felix.go
  goldmane/fv/daemon_test.go
  goldmane/fv/flow_collector_test.go
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
  goldmane/pkg/aggregator/bucketing/bucket.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/stats.go
  goldmane/pkg/aggregator/bucketing/utils.go
  goldmane/pkg/aggregator/index.go
  goldmane/pkg/aggregator/index_test.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/pkg/aggregator/stream_manager.go
  goldmane/pkg/client/client.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/flowgen/testserver.go
  goldmane/pkg/internal/flowcache/timed_cache.go
  goldmane/pkg/internal/types/flow.go
  goldmane/pkg/server/flow_collector_service.go
  goldmane/pkg/types/diachronic_flow.go
  goldmane/pkg/types/diachronic_flow_test.go
  goldmane/pkg/types/filters.go
  goldmane/pkg/types/flow.go
  goldmane/pkg/types/flow_test.go
  goldmane/pkg/types/list.go
  goldmane/proto/methods.go
Labels: docs-not-required, release-note-not-required

#10078 [release-v3.30] Auto pick #10071: Fix race condition in Goldmane UTs
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/aggregator_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10077 [release-v3.30] Auto pick #10076: Goldmane should emit proto.Flow objects, not type.Flows
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/emitter_test.go
Labels: docs-not-required, release-note-not-required

#10074 Goldmane: log grpc client target
  goldmane/pkg/client/client.go
Labels: docs-not-required, release-note-not-required

#10079 [Release v3.30] Goldmane: log grpc client target
  goldmane/pkg/client/client.go
Labels: docs-not-required, release-note-not-required

#10080 Remove debug log
  goldmane/pkg/emitter/emitter.go
Labels: docs-not-required, release-note-not-required

#10082 [master] Auto pick #10080: Remove debug log
  goldmane/pkg/emitter/emitter.go
Labels: docs-not-required, release-note-not-required

#10069 Forward packets from workload to host interfaces not managed by calico.
  felix/bpf-gpl/fib_common.h
  felix/bpf-gpl/ifstate.h
  felix/bpf/ifstate/map.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
  felix/fv/infrastructure/felix.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10085 [release-v3.30] Auto pick #10069: Forward packets from workload to host interfaces not
  felix/bpf-gpl/fib_common.h
  felix/bpf-gpl/ifstate.h
  felix/bpf/ifstate/map.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
  felix/fv/infrastructure/felix.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10091 Add managementclusterconnection finalizer and status permissions to the operator
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#10083 Remove CRDs from manifests/ocp and add new preflight check
  Makefile
  manifests/ocp/crd.projectcalico.org_felixconfigurations.yaml
  manifests/ocp/custom-resources.yaml
  manifests/ocp/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
Labels: docs-not-required, release-note-not-required

#10092 [PICK release-v3.30] Add managementclusterconnection finalizer and status permissions to the operator
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#10049 [BPF] cleanup CT entries for new UDP service IPs
  felix/bpf/conntrack/cleanup.go
  felix/bpf/conntrack/conntrack_test.go
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
  felix/bpf/proxy/syncer_test.go
  felix/fv/bpf_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10094 Fix whisker-backend fv failure - type mismatch on cli.Push()
  whisker-backend/test/fv/goldmaneintegration_test.go
Labels: docs-not-required, release-note-not-required

#10097 Ffix failing fvs for whisker
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-whisker-backend.yml
  whisker-backend/test/fv/goldmaneintegration_test.go
Labels: docs-not-required, release-note-not-required

#10099 [cherry pick] allow generating empty release note
  release/internal/outputs/releasenotes.go
Labels: docs-not-required, release-note-not-required

#9836 [release tool] fix branch commands
  release/cmd/branch.go
  release/cmd/flags.go
  release/internal/version/version.go
Labels: docs-not-required, release-note-not-required

#10102 Specify min TLS version 1.2 for Goldmane
  goldmane/pkg/emitter/http_client.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10101 [PICKS release-v3.30] FV picks
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-whisker-backend.yml
  whisker-backend/test/fv/goldmaneintegration_test.go
Labels: docs-not-required, release-note-not-required

#10084 Adjust flow generator implementation + mem optimization
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/bucketing/bucket.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/options.go
  goldmane/pkg/aggregator/index_test.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/pkg/client/client.go
  goldmane/pkg/flowgen/testserver.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10106 [release-v3.30] Auto pick #10102: Specify min TLS version 1.2 for Goldmane
  goldmane/pkg/emitter/http_client.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10105 [release-v3.30] Auto pick #10084: Adjust flow generator implementation
  goldmane/pkg/aggregator/aggregator.go
  goldmane/pkg/aggregator/bucketing/bucket.go
  goldmane/pkg/aggregator/bucketing/bucket_ring.go
  goldmane/pkg/aggregator/bucketing/options.go
  goldmane/pkg/aggregator/index_test.go
  goldmane/pkg/aggregator/ring_index.go
  goldmane/pkg/client/client.go
  goldmane/pkg/flowgen/testserver.go
Labels: docs-not-required, release-note-not-required

#10015 [CORE-11082] Install Calico in OCP with eBPF mode as the default
  Makefile
  manifests/generate.sh
  manifests/ocp/01-configmap-kubernetes-services-endpoint.yaml
  manifests/ocp/01-cr-installation.yaml
  manifests/ocp/cluster-network-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
Labels: release-note-required, docs-pr-required

#10061 flowlogs: sync with enterprise
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/events.h
  felix/bpf-gpl/tc.c
  felix/fv/flow_logs_goldmane_staged_test.go
  felix/fv/flow_logs_goldmane_test.go
  felix/fv/flowlogs/flow_tester.go
  felix/fv/flowlogs/goldmane_mock.go
  felix/fv/tiered_policy_test.go
Labels: docs-not-required, release-note-not-required

#10014 Adjust UI disaply of Global, Public, Private
  goldmane/pkg/aggregator/index.go
  goldmane/pkg/types/filters.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows.go
  whisker-backend/pkg/handlers/v1/protoconvert.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10109 [release-v3.30] Auto pick #10014: Adjust UI disaply of Global, Public, Private
  goldmane/pkg/aggregator/index.go
  goldmane/pkg/types/filters.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows.go
  whisker-backend/pkg/handlers/v1/protoconvert.go
Labels: docs-not-required, release-note-not-required

#10048 [EV-5631] Align pending_policies check to flush interval update
  felix/fv/flow_logs_goldmane_staged_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready
