Repository projectcalico/calico, pull requests merged in 2025-06, with the labels that each got.

#10492 [v3.30] reduce slack notifications to annoucing hashreleases. (#10305)
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/internal/slack/message.go
  release/internal/slack/message_test.go
  release/internal/slack/slack.go
  release/internal/slack/templates/failure.json.gotmpl
  release/internal/slack/templates/missing-images.json.gotmpl
  release/pkg/tasks/notification.go
Labels: docs-not-required, release-note-not-required

#10503 Fix mounting cgroupv2 into calico-node
  node/cmd/mountns/main.go
Labels: release-note-required, docs-not-required

#10499 Two small improvements to OpenStack UT coding
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
  networking-calico/Dockerfile
  networking-calico/Makefile
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
Labels: docs-not-required, release-note-not-required

#9813 [release tool] hashrelease promotion pipeline
  .semaphore/release/hashrelease.yml
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/internal/ci/semaphore.go
Labels: docs-not-required, release-note-not-required

#10508 Fix race in Goldmane writing to stream
  goldmane/pkg/stream/stream_manager.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#10506 [release-v3.28] Auto pick #10503: Fix mounting cgroupv2 into calico-node
  node/cmd/mountns/main.go
Labels: release-note-required, docs-not-required

#10505 [release-v3.29] Auto pick #10503: Fix mounting cgroupv2 into calico-node
  node/cmd/mountns/main.go
Labels: release-note-required, docs-not-required

#10504 [release-v3.30] Auto pick #10503: Fix mounting cgroupv2 into calico-node
  node/cmd/mountns/main.go
Labels: release-note-required, docs-not-required

#10515 Use common version implementation in app-policy
  app-policy/Makefile
  app-policy/cmd/dikastes/dikastes.go
Labels: docs-not-required, release-note-not-required

#10512 Close race condition in Goldmane startup
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/goldmane/goldmane.go
  goldmane/pkg/goldmane/goldmane_test.go
Labels: release-note-required, docs-not-required

#10489 [CORE-11448] QoS controls: add packet burst configuration
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/docker-image/Dockerfile
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/qos_controls_test.go
  felix/generictables/actions.go
  felix/iptables/actions.go
  felix/iptables/actions_test.go
  felix/nftables/actions.go
  felix/nftables/actions_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/rules/endpoints.go
  felix/rules/endpoints_test.go
  libcalico-go/lib/apis/v3/generated.openapi.go
  libcalico-go/lib/apis/v3/workloadendpoint.go
  libcalico-go/lib/backend/k8s/conversion/constants.go
  libcalico-go/lib/backend/k8s/conversion/conversion_test.go
  libcalico-go/lib/backend/k8s/conversion/workload_endpoint_default.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/workloadendpointprocessor_test.go
Labels: release-note-required, docs-pr-required

#10510 [CORE-11495] v3.28.5 - Upgrade golang 1.23.10 and x/net library
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  pod2daemon/patches/0001-Update-go.mod-to-patch-CVEs.patch
Labels: hold-merge, docs-not-required, release-note-not-required

#10521 OpenStack-level support for packet rate burst
  libcalico-go/lib/apis/v3/generated.openapi.go
  libcalico-go/lib/apis/v3/workloadendpoint.go
  networking-calico/networking_calico/common/config.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/endpoints.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
Labels: release-note-required, docs-pr-required

#10525 Use lib/std clock for time tracking in goldmane / whisker and use ControlledClock for fv tests
  goldmane/fv/daemon_test.go
  goldmane/fv/flow_collector_test.go
  goldmane/pkg/client/client.go
  goldmane/pkg/daemon/config.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/bucket_cache.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/emitter/http_client.go
  goldmane/pkg/flowgen/generator.go
  goldmane/pkg/goldmane/goldmane.go
  goldmane/pkg/goldmane/goldmane_test.go
  goldmane/pkg/goldmane/options.go
  goldmane/pkg/goldmane/utils_test.go
  goldmane/pkg/internal/flowcache/timed_cache.go
  goldmane/pkg/internal/utils/files.go
  goldmane/pkg/internal/utils/files_test.go
  goldmane/pkg/server/flow_collector_service.go
  goldmane/pkg/storage/bucket.go
  goldmane/pkg/storage/bucket_ring.go
  goldmane/pkg/storage/bucket_test.go
  goldmane/pkg/storage/options.go
  goldmane/pkg/storage/utils.go
  goldmane/pkg/stream/stream.go
  goldmane/pkg/stream/stream_manager.go
  guardian/.mockery.yaml
  guardian/pkg/thirdpartymocks/std/time/Clock.go
  guardian/pkg/thirdpartymocks/std/time/Ticker.go
  guardian/pkg/thirdpartymocks/std/time/Timer.go
  guardian/pkg/tunnel/dial.go
  guardian/pkg/tunnel/tunnel.go
  guardian/pkg/tunnel/tunnel_test.go
  lib/std/chanutil/chan.go
  lib/std/time/controlled.go
  lib/std/time/standard.go
  lib/std/time/time.go
  whisker-backend/pkg/apis/v1/flows.go
  whisker-backend/pkg/handlers/v1/flows_test.go
  whisker-backend/pkg/handlers/v1/protoconvert.go
  whisker-backend/pkg/handlers/v1/suite_test.go
  whisker-backend/test/fv/goldmaneintegration_test.go
  whisker-backend/test/fv/util.go
Labels: docs-not-required, release-note-not-required

#10513 [release-v3.30] Auto pick #10508: Fix race in Goldmane writing to stream
  goldmane/pkg/stream/stream_manager.go
Labels: release-note-required, docs-not-required

#10490 ebpf - Fix attaching ctlb for ipv6 and detaching programs in legacy mode.
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/ut/attach_test.go
  felix/cmd/calico-bpf/commands/connect_time.go
  felix/dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#10526 [CORE-11447] Fix ReadEgressQdisc in qos.go
  felix/dataplane/linux/qos/qos.go
Labels: docs-not-required, release-note-not-required

#10528 [release-v3.28] Auto pick #10490: Fix attaching ctlb for ipv6 and detaching programs in
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/ut/attach_test.go
  felix/cmd/calico-bpf/commands/connect_time.go
  felix/dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#10511 [BPF] fix regression for multihomed nodes
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/rpf.h
  felix/fv/bpf_multi_home_test.go
Labels: release-note-required, docs-not-required

#10533 [release-v3.30] Auto pick #10490: Fix attaching ctlb for ipv6 and detaching programs in
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/ut/attach_test.go
  felix/cmd/calico-bpf/commands/connect_time.go
  felix/dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#10535 [release-v3.30] Auto pick #10511: fix regression for multihomed nodes
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/rpf.h
  felix/fv/bpf_multi_home_test.go
Labels: release-note-required, docs-not-required

#10471 Add NextHopMode to BGPPeer API
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  confd/etc/calico/confd/templates/bird.cfg.template
  confd/etc/calico/confd/templates/bird6.cfg.template
  confd/pkg/backends/calico/client.go
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird6.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird6_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird6_ipam.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird_ipam.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird6.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird6_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird6_ipam.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird_ipam.cfg
  confd/tests/test_suite_common.sh
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10539 Update default trusted bundle file path from "tigera-ca-bundle.crt" to "ca.crt"
  test-tools/mocknode/cmd/mocknode/main.go
  whisker-backend/pkg/config/api.go
Labels: docs-not-required, release-note-not-required

#10486 eBPF - Cleanup unused code.
  felix/bpf/attach.go
  felix/bpf/tc/attach.go
  felix/bpf/xdp/attach.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#10462 [cherry-pick #8685] Add Ubuntu 24.04 noble support for OpenStack
  .semaphore/push-images/packaging.yaml
  felix/debian/calico-felix.upstart
  felix/debian/compat
  felix/debian/control
  felix/debian/rules
  felix/debian/source/options
  networking-calico/debian/calico-dhcp-agent.upstart
  networking-calico/debian/compat
  networking-calico/debian/control
  networking-calico/debian/rules
  networking-calico/debian/source/options
  networking-calico/requirements.txt
  networking-calico/setup.cfg
  release/packaging/docker-build-images/centos7-build.Dockerfile.amd64
  release/packaging/docker-build-images/centos7-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/docker-bake.hcl
  release/packaging/docker-build-images/install-ubuntu-build-deps
  release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/ubuntu-jammy-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-jammy-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/ubuntu.Dockerfile
  release/packaging/utils/create-update-packages.sh
  release/packaging/utils/lib.sh
  release/packaging/utils/make-packages.sh
  release/packaging/utils/publish-debs.sh
  release/packaging/utils/publish-rpms.sh
Labels: docs-not-required, release-note-not-required

#10542 update go build version for v3.30
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  goldmane/pkg/client/mocks/FlowsClient.go
  goldmane/proto/mocks/Flows_StreamClient.go
  lib/httpmachinery/go.mod
  lib/httpmachinery/pkg/context/mocks/Context.go
  lib/std/go.mod
  metadata.mk
Labels: docs-pr-required, release-note-not-required

#10547 Update k8s version
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  lib/httpmachinery/go.mod
  lib/std/go.mod
Labels: docs-not-required, release-note-not-required

#10559 [release-v3.30] Auto pick #10558: fix bpfEnforceRPF=Disabled
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#10558 [BPF] fix bpfEnforceRPF=Disabled
  felix/bpf-gpl/conntrack.h
  felix/bpf-gpl/rpf.h
  felix/bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#10550 Added Kind k8st tests for BGP next hop mode
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/openapi/generated.openapi.go
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  node/tests/k8st/infra/build-operator.sh
  node/tests/k8st/infra/values.yaml
  node/tests/k8st/test_base.py
  node/tests/k8st/tests/test_local_bgp_peer.py
Labels: release-note-required, docs-pr-required

#10552 [Release v3.30] Add delete permission to tigera operator for ANP/BANP CRDs
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-not-required

#10562 Added NextHopMode to BGPPeer API (cherry picked from #10471 #10550)
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  confd/etc/calico/confd/templates/bird.cfg.template
  confd/etc/calico/confd/templates/bird6.cfg.template
  confd/pkg/backends/calico/client.go
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird6.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird6_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird6_ipam.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/global_peers/bird_ipam.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird6.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird6_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird6_ipam.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird_aggr.cfg
  confd/tests/compiled_templates/next_hop_mode/route_reflectors/bird_ipam.cfg
  confd/tests/test_suite_common.sh
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  node/tests/k8st/test_base.py
  node/tests/k8st/tests/test_local_bgp_peer.py
Labels: release-note-required, docs-pr-required

#10561 [CORE-11468] BPF: Replace exec calls to 'tc' binary with netlink library calls
  felix/bpf/tc/attach.go
  felix/bpf/tc/cleanup.go
  felix/bpf/tc/cleanup_test.go
  felix/fv/qos_controls_test.go
Labels: docs-not-required, release-note-not-required

#10570 [release tool] write ISS results to file only for 200 series response code
  release/internal/imagescanner/scanner.go
Labels: docs-not-required, release-note-not-required

#10571 [cherry-pick][v3.30] ISS response processing
  release/internal/imagescanner/scanner.go
Labels: docs-not-required, release-note-not-required

#10524 update registries in operator when using dev/custom registries
  release/cmd/hashrelease.go
  release/internal/pinnedversion/templates/calico-versions.yaml.gotmpl
  release/internal/registry/registry.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/operator/manager.go
  release/pkg/manager/operator/options.go
  release/pkg/manager/operator/template/images.go.gotmpl
  release/pkg/postrelease/images_test.go
Labels: docs-not-required, release-note-not-required

#10576 CRD update
  charts/tigera-operator/crds/operator.tigera.io_gatewayapis.yaml
  charts/tigera-operator/crds/operator.tigera.io_installations.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#10574 Move API server component from calico-apiserver to calico-system name…
  manifests/ocp/00-namespace-calico-apiserver.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#10270 Fail and retry if mtu file is failed to be written or not found
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  cni-plugin/internal/pkg/utils/utils.go
  cni-plugin/internal/pkg/utils/utils_test.go
  cni-plugin/pkg/install/install.go
  cni-plugin/pkg/install/install_linux.go
  cni-plugin/pkg/install/install_test.go
  cni-plugin/pkg/plugin/plugin.go
  cni-plugin/pkg/types/types.go
  cni-plugin/tests/calico_cni_k8s_test.go
  felix/config/config_params.go
  felix/config/config_params_test.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10581 use correct docker version for bpf FVs
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  felix/.semaphore/create-test-vm
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#10583 [release tool] fix operator image list
  release/internal/pinnedversion/pinnedversion.go
  release/internal/pinnedversion/release.go
  release/internal/registry/image.go
  release/pkg/manager/operator/manager.go
Labels: docs-not-required, release-note-not-required

#10584 fix ISS result in slack annoucements
  release/cmd/hashrelease.go
  release/internal/slack/message.go
Labels: docs-not-required, release-note-not-required

#10588 Fix flakiness of win cni-plugin CI
  process/testing/winfv-cni-plugin/aso/Makefile
  process/testing/winfv-cni-plugin/aso/vmss.sh
Labels: docs-not-required, release-note-not-required

#10553 Reduce log level for spammy log
  felix/dataplane/linux/endpoint_mgr.go
Labels: release-note-required, docs-not-required

#10597 Fix flakiness of win cni-plugin CI (#10588)
  process/testing/winfv-cni-plugin/aso/Makefile
  process/testing/winfv-cni-plugin/aso/vmss.sh
Labels: docs-not-required, release-note-not-required

#10595 Cherry-pick to v3.30: Fix CalicoNodeStatus update stuck in conflict
  node/pkg/status/nodestatus.go
  node/pkg/status/nodestatus_test.go
  node/pkg/status/reporter.go
Labels: release-note-required, docs-not-required

#10598 Remove '--all' flag from wait_pod_ready() in kind
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
Labels: docs-not-required, release-note-not-required

#10603 Add missing permissions to operator
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#10609 remove checking image promotions
  release/internal/ci/semaphore.go
Labels: docs-not-required, release-note-not-required
