Repository projectcalico/calico, pull requests merged in 2025-07, with the labels that each got.

#10621 Update CI builds and felix depends
  .semaphore/push-images/packaging.yaml
  felix/debian/control
Labels: docs-not-required, release-note-not-required

#10608 Felix EndpointStatusReporter: do NOT coalesce status flaps
  felix/statusrep/status_reporter.go
  felix/statusrep/status_reporter_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#10613 Add clusterinformation read access to tigera-operator
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  manifests/tigera-operator.yaml
Labels: release-note-required, docs-pr-required

#10614 [CORE-11385] ebpf: add support for NATOutgoingExclusions
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/routes.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/nat_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-not-required, merge-when-ready

#10617 Auto resize the conntrack map from the userspace cleaner.
  felix/bpf/conntrack/conntrack_test.go
  felix/bpf/conntrack/scanner.go
  felix/bpf/proxy/syncer_test.go
  felix/cmd/calico-bpf/commands/conntrack.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_map_resize_test.go
Labels: docs-not-required, release-note-not-required

#10627 Consider LoadBalancerClass when assigning service IP
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller.go
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller_ut_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10577 [release-tool] publish hashrelease to VM and GCS
  go.mod
  go.sum
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/internal/command/gcloud.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/config_test.go
  release/internal/hashreleaseserver/server.go
  release/pkg/manager/calico/manager.go
  release/pkg/tasks/notification.go
Labels: docs-not-required, release-note-not-required

#10630 API server - Policy WatchManager (#10346)
  apiserver/cmd/apiserver/server/run_server.go
  apiserver/pkg/apiserver/apiserver.go
  apiserver/pkg/registry/projectcalico/globalpolicy/storage.go
  apiserver/pkg/registry/projectcalico/networkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/rest/storage_calico.go
  apiserver/pkg/registry/projectcalico/stagedglobalnetworkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/stagednetworkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/util/watch_manager.go
  apiserver/test/integration/clientset_test.go
Labels: docs-not-required, release-note-not-required

#10573 ebpf - tcx support
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/.semaphore/run-tests-on-vms
  felix/Makefile
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/tcx_test.c
  felix/bpf/attach.go
  felix/bpf/bpf.go
  felix/bpf/bpfdefs/defs.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/tc/cleanup.go
  felix/bpf/ut/attach_test.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/bpf_test.go
  felix/fv/containers/containers.go
  felix/fv/infrastructure/felix.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10618 update manifest generation variables
  manifests/generate.sh
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#10633 fix publishing hashreleases to GCS
  .semaphore/release/hashrelease.yml
  release/internal/command/gcloud.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/server.go
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#10628 [release tool] update checking images for a hashrelease
  release/pkg/errors/errors.go
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#10636 [release tool] fix publishing to hashrelease VM
  release/internal/hashreleaseserver/server.go
Labels: docs-not-required, release-note-not-required

#10634 [release tool] update handling for image scan results
  release/internal/imagescanner/scanner.go
  release/internal/imagescanner/scanner_test.TestWriteScanResultToFile.approved.txt
  release/internal/imagescanner/scanner_test.go
Labels: docs-not-required, release-note-not-required

#10639 [v3.29] Cherrypick changes to ISS and hashrelease publishing
  .semaphore/release/hashrelease.yml
  go.mod
  go.sum
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/config_test.go
  release/internal/hashreleaseserver/server.go
  release/internal/imagescanner/scanner.go
  release/internal/imagescanner/scanner_test.go
  release/internal/slack/message.go
  release/pkg/manager/calico/manager.go
  release/pkg/tasks/notification.go
Labels: docs-not-required, release-note-not-required

#10647 update when images are sent to the images scanner
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#10649 Update go and k8s pins
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#10616 Update ubuntu packaging scripts
  release/packaging/utils/create-update-packages.sh
  release/packaging/utils/make-packages.sh
Labels: docs-not-required, release-note-not-required

#10654 Fix a nil-pointer panic in bpf_prog_test.go
  felix/bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#10651 [v3.29] update when images are sent to the images scanner (#10647)
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#10622 Update CI builds and felix depends [v3.30]
  .semaphore/push-images/packaging.yaml
Labels: release-note-required, docs-pr-required

#10081 Refactor UTs for endpoint nftable/iptables rules
  felix/rules/endpoints_test.go
Labels: docs-not-required, release-note-not-required

#10661 [release-v3.30] Auto pick #10660: fix ICMP replies when host has multiple IPs
  felix/bpf-gpl/icmp4.h
  felix/bpf-gpl/icmp6.h
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/icmp_too_big_test.go
Labels: release-note-required, docs-not-required

#10667 CORE-11535: Fix svlogd rotated log files permissions (Cherry pick #10590 into release OSS v3.29.5)
  node/.dockerignore
  node/Dockerfile.amd64
  node/Dockerfile.arm64
  node/patches/svlogd_use_0644_permission_instead_of_0744.patch
Labels: docs-not-required, release-note-not-required

#10673 [BPF] fix handling SYN retransmits
  felix/bpf-gpl/conntrack.h
Labels: docs-not-required, release-note-not-required, repo-refactor

#10671 [BPF] on ingress to node use pre-dnat IP for icmp response
  felix/bpf-gpl/icmp4.h
  felix/bpf-gpl/icmp6.h
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/icmp_port_unreachable_test.go
  felix/bpf/ut/icmp_too_big_test.go
  felix/bpf/ut/icmp_ttl_exceeded_test.go
  felix/bpf/ut/nat_test.go
Labels: release-note-required, docs-not-required

#10675 Added ReversePeering to BGPPeer API
  api/pkg/apis/projectcalico/v3/bgppeer.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  confd/pkg/backends/calico/client.go
  confd/tests/compiled_templates/reverse_peering/auto/bird.cfg
  confd/tests/compiled_templates/reverse_peering/auto/bird6.cfg
  confd/tests/compiled_templates/reverse_peering/auto/bird6_aggr.cfg
  confd/tests/compiled_templates/reverse_peering/auto/bird6_ipam.cfg
  confd/tests/compiled_templates/reverse_peering/auto/bird_aggr.cfg
  confd/tests/compiled_templates/reverse_peering/auto/bird_ipam.cfg
  confd/tests/compiled_templates/reverse_peering/manual/bird.cfg
  confd/tests/compiled_templates/reverse_peering/manual/bird6.cfg
  confd/tests/compiled_templates/reverse_peering/manual/bird6_aggr.cfg
  confd/tests/compiled_templates/reverse_peering/manual/bird6_ipam.cfg
  confd/tests/compiled_templates/reverse_peering/manual/bird_aggr.cfg
  confd/tests/compiled_templates/reverse_peering/manual/bird_ipam.cfg
  confd/tests/test_suite_common.sh
  libcalico-go/config/crd/crd.projectcalico.org_bgppeers.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  node/tests/k8st/tests/test_local_bgp_peer.py
Labels: release-note-required, docs-pr-required

#10679 Fix confd ut on local bgp peer
  confd/Makefile
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird6.cfg
  confd/tests/test_suite_common.sh
Labels: docs-not-required, release-note-not-required

#10653 Update urfave/cli to v3 in release tool [master]
  go.mod
  go.sum
  release/cmd/branch.go
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/main.go
  release/cmd/release.go
  release/cmd/shared.go
Labels: docs-not-required, release-note-not-required

#10680 [BPF] Set missing tunnel key on vxlan if BYPASS is set
  felix/bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#10682 deps: Bump go packages
  metadata.mk
  third_party/envoy-gateway/patches/0001-Bumping-x-net-and-containerd.patch
  third_party/envoy-ratelimit/Makefile
  third_party/envoy-ratelimit/patches/0001-Bump-golang.org-x-deps.patch
Labels: docs-not-required, release-note-not-required

#10678 OpenStack: Ignore 'updated_at' field when filtering status-only changes
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
Labels: docs-not-required, release-note-not-required

#10658 Avoid IPAM handle leak when context expires during assignment.
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  libcalico-go/lib/ipam/ipam.go
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
Labels: release-note-required, docs-not-required

#10698 Squash "bad CIDR" log when parsing headless service.
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-not-required

#10607 CORE-11601: Initializing BPF networking in `mount-bpffs` init container
  node/Makefile
  node/pkg/nodeinit/calico-init_linux.go
  node/pkg/nodeinit/calico-init_test.go
Labels: release-note-required, docs-pr-required

#10694 BPF: Fix BW QoS controls
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/routes.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/routes/map.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/whitelist_test.go
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/fv/qos_controls_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: docs-not-required, release-note-not-required

#10688 [release-v3.30] cherry-pick: defend against malformed notnets rules
  felix/rules/policy.go
  felix/rules/policy_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
Labels: release-note-required, docs-pr-required

#10702 [v3.29] Squash "bad CIDR" log when parsing headless service. (#10698)
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: release-note-required, docs-not-required

#10703 Fix confd on Windows by skipping watching endpoint status files (#10691)
  confd/pkg/backends/calico/client.go
  process/testing/winfv-cni-plugin/aso/vmss.sh
Labels: release-note-required, docs-not-required

#10713 Fix confd ut on local bgp peer (#10679)
  confd/Makefile
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird.cfg
  confd/tests/compiled_templates/explicit_peering/local_bgp_peer/bird6.cfg
  confd/tests/test_suite_common.sh
Labels: docs-not-required, release-note-not-required

#10716 OpenStack: ignore 'revision_number' when detecting status-only port updates
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
Labels: docs-not-required, release-note-not-required

#10472 Felix programs in-cluster no encapsulation routes
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/noencap_mgr.go
  felix/dataplane/linux/noencap_mgr_test.go
  felix/dataplane/linux/route_mgr.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/fv/ipip_test.go
  felix/fv/routing_test.go
  felix/routetable/defs.go
  felix/routetable/routeclass_string.go
Labels: release-note-required, docs-pr-required

#10721 BPF: Fix that stale-NAT cleanup didn't wait for kube-proxy sync
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/kube-proxy_internal_test.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10724 [v3.30] BPF: Fix that stale-NAT cleanup didn't wait for kube-proxy sync
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/kube-proxy_internal_test.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10722 [TSLA-9908] bump eslint dependencies
  whisker/README.md
  whisker/package.json
  whisker/yarn.lock
Labels: docs-not-required, release-note-not-required

#10725 [v3.29] BPF: Fix that stale-NAT cleanup didn't wait for kube-proxy sync
  felix/bpf/proxy/kube-proxy.go
  felix/bpf/proxy/kube-proxy_internal_test.go
  felix/bpf/proxy/proxy.go
  felix/bpf/proxy/proxy_test.go
  felix/bpf/proxy/syncer.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10742 Allow changing extenal client image in Felix FVs
  felix/fv/infrastructure/ext_client.go
Labels: docs-not-required, release-note-not-required

#10747 Replace IPSetMember struct with an interface
  felix/bpf/bpf.go
  felix/bpf/bpf_test.go
  felix/bpf/cmd/felix-xdp.go
  felix/bpf/mock_bpf_lib.go
  felix/calc/calc_graph.go
  felix/calc/calc_graph_bench_test.go
  felix/calc/event_sequencer.go
  felix/calc/rule_scanner.go
  felix/calc/state_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/ipsets/ipset_defs.go
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/labelindex/ipsetmember/ip_set_member.go
  felix/labelindex/ipsetmember/ipset_port_protocol.go
  felix/labelindex/named_port_bench_test.go
  felix/labelindex/named_port_index.go
  felix/labelindex/named_port_index_test.go
  felix/serviceindex/serviceindex.go
  felix/serviceindex/serviceindex_test.go
Labels: docs-not-required, release-note-not-required, area/performance

#10744 Enrich diags with webhook and apiservice information
  calicoctl/calicoctl/commands/cluster/diags.go
Labels: release-note-required, docs-pr-required

#10726 Add publishing OpenStack RPMs to Google Artifact Registry
  release/packaging/utils/create-update-packages.sh
  release/packaging/utils/lib.sh
  release/packaging/utils/publish-rpms.sh
Labels: docs-not-required, release-note-not-required

#10740 [CORE-11657] BPF: add packet rate QoS control
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/counters.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/ifstate.h
  felix/bpf-gpl/qos.h
  felix/bpf-gpl/reasons.h
  felix/bpf-gpl/tc.c
  felix/bpf/counters/counters.go
  felix/bpf/counters/map.go
  felix/bpf/ifstate/map.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/qos_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/docker-image/Dockerfile
  felix/fv/qos_controls_test.go
Labels: release-note-required, docs-pr-required

#10749 Rely on operator status to figure out when calico is up
  node/tests/k8st/deploy_resources_on_kind_cluster.sh
Labels: docs-not-required, release-note-not-required

#10743 Some clean up in static rules
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: docs-not-required, release-note-not-required

#10756 QoS: rename funcs and vars in endpoints_test
  felix/rules/endpoints_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready
