Repository projectcalico/calico, pull requests merged in 2025-09, with the labels that each got.

#10908 [v3.30] Fix serviceaccount name in helm chart
  charts/tigera-operator/templates/tigera-operator/02-rolebinding-tigera-operator-secrets.yaml
Labels: release-note-required, docs-not-required

#10898 BPF: use separate QoS map for state
  felix/bpf-gpl/Makefile
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/ifstate.h
  felix/bpf-gpl/qos.h
  felix/bpf-gpl/tc.c
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/ifstate/map.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/qos/map.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/qos_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_ep_mgr_test.go
  felix/fv/qos_controls_test.go
Labels: docs-not-required, release-note-not-required

#10919 Regenerate semaphore yamls.
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#10920 Ignore sem pipeline file itself.
  .semaphore/semaphore.yml
  hack/cmd/deps/deps.go
Labels: docs-not-required, release-note-not-required

#10921 Add TokenReviews permission to operator
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#10916 Remove manual Windows Kubernetes service installation (#10893)
  node/windows-packaging/CalicoWindows/kubernetes/README.txt
  node/windows-packaging/CalicoWindows/kubernetes/install-kube-services.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  node/windows-packaging/CalicoWindows/kubernetes/uninstall-kube-services.ps1
  process/testing/winfv-felix/run-fv-full.ps1
  process/testing/winfv-felix/setup-fv-capz.sh
Labels: release-note-required, docs-pr-required

#10925 Fixes to semaphore.yml generation
  .semaphore/generate-semaphore-yaml.sh
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/10-check-images.yml
  .semaphore/semaphore.yml.d/blocks/20-api.yml
  .semaphore/semaphore.yml.d/blocks/20-e2e-validation.yml
  .semaphore/semaphore.yml.d/blocks/20-envoy-gateway.yml
  .semaphore/semaphore.yml.d/blocks/20-envoy-proxy.yml
  .semaphore/semaphore.yml.d/blocks/20-envoy-ratelimit.yml
  .semaphore/semaphore.yml.d/blocks/20-lib.yml
  .semaphore/semaphore.yml.d/blocks/20-tools.yml
  .semaphore/semaphore.yml.d/blocks/20-whisker.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
  hack/cmd/deps/deps.go
Labels: docs-not-required, release-note-not-required

#10888 support namespace selector field in ip pool
  api/pkg/apis/projectcalico/v3/ippool.go
  api/pkg/openapi/generated.openapi.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller.go
  libcalico-go/config/crd/crd.projectcalico.org_ippools.yaml
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block_reader_writer_test.go
  libcalico-go/lib/ipam/ipam_test.go
  libcalico-go/lib/ipam/ipam_types.go
  libcalico-go/lib/ipam/namespace_selector_test.go
  libcalico-go/lib/ipam/pools.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required, merge-when-ready, squash-commits

#10930 Fix test flake due to env pollution
  node/pkg/lifecycle/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#10912 Match DSCP rules only for traffic originating from endpoints with DSCP annotation
  felix/dataplane/linux/dscp_mgr.go
  felix/dataplane/linux/dscp_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/dscp_test.go
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: docs-not-required, release-note-not-required

#10933 Break loop when there is no more flows to process
  goldmane/pkg/goldmane/goldmane.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#10910 chore: use correct repository path variable to avoid spurious errors
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#10938 [v3.30] - Whisker Policy Trace UI
  whisker/package.json
  whisker/src/components/common/FlowLogActionIndicator/__tests__/__snapshots__/index.test.tsx.snap
  whisker/src/components/common/PolicyActionIndicator/__tests__/index.test.tsx
  whisker/src/components/common/PolicyActionIndicator/index.tsx
  whisker/src/components/common/PolicyActionIndicator/styles.ts
  whisker/src/features/flowLogs/components/FlowLogDetails/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/FlowLogDetails/index.tsx
  whisker/src/features/flowLogs/components/PoliciesLogDetails/__tests__/index.test.tsx
  whisker/src/features/flowLogs/components/PoliciesLogDetails/index.tsx
  whisker/src/features/flowLogs/components/PoliciesLogDetails/styles.ts
  whisker/src/icons/TriggeredIcon.tsx
  whisker/src/icons/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/__test__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/components/LogDetailsTable/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/index.tsx
  whisker/src/libs/tigera/ui-components/components/common/LogDetailsView/styles.ts
  whisker/src/libs/tigera/ui-components/components/common/StatusIndicator/__tests__/__snapshots__/index.test.tsx.snap
  whisker/src/libs/tigera/ui-components/components/common/StatusIndicator/styles.ts
  whisker/src/theme/components/Popover.ts
  whisker/src/theme/components/Table.ts
  whisker/src/types/api.ts
Labels: release-note-required, docs-not-required

#10856 Make OpenStack resync interval configurable and disable-able
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/plugin.sh
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
Labels: docs-pr-required, release-note-not-required

#10943 Update operator manifests.
  charts/tigera-operator/crds/operator.tigera.io_installations.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#10936 nftables: properly mark base chains as dirty after a flush
  felix/nftables/table.go
  felix/nftables/table_test.go
Labels: release-note-required, docs-not-required

#10881 bpf: support for adding DSCP for egress traffic
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/qos.h
  felix/bpf-gpl/tc.c
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/qos_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/fv/bpf_test.go
  felix/fv/dscp_test.go
Labels: docs-not-required, release-note-not-required

#10968 Fix deps tool: fix missing dependency on the top-level package itself
  .semaphore/semaphore.yml
  hack/cmd/deps/deps.go
Labels: docs-not-required, release-note-not-required

#10931 OpenStack: Respond immediately to all QoS configuration changes
  networking-calico/devstack/bootstrap.sh
  networking-calico/devstack/qos_responsiveness_tests.py
  networking-calico/networking_calico/plugins/calico/plugin.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/endpoints.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/qos_driver.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/lib.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
  networking-calico/tox.ini
Labels: release-note-required, docs-not-required

#10964 Fix pod2daemon static checks
  pod2daemon/binder/binder.go
  pod2daemon/csidriver/driver/driver.go
  pod2daemon/csidriver/driver/driver_test.go
  pod2daemon/csidriver/driver/node.go
  pod2daemon/flexvol/flexvoldriver.go
Labels: docs-not-required, release-note-not-required

#10962 Fix kube-controllers static checks
  kube-controllers/cmd/kube-controllers/fv_test.go
  kube-controllers/pkg/config/config_fv_test.go
  kube-controllers/pkg/config/config_test.go
  kube-controllers/pkg/controllers/flannelmigration/config.go
  kube-controllers/pkg/controllers/flannelmigration/config_test.go
  kube-controllers/pkg/controllers/flannelmigration/flannel_migration_fv_test.go
  kube-controllers/pkg/controllers/flannelmigration/ipam_migrator.go
  kube-controllers/pkg/controllers/flannelmigration/k8s_resources.go
  kube-controllers/pkg/controllers/flannelmigration/migration_controller.go
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller.go
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller_fv_test.go
  kube-controllers/pkg/controllers/namespace/namespace_controller.go
  kube-controllers/pkg/controllers/namespace/namespace_controller_fv_test.go
  kube-controllers/pkg/controllers/networkpolicy/policy_controller_fv_test.go
  kube-controllers/pkg/controllers/node/auto_hep_fv_test.go
  kube-controllers/pkg/controllers/node/etcd_ipam_gc_fv_test.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_test.go
  kube-controllers/pkg/controllers/node/kdd_ipam_gc_fv_test.go
  kube-controllers/pkg/controllers/node/labels.go
  kube-controllers/pkg/controllers/node/metrics_fv_test.go
  kube-controllers/pkg/controllers/node/node_controller_fv_test.go
  kube-controllers/pkg/controllers/pod/pod_controller_fv_test.go
  kube-controllers/pkg/controllers/serviceaccount/serviceaccount_controller_fv_test.go
  kube-controllers/pkg/status/status_test.go
  kube-controllers/tests/testutils/flannel_migration_utils.go
  kube-controllers/tests/testutils/utils.go
Labels: docs-not-required, release-note-not-required

#10953 Update birdcl path to /bin/birdcl for liveness probe in calico-node.
  node/pkg/health/health.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required, merge-when-ready

#10976 add more non-owned dirs to ignored for yamllint
  .yamllint.yaml
Labels: docs-not-required, release-note-not-required

#10977 Cleanup kube-proxy rules when NFT is enabled and in BPF dataplane.
  felix/dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#10982 Upgrade CLUSTER_API_VERSION to v1.11.1
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  felix/fv/winfv/policy_test.go
  hack/cmd/deps/deps.go
  process/testing/winfv-felix/capz/OSS/custom-resources.yaml
  process/testing/winfv-felix/capz/create-cluster.sh
  process/testing/winfv-felix/capz/export-env.sh
Labels: docs-pr-required, release-note-not-required

#10996 [v3.30] enable kube-proxy healthz server
  felix/bpf/proxy/options.go
  felix/bpf/proxy/proxy.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
Labels: release-note-required, docs-not-required

#11010 Fix linter error to use tagged switch
  felix/bpf/attach.go
  felix/bpf/polprog/pol_prog_builder.go
  felix/calc/stats_collector.go
  felix/collector/flowlog/types.go
  felix/config/param_types.go
  felix/daemon/daemon.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/ipsets/utils_for_test.go
  felix/iptables/renderer.go
  felix/nfnetlink/conntrack.go
  felix/rules/rule_defs.go
  felix/statusrep/status_file_reporter.go
Labels: docs-not-required, release-note-not-required

#11014 Configure branch for v3.31
  charts/calico/values.yaml
  charts/tigera-operator/values.yaml
  manifests/alp/istio-inject-configmap-1.1.0.yaml
  manifests/alp/istio-inject-configmap-1.1.1.yaml
  manifests/alp/istio-inject-configmap-1.1.10.yaml
  manifests/alp/istio-inject-configmap-1.1.11.yaml
  manifests/alp/istio-inject-configmap-1.1.12.yaml
  manifests/alp/istio-inject-configmap-1.1.13.yaml
  manifests/alp/istio-inject-configmap-1.1.14.yaml
  manifests/alp/istio-inject-configmap-1.1.15.yaml
  manifests/alp/istio-inject-configmap-1.1.16.yaml
  manifests/alp/istio-inject-configmap-1.1.17.yaml
  manifests/alp/istio-inject-configmap-1.1.2.yaml
  manifests/alp/istio-inject-configmap-1.1.3.yaml
  manifests/alp/istio-inject-configmap-1.1.4.yaml
  manifests/alp/istio-inject-configmap-1.1.5.yaml
  manifests/alp/istio-inject-configmap-1.1.6.yaml
  manifests/alp/istio-inject-configmap-1.1.7.yaml
  manifests/alp/istio-inject-configmap-1.1.8.yaml
  manifests/alp/istio-inject-configmap-1.1.9.yaml
  manifests/alp/istio-inject-configmap-1.10.yaml
  manifests/alp/istio-inject-configmap-1.15.yaml
  manifests/alp/istio-inject-configmap-1.2.0.yaml
  manifests/alp/istio-inject-configmap-1.2.1.yaml
  manifests/alp/istio-inject-configmap-1.2.2.yaml
  manifests/alp/istio-inject-configmap-1.2.3.yaml
  manifests/alp/istio-inject-configmap-1.2.4.yaml
  manifests/alp/istio-inject-configmap-1.2.5.yaml
  manifests/alp/istio-inject-configmap-1.2.6.yaml
  manifests/alp/istio-inject-configmap-1.2.7.yaml
  manifests/alp/istio-inject-configmap-1.2.8.yaml
  manifests/alp/istio-inject-configmap-1.2.9.yaml
  manifests/alp/istio-inject-configmap-1.3.0.yaml
  manifests/alp/istio-inject-configmap-1.3.1.yaml
  manifests/alp/istio-inject-configmap-1.3.2.yaml
  manifests/alp/istio-inject-configmap-1.3.3.yaml
  manifests/alp/istio-inject-configmap-1.3.4.yaml
  manifests/alp/istio-inject-configmap-1.3.5.yaml
  manifests/alp/istio-inject-configmap-1.4.0.yaml
  manifests/alp/istio-inject-configmap-1.4.1.yaml
  manifests/alp/istio-inject-configmap-1.4.2.yaml
  manifests/alp/istio-inject-configmap-1.6.yaml
  manifests/alp/istio-inject-configmap-1.7.yaml
  manifests/alp/istio-inject-configmap-1.9.yaml
  manifests/calico-bpf.yaml
  manifests/calico-etcd.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal-etcd.yaml
  manifests/canal.yaml
  manifests/flannel-migration/calico.yaml
  manifests/ocp/02-tigera-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  manifests/tigera-operator.yaml
  metadata.mk
  process/testing/winfv-felix/setup-fv-capz.sh
Labels: docs-not-required, release-note-not-required

#11026 [v3.31] Handle ENOLINK when updating an existing tcx program
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-not-required

#11030 Update Operator CRDs
  charts/tigera-operator/crds/operator.tigera.io_installations.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#11023 WatcherCache handles missing APIs gracefully
  libcalico-go/lib/backend/watchersyncer/watchercache.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer.go
  libcalico-go/lib/backend/watchersyncer/watchersyncer_test.go
  typha/Makefile
Labels: release-note-required, docs-not-required

#11034 Update getNumTyphas to use endpointslice
  typha/pkg/k8s/lookup.go
Labels: docs-not-required, release-note-not-required

#11042 Add check to see if projectcalico/v3 api is available (#11040)
  e2e/pkg/utils/client/client.go
Labels: docs-not-required, release-note-not-required

#11045 [v3.31] Retry connection attempts once in e2e
  e2e/pkg/utils/conncheck/conncheck.go
Labels: docs-not-required, release-note-not-required

#11038 [v3.31] reduce bpf_jit_harden from 2 to 1 when possible; Add BPFJITHardening configuration option to control JIT hardening behavior
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required, merge-when-ready

#11047 Fix crypto FV tests after golang 1.24 update
  crypto/Makefile
  crypto/fv/expected-nmap.log
Labels: docs-not-required, release-note-not-required

#10900 Felix FV: Check cluster connectivity expectations in one test
  felix/fv/ipip_test.go
  felix/fv/routing_test.go
  felix/fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#11043 Update getNumTyphas to use endpointslice (#11034)
  typha/pkg/k8s/lookup.go
Labels: docs-not-required, release-note-not-required

#11048 [v3.31] Fix break in e2e to break out of intended loop
  e2e/pkg/utils/conncheck/conncheck.go
Labels: docs-not-required, release-note-not-required

#9400 Cleanup unused calico-bgp-daemon service
  node/filesystem/etc/rc.local
  node/filesystem/etc/service/available/calico-bgp-daemon/log/run
  node/filesystem/etc/service/available/calico-bgp-daemon/run
Labels: docs-not-required, release-note-not-required, merge-when-ready

#11066 [v3.31] fix(bpf): enable running QoS tests on BPF CI
  felix/fv/qos_controls_test.go
Labels: docs-not-required, release-note-not-required

#11074 Omit dwz when building Debian packages for Felix
  felix/debian/rules
Labels: release-note-required, docs-not-required

#11075 [v3.31] add "End of" lines in concise policy dump
  felix/cmd/calico-bpf/commands/policy_debug.go
Labels: release-note-required, docs-not-required

#11056 [CORE-11858] fix (bpf): enforce QoS packet rate in main codepath of calico_tc_main()
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tc_preamble.c
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/qos_test.go
  felix/calc/event_sequencer.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/fv/qos_controls_test.go
Labels: docs-not-required, release-note-not-required

#11081 [cherry-pick][v3.31] align hashrelease with release artifacts
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/release.go
  release/deps.txt
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#11082 [cherry-pick][v3.30] align hashrelease with release artifacts
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/release.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#11083 [cherry-pick][v3.29] align hashrelease with release artifacts
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/cmd/release.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/calico/options.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#11088 [v3.31] Change tests to use conntrack v4 and fix a leaking FD in tests
  felix/bpf/conntrack/v3/map.go
  felix/bpf/conntrack/v4/map.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
  felix/bpf/ut/icmp_too_big_test.go
  felix/bpf/ut/nat_test.go
  felix/bpf/ut/whitelist_test.go
  felix/fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#11087 [v3.31] fix (bpf): enforce QoS packet rate in main codepath of calico_tc_main()
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/tc_preamble.c
  felix/bpf/ut/bpf_prog_test.go
  felix/bpf/ut/qos_test.go
  felix/calc/event_sequencer.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/fv/qos_controls_test.go
Labels: docs-not-required, release-note-not-required

#11077 Move e2e pipelines from a private repo into the monorepo
  .semaphore/end-to-end/pipelines/benchmarking.yml
  .semaphore/end-to-end/pipelines/bpf.yml
  .semaphore/end-to-end/pipelines/certification.yml
  .semaphore/end-to-end/pipelines/iptables.yml
  .semaphore/end-to-end/pipelines/nftables.yml
  .semaphore/end-to-end/pipelines/patch-verification.yml
  .semaphore/end-to-end/pipelines/test.yml
  .semaphore/end-to-end/pipelines/upgrade.yml
  .semaphore/end-to-end/pipelines/vpp.yml
  .semaphore/end-to-end/pipelines/windows.yml
  .semaphore/end-to-end/scripts/body_standard.sh
  .semaphore/end-to-end/scripts/global_prologue.sh
Labels: docs-not-required, release-note-not-required

#11101 Fix static checks due to unnecessary ObjectMeta reference
  api/pkg/apis/projectcalico/v3/stagedglobalnetworkpolicy.go
  api/pkg/apis/projectcalico/v3/stagedkubernetesnetworkpolicy.go
  api/pkg/apis/projectcalico/v3/stagednetworkpolicy.go
Labels: docs-not-required, release-note-not-required
