Repository projectcalico/calico, pull requests merged in 2025-10, with the labels that each got.

#11089 Rename interfaceSelector to interfacePattern
  api/pkg/apis/projectcalico/v3/kubecontrollersconfig.go
  api/pkg/openapi/generated.openapi.go
  kube-controllers/pkg/config/runconfig.go
  kube-controllers/pkg/controllers/node/auto_hep_fv_test.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
  libcalico-go/config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  libcalico-go/lib/clientv3/kubecontrollersconfig.go
  libcalico-go/lib/clientv3/kubecontrollersconfig_e2e_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#11107 ci: use the correct OIDC credentials for hashreleases
  .semaphore/release/hashrelease.yml
Labels: docs-not-required, release-note-not-required

#11111 Check for Whisker in cluster before running tests
  Makefile
  e2e/pkg/tests/policy/staged_policy.go
  e2e/pkg/utils/autodetection.go
  e2e/pkg/utils/client/client.go
Labels: docs-not-required, release-note-not-required

#11110 Fix conntrack upgrade for ipv6
  felix/bpf/conntrack/v3/map6.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#11094 [v3.31] Fix performance of IPAM.ReleaseIPs() on disabled/deleted pools.
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block_reader_writer.go
  libcalico-go/lib/ipam/ipam_test.go
Labels: release-note-required, docs-not-required

#11095 [v3.30] Fix performance of IPAM.ReleaseIPs() on disabled/deleted pools.
  apiserver/Makefile
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_block_reader_writer.go
  libcalico-go/lib/ipam/ipam_test.go
Labels: release-note-required, docs-not-required

#11097 [v3.29] Avoid IPAM handle leak when context expires during assignment.
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  libcalico-go/lib/ipam/ipam.go
Labels: release-note-required, docs-not-required

#11099 [v3.30] Merge pull request #11052 from nelljerram/maintain-static-arp
  felix/netlinkshim/mocknetlink/netlink.go
  felix/routetable/route_table.go
  felix/routetable/route_table_test.go
Labels: release-note-required, docs-not-required

#10783 Run BPF UTs on Ubuntu 25.04
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  .semaphore/semaphore.yml.d/blocks/20-node.yml
  .semaphore/vms/clean-up-vms
  .semaphore/vms/cleanup.yml
  .semaphore/vms/collect-artifacts
  .semaphore/vms/collect-artifacts-from-vms
  .semaphore/vms/create-test-vm
  .semaphore/vms/create-test-vms
  .semaphore/vms/on-test-vm
  .semaphore/vms/publish-artifacts
  .semaphore/vms/run-tests-on-vms
  .semaphore/vms/scp-from-test-vm
  .semaphore/vms/vm-tests-common.sh
  felix/.semaphore/batches.sh
  felix/.semaphore/clean-up-vms
  felix/.semaphore/create-test-vm
  felix/.semaphore/create-test-vms
  felix/.semaphore/new-kernel-common.sh
  felix/.semaphore/on-test-vm
  felix/.semaphore/run-tests-on-vms
  node/.semaphore/batches.sh
Labels: docs-not-required, release-note-not-required

#11125 Re-generate app-policy healthz protobuf files
  app-policy/proto/healthz.pb.go
  app-policy/proto/healthz_grpc.pb.go
Labels: docs-not-required, release-note-not-required

#11113 ci: Grab crane from github instead of via go-build
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#11127 ci: Ensure we put crane in $(REPO_ROOT) and look there
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#11122 Remove complexity that's no longer needed for current OpenStack versions
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
Labels: docs-not-required, release-note-not-required

#11129 Semaphore: depend on input YAML templates
  .semaphore/generate-semaphore-yaml.sh
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/09-blocks.yml
  Makefile
  hack/cmd/deps/deps.go
Labels: docs-not-required, release-note-not-required

#11124 Disable bpf kube-proxy healthz server in fv tests
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_test.go
  felix/fv/infrastructure/topology.go
Labels: docs-not-required, release-note-not-required

#11131 [CORE-11921] [v3.30] New felixConfig CgroupV2Path
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/config/config_params.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required, merge-bot-cherry-pick

#11136 [v3.31] Fix get map info
  felix/bpf/conntrack/v3/map6.go
  felix/bpf/maps/syscall.go
Labels: docs-not-required, release-note-not-required

#11146 [master] Semaphore Auto go-build Update
  metadata.mk
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#11119 [BPF] Expand conntrack flags memory beyond 16 bits
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/types.h
  felix/bpf/conntrack/cleanup.go
  felix/bpf/conntrack/cttestdata/ct_data.go
  felix/bpf/conntrack/inforeader.go
  felix/bpf/conntrack/inforeader_test.go
  felix/bpf/conntrack/map.go
  felix/bpf/conntrack/v4/map.go
  felix/bpf/conntrack/v4/map6.go
  felix/bpf/state/map.go
Labels: docs-not-required, release-note-not-required
