Repository projectcalico/calico, pull requests merged in 2025-05, with the labels that each got.

#10329 Update operator manifests
  charts/tigera-operator/crds/operator.tigera.io_apiservers.yaml
  charts/tigera-operator/crds/operator.tigera.io_gatewayapis.yaml
  charts/tigera-operator/crds/operator.tigera.io_goldmanes.yaml
  charts/tigera-operator/crds/operator.tigera.io_imagesets.yaml
  charts/tigera-operator/crds/operator.tigera.io_installations.yaml
  charts/tigera-operator/crds/operator.tigera.io_managementclusterconnections.yaml
  charts/tigera-operator/crds/operator.tigera.io_tigerastatuses.yaml
  charts/tigera-operator/crds/operator.tigera.io_whiskers.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#10334 update license bin dir path
  apiserver/Dockerfile
  app-policy/Dockerfile
  whisker/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#8961 Pod in nat-outgoing should not be SNATed when it accesses local cluster
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/rules/nat.go
  felix/rules/nat_test.go
  felix/rules/rule_defs.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10330 [CORE-11367] openstack: Add workaround for limited /boot partition space when an initramfs update is needed
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
Labels: docs-not-required, release-note-not-required

#10203 Start Goldmane package refactor
  goldmane/pkg/daemon/config.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/bucket_cache.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/goldmane/goldmane.go
  goldmane/pkg/goldmane/goldmane_test.go
  goldmane/pkg/goldmane/options.go
  goldmane/pkg/goldmane/stream_test.go
  goldmane/pkg/goldmane/utils_test.go
  goldmane/pkg/server/flow_service.go
  goldmane/pkg/server/statistics_service.go
  goldmane/pkg/storage/bucket.go
  goldmane/pkg/storage/bucket_ring.go
  goldmane/pkg/storage/deferred_builder.go
  goldmane/pkg/storage/diachronic_flow.go
  goldmane/pkg/storage/diachronic_flow_test.go
  goldmane/pkg/storage/index.go
  goldmane/pkg/storage/index_test.go
  goldmane/pkg/storage/options.go
  goldmane/pkg/storage/ring_index.go
  goldmane/pkg/storage/sink.go
  goldmane/pkg/storage/stats.go
  goldmane/pkg/storage/utils.go
  goldmane/pkg/stream/stream.go
  goldmane/pkg/stream/stream_manager.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10291 Felix program IPIP routes
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/calc/calc_graph.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/dataplanedefs/dataplane_defs.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/ipip_mgr_test.go
  felix/dataplane/linux/routing.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/apply_on_forward_test.go
  felix/fv/bpf_dual_stack_test.go
  felix/fv/bpf_test.go
  felix/fv/donottrack_test.go
  felix/fv/ep_to_host_action_test.go
  felix/fv/flow_logs_goldmane_staged_test.go
  felix/fv/flow_logs_goldmane_test.go
  felix/fv/hostendpoints_test.go
  felix/fv/infrastructure/topology.go
  felix/fv/ip6tables_test.go
  felix/fv/ipip_test.go
  felix/fv/latency_test.go
  felix/fv/mtu_test.go
  felix/fv/routes_test.go
  felix/fv/service_loop_prevention_test.go
  felix/fv/spoof_test.go
  felix/fv/status_report_test.go
  felix/fv/tiered_policy_test.go
  felix/fv/vxlan_test.go
  felix/fv/wireguard_test.go
  felix/routetable/defs.go
  felix/routetable/ownershippol/main_route_table_policy.go
  felix/routetable/routeclass_string.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10343 [release-v3.30] Auto pick #10330: Add workaround for limited /boot partition space
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
Labels: docs-not-required, release-note-not-required

#10344 [release-v3.29] Auto pick #10330: Add workaround for limited /boot partition space
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
Labels: docs-not-required, release-note-not-required

#10345 [release-v3.28] Auto pick #10330: Add workaround for limited /boot partition space
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/40-openstack.yml
Labels: docs-not-required, release-note-not-required

#10308 Do not use redirect_peer when sending packets to kubevirt VMs
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/routes.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf/conntrack/v3/map.go
  felix/bpf/routes/map.go
  felix/bpf/ut/whitelist_test.go
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10355 [CORE-11093] calicoctl: fix panic when using wrong WorkloadEndpoint name
  libcalico-go/lib/names/workloadendpoint.go
  libcalico-go/lib/names/workloadendpoint_test.go
Labels: release-note-required, docs-not-required

#10359 Update Felix Grafana dashboard.
  manifests/grafana-dashboards.yaml
Labels: release-note-required, docs-not-required

#10358 Fix calico-selector tool to use new API. Add test.
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-tools.yml
  hack/Makefile
  hack/cmd/calico-selector/calico-selector.go
  hack/cmd/calico-selector/calico-selector_test.go
Labels: docs-not-required, release-note-not-required

#10363 Fix flannel tests and duplicated release notes
  hack/postrelease/golang/tests/oss/github/flannel/github_flannel_test.go
  release-notes/v3.30.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#10347 Cherry pick uninstall permissions fix
  charts/tigera-operator/templates/tigera-operator/02-role-tigera-operator.yaml
  manifests/ocp/02-role-tigera-operator.yaml
  manifests/tigera-operator-ocp-upgrade.yaml
  manifests/tigera-operator.yaml
Labels: docs-not-required, release-note-not-required

#10362 [release-v3.30] Auto pick #10355: calicoctl: fix panic when using wrong
  libcalico-go/lib/names/workloadendpoint.go
  libcalico-go/lib/names/workloadendpoint_test.go
Labels: release-note-required, docs-not-required

#10349 [release-v3.30] Auto pick #10203: Refactor package structure
  goldmane/pkg/daemon/config.go
  goldmane/pkg/daemon/daemon.go
  goldmane/pkg/emitter/bucket_cache.go
  goldmane/pkg/emitter/emitter.go
  goldmane/pkg/emitter/emitter_test.go
  goldmane/pkg/goldmane/goldmane.go
  goldmane/pkg/goldmane/goldmane_test.go
  goldmane/pkg/goldmane/options.go
  goldmane/pkg/goldmane/stream_test.go
  goldmane/pkg/goldmane/utils_test.go
  goldmane/pkg/server/flow_service.go
  goldmane/pkg/server/statistics_service.go
  goldmane/pkg/storage/bucket.go
  goldmane/pkg/storage/bucket_ring.go
  goldmane/pkg/storage/deferred_builder.go
  goldmane/pkg/storage/diachronic_flow.go
  goldmane/pkg/storage/diachronic_flow_test.go
  goldmane/pkg/storage/index.go
  goldmane/pkg/storage/index_test.go
  goldmane/pkg/storage/options.go
  goldmane/pkg/storage/ring_index.go
  goldmane/pkg/storage/sink.go
  goldmane/pkg/storage/stats.go
  goldmane/pkg/storage/utils.go
  goldmane/pkg/stream/stream.go
  goldmane/pkg/stream/stream_manager.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10360 [v3.30] Update Felix Grafana Dashboard
  manifests/grafana-dashboards.yaml
Labels: docs-not-required, release-note-not-required

#10365 [release tool] fixes for image scanning service
  release/internal/imagescanner/scanner.go
  release/internal/pinnedversion/pinnedversion.go
  release/pkg/manager/calico/manager.go
Labels: docs-not-required, release-note-not-required

#10367 [cherry pick] [v3.29] [release tool] fixes for image scanning service (#10365) [DE-3382]
  release/internal/imagescanner/scanner.go
  release/internal/pinnedversion/pinnedversion.go
Labels: docs-not-required, release-note-not-required

#10368 [CORE-11318] : Upgrade golang.org libs
  api/go.sum
  go.mod
  go.sum
  pod2daemon/patches/0002-Update-go.mod-to-patch-CVEs.patch
Labels: docs-not-required, release-note-not-required

#10369 Add GH action for stale enhancements and bugs
  .github/workflows/inactive_issues.yml
Labels: docs-not-required, release-note-not-required

#10373 [master] Semaphore Auto go-build Update
  metadata.mk
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#10372 fix publishing whisker images
  whisker/Makefile
  whisker/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#10371 [cherry-pick] [release tool] fix generating release notes
  release/internal/outputs/releasenotes.go
Labels: docs-not-required, release-note-not-required

#10377 Switch delete-local-data to delete-emptydir-data
  kube-controllers/pkg/controllers/flannelmigration/k8s_resources.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10378 Add hack tool to stress IPAM GC node deletion logic
  hack/cmd/ipam-hammer/README.md
  hack/cmd/ipam-hammer/main.go
Labels: docs-not-required, release-note-not-required

#10379 [release-v3.30] Auto pick #10377: Switch delete-local-data to delete-emptydir-data
  kube-controllers/pkg/controllers/flannelmigration/k8s_resources.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10381 [CORE-11318] : Upgrade node-driver-registrar golang.org libs
  pod2daemon/patches/0001-Update-go.mod-to-patch-CVEs.patch
  pod2daemon/patches/0002-Update-go.mod-to-patch-CVEs.patch
Labels: docs-not-required, release-note-not-required

#10100 Add FV test for deleting an iptables insert rule.
  felix/fv/iptables_disruption_test.go
Labels: docs-not-required, release-note-not-required

#10192 OpenStack: Don't modify port dict when collecting additional information
  networking-calico/networking_calico/plugins/ml2/drivers/calico/endpoints.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
Labels: docs-not-required, release-note-not-required

#10383 Add missing tier permissions to flannel migration controller
  manifests/flannel-migration/migration-job.yaml
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10385 [release-v3.30] Auto pick #10383: Add missing tier permissions to flannel migration controller
  manifests/flannel-migration/migration-job.yaml
Labels: release-note-required, docs-not-required

#10374 [Release v3.30] Picks from master
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/events.h
  felix/bpf-gpl/tc.c
  felix/collector/dpstatshelper.go
  felix/collector/goldmane/client.go
  felix/collector/local/reporter.go
  felix/collector/local/server.go
  felix/config/config_params.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/flow_logs_goldmane_staged_test.go
  felix/fv/flow_logs_goldmane_test.go
  felix/fv/flowlogs/flow_tester.go
  felix/fv/flowlogs/goldmane_mock.go
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/topology.go
  felix/fv/tiered_policy_test.go
  goldmane/pkg/types/flow.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  libcalico-go/lib/validator/v3/validator.go
  libcalico-go/lib/validator/v3/validator_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  node/cmd/calico-node/main.go
  node/pkg/flowlogs/flowlogs.go
Labels: docs-not-required, release-note-not-required

#10386 Update number of retries in python k8st
  node/tests/k8st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#9965 [BPF] rework L2 overlay (vxlan) for performance
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/globals.h
  felix/bpf-gpl/nat.h
  felix/bpf-gpl/routes.h
  felix/bpf/bpf_syscall.go
  felix/bpf/bpfutils/bpf_utils.go
  felix/bpf/hook/load.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_common.go
  felix/bpf/nat/connecttime.go
  felix/bpf/routes/map.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/precompilation_test.go
  felix/bpf/utils/utils.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/fv/bpf_test.go
  felix/fv/vxlan_test.go
  felix/vxlanfdb/vxlan_fdb.go
Labels: docs-not-required, release-note-not-required

#10370 Add OCP-required labels to new v3.30+ images [master]
  goldmane/docker/Dockerfile
  third_party/envoy-gateway/Dockerfile
  third_party/envoy-proxy/Dockerfile
  third_party/envoy-ratelimit/Dockerfile
  whisker-backend/docker/Dockerfile
  whisker/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#10384 Go dependency update May 2025
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/postrelease/golang/go.mod
  hack/postrelease/golang/go.sum
  lib/httpmachinery/go.mod
  lib/httpmachinery/go.sum
  lib/httpmachinery/pkg/apiutil/handler_test.go
  lib/std/go.mod
  metadata.mk
Labels: docs-not-required, release-note-not-required

#10346 API server - Policy WatchManager
  apiserver/cmd/apiserver/server/run_server.go
  apiserver/pkg/apiserver/apiserver.go
  apiserver/pkg/registry/projectcalico/globalpolicy/storage.go
  apiserver/pkg/registry/projectcalico/networkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/rest/storage_calico.go
  apiserver/pkg/registry/projectcalico/stagedglobalnetworkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/stagednetworkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/util/watch_manager.go
  apiserver/test/integration/clientset_test.go
Labels: docs-not-required, release-note-not-required

#10390 Add OCP-required labels to new v3.30+ images [v3.30]
  goldmane/docker/Dockerfile
  third_party/envoy-gateway/Dockerfile
  third_party/envoy-proxy/Dockerfile
  third_party/envoy-ratelimit/Dockerfile
  whisker-backend/docker/Dockerfile
  whisker/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#10392 Run GH action more frequently, and increase ratelimit
  .github/workflows/inactive_issues.yml
Labels: docs-not-required, release-note-not-required

#10387 [release tool] update image version assertion
  goldmane/docker/Dockerfile
  release/pkg/manager/calico/manager.go
  whisker-backend/docker/Dockerfile
  whisker/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#10388 [release tool] [v3.30] update image version assertion
  goldmane/docker/Dockerfile
  release/pkg/manager/calico/manager.go
  whisker-backend/docker/Dockerfile
  whisker/docker-image/Dockerfile
Labels: docs-not-required, release-note-not-required

#10393 [release-v3.29] Auto pick #9859: Update image used to enable qemu emulation.
  .semaphore/release/hashrelease.yml
  .semaphore/vms/create-test-vm
  app-policy/Dockerfile
  felix/.semaphore/create-test-vm
  felix/docker-image/Dockerfile
  kube-controllers/Dockerfile
  kube-controllers/docker-image/flannel-migration/Dockerfile
  lib.Makefile
  node/Dockerfile.arm64
  node/Dockerfile.ppc64le
  node/Dockerfile.s390x
Labels: docs-not-required, release-note-not-required

#10397 Upstream IP sets dataplane API changes.
  felix/bpf/ipsets/ipsets.go
  felix/bpf/ipsets/map.go
  felix/dataplane/ipsets/ipsets_mgr.go
  felix/dataplane/ipsets/mock_ipsets.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/windows/ipsets/ipsets.go
  felix/ipsets/cmd_shim.go
  felix/ipsets/ipset_defs.go
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/nftables/ipsets.go
  felix/nftables/ipsets_test.go
Labels: docs-not-required, release-note-not-required

#10407 [release-v3.29] Auto pick #10117: Add support for custom DNS in the operator
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required

#10406 [release-v3.30] Auto pick #10117: Add support for custom DNS in the operator
  charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required

#10333 Improve performance of IPAM GC controller
  calicoctl/calicoctl/commands/ipam/release.go
  calicoctl/tests/fv/ipam_test.go
  calicoctl/tests/fv/migrate_ipam_test.go
  cni-plugin/pkg/ipamplugin/ipam_plugin.go
  cni-plugin/pkg/k8s/k8s.go
  kube-controllers/cmd/kube-controllers/main.go
  kube-controllers/pkg/controllers/loadbalancer/loadbalancer_controller.go
  kube-controllers/pkg/controllers/node/fake_client.go
  kube-controllers/pkg/controllers/node/ipam.go
  kube-controllers/pkg/controllers/node/ipam_test.go
  kube-controllers/pkg/controllers/node/kdd_ipam_gc_fv_test.go
  kube-controllers/pkg/controllers/node/metrics_fv_test.go
  kube-controllers/pkg/controllers/node/node_controller_fv_test.go
  kube-controllers/pkg/controllers/utils/retry_controller.go
  kube-controllers/pkg/controllers/utils/retry_controller_test.go
  libcalico-go/lib/backend/syncersv1/bgpsyncer/bgpsyncer_e2e_test.go
  libcalico-go/lib/clientv3/ippool_e2e_test.go
  libcalico-go/lib/clientv3/node.go
  libcalico-go/lib/ipam/interface.go
  libcalico-go/lib/ipam/ipam.go
  libcalico-go/lib/ipam/ipam_test.go
  node/pkg/allocateip/allocateip.go
Labels: release-note-required, docs-not-required

#9674 Implement partial resync after IP set update failures
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/ipsets/utils_for_test.go
Labels: release-note-required, docs-not-required

#10391 Policy name in default Tier
  apiserver/pkg/registry/projectcalico/globalpolicy/strategy.go
  apiserver/pkg/registry/projectcalico/networkpolicy/strategy.go
  apiserver/pkg/storage/calico/policy_storage_test.go
  apiserver/test/integration/clientset_test.go
  calicoctl/tests/st/calicoctl/test_crud.py
  calicoctl/tests/st/utils/data.py
  libcalico-go/lib/backend/etcdv3/etcdv3.go
  libcalico-go/lib/backend/k8s/k8s_test.go
  libcalico-go/lib/backend/k8s/resources/customresource.go
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/clientv3/globalnetworkpolicy.go
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/lib/names/policy.go
Labels: release-note-required, docs-not-required

#10400 Disable CSI driver by default in helm chart
  charts/tigera-operator/templates/crs/custom-resources.yaml
  charts/tigera-operator/values.yaml
Labels: release-note-required, docs-not-required

#10414 [release tool] use go-containerregistry for image validations
  go.mod
  go.sum
  release/internal/registry/auth.go
  release/internal/registry/component.go
  release/internal/registry/docker.go
  release/internal/registry/gar.go
  release/internal/registry/gcr.go
  release/internal/registry/image.go
  release/internal/registry/quay.go
  release/internal/registry/registry.go
  release/pkg/manager/calico/manager.go
  release/pkg/manager/operator/manager.go
Labels: docs-not-required, release-note-not-required

#10401 fix version output for cni-plugin and envoy images
  cni-plugin/cmd/calico/calico.go
  third_party/envoy-gateway/Dockerfile
  third_party/envoy-gateway/Makefile
  third_party/envoy-proxy/Dockerfile
  third_party/envoy-proxy/Makefile
  third_party/envoy-ratelimit/Dockerfile
  third_party/envoy-ratelimit/Makefile
  typha/pkg/buildinfo/version.go
Labels: docs-not-required, release-note-not-required

#10417 Remove default tier prefix from Policy CRD without annotation
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/test/mock-policies.yaml
Labels: release-note-required, docs-not-required

#10420 Add target to update copyrights for all committed files that are out of date
  Makefile
Labels: docs-not-required, release-note-not-required

#10419 [v3.30] fix version output for envoy images (#10401)
  third_party/envoy-gateway/Dockerfile
  third_party/envoy-gateway/Makefile
  third_party/envoy-proxy/Dockerfile
  third_party/envoy-proxy/Makefile
  third_party/envoy-ratelimit/Dockerfile
  third_party/envoy-ratelimit/Makefile
Labels: docs-not-required, release-note-not-required

#10416 Improve IPSet dataplane callback API.
  felix/bpf/ipsets/ipsets.go
  felix/dataplane/ipsets/ipsets_mgr.go
  felix/dataplane/ipsets/mock_ipsets.go
  felix/dataplane/windows/ipsets/ipsets.go
  felix/ipsets/ipsets.go
  felix/ipsets/ipsets_test.go
  felix/nftables/ipsets.go
Labels: docs-not-required, release-note-not-required

#10418 Remove default tier prefix from Policy CRD without annotation
  libcalico-go/lib/backend/k8s/resources/resources.go
  libcalico-go/lib/backend/model/keys.go
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/stagedglobalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/stagednetworkpolicy_e2e_test.go
  libcalico-go/test/mock-policies.yaml
Labels: release-note-required, docs-not-required

#10424 Short names for staged policies (#10280)
  apiserver/pkg/registry/projectcalico/rest/storage_calico.go
  apiserver/pkg/registry/projectcalico/stagedglobalnetworkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/stagedkubernetesnetworkpolicy/storage.go
  apiserver/pkg/registry/projectcalico/stagednetworkpolicy/storage.go
Labels: release-note-required, docs-not-required

#10423 [TSLA-9204] Run ci for lib folder (previously missing)
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-lib.yml
  lib/Makefile
  lib/httpmachinery/pkg/apiutil/handler_test.go
  lib/httpmachinery/pkg/codec/decode.go
Labels: docs-not-required, release-note-not-required

#10422 Update update-file-copyrights target to add copyright to new files
  Makefile
  hack/copyright.template
Labels: docs-not-required, release-note-not-required

#10380 CORE-11022: Implementing TLS Cipher configurable for API Server
  apiserver/cmd/apiserver/server/options.go
  crypto/fv/main/main.go
  crypto/pkg/tls/tls.go
  crypto/pkg/tls/tls_test.go
  goldmane/pkg/client/tls.go
  goldmane/pkg/emitter/http_client.go
  guardian/pkg/config/config.go
  guardian/pkg/server/proxy.go
  guardian/pkg/server/server.go
  guardian/pkg/tunnel/dial.go
  kube-controllers/cmd/kube-controllers/main.go
  libcalico-go/lib/backend/etcdv3/etcdv3.go
  typha/pkg/syncclient/sync_client.go
  typha/pkg/syncserver/sync_server.go
Labels: release-note-required, docs-pr-required

#10210 Enable whisker + goldmane in e2e tests
  .semaphore/vms/create-test-vm
  node/Makefile
  node/tests/k8st/infra/values.yaml
  node/tests/k8st/load_images_on_kind_cluster.sh
  node/tests/k8st/tests/test_simple.py
  node/tests/k8st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#10431 Highlight upgrade change in v3.30.0
  release-notes/v3.30.0-release-notes.md
Labels: docs-not-required, release-note-not-required

#10436 Add go vet to pre-flight checks.
  Makefile
  node/pkg/lifecycle/startup/startup_test.go
Labels: docs-not-required, release-note-not-required

#10433 Disable watchlist in API server
  apiserver/cmd/apiserver/apiserver.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10440 [release-v3.30] (pick #10433) Disable watchlist in API server
  apiserver/cmd/apiserver/apiserver.go
Labels: release-note-required, docs-not-required

#10413 Remove old unused client v1 code
  libcalico-go/lib/client/bgppeer.go
  libcalico-go/lib/client/client.go
  libcalico-go/lib/client/client_suite_test.go
  libcalico-go/lib/client/client_test.go
  libcalico-go/lib/client/config.go
  libcalico-go/lib/client/doc.go
  libcalico-go/lib/client/hostendpoint.go
  libcalico-go/lib/client/ippool.go
  libcalico-go/lib/client/node.go
  libcalico-go/lib/client/policy.go
  libcalico-go/lib/client/profile.go
  libcalico-go/lib/client/tier.go
  libcalico-go/lib/client/workloadendpoint.go
Labels: docs-not-required, release-note-not-required

#10404 Add Guardian UT tests
  guardian/pkg/conn/forward_test.go
  guardian/pkg/server/proxy_test.go
  guardian/pkg/tunnel/dial_test.go
  guardian/test/utils/util.go
Labels: docs-not-required, release-note-not-required

#10415 [release-v3.30] Auto pick #10308: Avoid redirect_peer when sending packets to a vm
  felix/bpf-gpl/conntrack_types.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/routes.h
  felix/bpf-gpl/tc.c
  felix/bpf-gpl/types.h
  felix/bpf/conntrack/v3/map.go
  felix/bpf/routes/map.go
  felix/bpf/ut/whitelist_test.go
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/dataplane/linux/bpf_route_mgr.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10350 Goldmane Stream refactor
  goldmane/.gitignore
  goldmane/pkg/flowgen/generator.go
  goldmane/pkg/goldmane/goldmane.go
  goldmane/pkg/goldmane/goldmane_test.go
  goldmane/pkg/storage/bucket.go
  goldmane/pkg/storage/bucket_ring.go
  goldmane/pkg/storage/bucket_test.go
  goldmane/pkg/storage/deferred_builder.go
  goldmane/pkg/storage/options.go
  goldmane/pkg/storage/utils.go
  goldmane/pkg/stream/stream.go
  goldmane/pkg/stream/stream_manager.go
  whisker-backend/test/fv/goldmaneintegration_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10356 Move vxlan and ipip manager duplicate code into route manager
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/ipip_mgr_test.go
  felix/dataplane/linux/route_mgr.go
  felix/dataplane/linux/routing.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
  felix/fv/ipip_test.go
Labels: docs-not-required, release-note-not-required

#10444 Add FVs for borrowed IPs in IPIP
  felix/fv/bpf_test.go
  felix/fv/infrastructure/infra_etcd.go
  felix/fv/infrastructure/infra_k8s.go
  felix/fv/infrastructure/infrastructure.go
  felix/fv/infrastructure/topology.go
  felix/fv/infrastructure/tunnel.go
  felix/fv/ipip_test.go
  felix/fv/mtu_test.go
  felix/fv/routes_test.go
  felix/fv/status_report_test.go
  felix/fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#10437 Fix unwanted hns policy update for windows endpoints
  felix/dataplane/windows/endpoint_mgr.go
Labels: release-note-required, docs-not-required

#10443 Add initial Guardian FV
  guardian/Makefile
  guardian/tests/fv/fv_test.go
  guardian/tests/fv/util_test.go
  lib/std/cryptoutils/ca.go
Labels: docs-not-required, release-note-not-required

#10448 Update policy tests to not rely on external file
  libcalico-go/lib/clientv3/globalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/networkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/stagedglobalnetworkpolicy_e2e_test.go
  libcalico-go/lib/clientv3/stagednetworkpolicy_e2e_test.go
  libcalico-go/test/mock-policies.yaml
Labels: docs-not-required, release-note-not-required

#10451 [BPF] repurpose unused mark for CALI_SKB_MARK_TUNNEL_KEY_SET
  felix/bpf-gpl/bpf.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/tc.c
  felix/bpf/tc/defs/defs.go
Labels: docs-not-required, release-note-not-required

#10445 Replace the existing tc filter program
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10453 Run BPF CI on ubuntu 24.04 and 22.04 (nftables)
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-felix.yml
  felix/.semaphore/create-test-vm
Labels: docs-not-required, release-note-not-required

#10456 [release-v3.28] Auto pick #10445: Replace the existing tc filter program
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#10425 Pin CTLB programs to BPF filesystem.
  felix/bpf/bpfdefs/defs.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/ut/attach_test.go
Labels: docs-not-required, release-note-not-required

#10459 Sync collector dpstatshelper with ee
  felix/collector/dpstatshelper.go
Labels: docs-not-required, release-note-not-required

#10464 Fix conversion of handle from string to int
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/tc/attach.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#10468 [release-v3.28] Auto pick #10466: Pin ctlb programs
  felix/bpf/bpfdefs/defs.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
Labels: docs-not-required, release-note-not-required

#10467 [release-v3.29] Auto pick #10466: Pin ctlb programs
  felix/bpf/bpfdefs/defs.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
Labels: docs-not-required, release-note-not-required

#10466 [release-v3.30] Auto pick #10425: Pin ctlb programs
  felix/bpf/bpfdefs/defs.go
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/nat/connecttime.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
Labels: docs-not-required, release-note-not-required

#10465 [DE-2920] Move postrelease tests to release tool
  Makefile
  go.mod
  go.sum
  hack/postrelease/Dockerfile
  hack/postrelease/config.json
  hack/postrelease/golang/README.md
  hack/postrelease/golang/go.mod
  hack/postrelease/golang/go.sum
  hack/postrelease/golang/pkg/container/container.go
  hack/postrelease/golang/pkg/github/github.go
  hack/postrelease/golang/pkg/helm/helm.go
  hack/postrelease/golang/pkg/registry/registry.go
  hack/postrelease/golang/pkg/utils/download.go
  hack/postrelease/golang/pkg/variables/oss_defaults.go
  hack/postrelease/golang/tests/operator/images/images_test.go
  hack/postrelease/golang/tests/oss/github/calico/github_calico_test.go
  hack/postrelease/golang/tests/oss/github/flannel/github_flannel_test.go
  hack/postrelease/golang/tests/oss/helm/helm_test.go
  hack/postrelease/golang/tests/oss/images/images_test.go
  hack/postrelease/golang/tests/oss/openstack/openstack_test.go
  hack/postrelease/requirements.txt
  hack/postrelease/test_helm_artifacts.py
  hack/postrelease/test_images.py
  hack/postrelease/test_manifests_archives.py
  hack/postrelease/test_openstack_artifacts.py
  hack/postrelease/test_projectcalico_docs_updated.py
  hack/postrelease/test_tags_tars.py
  hack/postrelease/test_windows_artifacts.py
  hack/postrelease/versions.py
  metadata.mk
  release/Makefile
  release/cmd/release.go
  release/internal/pinnedversion/pinnedversion.go
  release/internal/pinnedversion/release.go
  release/internal/registry/image.go
  release/internal/version/version.go
  release/pkg/manager/calico/manager.go
  release/pkg/postrelease/github_test.go
  release/pkg/postrelease/helm_test.go
  release/pkg/postrelease/images_test.go
  release/pkg/postrelease/openstack_test.go
  release/pkg/postrelease/setup_test.go
Labels: docs-not-required, release-note-not-required

#10478 UTs for IPIP and VXLAN managers
  felix/dataplane/linux/ipip_mgr_test.go
  felix/dataplane/linux/vxlan_mgr_test.go
Labels: docs-not-required, release-note-not-required

#10461 More Openstack packaging fixups [master]
  release/packaging/docker-build-images/docker-bake.hcl
  release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-focal-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/ubuntu-jammy-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-jammy-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/ubuntu-noble-build.Dockerfile.amd64
  release/packaging/docker-build-images/ubuntu-noble-build.Dockerfile.ppc64le
  release/packaging/docker-build-images/ubuntu.Dockerfile
  release/packaging/utils/make-packages.sh
  release/packaging/utils/publish-debs.sh
Labels: docs-not-required, release-note-not-required

#10482 Some clean ups in route manager
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/ipip_mgr_test.go
  felix/dataplane/linux/route_mgr.go
  felix/dataplane/linux/vxlan_mgr.go
  felix/dataplane/linux/vxlan_mgr_test.go
Labels: docs-not-required, release-note-not-required

#9829 [BPF] add redirect counters
  felix/bpf-gpl/counters.h
  felix/bpf-gpl/fib_co_re.h
  felix/bpf-gpl/reasons.h
  felix/bpf-gpl/types.h
  felix/bpf/attach.go
  felix/bpf/bpf.go
  felix/bpf/counters/counters.go
  felix/bpf/maps/syscall.go
  felix/bpf/ut/bpf_prog_test.go
  felix/dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#10463 Add gomodder utility to verify / modify go module imports and structure
  Makefile
  go.mod
  go.sum
  gomodder_config.yaml
  hack/cmd/gomodder/main.go
  lib.Makefile
  lib/std/gomodder_config.yaml
Labels: docs-not-required, release-note-not-required

#10491 Change ProgramRoutes config option to ProgramClusterRoutes
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/apis/projectcalico/v3/zz_generated.deepcopy.go
  api/pkg/openapi/generated.openapi.go
  felix/calc/calc_graph.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/ipip_mgr_test.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  felix/fv/ipip_test.go
  felix/fv/wireguard_test.go
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required
