Repository projectcalico/calico, pull requests merged in 2025-08, with the labels that each got.

#10672 AutoHEPs - include all Node ips and interfaceName selector
  api/pkg/apis/projectcalico/v3/kubecontrollersconfig.go
  api/pkg/openapi/generated.openapi.go
  go.mod
  kube-controllers/pkg/config/runconfig.go
  kube-controllers/pkg/controllers/node/auto_hep_fv_test.go
  kube-controllers/pkg/controllers/node/hostendpoints.go
  libcalico-go/config/crd/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  libcalico-go/lib/apis/v3/generated.openapi.go
  libcalico-go/lib/apis/v3/node.go
  libcalico-go/lib/apis/v3/zz_generated.deepcopy.go
  libcalico-go/lib/backend/k8s/resources/node.go
  libcalico-go/lib/backend/k8s/resources/node_test.go
  libcalico-go/lib/clientv3/kubecontrollersconfig.go
  libcalico-go/lib/clientv3/kubecontrollersconfig_e2e_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
  node/pkg/lifecycle/startup/autodetection/autodetection_methods.go
  node/pkg/lifecycle/startup/autodetection/interfaces.go
  node/pkg/lifecycle/startup/startup.go
  node/pkg/lifecycle/startup/startup_test.go
Labels: release-note-required, docs-pr-required

#10751 Start adding Calico specific e2es to repository
  Makefile
  api/pkg/apis/projectcalico/v3/register.go
  e2e/Makefile
  e2e/cmd/k8s/e2e_test.go
  e2e/pkg/config/config.go
  e2e/pkg/describe/describe.go
  e2e/pkg/tests/policy/policy.go
  e2e/pkg/utils/clean.go
  e2e/pkg/utils/client/client.go
  e2e/pkg/utils/conncheck/client.go
  e2e/pkg/utils/conncheck/conncheck.go
  e2e/pkg/utils/conncheck/k8s.go
  e2e/pkg/utils/conncheck/server.go
  e2e/pkg/utils/conncheck/target.go
  e2e/pkg/utils/framework.go
  e2e/pkg/utils/images/images.go
  e2e/pkg/utils/platforms.go
  e2e/pkg/utils/remotecluster/exec.go
  e2e/pkg/utils/windows/windows.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#10768 Make tc/tcx enums upper-case.
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/bpf/tc/attach.go
  felix/bpf/ut/attach_test.go
  felix/config/config_params.go
  felix/dataplane/driver.go
  felix/dataplane/linux/bpf_ep_mgr.go
  felix/dataplane/linux/endpoint_mgr.go
  felix/dataplane/linux/endpoint_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/qos_controls.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: docs-not-required, release-note-not-required

#10764 Add e2e tests for auto host endpoints
  e2e/cmd/k8s/e2e_test.go
  e2e/pkg/describe/describe.go
  e2e/pkg/tests/hostendpoints/auto_hostendpoints.go
Labels: docs-not-required, release-note-not-required

#10769 build: Make init-source consistent across Makefiles
  third_party/envoy-gateway/Makefile
  third_party/envoy-ratelimit/Makefile
Labels: docs-not-required, release-note-not-required

#10027 Use new set.Adaptive type in named port index
  felix/labelindex/label_inheritance_index.go
  felix/labelindex/labelnamevalueindex/label_name_value_index.go
  felix/labelindex/labelrestrictionindex/label_restriction_index.go
  felix/labelindex/named_port_index.go
  felix/multidict/multidict.go
  libcalico-go/lib/set/adaptive.go
  libcalico-go/lib/set/adaptive_test.go
  libcalico-go/lib/set/benchmarks_test.go
  libcalico-go/lib/set/set.go
  libcalico-go/lib/set/set_test.go
Labels: release-note-required, docs-not-required

#10772 Fix error handling for v6 Services in e2e
  .semaphore/semaphore-scheduled-builds.yml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.d/blocks/20-e2e.yml
  e2e/pkg/tests/policy/service_policy.go
  e2e/pkg/utils/conncheck/k8s.go
  e2e/pkg/utils/conncheck/target.go
Labels: docs-not-required, release-note-not-required

#10773 Release v3.30 pins update
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  metadata.mk
  whisker/README.md
  whisker/package.json
  whisker/yarn.lock
Labels: release-note-required, docs-not-required

#10771 Rework ProgramsMap to allow concurrent loads.
  felix/bpf/hook/load.go
  felix/bpf/hook/map.go
  felix/bpf/ut/attach_test.go
Labels: release-note-required, docs-not-required, flake-fix

#10776 Felix FV tests: Wait for felix to report ready
  felix/fv/infrastructure/felix.go
  felix/fv/infrastructure/topology.go
Labels: docs-not-required, release-note-not-required, flake-fix

#10736 eBPF: Hybrid conntrack cleaner
  felix/bpf-gpl/conntrack_cleanup.c
  felix/bpf-gpl/conntrack_cleanup.h
  felix/bpf/bpfmap/bpf_maps.go
  felix/bpf/conntrack/bpf_scanner.go
  felix/bpf/conntrack/cleanup.go
  felix/bpf/conntrack/cleanupv1/map.go
  felix/bpf/conntrack/cleanupv1/map6.go
  felix/bpf/conntrack/conntrack_test.go
  felix/bpf/conntrack/inforeader.go
  felix/bpf/conntrack/map.go
  felix/bpf/conntrack/scanner.go
  felix/bpf/mock/cleaner.go
  felix/bpf/proxy/syncer_test.go
  felix/bpf/ut/bpf_ct_cleanup_test.go
  felix/bpf/ut/bpf_prog_test.go
  felix/cachingmap/caching_map.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/bpf_map_resize_test.go
Labels: release-note-required, docs-not-required

#10782 Update e2e hep to correctly check for hostEndpoints enabled
  e2e/pkg/tests/hostendpoints/auto_hostendpoints.go
Labels: docs-not-required, release-note-not-required

#10781 Support passing target options to other functions in e2e
  e2e/pkg/utils/conncheck/server.go
Labels: docs-not-required, release-note-not-required

#10784 Add optional calicoctl API client
  e2e/pkg/tests/hostendpoints/auto_hostendpoints.go
  e2e/pkg/tests/policy/policy.go
  e2e/pkg/tests/policy/service_policy.go
  e2e/pkg/utils/client/calicoctl.go
  e2e/pkg/utils/client/client.go
Labels: docs-not-required, release-note-not-required

#10758 Add upgrade e2e pipeline
  .gitignore
  .semaphore/end-to-end/pipelines/cleanup.yml
  .semaphore/end-to-end/pipelines/semaphore.yml
  .semaphore/end-to-end/pipelines/test.yml
  .semaphore/end-to-end/pipelines/upgrade.yml
  .semaphore/end-to-end/scripts/body_standard.sh
  .semaphore/end-to-end/scripts/global_epilogue.sh
  .semaphore/end-to-end/scripts/global_prologue.sh
  .semaphore/end-to-end/scripts/test_scripts/operator_migrate.sh
Labels: docs-not-required, release-note-not-required

#10791 Add rbac for kube-controllers to access services
  charts/calico/templates/calico-kube-controllers-rbac.yaml
  manifests/calico-etcd.yaml
  manifests/canal-etcd.yaml
Labels: release-note-required, docs-not-required

#10790 [v3.29][release tool] remove utilizing VM server for hashrelease (#10774)
  go.mod
  go.sum
  release/cmd/flags.go
  release/cmd/hashrelease.go
  release/internal/hashreleaseserver/config.go
  release/internal/hashreleaseserver/config_test.go
  release/internal/hashreleaseserver/server.go
  release/internal/hashreleaseserver/ssh.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#10794 do not mark already published hashreleases as failed
  release/cmd/hashrelease.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, squash-commits

#10793 Fix logging of error when falling back to calicoctl client in e2e
  e2e/pkg/utils/client/client.go
Labels: docs-not-required, release-note-not-required

#10788 Make `var-require` targets less noisy
  lib.Makefile
Labels: docs-not-required, release-note-not-required

#10797 [v3.29] do not mark already published hashreleases as failed (#10794)
  release/cmd/hashrelease.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#10787 Fix route table conflict test.
  felix/fv/routes_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, flake-fix

#10804 Add lock to fake NFT to guard fake control fields.
  felix/nftables/fake_test.go
Labels: docs-not-required, release-note-not-required

#10809 Bump golang to v1.24.6 and update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/cmd/gomodder/main.go
  lib/httpmachinery/go.mod
  lib/httpmachinery/go.sum
  lib/std/go.mod
  metadata.mk
  node/pkg/lifecycle/startup/startup.go
  release/internal/pinnedversion/pinnedversion.go
  release/pkg/manager/calico/manager.go
  release/pkg/postrelease/helm_test.go
  release/pkg/postrelease/images_test.go
Labels: docs-not-required, release-note-not-required

#10761 IPv6 support in noencap route manager
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/noencap_mgr.go
  felix/dataplane/linux/noencap_mgr_test.go
  felix/dataplane/linux/route_mgr.go
  felix/fv/routing_test.go
  felix/fv/vxlan_test.go
Labels: docs-pr-required, release-note-not-required

#10806 find parent release branch script: Handle all configured remotes
  hack/find-parent-release-branch.sh
Labels: docs-not-required, release-note-not-required

#10823 Apply 'black' formatting to OpenStack-related Python code
  networking-calico/Makefile
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
  networking-calico/networking_calico/agent/linux/interface.py
  networking-calico/networking_calico/common/__init__.py
  networking-calico/networking_calico/common/config.py
  networking-calico/networking_calico/datamodel_v1.py
  networking-calico/networking_calico/datamodel_v2.py
  networking-calico/networking_calico/datamodel_v3.py
  networking-calico/networking_calico/etcdutils.py
  networking-calico/networking_calico/etcdv3.py
  networking-calico/networking_calico/logutils.py
  networking-calico/networking_calico/monotonic.py
  networking-calico/networking_calico/plugins/calico/plugin.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/election.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/endpoints.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/policy.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/qos_driver.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/status.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/subnets.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/syncer.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/lib.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/stub_etcd.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_compaction.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_election.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
  networking-calico/networking_calico/tests/base.py
  networking-calico/networking_calico/tests/test_common.py
  networking-calico/networking_calico/tests/test_datamodel_v1.py
  networking-calico/networking_calico/tests/test_datamodel_v3.py
  networking-calico/networking_calico/tests/test_dhcp_agent.py
  networking-calico/networking_calico/tests/test_etcdutils.py
  networking-calico/networking_calico/tests/test_etcdv3.py
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
  networking-calico/networking_calico/tests/test_interface_driver.py
  networking-calico/networking_calico/tests/test_monotonic.py
  networking-calico/networking_calico/tests/test_subnet_watcher.py
  networking-calico/networking_calico/timestamp.py
  networking-calico/tox.ini
Labels: docs-not-required, release-note-not-required

#10824 Fix networking-calico problems reported by flake8
  networking-calico/.flake8
  networking-calico/Makefile
  networking-calico/networking_calico/agent/dhcp_agent.py
  networking-calico/networking_calico/agent/linux/dhcp.py
  networking-calico/networking_calico/common/__init__.py
  networking-calico/networking_calico/common/config.py
  networking-calico/networking_calico/datamodel_v3.py
  networking-calico/networking_calico/etcdutils.py
  networking-calico/networking_calico/etcdv3.py
  networking-calico/networking_calico/plugins/calico/plugin.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/election.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/endpoints.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/mech_calico.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/policy.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/qos_driver.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/status.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/subnets.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/lib.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/stub_etcd.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_compaction.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_election.py
  networking-calico/networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py
  networking-calico/networking_calico/tests/test_common.py
  networking-calico/networking_calico/tests/test_dhcp_agent.py
  networking-calico/networking_calico/tests/test_etcdutils.py
  networking-calico/networking_calico/tests/test_etcdv3.py
  networking-calico/networking_calico/tests/test_fv_etcdutils.py
  networking-calico/networking_calico/tests/test_subnet_watcher.py
  networking-calico/setup.py
Labels: docs-not-required, release-note-not-required

#10826 ci: Fix logging to stdout instead of stderr
  hack/find-parent-release-branch.sh
Labels: docs-not-required, release-note-not-required

#10846 chore: fix nginx config, add nginx self-test after image is built
  whisker/Makefile
  whisker/docker-image/default.conf
Labels: docs-not-required, release-note-not-required

#10850 chore: split image build and image test
  whisker/Makefile
  whisker/docker-image/Dockerfile
  whisker/docker-image/nginx-start.sh
Labels: docs-not-required, release-note-not-required

#10851 [v3.30] chore: split image build and image test
  whisker/Makefile
  whisker/docker-image/Dockerfile
  whisker/docker-image/nginx-start.sh
Labels: docs-not-required, release-note-not-required

#10841 Add a new manager for all-hosts ipset even when IPIP is not enabled
  felix/dataplane/linux/int_dataplane.go
  felix/dataplane/linux/ipip_mgr.go
  felix/dataplane/linux/ipip_mgr_test.go
  felix/dataplane/linux/ipset_hosts_mgr.go
  felix/dataplane/linux/ipset_hosts_mgr_test.go
  felix/fv/nat_outgoing_test.go
  felix/fv/routing_test.go
Labels: docs-not-required, release-note-not-required

#10835 [master] Semaphore Auto go-build Update
  metadata.mk
Labels: docs-not-required, release-note-not-required

#10825 Set DSCP for host endpoints
  felix/calc/event_sequencer.go
  felix/calc/event_sequencer_test.go
  felix/dataplane/linux/qos_policy_mgr.go
  felix/dataplane/linux/qos_policy_mgr_test.go
  felix/fv/qos_policy_test.go
  felix/proto/felixbackend.pb.go
  felix/proto/felixbackend.proto
  felix/rules/static.go
  felix/rules/static_test.go
  libcalico-go/lib/backend/model/hostendpoint.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/hostendpointprocessor.go
  libcalico-go/lib/backend/syncersv1/updateprocessors/hostendpointprocessor_test.go
Labels: docs-not-required, release-note-not-required

#10869 Rename QoS policy manager to DSCP manager to avoid confusion
  felix/dataplane/linux/dscp_mgr.go
  felix/dataplane/linux/dscp_mgr_test.go
  felix/dataplane/linux/int_dataplane.go
  felix/fv/dscp_test.go
  felix/rules/dscp.go
  felix/rules/dscp_test.go
  felix/rules/rule_defs.go
  felix/rules/static.go
  felix/rules/static_test.go
Labels: docs-not-required, release-note-not-required

#10877 [CORE-11756] New felixConfig CgroupV2Path
  api/pkg/apis/projectcalico/v3/felixconfig.go
  api/pkg/openapi/generated.openapi.go
  felix/config/config_params.go
  felix/docs/config-params.json
  felix/docs/config-params.md
  libcalico-go/config/crd/crd.projectcalico.org_felixconfigurations.yaml
  libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go
  manifests/calico-bpf.yaml
  manifests/calico-policy-only.yaml
  manifests/calico-typha.yaml
  manifests/calico-vxlan.yaml
  manifests/calico.yaml
  manifests/canal.yaml
  manifests/crds.yaml
  manifests/flannel-migration/calico.yaml
  manifests/operator-crds.yaml
Labels: release-note-required, docs-pr-required

#10884 Fix calicoctl detection in e2e
  e2e/pkg/utils/client/client.go
Labels: docs-not-required, release-note-not-required

#10802 bpf map batch cachingmap
  felix/bpf/libbpf/libbpf.go
  felix/bpf/libbpf/libbpf_api.h
  felix/bpf/libbpf/libbpf_stub.go
  felix/bpf/maps/maps.go
  felix/cachingmap/caching_map.go
  felix/cachingmap/caching_map_test.go
  felix/deltatracker/delta_tracker.go
Labels: release-note-required, docs-pr-required

#10893 Remove manual Windows Kubernetes service installation
  node/windows-packaging/CalicoWindows/kubernetes/README.txt
  node/windows-packaging/CalicoWindows/kubernetes/install-kube-services.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kube-proxy-service.ps1
  node/windows-packaging/CalicoWindows/kubernetes/kubelet-service.ps1
  node/windows-packaging/CalicoWindows/kubernetes/uninstall-kube-services.ps1
  process/testing/winfv-felix/run-fv-full.ps1
  process/testing/winfv-felix/setup-fv-capz.sh
Labels: release-note-required, docs-pr-required

#10892 Add several more e2e tests
  e2e/cmd/k8s/e2e_test.go
  e2e/pkg/config/config.go
  e2e/pkg/describe/describe.go
  e2e/pkg/tests/apis/owner_references.go
  e2e/pkg/tests/hostendpoints/hostendpoints.go
  e2e/pkg/tests/networking/hostports.go
  e2e/pkg/tests/networking/mtu.go
  e2e/pkg/tests/policy/tiers.go
  e2e/pkg/utils/autodetection.go
  e2e/pkg/utils/clean.go
  e2e/pkg/utils/conncheck/server.go
  e2e/pkg/utils/externalnode/client.go
  e2e/pkg/utils/images/images.go
Labels: docs-not-required, release-note-not-required

#10896 Fix panic in autohep e2e
  e2e/pkg/tests/hostendpoints/auto_hostendpoints.go
Labels: docs-not-required, release-note-not-required

#10821 Wireguard: Prevent unnecessary module loading
  felix/dataplane/driver.go
  felix/wireguard/metrics_linux.go
Labels: release-note-required, docs-not-required, merge-when-ready

#10859 [BPF] disable ip defrag on old kernels
  felix/bpf-gpl/counters.h
  felix/bpf-gpl/ip_v4_fragment.h
  felix/bpf-gpl/reasons.h
  felix/bpf-gpl/tc.c
  felix/bpf/counters/counters.go
  felix/bpf/counters/map.go
Labels: release-note-required, docs-not-required
